const fs=require('fs'),P=require('path'),R=P.resolve(__dirname,'..');let F=[];const ok=(v,s)=>{if(!v)F.push(s)};const edu=fs.readFileSync(P.join(R,'data/tow_steamsteel/export_descr_unit.txt'),'utf8').replace(/\r/g,''),mir=fs.readFileSync(P.join(R,'data/export_descr_unit.txt'),'utf8').replace(/\r/g,''),edb=fs.readFileSync(P.join(R,'data/tow_steamsteel/export_descr_buildings.txt'),'utf8').replace(/\r/g,''),medb=fs.readFileSync(P.join(R,'data/unit_models/battle_models.modeldb'),'utf8').replace(/\r/g,'');
function unit(t){let start=edu.indexOf('type             '+t+'\n');if(start<0)start=edu.indexOf('type            '+t+'\n');ok(start>=0,'missing '+t);if(start<0)return '';let end=edu.indexOf('\ntype ',start+6);return edu.slice(start,end<0?edu.length:end)}
function model(t){let r=new RegExp('(?:^|\\n)\\d+ '+t+' \\n','m'),m=r.exec(medb);ok(!!m,'modeldb missing '+t);if(!m)return '';return medb.slice(m.index,m.index+5000)}
ok(edu===mir,'EDU mirror drift');
const req={siam_agent:['soldier          siam_agent, 40','arquebus_bullet_c','era 0'],Siam_Archers:['soldier          Siam_Archers, 40','musket_bullet_c','era 0','era 1'],siam_inf:['soldier          siam_inf, 40','rifled_musket_bullet_c','era 0','era 1'],siam_late_inf:['soldier          siam_late_inf, 40','rifle_bullet_c','era 2'],siam_sea:['soldier          siam_sea, 30','rifle_bullet_b, 280','formation        1.4, 1.8, 2.8, 3.6','era 1','era 2'],fra_vietna:['soldier          fra_vietna, 40','rifle_bullet_c','axe','era 2'],burmese_inf:['soldier          burmese_inf, 40','rifled_musket_bullet_c','era 0','era 1'],siam_sword_cav:['soldier          siam_sword_cav, 24','class            light','stat_pri         4, 3, no','era 0','era 1'],siam_late_cav:['soldier          siam_late_cav, 24','class            missile','rifled_musket_carbine_bullet_c','era 2'],Siam_bodyguard:['soldier          Siam_bodyguard, 4','class            light','magazine_rifle_bullet_c','formation        2, 2, 4, 4, 2, square'],siam_ele_gunner:['soldier          siam_ele_gunner, 12','musket_bullet_c']};
for(const [t,qs] of Object.entries(req)){let x=unit(t);for(const q of qs)ok(x.includes(q),t+' lacks '+q);ok(x.includes('stat_ground      0, 0, 0, 0'),t+' terrain');ok(!/hardy|very_hardy|hide_improved_forest/.test(x),t+' inherited bonus');let c=x.match(/^stat_cost\s+(.+)$/m);if(c){let z=c[1].split(',').map(v=>v.trim());ok(z[3]==='100'&&z[4]==='100',t+' upgrades')}}
for(const t of ['viet_inf','merc_aceh_marines','merc_aceh_noble','merc_aceh_reg','merc_aceh_gold','merc_aceh_warband','merc_aceh_inf','byz_armstrong','byz_12lb','byz_5lb','byz_maxim','byz_gatling','byz_150mm'])ok(!/(ownership|era [012]).*\bcru\b/.test(unit(t)),t+' shares cru custom battle');
for(const t of ['siam_armstrong','siam_12lb','siam_5lb','siam_maxim']){ok(unit(t).includes('ownership        cru, slave'),t+' ownership');ok(edb.includes('recruit_pool "'+t+'"'),'EDB '+t)}
ok(!/byz_(gatling|150mm).*factions \{ cru, \}/.test(edb),'forbidden artillery recruitment');ok(!/recruit_pool "viet_inf".*factions \{ cru, \}/.test(edb),'viet_inf duplicate');
for(const t of ['siam_late_inf','fra_vietna'])ok(model(t).includes('MTW2_Musket_SS'),t+' SS animation');ok(model('siam_sea').includes('MTW2_Musket_SSK'),'siam_sea SSK animation');for(const t of ['Siam_bodyguard','siam_sword_cav','siam_late_cav'])ok(/cavalry|Cavalry|Horse|Mounted|hussar|dragoon/.test(model(t)),t+' mounted sprite');{const m=model('siam_sword_cav'),mesh='unit_models/_Units/sia/siam_sword_cav_lod0.mesh';ok(m.includes(mesh.length+' '+mesh)&&m.includes('13 MTW2_HR_Sword 0')&&!m.includes('MTW2_HR_Pistol'),'siam sword cavalry mounted sabre-only mapping');const z=fs.readFileSync(P.join(R,'data',mesh)).toString('latin1');ok(z.includes('primaryactive0')&&!z.includes('inactive0')&&!z.includes('secondaryactive0')&&!z.toLowerCase().includes('lebel'),'siam sword cavalry mesh groups')}
const cards=['siam_sword_cav','siam_ele_gunner','fra_vietna','siam_sea','siam_late_inf','siam_late_cav','siam_agent','siam_inf','Siam_bodyguard','Siam_Archers','burmese_inf','siam_armstrong','siam_12lb','siam_5lb','siam_maxim'];for(const t of cards)ok(fs.existsSync(P.join(R,'data/ui/units/cru/#'+t+'.tga')),'card '+t);
for(const t of ['siam_agent','Siam_Archers','siam_inf'])ok(!unit(t).includes('siam_standard_bearer'),t+' bearer removed');ok(!unit('siam_late_inf').includes('officer          siam_standard_bearer'),'late infantry bearer exclusion');ok(!unit('siam_sea').includes('officer          siam_standard_bearer'),'skirmisher bearer exclusion');ok(unit('Siam_bodyguard').includes('stat_pri_armour  7, 4, 0, metal'),'general cuirassier armour');if(F.length){console.error(F.join('\n'));process.exit(1)}console.log('Siam structural validation passed: 10 core units, 4 artillery clones, 14 tactical cards.');