const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const eduC=path.join(root,'data/tow_steamsteel/export_descr_unit.txt'),eduR=path.join(root,'data/export_descr_unit.txt');
const edbC=path.join(root,'data/tow_steamsteel/export_descr_buildings.txt'),edbR=path.join(root,'data/export_descr_buildings.txt');
const modelP=path.join(root,'data/unit_models/battle_models.modeldb'),locP=path.join(root,'data/text/export_units.txt');
const cardDir=path.join(root,'data/ui/units/egypt'),archiveDir=path.join(root,'tools/card_source_archive/qajar_before_standardization');
const stratC=path.join(root,'data/world/maps/campaign/camp_steamsteel/descr_strat.txt'),stratR=path.join(root,'data/world/maps/campaign/imperial_campaign/descr_strat.txt');

const E={early:{n:0,name:'Early',form:'1.2, 1.2, 1.2, 1.2, 3, square'},mid:{n:1,name:'Mid',form:'1.2, 1.2, 2.0, 2.4, 3, square'},high:{n:2,name:'Late',form:'1.2, 1.4, 2.4, 2.8, 3, square'}};
const W={
  tufang:{name:'Persian tufang matchlock',damage:32,family:'arquebus',range:160,ammo:35,smoke:'musket_shot_set',base:900,muzzle:true},
  enfield:{name:'Pattern 1853 Enfield rifle-musket',damage:37,family:'rifled_musket',range:220,ammo:35,smoke:'musket_shot_set',base:1200,muzzle:true},
  tabatiere:{name:'Mle 1853/67 Tabatiere conversion rifle',damage:29,family:'rifled_musket',range:220,ammo:35,smoke:'musket_shot_set',base:1200},
  werndl:{name:'Werndl-Holub M1867 rifle',damage:29,family:'rifle',range:240,ammo:35,smoke:'musket_shot_set',base:1500}
};
const Q={
  militia:{melee:2,charge:2,def:1,morale:2,disc:'low',training:'trained',proj:'c',premium:-200},
  regular:{melee:4,charge:3,def:2,morale:3,disc:'low',training:'trained',proj:'b',premium:0},
  elite:{melee:6,charge:4,def:3,morale:5,disc:'normal',training:'highly_trained',proj:'a',premium:200}
};
const infantry=[];
function add(type,label,p,w,donor,card,quality,role='line',limit=1,eras=null,tier='D'){infantry.push({type,label,p,w,donor,card,quality,role,limit,eras:eras||[E[p].n],tier});}
add('qaj_tofangchi','Tofangchi-ye Mahalli','early',W.tufang,'qajar_lt','__generated_tofangchi','militia','line',3,[0,1,2]);
add('qaj_sarbaz_early','Sarbazan-e Nezam','early',W.enfield,'rus_guard','rus_guard_eg','regular','line',3);
add('qaj_sarbaz_mid','Sarbazan-e Nezam','mid',W.tabatiere,'qaj_sarbaz_early','rus_guard_eg','regular','line',3);
add('qaj_sarbaz_high','Sarbazan-e Nezam','high',W.werndl,'qaj_sarbaz_mid','rus_guard_eg','regular','line',3);
add('qaj_guard_early','Negahbanan-e Shah','early',W.enfield,'qajar_inf','qajar_inf','elite');
add('qaj_guard_mid','Negahbanan-e Shah','mid',W.tabatiere,'qaj_guard_early','qajar_inf','elite');
add('qaj_guard_high','Negahbanan-e Shah','high',W.werndl,'qaj_guard_mid','qajar_inf','elite');
add('qaj_sharpshooters','Neshanzanan-e Shahi','mid',W.werndl,'qajar_lt','qajar_lt','regular','sharpshooter',1,[1,2]);
add('qaj_austrian_corps','Fowj-e Otrishi','mid',W.werndl,'gr_inf','gr_inf_eg','regular','line',1,[1,2],'B');
const cavalry=[
  {type:'qaj_tribal_cavalry',label:'Savaran-e Ashayeri',kind:'lance',donor:'afghan_cav',card:'__generated_tribal_cavalry',quality:'militia',tier:'C',eras:[0,1,2]},
  {type:'qaj_cossack_brigade',label:'Brigad-e Qazzaq',kind:'lance',donor:'rus_georgian_cav',card:'rus_georgian_cav_eg',quality:'regular',tier:'B',eras:[1,2],disc:'disciplined'},
  {type:'qaj_horse_guard',label:'Gholaman-e Shah',kind:'pistol',donor:'qaj_cav_1g',card:'rus_sib_cossacks',quality:'elite',tier:'D',eras:[0,1,2]},
  {type:'qaj_general_staff',label:'Farmandeh va Setad',kind:'command',donor:'qaj_cav_1g',card:'__generated_general',quality:'elite',tier:'D',eras:[0,1,2]}
];
const upkeep=n=>Math.round(n/3),cost=(n,limit=1,time=3)=>`${time}, ${n}, ${upkeep(n)}, 100, 100, ${n}, ${limit}, ${upkeep(n)}`;
const projUp={c:'b',b:'a',a:'s',s:'s'};
function infRecord(u){const q=Q[u.quality],sword=u.type==='qaj_tofangchi'||u.type==='qaj_sharpshooters';let projectile=q.proj;if(u.role==='sharpshooter')projectile=projUp[projUp[projectile]];if(u.tier==='D'&&projectile!=='c')projectile={b:'c',a:'b',s:'a'}[projectile];const stats=u.tier==='B'?{melee:5,charge:3,def:3,morale:4,disc:'normal',training:'trained'}:q;const attrs=['free_upkeep_unit','sea_faring','hide_forest'];if(u.w.muzzle)attrs.push('gunpowder_unit');attrs.push('gunmen','start_not_skirmishing','cannot_skirmish');if(u.p==='high')attrs.push('stakes');const total=u.w.base+q.premium+(u.role==='sharpshooter'?200:0);const bearer=(u.type.startsWith('qaj_sarbaz_')||u.type.startsWith('qaj_guard_'))&&u.p!=='high';const range=u.w.range+(u.role==='sharpshooter'?40:0);return [
`type             ${u.type}`,`dictionary       ${u.type} ; ${u.label}${u.eras.length===1?` (${E[u.p].name}; ${u.w.name}${sword?' and shamshir':''})`:` (${u.w.name}${sword?' and shamshir':''})`}`,'category         infantry','class            missile','voice_type       Light','accent           farsi','banner faction   main_infantry','banner holy      crusade',`soldier          ${u.type}, ${u.role==='sharpshooter'?30:40}, 0, ${u.role==='sharpshooter'?'1.3':'1.2'}`,'officer          qajargeneral',...(bearer?['officer          qaj_standard_bearer']:[]),`attributes       ${attrs.join(', ')}`,`formation        ${u.role==='sharpshooter'?'1.4, 1.8, 2.8, 3.6, 3, square':E[u.p].form}`,'stat_health      1, 0',`stat_pri         ${u.w.damage}, 0, ${u.w.family}_bullet_${projectile}, ${range}, ${u.w.ammo}, missile, missile_gunpowder, piercing, none, ${u.w.smoke}, 0, -999`,'stat_pri_attr    ap',`stat_sec         ${stats.melee+(sword?1:0)}, ${stats.charge}, no, 0, 0, melee, melee_blade, piercing, ${sword?'sword, 25, 1':'spear, 25, 1.2'}`,`stat_sec_attr    ${sword?'no':'short_pike, ap'}`,`stat_pri_armour  3, ${stats.def}, 0, leather`,'stat_sec_armour  0, 0, flesh','stat_heat        0','stat_ground      0, 0, 0, 0',`stat_mental      ${stats.morale}, ${stats.disc}, ${stats.training}`,'stat_charge_dist 40','stat_fire_delay  0','stat_food        60, 300',`stat_cost        ${cost(total,u.limit)}`,'ownership        egypt, slave',...u.eras.map(e=>`era ${e}            egypt`)].join('\n');}
function cavRecord(u){const command=u.kind==='command',pistol=u.kind==='pistol',cossack=u.type==='qaj_cossack_brigade';let melee=u.quality==='elite'?6:u.quality==='regular'?5:2,charge=u.quality==='elite'?4:u.quality==='regular'?3:2,def=u.tier==='D'?3:4,morale=u.quality==='elite'?5:u.quality==='regular'?4:3,disc=u.disc||(u.type==='qaj_tribal_cavalry'?'impetuous':u.quality==='elite'?'normal':'low'),training=u.quality==='elite'?'highly_trained':'trained';const attrs=['free_upkeep_unit','sea_faring','hide_forest','can_withdraw'];if(pistol)attrs.push('guncavalry','gunmen','start_not_skirmishing','cannot_skirmish');if(command)attrs.push('general_unit','command');if(u.kind==='lance')attrs.push('can_formed_charge');const pistolRow='20, 4, magazine_rifle_bullet_c, 60, 15, missile, missile_gunpowder, piercing, none, musket_shot_set, 25, 1';const total=command?200:pistol?1400:u.type==='qaj_tribal_cavalry'?1000:1200;const rows=command?[`stat_pri         ${melee}, ${charge}, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1`,'stat_pri_attr    no','stat_sec         0, 0, no, 0, 0, no, melee_simple, blunt, none, 0, 1','stat_sec_attr    no']:pistol?[`stat_pri         ${pistolRow}`,'stat_pri_attr    ap',`stat_sec         ${melee}, ${charge}, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1`,'stat_sec_attr    no']:[`stat_pri         ${melee}, ${charge+3}, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1`,'stat_pri_attr    no',`stat_sec         ${melee}, ${charge}, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1`,'stat_sec_attr    no'];return [
`type             ${u.type}`,`dictionary       ${u.type} ; ${u.label} (${command?'mounted command':pistol?'pistol and shamshir':'lance and shamshir'})`,'category         cavalry','class            light','voice_type       Heavy','accent           farsi','banner faction   main_cavalry','banner holy      crusade_cavalry',`soldier          ${u.type}, ${command?4:24}, 0, 1`,...(command?[]:['officer          qajargeneral']),`mount            ${u.kind==='lance'?'lancer':'hussar'}`,'mount_effect     elephant -4, camel -4',`attributes       ${attrs.join(', ')}`,`formation        2, 2, 4, 4, ${command?2:3}, square`,'stat_health      1, 0',...rows,`stat_pri_armour  4, ${def}, 0, leather`,'stat_sec_armour  0, 0, flesh','stat_heat        0','stat_ground      0, 0, 0, 0',`stat_mental      ${morale}, ${disc}, ${training}`,'stat_charge_dist 45','stat_fire_delay  0','stat_food        60, 300',`stat_cost        ${cost(total,1,command?1:3)}`,'ownership        egypt, slave',...u.eras.map(e=>`era ${e}            egypt`)].join('\n');}
const all=[...infantry,...cavalry],records=all.map(u=>u.kind?cavRecord(u):infRecord(u)),byType=Object.fromEntries(all.map(u=>[u.type,u.kind?cavRecord(u):infRecord(u)]));
const legacy=['rus_sib_cossacks','qajar_foot','gr_inf_eg','qajar_lt','rus_georgian_cav_eg','qajar_inf','rus_guard_eg','us_zouave_eg'];
const foreign=['merc_kaz_inf','merc_kaz_cav','merc_kok_royal_cav'];
function stripEgypt(b){b=b.replace(/^ownership\s+(.+)$/m,(m,x)=>{const a=x.split(',').map(y=>y.trim()).filter(y=>y&&y!=='egypt');return `ownership        ${a.length?a.join(', '):'slave'}`;});b=b.replace(/^era ([012])\s+(.+)$/gm,(m,e,x)=>{const a=x.split(',').map(y=>y.trim()).filter(y=>y&&y!=='egypt');return a.length?`era ${e}            ${a.join(', ')}`:'';});if(!/^ownership\s+/m.test(b))b=b.trimEnd()+'\n'+'ownership        slave\n\n';return b.replace(/\n{3,}/g,'\n\n');}
function replaceType(text,type,replacement){const s=[...text.matchAll(/^type\s+(\S+)/gm)],i=s.findIndex(x=>x[1]===type);if(i<0)throw Error(`Missing Qajar legacy type ${type}`);return text.slice(0,s[i].index)+replacement+'\n\n'+text.slice(i+1<s.length?s[i+1].index:text.length);}
let edu=fs.readFileSync(eduC,'utf8').replace(/\r\n/g,'\n');const begin='; BEGIN STANDARDIZED QAJAR',end='; END STANDARDIZED QAJAR';if(edu.includes(begin)){const a=edu.indexOf(begin),z=edu.indexOf(end,a);edu=edu.slice(0,a)+edu.slice(z+end.length).replace(/^\s*/,'');}
let starts=[...edu.matchAll(/^type\s+(\S+)/gm)],parts=[edu.slice(0,starts[0].index)];for(let i=0;i<starts.length;i++){const t=starts[i][1],z=i+1<starts.length?starts[i+1].index:edu.length;let b=edu.slice(starts[i].index,z);if([...legacy,...foreign].includes(t))b=stripEgypt(b);parts.push(b);}edu=parts.join('');const at=edu.indexOf('type             rus_sib_cossacks');if(at<0)throw Error('Qajar insertion point missing');edu=edu.slice(0,at)+`${begin}\n\n${records.join('\n\n')}\n\n${end}\n\n`+edu.slice(at);
const aliases={rus_sib_cossacks:'qaj_horse_guard',qajar_foot:'qaj_tofangchi',gr_inf_eg:'qaj_austrian_corps',qajar_lt:'qaj_sharpshooters',rus_georgian_cav_eg:'qaj_cossack_brigade',qajar_inf:'qaj_guard_early',rus_guard_eg:'qaj_sarbaz_early'};
for(const [old,modern] of Object.entries(aliases)){const a=byType[modern].replace(/^type\s+.*$/m,`type             ${old}`).replace(/^dictionary\s+\S+.*$/m,`dictionary       ${old}`).replace(/^soldier\s+\S+,/m,`soldier          ${modern},`).replace(/^officer\s+qaj_standard_bearer\s*\n?/m,'').replace(/^ownership\s+.*$/m,'ownership        slave').replace(/^era [012]\s+.*\n?/gm,'').trimEnd();edu=replaceType(edu,old,a);}fs.writeFileSync(eduC,edu.replace(/\n/g,'\r\n'));fs.writeFileSync(eduR,edu.replace(/\n/g,'\r\n'));

for(const p of [eduC,eduR]){let s=fs.readFileSync(p,'utf8').replace(/\r\n/g,'\n');for(const [t,modelName] of [['fra_carbs','fra_chasseurs_cheval'],['nl_carbs','net_huzaren'],['balk_cav_gr','pru_husaren']]){s=s.replace(new RegExp('(^type\\s+'+t+'\\n[\\s\\S]*?^soldier\\s+)\\S+,','m'),(m,a)=>a+modelName+',');s=s.replace(new RegExp('(^type\\s+'+t+'\\n[\\s\\S]*?^stat_fire_delay\\s+)-?\\d+','m'),(m,a)=>a+'0');}fs.writeFileSync(p,s.replace(/\n/g,'\r\n'));}
let edb=fs.readFileSync(edbC,'utf8');for(const [old,modern] of Object.entries(aliases))edb=edb.split(`"${old}"`).join(`"${modern}"`);
edb=edb.split(/\r?\n/).filter(line=>!/^\s*recruit_pool "qaj_(?:sarbaz|guard)_(?:mid|high)"/.test(line)&&!/^\s*recruit_pool "qaj_tribal_cavalry"/.test(line)).join('\r\n');
function expandLineages(text){return text.split(/\r?\n/).flatMap(line=>{const m=line.match(/^(\s*recruit_pool "qaj_(sarbaz|guard)_early".*?requires factions \{ egypt, \})(.*)$/);if(!m)return [line];let tail=m[3].replace(/\s+and (?:not )?event_counter military_reforms_(?:1870|1890|1) 1/g,'');const stem=m[1],kind=m[2];return [stem+tail+' and not event_counter military_reforms_1870 1',stem.replace(`${kind}_early`,`${kind}_mid`)+tail+' and event_counter military_reforms_1870 1 and not event_counter military_reforms_1890 1',stem.replace(`${kind}_early`,`${kind}_high`)+tail+' and event_counter military_reforms_1890 1'];}).join('\r\n');}
edb=expandLineages(edb);edb=edb.split(/\r?\n/).flatMap(line=>{if(!line.includes('recruit_pool "qaj_cossack_brigade"'))return [line];const tribal=line.replace('"qaj_cossack_brigade"','"qaj_tribal_cavalry"').replace(/\s+and event_counter military_reforms_(?:1870|1) 1/g,'');return [tribal,line.replace(/event_counter military_reforms_1870 1/g,'event_counter military_reforms_1 1')];}).join('\r\n');fs.writeFileSync(edbC,edb);fs.writeFileSync(edbR,edb);

function entries(text){const a=text.replace(/\r\n/g,'\n').split('\n'),r=[];let start=1;for(let i=1;i<a.length;i++)if(/^16 -0\.090000004 /.test(a[i])){r.push({lines:a.slice(start,i+1),name:(a[start].match(/^\d+ (\S+)/)||[])[1]});start=i+1;}return r;}
function entry(text,name){const e=entries(text).find(x=>x.name===name);if(!e)throw Error(`Missing Qajar model donor ${name}`);return e.lines.join('\n');}
function clone(text,donor,name,anim=null,mounted=false){let e=entry(text,donor).replace(new RegExp(`^${donor.length} ${donor}\\s*$`,'m'),`${name.length} ${name} `);if(anim){const a=anim==='muzzle'?'20 MTW2_Fast_Arquebus_3':anim==='skirm'?'15 MTW2_Musket_SSK':'14 MTW2_Musket_SS';e=e.replace(/(?:20 MTW2_Fast_Arquebus_3|18 MTW2_Fast_Arquebus|18 MTW2_Fast_Musket_3|14 MTW2_Musket_SS|15 MTW2_Musket_SSK)(?=\s)/,a);}if(mounted)e=e.replace(/^\d+ unit_sprites\/[^\s]+_sprite\.spr\s*$/gm,'35 unit_sprites/tmp_cavalry_sprite.spr ');return e;}
function swordAnim(e){e=e.replace(/(?:9 MTW2_Pike|11 MTW2_2H_Axe|14 MTW2_Swordsman|16 MTW2_2HSwordsman)(?!_primary)/,'16 MTW2_2HSwordsman');return e.replace(/(?:17 MTW2_Pike_primary|18 MTW2_Sword_Primary|19 MTW2_2H_Axe_primary|24 MTW2_2HSwordsman_Primary)/,'24 MTW2_2HSwordsman_Primary');}
function addMountedSprite(e){const first=e.indexOf('\n6 \n'),second=e.indexOf('\n6 \n',first+1);if(first<0||second<0)throw Error('Unsupported mounted model mapping without a sprite');const head=e.slice(0,second).replace(/^(\d+ \S+_n\.texture) 0\s*$/gm,'$1 \n35 unit_sprites/tmp_cavalry_sprite.spr ');return head+e.slice(second);}
function counted(e,a,b){return e.replace(`${a.length} ${a}`,`${b.length} ${b}`);}
let model=fs.readFileSync(modelP,'utf8').replace(/\r\n/g,'\n'),added=0;for(const u of infantry){let fresh=clone(model,u.donor,u.type,u.w.muzzle?'muzzle':u.role==='sharpshooter'?'skirm':'line');if(u.type==='qaj_tofangchi'||u.type==='qaj_sharpshooters')fresh=swordAnim(fresh);if(u.type==='qaj_austrian_corps')fresh=fresh.replace(/unit_models\/_Units\/attachments\/textures\/whi_rugrxx\.texture/g,'unit_models/_Units/attachments/textures/per_rugbxx.texture');if(entries(model).some(x=>x.name===u.type))model=model.replace(entry(model,u.type),fresh);else{model=model.trimEnd()+'\n'+fresh+'\n';added++;}}
for(const u of cavalry){let fresh=clone(model,u.donor,u.type,null,true);if(u.type==='qaj_tribal_cavalry')fresh=fresh.replace(/^8 timurids\s*$/gm,'5 egypt ');if(u.kind==='command'){const donorMesh='unit_models/_Units/qaj/qaj_cav_1g_lod0.mesh',generalMesh='unit_models/_Units/qaj/qaj_general_staff_lod0.mesh';if(!fs.existsSync(path.join(root,'data',generalMesh)))throw Error('Missing built Qajar mounted general mesh');fresh=fresh.split(`${donorMesh.length} ${donorMesh}`).join(`${generalMesh.length} ${generalMesh}`);fresh=fresh.replace('14 MTW2_HR_Pistol \n13 MTW2_HR_Sword \n1 \n22 MTW2_HR_Pistol_Primary \n1 \n18 MTW2_Sword_Primary','13 MTW2_HR_Sword 0 \n1 \n18 MTW2_Sword_Primary \n0');}if(!fresh.includes('unit_sprites/tmp_cavalry_sprite.spr'))fresh=addMountedSprite(fresh);if(entries(model).some(x=>x.name===u.type))model=model.replace(entry(model,u.type),fresh);else{model=model.trimEnd()+'\n'+fresh+'\n';added++;}}
{const donor='rus_guard',name='qaj_standard_bearer',mesh0='unit_models/_Units/qaj/qaj_inf_1g_lod0.mesh',mesh='unit_models/_Units/off/qaj_standard_bearer_lod0.mesh',face='unit_models/_Units/attachments/textures/per_rugbxx.texture',flag='unit_models/_Units/bnw/textures/qaj_standard_flag.texture',normal='unit_models/_Units/attachments/textures/blank_norm.texture',flagN='unit_models/_Units/bnw/textures/qaj_standard_flag_n.texture';let fresh=clone(model,donor,name,null);fresh=counted(fresh,mesh0,mesh);fresh=fresh.split(`${face.length} ${face}`).join(`${flag.length} ${flag}`);fresh=fresh.split(`${flag.length} ${flag} \n${normal.length} ${normal} 0`).join(`${flag.length} ${flag} \n${flagN.length} ${flagN} 0`);if(entries(model).some(x=>x.name===name))model=model.replace(entry(model,name),fresh);else{model=model.trimEnd()+'\n'+fresh+'\n';added++;}}
if(added){const h=model.match(/^(22 serialization::archive 3 0 0 0 0 )(\d+)( 0 0 )/);if(!h)throw Error('Bad modeldb header');model=model.replace(h[0],`${h[1]}${+h[2]+added}${h[3]}`);}fs.writeFileSync(modelP,model.replace(/\n/g,'\r\n'));

let raw=fs.readFileSync(locP),loc=raw.slice(raw[0]===255&&raw[1]===254?2:0).toString('utf16le').replace(/\r\n/g,'\n');for(const u of all)for(const k of [u.type,`${u.type}_descr`,`${u.type}_descr_short`])loc=loc.replace(new RegExp(`^\\{${k}\\}.*(?:\\n|$)`,'gm'),'');const rows=all.map(u=>{let equip;if(!u.kind)equip=`${u.w.name}${u.type==='qaj_tofangchi'||u.type==='qaj_sharpshooters'?' and shamshir':' and bayonet'}`;else equip=u.kind==='pistol'?'pistol and shamshir':u.kind==='command'?'mounted command retinue':'lance and shamshir';const desc=u.type==='qaj_austrian_corps'?'Austrian-trained Persian regulars of the late Qajar reform programme.':u.type==='qaj_cossack_brigade'?'Russian-drilled Persian cavalry formed on the Cossack model.':u.type==='qaj_tribal_cavalry'?'Tribal horsemen who preserve the strongest traditional arm of the Qajar host.':u.type==='qaj_tofangchi'?'Locally raised matchlock infantry carrying the Persian tufang and shamshir.':u.type==='qaj_general_staff'?'The Shah and his compact mounted command staff.':`${u.label} serve in the reorganised army of Qajar Persia.`;return `{${u.type}}${u.label}${u.p&&u.eras.length===1?` (${E[u.p].name})`:''}\n{${u.type}_descr}${desc}\n{${u.type}_descr_short}${u.label} (${equip})`;});loc=loc.trimEnd()+'\n\n'+rows.join('\n\n')+'\n';fs.writeFileSync(locP,Buffer.concat([Buffer.from([255,254]),Buffer.from(loc.replace(/\n/g,'\r\n'),'utf16le')]));

fs.mkdirSync(archiveDir,{recursive:true});for(const n of ['qajar_foot','rus_guard_eg','qajar_inf','qajar_lt','gr_inf_eg','rus_georgian_cav_eg','rus_sib_cossacks']){const s=path.join(cardDir,`#${n}.tga`),d=path.join(archiveDir,`#${n}.tga`);if(!fs.existsSync(s))throw Error(`Missing original Qajar card ${n}`);if(!fs.existsSync(d))fs.copyFileSync(s,d);}for(const u of all)if(!u.card.startsWith('__generated_'))fs.copyFileSync(path.join(cardDir,`#${u.card}.tga`),path.join(cardDir,`#${u.type}.tga`));
for(const p of [stratC,stratR])if(fs.existsSync(p)){let s=fs.readFileSync(p,'utf8');s=s.replace(/unit\s+rus_sib_cossacks(\s+)/g,'unit\t\tqaj_horse_guard$1').replace(/unit\s+qajar_inf(\s+)/g,'unit\t\tqaj_guard_early$1').replace(/unit\s+qajar_foot(\s+)/g,'unit\t\tqaj_tofangchi$1').replace(/unit\s+rus_guard_eg(\s+)/g,'unit\t\tqaj_sarbaz_early$1');fs.writeFileSync(p,s);}
if(!fs.readFileSync(eduC).equals(fs.readFileSync(eduR)))throw Error('Qajar EDU mirrors differ');if(!fs.readFileSync(edbC).equals(fs.readFileSync(edbR)))throw Error('Qajar EDB mirrors differ');console.log(`Standardized ${records.length} Qajar records; added ${added} model entries.`);
