const fs=require('fs'),P=require('path'),R=P.resolve(__dirname,'..');
const EC=P.join(R,'data/tow_steamsteel/export_descr_unit.txt'),ER=P.join(R,'data/export_descr_unit.txt'),MP=P.join(R,'data/unit_models/battle_models.modeldb');let e=fs.readFileSync(EC,'utf8').replace(/\r/g,''),m=fs.readFileSync(MP,'utf8').replace(/\r/g,'');
function b(n){const x=e.match(new RegExp(`^type\\s+${n}\\n[\\s\\S]*?(?=^type\\s+|(?![\\s\\S]))`,'m'));if(!x)throw Error(`EDU ${n}`);return x[0].trimEnd()}function rep(n,x){e=e.replace(b(n),x)}const up=n=>Math.round(n/3),cost=(n,l)=>`3, ${n}, ${up(n)}, 100, 100, ${n}, ${l}, ${up(n)}`;
let x=b('boer_kommando_early').replace(/^dictionary.*$/m,'dictionary       boer_kommando_early ; Boer Kommando (Early; Pattern 1853 Enfield rifle-musket)').replace(/^attributes.*$/m,'attributes       free_upkeep_unit, sea_faring, hide_forest, gunpowder_unit, gunmen, start_not_skirmishing, cannot_skirmish').replace(/^officer\s+usa_off_1g$/m,'officer          usa_off_1g\nofficer          boer_standard_bearer');rep('boer_kommando_early',x);x=b('boer_kommando_mid').replace(/^officer\s+usa_off_1g$/m,'officer          usa_off_1g\nofficer          boer_standard_bearer');rep('boer_kommando_mid',x);
function cav(n,label,era,dmg,shot,range,total,muzzle){return `type             ${n}\ndictionary       ${n} ; ${label}\ncategory         cavalry\nclass            missile\nvoice_type       heavy\naccent           dutch\nbanner faction   main_cavalry\nbanner holy      crusade_cavalry\nsoldier          ${n}, 24, 0, 1\nofficer          rus_cos_hussar\nmount            dragoon\nmount_effect     elephant -4, camel -4\nattributes       free_upkeep_unit, sea_faring, can_withdraw, hide_forest, ${muzzle?'gunpowder_unit, ':''}gunmen, guncavalry, start_not_skirmishing\nmove_speed_mod   0.9\nformation        2, 2, 4, 4, 3, square\nstat_health      1, 0\nstat_pri         ${dmg}, 2, ${shot}, ${range}, 35, missile, missile_gunpowder, piercing, none, ${era===2?'smokeless_shot_set':'musket_shot_set'}, 50, 1\nstat_pri_attr    ap\nstat_sec         2, 2, no, 0, 0, melee, melee_blade, blunt, mace, 25, 1\nstat_sec_attr    ap\nstat_pri_armour  4, 4, 0, leather\nstat_sec_armour  0, 0, flesh\nstat_heat        2\nstat_ground      0, 0, 0, 0\nstat_mental      4, impetuous, trained\nstat_charge_dist 45\nstat_fire_delay  0\nstat_food        60, 300\nstat_cost        ${cost(total,2)}\nownership        teu, slave\nera ${era}            teu, slave`;}
const ce=cav('boer_mounted_kommando_early','Mounted Boer Kommando (Early; Pattern 1856 Enfield cavalry carbine)',0,25,'rifled_musket_carbine_bullet_b',200,1200,true),cm=cav('boer_mounted_kommando_mid','Mounted Boer Kommando (Mid; Westley Richards Monkey Tail carbine)',1,25,'rifled_musket_carbine_bullet_b',200,1200,false),ch=cav('boer_mounted_kommando_high','Mounted Boer Kommando (Late; Mauser Model 1895 short rifle)',2,13,'magazine_rifle_carbine_bullet_b',240,1800,false);e=e.replace(b('us_farmer_cav'),ce+'\n\n'+cm+'\n\n'+ch);fs.writeFileSync(EC,e.replace(/\n/g,'\r\n'));fs.writeFileSync(ER,e.replace(/\n/g,'\r\n'));
const ents=()=>[...m.matchAll(/^(\d+) ([^\s;]+)\s*\n\d+ \d+\s*$/gm)].filter(z=>+z[1]===z[2].length);function mb(n){const a=ents(),i=a.findIndex(z=>z[2]===n);if(i<0)throw Error(`model ${n}`);return m.slice(a[i].index,i+1<a.length?a[i+1].index:m.length).trimEnd()}function addClone(d,n,transform=z=>z){if(ents().some(y=>y[2]===n))return;let z=transform(mb(d).replace(new RegExp(`^${d.length} ${d}`),`${n.length} ${n}`));m=m.trimEnd()+'\n'+z+'\n';added++}let added=0;
{const old=mb('boer_kommando_early'),fresh=old.replace(/\n1 \n4 None \n[\s\S]*?(?=\n16 -0\.090000004 )/,'\n1 \n4 None \n20 MTW2_Fast_Arquebus_3 9 MTW2_Pike \n1 \n21 MTW2_Arquebus_Primary \n1 \n17 MTW2_Pike_primary ');m=m.replace(old,fresh)}
for(const n of ['boer_mounted_kommando_early','boer_mounted_kommando_mid','boer_mounted_kommando_high'])addClone('us_farmer_cav',n);addClone('BRIT_FootA_Bearer1','boer_standard_bearer');if(added){const h=m.match(/^(22 serialization::archive 3 0 0 0 0 )(\d+)( 0 0 )/);m=m.replace(h[0],`${h[1]}${+h[2]+added}${h[3]}`)}fs.writeFileSync(MP,m.replace(/\n/g,'\r\n'));
const BC=P.join(R,'data/tow_steamsteel/export_descr_buildings.txt'),BR=P.join(R,'data/export_descr_buildings.txt');let d=fs.readFileSync(BC,'utf8').replace(/\r/g,'');d=d.split('\n').flatMap(line=>{if(!line.includes('"us_farmer_cav"'))return[line];let q=line.replace(/\s+and (?:not )?event_counter military_reforms_(?:1870|1890) 1/g,'');return[q.replace('"us_farmer_cav"','"boer_mounted_kommando_early"')+' and not event_counter military_reforms_1870 1',q.replace('"us_farmer_cav"','"boer_mounted_kommando_mid"')+' and event_counter military_reforms_1870 1 and not event_counter military_reforms_1890 1',q.replace('"us_farmer_cav"','"boer_mounted_kommando_high"')+' and event_counter military_reforms_1890 1']}).join('\n');fs.writeFileSync(BC,d.replace(/\n/g,'\r\n'));fs.writeFileSync(BR,d.replace(/\n/g,'\r\n'));
const LP=P.join(R,'data/text/export_units.txt'),enc='utf16le';let l=fs.readFileSync(LP,enc);const rows=[['boer_mounted_kommando_early','Mounted Boer Kommando (Early)','Pattern 1856 Enfield cavalry carbine'],['boer_mounted_kommando_mid','Mounted Boer Kommando (Mid)','Westley Richards Monkey Tail carbine'],['boer_mounted_kommando_high','Mounted Boer Kommando (Late)','Mauser Model 1895 short rifle']];l=l.replace(/\{boer_kommando_early\}[^\r\n]*/,'{boer_kommando_early}Boer Kommando (Early)').replace(/\{boer_kommando_early_descr_short\}[^\r\n]*/,'{boer_kommando_early_descr_short}Boer Kommando (Early; Pattern 1853 Enfield rifle-musket)');for(const [n,label,w] of rows)if(!l.includes(`{${n}}`))l+=`\r\n{${n}}${label}\r\n{${n}_descr}Mounted citizen commandos who use their horses for operational mobility and dismount when sustained fire is required. Their ${w} supports reconnaissance, screening, and rapid concentration across the veld.\r\n{${n}_descr_short}${label} (${w})\r\n`;fs.writeFileSync(LP,l,enc);
const cd=P.join(R,'data/ui/units/teu');for(const n of rows.map(z=>z[0]))fs.copyFileSync(P.join(cd,'#us_farmer_cav.tga'),P.join(cd,`#${n}.tga`));console.log(`Refined Boers; ${added} model entries added`);
