const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const eduC=path.join(root,'data/tow_steamsteel/export_descr_unit.txt'),eduR=path.join(root,'data/export_descr_unit.txt');
const edbC=path.join(root,'data/tow_steamsteel/export_descr_buildings.txt'),edbR=path.join(root,'data/export_descr_buildings.txt');
const modelP=path.join(root,'data/unit_models/battle_models.modeldb'),locP=path.join(root,'data/text/export_units.txt');
const stratC=path.join(root,'data/world/maps/campaign/camp_steamsteel/descr_strat.txt'),stratR=path.join(root,'data/world/maps/campaign/imperial_campaign/descr_strat.txt');
const cards=path.join(root,'data/ui/units/portugala'),archive=path.join(root,'tools/card_source_archive/union_before_standardization');
const E={early:{n:0,label:'Early',form:'1.2, 1.2, 1.2, 1.2, 3, square'},mid:{n:1,label:'Mid',form:'1.2, 1.2, 2.0, 2.4, 3, square'},high:{n:2,label:'Late',form:'1.2, 1.4, 2.4, 2.8, 3, square'}};
const W={pistol:{name:'Colt Revolver',damage:20,family:'magazine_rifle',range:60,ammo:15,smoke:'musket_shot_set',base:1000,muzzle:false},
 springfield55:{name:'Springfield Model 1855 rifle-musket',damage:29,family:'rifled_musket',range:220,ammo:35,smoke:'musket_shot_set',base:1200,muzzle:true},
 lorenz54:{name:'Lorenz Model 1854 rifle-musket',damage:29,family:'rifled_musket',range:220,ammo:35,smoke:'musket_shot_set',base:1200,muzzle:true},
 minie:{name:'Fusil Minié rifle-musket',damage:29,family:'rifled_musket',range:220,ammo:35,smoke:'musket_shot_set',base:1200,muzzle:true},
 springfield61:{name:'Springfield Model 1861 rifle-musket',damage:29,family:'rifled_musket',range:220,ammo:35,smoke:'musket_shot_set',base:1200,muzzle:true},
 plymouth61:{name:'Plymouth Model 1861 rifle-musket',damage:29,family:'rifled_musket',range:220,ammo:35,smoke:'musket_shot_set',base:1200,muzzle:true},
 sharps59:{name:'Sharps Model 1859 rifle',damage:21,family:'rifle',range:240,ammo:35,smoke:'musket_shot_set',base:1500},
 springfield73:{name:'Springfield Model 1873 rifle',damage:21,family:'rifle',range:240,ammo:35,smoke:'musket_shot_set',base:1500},
 rolling67:{name:'Remington Rolling Block Model 1867 rifle',damage:21,family:'rifle',range:240,ammo:35,smoke:'musket_shot_set',base:1500},
 krag98:{name:'Krag–Jørgensen Model 1898 magazine rifle',damage:13,family:'magazine_rifle',range:260,ammo:40,smoke:'smokeless_shot_set',base:1800},
 lee95:{name:'Lee Navy Model 1895 magazine rifle',damage:13,family:'magazine_rifle',range:260,ammo:40,smoke:'smokeless_shot_set',base:1800},
 sharpsCarbine:{name:'Sharps Model 1859 carbine',damage:20,family:'rifle_carbine',range:220,ammo:35,smoke:'musket_shot_set',base:1500},
 springfieldCarbine:{name:'Springfield Model 1873 carbine',damage:20,family:'rifle_carbine',range:220,ammo:35,smoke:'musket_shot_set',base:1500},
 kragCarbine:{name:'Krag–Jørgensen Model 1898 carbine',damage:13,family:'magazine_rifle_carbine',range:240,ammo:40,smoke:'smokeless_shot_set',base:1800},
 burnside:{name:'Burnside carbine',damage:20,family:'rifle_carbine',range:220,ammo:35,smoke:'musket_shot_set',base:1500}
};
const Q={militia:{melee:3,charge:2,def:2,morale:3,proj:'c',disc:'low',training:'trained',premium:-200},regular:{melee:5,charge:3,def:3,morale:4,proj:'b',disc:'normal',training:'trained',premium:0},elite:{melee:7,charge:4,def:4,morale:6,proj:'a',disc:'disciplined',training:'highly_trained',premium:200}};
const up={c:'b',b:'a',a:'s',s:'s'},down={c:'c',b:'c',a:'b',s:'a'};
const infantry=[
 {type:'uni_state_volunteers_early',label:'State Volunteers',p:'early',w:W.springfield61,quality:'militia',role:'line',donor:'us_inf',card:'us_inf',eras:[0],limit:6},
 {type:'uni_regulars_mid',label:'United States Regulars',p:'mid',w:W.springfield73,quality:'regular',role:'line',donor:'us_late_inf',card:'us_late_inf',eras:[1],limit:2},
 {type:'uni_regulars_high',label:'United States Regulars',p:'high',w:W.krag98,quality:'regular',role:'line',donor:'us_militia',card:'us_militia',eras:[2],limit:2},
 {type:'uni_national_guard_mid',label:'National Guard',p:'mid',w:W.springfield73,quality:'militia',role:'line',donor:'us_late_inf',card:'us_late_inf',eras:[1],limit:4},
 {type:'uni_national_guard_high',label:'National Guard',p:'high',w:W.springfield73,quality:'militia',role:'line',donor:'us_late_inf',card:'us_late_inf',eras:[2],limit:4},
 {type:'uni_colored_troops_early',label:'United States Colored Troops',p:'early',w:W.springfield55,quality:'militia',role:'line',donor:'us_blacks',card:'us_blacks',eras:[0],limit:2},
 {type:'uni_irish_brigade_early',label:'Irish Brigade',p:'early',w:W.lorenz54,quality:'militia',role:'line',donor:'us_inf',card:'union_irish_brigade',eras:[0],limit:1},
 {type:'uni_zouaves_early',label:'Zouave Volunteers',p:'early',w:W.minie,quality:'militia',role:'skirmisher',donor:'us_zouave',card:'us_zouave',eras:[0],limit:2},
 {type:'uni_marines_early',label:'United States Marines',p:'early',w:W.plymouth61,quality:'regular',role:'line',donor:'us_colo_inf',card:'us_colo_inf',eras:[0],limit:1},
 {type:'uni_marines_mid',label:'United States Marines',p:'mid',w:W.rolling67,quality:'regular',role:'line',donor:'us_colo_inf',card:'us_colo_inf',eras:[1],limit:1},
 {type:'uni_marines_high',label:'United States Marines',p:'high',w:W.lee95,quality:'regular',role:'line',donor:'us_colo_inf',card:'us_colo_inf',eras:[2],limit:1},
 {type:'uni_sharpshooters_early',label:'United States Sharpshooters',p:'early',w:W.sharps59,quality:'regular',role:'sharpshooter',donor:'berdan_inf',card:'berdan_inf',eras:[0],limit:1},
 {type:'uni_indian_scouts',label:'Indian Scouts',p:'early',w:W.springfield55,quality:'militia',role:'skirmisher',donor:'apache_inf',card:'apache_inf',eras:[0,1],limit:1,aux:true,axe:true}
];
const cavalry=[
 {type:'uni_volunteer_cavalry_early',label:'Union Volunteer Cavalry',p:'early',w:W.sharpsCarbine,quality:'militia',donor:'us_front_inf',card:'us_front_inf',eras:[0],limit:3},
 {type:'uni_dragoons_early',label:'United States Dragoons',p:'early',w:W.sharpsCarbine,quality:'regular',donor:'us_scout_cav',card:'us_scout_cav',eras:[0],limit:1},
 {type:'uni_dragoons_mid',label:'United States Dragoons',p:'mid',w:W.springfieldCarbine,quality:'regular',donor:'us_scout_cav',card:'us_scout_cav',eras:[1],limit:1},
 {type:'uni_dragoons_high',label:'United States Dragoons',p:'high',w:W.kragCarbine,quality:'regular',donor:'us_scout_cav',card:'us_scout_cav',eras:[2],limit:1},
 {type:'uni_indian_scout_cavalry',label:'Indian Scout Cavalry',p:'mid',w:W.pistol,quality:'militia',donor:'ap_front_cav',card:'ap_front_cav',eras:[0,1],limit:1,aux:true,pistolSpear:true},
 {type:'uni_general_staff',label:'General and Staff',p:'early',quality:'elite',donor:'us_sword_cav',card:'us_front_cav',eras:[0,1,2],limit:1,command:true}
];
const upkeep=n=>Math.round(n/3),cost=(n,limit=1,time=3)=>`${time}, ${n}, ${upkeep(n)}, 100, 100, ${n}, ${limit}, ${upkeep(n)}`;
function projectile(u){let p=Q[u.quality].proj;if(u.role==='skirmisher')p=up[p];if(u.role==='sharpshooter')p=up[up[p]];return `${u.w.family}_bullet_${p}`;}
function infRecord(u){const q=Q[u.quality],skirm=u.role!=='line',bearer=u.p!=='high'&&!u.aux,attrs=['free_upkeep_unit','sea_faring','hide_forest'];if(u.w.muzzle)attrs.push('gunpowder_unit');attrs.push('gunmen','start_not_skirmishing','cannot_skirmish');if(u.p==='high')attrs.push('stakes');if(u.aux)attrs.push('hide_improved_forest');const total=u.w.base+q.premium+(u.role==='sharpshooter'?200:0);return [
`type             ${u.type}`,`dictionary       ${u.type} ; ${u.label} (${E[u.p].label}; ${u.w.name}${u.axe?' and tomahawk':''})`,'category         infantry','class            missile','voice_type       Light','accent           american','banner faction   main_infantry','banner holy      crusade',`soldier          ${u.type}, ${skirm?30:40}, 0, ${skirm?'1.3':'1.2'}`,...(u.aux?[]:['officer          usa_off_1g']),...(bearer?['officer          usa_standard_bearer']:[]),`attributes       ${attrs.join(', ')}`,`formation        ${skirm?'1.4, 1.8, 2.8, 3.6, 3, square':E[u.p].form}`,'stat_health      1, 0',`stat_pri         ${u.w.damage}, 0, ${projectile(u)}, ${u.w.range+(skirm?40:0)}, ${u.w.ammo}, missile, missile_gunpowder, piercing, none, ${u.w.smoke}, 0, -999`,'stat_pri_attr    ap',`stat_sec         ${q.melee}, ${q.charge}, no, 0, 0, melee, melee_blade, piercing, ${u.axe?'axe, 25, 1':'spear, 25, 1.2'}`,`stat_sec_attr    ${u.axe?'ap':'ap, short_pike'}`,`stat_pri_armour  3, ${q.def}, 0, leather`,'stat_sec_armour  0, 0, flesh','stat_heat        0','stat_ground      0, 0, 0, 0',`stat_mental      ${q.morale}, ${u.aux?'impetuous':q.disc}, ${q.training}`,'stat_charge_dist 40','stat_fire_delay  0','stat_food        60, 300',`stat_cost        ${cost(total,u.limit)}`,'ownership        portugala, slave',...u.eras.map(e=>`era ${e}            portugala`)].join('\n');}
function cavRecord(u){const q=Q[u.quality];if(u.command)return [`type             ${u.type}`,`dictionary       ${u.type} ; ${u.label} (mounted command)`,'category         cavalry','class            light','voice_type       Heavy','accent           american','banner faction   main_cavalry','banner holy      crusade_cavalry',`soldier          ${u.type}, 4, 0, 1`,'mount            hussar','mount_effect     elephant -4, camel -4','attributes       free_upkeep_unit, sea_faring, hide_forest, general_unit, command','formation        2, 2, 4, 4, 2, square','stat_health      1, 0','stat_pri         20, 4, magazine_rifle_bullet_c, 60, 15, missile, missile_gunpowder, piercing, none, musket_shot_set, 25, 1','stat_pri_attr    ap',`stat_sec         ${q.melee}, ${q.charge}, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1`,'stat_sec_attr    no',`stat_pri_armour  4, ${q.def}, 0, leather`,'stat_sec_armour  0, 0, flesh','stat_heat        0','stat_ground      0, 0, 0, 0',`stat_mental      ${q.morale}, ${q.disc}, ${q.training}`,'stat_charge_dist 45','stat_fire_delay  0','stat_food        60, 300',`stat_cost        ${cost(200,1,1)}`,'ownership        portugala, slave',...u.eras.map(e=>`era ${e}            portugala`)].join('\n');const attrs=['free_upkeep_unit','sea_faring','hide_forest','can_withdraw'];if(u.w.muzzle)attrs.push('gunpowder_unit');attrs.push('guncavalry','gunmen','start_not_skirmishing','cannot_skirmish');if(u.aux)attrs.push('hide_improved_forest');const p=down[q.proj],total=u.pistolSpear?1200:u.w.base+q.premium+200;if(u.pistolSpear)return [`type             ${u.type}`,`dictionary       ${u.type} ; ${u.label} (Colt Revolver and spear)`,'category         cavalry','class            light','voice_type       Heavy','accent           american','banner faction   main_cavalry','banner holy      crusade_cavalry',`soldier          ${u.type}, 24, 0, 1`,'mount            dragoon','mount_effect     elephant -4, camel -4','attributes       free_upkeep_unit, sea_faring, hide_forest, can_withdraw, guncavalry, gunmen, start_not_skirmishing, cannot_skirmish, hide_improved_forest','formation        2, 2, 4, 4, 3, square','stat_health      1, 0','stat_pri         20, 4, magazine_rifle_bullet_c, 60, 15, missile, missile_gunpowder, piercing, none, musket_shot_set, 25, 1','stat_pri_attr    ap',`stat_sec         ${q.melee}, ${q.charge}, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1`,'stat_sec_attr    no',`stat_pri_armour  4, ${q.def}, 0, leather`,'stat_sec_armour  0, 0, flesh','stat_heat        0','stat_ground      0, 0, 0, 0',`stat_mental      ${q.morale}, impetuous, ${q.training}`,'stat_charge_dist 45','stat_fire_delay  0','stat_food        60, 300',`stat_cost        ${cost(total,u.limit)}`,'ownership        portugala, slave',...u.eras.map(e=>`era ${e}            portugala`)].join('\n');return [
`type             ${u.type}`,`dictionary       ${u.type} ; ${u.label} (${u.eras.length===1?E[u.p].label+'; ':''}${u.w.name} and sabre)`,'category         cavalry','class            light','voice_type       Heavy','accent           american','banner faction   main_cavalry','banner holy      crusade_cavalry',`soldier          ${u.type}, 24, 0, 1`,...(u.aux?[]:['officer          usa_off_1g']),'mount            dragoon','mount_effect     elephant -4, camel -4',`attributes       ${attrs.join(', ')}`,'formation        2, 2, 4, 4, 3, square','stat_health      1, 0',`stat_pri         ${u.w.damage}, 2, ${u.w.family}_bullet_${p}, ${u.w.range}, ${u.w.ammo}, missile, missile_gunpowder, piercing, none, ${u.w.smoke}, 25, 1`,'stat_pri_attr    ap',`stat_sec         ${q.melee}, ${q.charge}, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1`,'stat_sec_attr    no',`stat_pri_armour  4, ${q.def}, 0, leather`,'stat_sec_armour  0, 0, flesh','stat_heat        0','stat_ground      0, 0, 0, 0',`stat_mental      ${q.morale}, ${u.aux?'impetuous':q.disc}, ${q.training}`,'stat_charge_dist 45','stat_fire_delay  0','stat_food        60, 300',`stat_cost        ${cost(total,u.limit)}`,'ownership        portugala, slave',...u.eras.map(e=>`era ${e}            portugala`)].join('\n');}
const all=[...infantry,...cavalry],records=[...infantry.map(infRecord),...cavalry.map(cavRecord)];
function stripFaction(b,f){b=b.replace(/^ownership\s+(.+)$/m,(m,x)=>{const a=x.split(',').map(y=>y.trim()).filter(y=>y&&y!==f);return `ownership        ${a.length?a.join(', '):'slave'}`;});b=b.replace(/^era ([012])\s+(.+)$/gm,(m,e,x)=>{const a=x.split(',').map(y=>y.trim()).filter(y=>y&&y!==f);return a.length?`era ${e}            ${a.join(', ')}`:'';});return b;}
let edu=fs.readFileSync(eduC,'utf8').replace(/\r\n/g,'\n'),begin='; BEGIN STANDARDIZED UNION',end='; END STANDARDIZED UNION';if(edu.includes(begin)){const a=edu.indexOf(begin),z=edu.indexOf(end,a);edu=edu.slice(0,a)+edu.slice(z+end.length).replace(/^\s*/, '');}
const legacy=['berdan_inf','ap_front_cav','us_front_cav','us_scout_cav','us_zouave','union_irish_brigade','us_inf','us_blacks','us_colo_inf','us_late_inf','us_front_inf','us_militia','apache_inf','rus_sailors_portugala'];let starts=[...edu.matchAll(/^type\s+(\S+)/gm)],parts=[edu.slice(0,starts[0].index)];for(let i=0;i<starts.length;i++){const t=starts[i][1],z=i+1<starts.length?starts[i+1].index:edu.length;let b=edu.slice(starts[i].index,z);if(legacy.includes(t))b=stripFaction(b,'portugala');parts.push(b);}edu=parts.join('');const at=edu.indexOf('type             berdan_inf');if(at<0)throw Error('Union insertion point missing');edu=edu.slice(0,at)+`${begin}\n\n${records.join('\n\n')}\n\n${end}\n\n`+edu.slice(at);fs.writeFileSync(eduC,edu.replace(/\n/g,'\r\n'));fs.writeFileSync(eduR,edu.replace(/\n/g,'\r\n'));
function cleanGates(line){return line.replace(/\s+and (?:not )?event_counter (?:military_reforms_(?:1|1870|1890)|repeating_rifles) 1/g,'');}const gate={early:' and not event_counter military_reforms_1870 1',mid:' and event_counter military_reforms_1870 1 and not event_counter military_reforms_1890 1',high:' and event_counter military_reforms_1890 1'};function mapped(line,type,period){return cleanGates(line).replace(/recruit_pool "[^"]+"/,`recruit_pool "${type}"`)+gate[period];}
let edb=fs.readFileSync(edbC,'utf8').replace(/\r\n/g,'\n');edb=edb.split('\n').flatMap(line=>{if(!/recruit_pool "(?:berdan_inf|ap_front_cav|us_front_cav|us_scout_cav|us_zouave|union_irish_brigade|us_inf|us_blacks|us_colo_inf|us_late_inf|us_front_inf|us_militia|apache_inf)"/.test(line)||!line.includes('portugala'))return [line];if(line.includes('"us_front_cav"'))return [cleanGates(line).replace('"us_front_cav"','"uni_general_staff"')];if(line.includes('"berdan_inf"'))return [mapped(line,'uni_sharpshooters_early','early')];if(line.includes('"ap_front_cav"'))return [mapped(line,'uni_indian_scout_cavalry','early'),mapped(line,'uni_indian_scout_cavalry','mid')];if(line.includes('"us_zouave"'))return [mapped(line,'uni_zouaves_early','early')];if(line.includes('"union_irish_brigade"'))return [mapped(line,'uni_irish_brigade_early','early')];if(line.includes('"us_blacks"'))return [mapped(line,'uni_colored_troops_early','early')];if(line.includes('"us_front_inf"'))return [mapped(line,'uni_volunteer_cavalry_early','early')];if(line.includes('"apache_inf"'))return [mapped(line,'uni_indian_scouts','early'),mapped(line,'uni_indian_scouts','mid')];if(line.includes('"us_scout_cav"'))return [mapped(line,'uni_dragoons_early','early'),mapped(line,'uni_dragoons_mid','mid'),mapped(line,'uni_dragoons_high','high')];if(line.includes('"us_late_inf"'))return [mapped(line,'uni_national_guard_mid','mid'),mapped(line,'uni_national_guard_high','high')];if(line.includes('"us_militia"'))return [mapped(line,'uni_regulars_high','high')];if(line.includes('"us_inf"'))return line.includes('repeating_rifles')?[]:[mapped(line,'uni_state_volunteers_early','early'),mapped(line,'uni_regulars_mid','mid')];if(line.includes('"us_colo_inf"'))return /not event_counter military_reforms_1/.test(line)?[mapped(line,'uni_marines_early','early')]:[mapped(line,'uni_marines_mid','mid'),mapped(line,'uni_marines_high','high')];return [line];}).join('\n');fs.writeFileSync(edbC,edb.replace(/\n/g,'\r\n'));fs.writeFileSync(edbR,edb.replace(/\n/g,'\r\n'));
let strat=fs.readFileSync(stratC,'utf8');const fm=strat.match(/(^faction\s+portugala\b[\s\S]*?)(?=^faction\s+)/m);if(!fm)throw Error('Union campaign block missing');let fb=fm[1];const sm={us_front_cav:'uni_general_staff',us_scout_cav:'uni_dragoons_early',us_inf:'uni_state_volunteers_early',us_front_inf:'uni_volunteer_cavalry_early',us_colo_inf:'uni_marines_early',berdan_inf:'uni_sharpshooters_early',union_irish_brigade:'uni_irish_brigade_early',us_zouave:'uni_zouaves_early',us_blacks:'uni_colored_troops_early',ap_front_cav:'uni_indian_scout_cavalry',apache_inf:'uni_indian_scouts'};for(const [a,b] of Object.entries(sm))fb=fb.replace(new RegExp(`^(\\s*unit\\s+)${a}(\\s+)`,'gm'),`$1${b}$2`);strat=strat.replace(fm[1],fb);fs.writeFileSync(stratC,strat);fs.writeFileSync(stratR,strat);
function entries(text){const a=text.replace(/\r\n/g,'\n').split('\n'),r=[];let start=1;for(let i=1;i<a.length;i++)if(/^16 -0\.090000004 /.test(a[i])){r.push({lines:a.slice(start,i+1),name:(a[start].match(/^\d+ (\S+)/)||[])[1]});start=i+1;}return r;}function entry(text,n){const e=entries(text).find(x=>x.name===n);if(!e)throw Error(`Missing model donor ${n}`);return e.lines.join('\n');}function clone(text,donor,name){return entry(text,donor).replace(new RegExp(`^${donor.length} ${donor}\\s*$`,'m'),`${name.length} ${name} `);}function mounted(e){return e.replace(/^\d+ unit_sprites\/[^\s]+_sprite\.spr\s*$/gm,'35 unit_sprites/tmp_cavalry_sprite.spr ');}function infAnim(e,u){const a=u.w.muzzle?'20 MTW2_Fast_Arquebus_3':u.role==='sharpshooter'?'15 MTW2_Musket_SSK':u.p==='high'?'20 MTW2_Fast_Arquebus_3':'14 MTW2_Musket_SS';return e.replace(/(?:20 MTW2_Fast_Arquebus_3|18 MTW2_Fast_Musket_3|18 MTW2_Fast_Arquebus|14 MTW2_Musket_SS|15 MTW2_Musket_SSK)(?=\s)/,a).replace(/(?:11 MTW2_2H_Axe|14 MTW2_Swordsman|16 MTW2_2HSwordsman)(?=\s)/,'9 MTW2_Pike').replace(/(?:19 MTW2_2H_Axe_primary|18 MTW2_Sword_Primary|24 MTW2_2HSwordsman_Primary)/,'17 MTW2_Pike_primary');}
let model=fs.readFileSync(modelP,'utf8').replace(/\r\n/g,'\n'),added=0;for(const u of all){let fresh=clone(model,u.donor,u.type);if(infantry.includes(u))fresh=u.axe?fresh.replace(/(?:18 MTW2_Fast_Musket_3|20 MTW2_Fast_Arquebus_3)(?=\s)/,'20 MTW2_Fast_Arquebus_3'):infAnim(fresh,u);else{fresh=mounted(fresh);if(u.command)fresh=fresh.replace('14 MTW2_HR_Pistol 13 MTW2_HR_Spear','14 MTW2_HR_Pistol 13 MTW2_HR_Sword').replace('21 MTW2_HR_spear_Primary','18 MTW2_Sword_Primary');}const old=entries(model).find(x=>x.name===u.type);if(old)model=model.replace(old.lines.join('\n'),fresh);else{model=model.trimEnd()+'\n'+fresh+'\n';added++;}}{const donor='francejunqshou',name='usa_standard_bearer',fresh=clone(model,donor,name),old=entries(model).find(x=>x.name===name);if(old)model=model.replace(old.lines.join('\n'),fresh);else{model=model.trimEnd()+'\n'+fresh+'\n';added++;}}if(added){const h=model.match(/^(22 serialization::archive 3 0 0 0 0 )(\d+)( 0 0 )/);if(!h)throw Error('Bad modeldb header');model=model.replace(h[0],`${h[1]}${+h[2]+added}${h[3]}`);}fs.writeFileSync(modelP,model.replace(/\n/g,'\r\n'));
let raw=fs.readFileSync(locP),loc=raw.slice(raw[0]===255&&raw[1]===254?2:0).toString('utf16le').replace(/\r\n/g,'\n');for(const u of [...all,{type:'uni_regulars_early'}])for(const k of [u.type,`${u.type}_descr`,`${u.type}_descr_short`])loc=loc.replace(new RegExp(`^\\{${k}\\}.*(?:\\n|$)`,'gm'),'');const rows=all.map(u=>{const desc=u.command?'The Union commander and his compact mounted staff direct the army in battle.':u.aux?`${u.label} serve as locally recruited frontier auxiliaries to Union field forces.`:`${u.label} serve in the armies of the United States.`;return `{${u.type}}${u.label}${u.eras.length===1?` (${E[u.p].label})`:''}\n{${u.type}_descr}${desc}\n{${u.type}_descr_short}${u.label}${u.w?` (${u.w.name})`:''}`;});loc=loc.trimEnd()+'\n\n'+rows.join('\n\n')+'\n';fs.writeFileSync(locP,Buffer.concat([Buffer.from([255,254]),Buffer.from(loc.replace(/\n/g,'\r\n'),'utf16le')]));
fs.mkdirSync(archive,{recursive:true});for(const n of ['us_inf','us_militia','us_front_inf','us_late_inf','us_blacks','us_colo_inf','us_zouave','berdan_inf','union_irish_brigade','us_scout_cav','ap_front_cav','us_front_cav','apache_inf']){const s=path.join(cards,`#${n}.tga`),d=path.join(archive,`#${n}.tga`);if(fs.existsSync(s)&&!fs.existsSync(d))fs.copyFileSync(s,d);}for(const u of all)if(u.type!=='uni_indian_scout_cavalry')fs.copyFileSync(path.join(cards,`#${u.card}.tga`),path.join(cards,`#${u.type}.tga`));
let agents=fs.readFileSync(path.join(root,'agents.md'),'utf8');if(!agents.includes('### Union modifiers')){agents=agents.trimEnd()+`\n\n### Union modifiers\n\nThe Union is B tier. Most Union field formations are militia-quality citizen soldiers: the National Guard, United States Colored Troops, Irish Brigade, Zouave Volunteers, and Union Volunteer Cavalry use militia baselines even when their historical identity or specialist role is distinguished. United States Regulars, United States Marines, and United States Dragoons use regular baselines. United States Sharpshooters are regular-quality sharpshooters: the role affects projectile accuracy and cost but does not make them elite in melee, armour, morale, or training. Indian Scouts and Indian Scout Cavalry are regional militia-quality auxiliaries, retain impetuous discipline, and may retain improved forest concealment as an explicit scouting-role exception. Early and mid national infantry uses usa_off_1g plus the verified usa_standard_bearer cloned from the complete francejunqshou model mapping: its existing portugala body texture visibly depicts a blue Union uniform and its existing portugala flag texture visibly depicts the United States flag. Late infantry uses only usa_off_1g. Artillery remains outside this infantry-and-cavalry balance pass.\n`;fs.writeFileSync(path.join(root,'agents.md'),agents);}
if(!fs.readFileSync(eduC).equals(fs.readFileSync(eduR)))throw Error('EDU mirrors differ');if(!fs.readFileSync(edbC).equals(fs.readFileSync(edbR)))throw Error('EDB mirrors differ');if(!fs.readFileSync(stratC).equals(fs.readFileSync(stratR)))throw Error('campaign mirrors differ');console.log(`Standardized Union: ${records.length} records; added ${added} model entries.`);
