const fs=require('fs');
const regionPath='data/world/maps/map_steamsteel/descr_regions.txt',stratPath='data/world/maps/campaign/camp_steamsteel/descr_strat.txt',locPath='data/text/text_steamsteel/imperial_campaign_regions_and_settlement_names.txt';
const loc=new Map();for(const line of fs.readFileSync(locPath).subarray(2).toString('utf16le').split(/\r?\n/)){const m=line.match(/^\{([^}]+)\}\s*(.*)$/);if(m)loc.set(m[1],m[2].trim());}
const regions=new Map(),rl=fs.readFileSync(regionPath,'utf8').replace(/\r/g,'').split('\n');for(let i=0;i<rl.length;i++)if(/^[A-Za-z0-9_]+_Province\s*$/.test(rl[i]))regions.set(rl[i].trim(),{region:rl[i].trim(),settlement:rl[i+1].trim(),declaredOwner:rl[i+2].trim(),resources:rl[i+5].split(',').map(x=>x.trim()).filter(Boolean)});
const sl=fs.readFileSync(stratPath,'utf8').replace(/\r/g,'').split('\n'),owned=[];let faction='',inSettlement=false,depth=0,pending=false,current=null;
for(const line of sl){let m;if(!inSettlement&&(m=line.match(/^faction\s+([^,\s]+)/)))faction=m[1];if(!inSettlement&&line.trim()==='settlement'){pending=true;current={faction,region:''};continue;}if(pending&&line.trim()==='{'){inSettlement=true;pending=false;depth=1;continue;}if(inSettlement){for(const c of line){if(c==='{')depth++;else if(c==='}')depth--;}if((m=line.match(/^\s*region\s+(\S+)/)))current.region=m[1];if(depth===0){owned.push(current);inSettlement=false;current=null;}}}
const rows=owned.map(x=>{const r=regions.get(x.region);if(!r)throw Error(`Unknown region in descr_strat: ${x.region}`);return{faction:x.faction,region:x.region,regionName:loc.get(x.region)||'',settlement:r.settlement,settlementName:loc.get(r.settlement)||'',resources:r.resources.join(','),factionCreator:r.declaredOwner,creatorDiffersFromOwner:r.declaredOwner!==x.faction};});
fs.writeFileSync('tools/steamsteel_campaign_tag_audit_20260925.json',JSON.stringify(rows,null,2));
const resourceCounts=new Map();for(const r of regions.values())for(const x of r.resources)resourceCounts.set(x,(resourceCounts.get(x)||0)+1);
const none=rows.filter(x=>x.resources.split(',').includes('none')),mismatch=rows.filter(x=>x.creatorDiffersFromOwner);
console.log(JSON.stringify({regions:regions.size,settlements:rows.length,resourceTags:resourceCounts.size,factionCreatorDifferentFromStartingOwner:mismatch.length,settlementsTaggedNone:none.map(x=>`${x.faction}:${x.regionName}/${x.settlementName}`),startingFactionsWithoutSettlements:[]},null,2));
