const fs=require('fs'),P=require('path'),R=P.resolve(__dirname,'..'),B=P.join(R,'tools/backup_before_ethiopia_balance_20260918');fs.mkdirSync(B,{recursive:true});
const edus=['data/tow_steamsteel/export_descr_unit.txt','data/export_descr_unit.txt'],mp='data/unit_models/battle_models.modeldb',lp='data/text/export_units.txt';for(const f of [...edus,mp,lp,'AGENTS.md'])fs.copyFileSync(P.join(R,f),P.join(B,f.replace(/[\\/]/g,'__')));
const get=(s,n)=>{const m=s.match(new RegExp(`^type\\s+${n.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')}\\s*$[\\s\\S]*?(?=^type\\s+|(?![\\s\\S]))`,'m'));if(!m)throw Error('missing '+n);return m[0]};
const line=(b,k,v)=>b.match(new RegExp(`^${k}\\s+`,'m'))?b.replace(new RegExp(`^${k}.*$`,'m'),k.padEnd(17)+v):b.replace(/^(dictionary.*)$/m,`$1\n${k.padEnd(17)}${v}`);
const own=(b,eras)=>{b=line(b,'ownership','papal_states, slave');b=b.replace(/^era [012].*\r?\n/gm,'');for(const e of eras)b+=`era ${e}`.padEnd(17)+'papal_states, slave\n';return b};
function set(e,n,vals,eras){let b=get(e,n);for(const [k,v] of Object.entries(vals))b=line(b,k,v);b=own(b,eras);return e.replace(get(e,n),b)}
function strip(e,n){let b=get(e,n).replace(/^era [012].*\bpapal_states\b.*\r?\n/gm,'');b=b.replace(/^ownership.*$/m,x=>x.replace(/papal_states,?\s*/g,'').replace(/,\s*,/g,',').replace(/ownership\s+,/,'ownership        '));return e.replace(get(e,n),b)}
for(const f of edus){let p=P.join(R,f),e=fs.readFileSync(p,'utf8');
e=set(e,'merc_viet_early_inf',{dictionary:'merc_viet_early_inf ; Č̣äwa',category:'infantry',class:'missile',soldier:'aby_grd_1g, 80, 0, 1',attributes:'free_upkeep_unit, sea_faring, hide_forest',formation:'1.2, 1.2, 1.2, 1.2, 3, square',stat_pri:'6, 2, javelin, 60, 1, thrown, missile_mechanical, piercing, spear, 25, 1',stat_pri_attr:'thrown',stat_sec:'5, 3, no, 0, 0, melee, melee_blade, blunt, mace, 25, 1',stat_sec_attr:'no',stat_pri_armour:'3, 3, 4, leather',stat_ground:'0, 0, 0, 0',stat_mental:'5, impetuous, trained',stat_cost:'1, 700, 233, 100, 100, 700, 2, 233'},[0,1,2]);
e=set(e,'ethiopian_warband',{dictionary:'ethiopian_warband ; Fanno',soldier:'aby_spr_1g, 96, 0, 0.7',attributes:'free_upkeep_unit, sea_faring, hide_forest',formation:'1.2, 1.2, 3, 3, 5, square',stat_pri:'3, 2, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1',stat_pri_attr:'spear',stat_pri_armour:'3, 2, 3, leather',stat_ground:'0, 0, 0, 0',stat_mental:'4, impetuous, untrained',stat_cost:'1, 500, 167, 100, 100, 500, 3, 167'},[0,1,2]);
e=set(e,'aby_grd_2g',{dictionary:'aby_grd_2g ; Ras and Retinue',category:'cavalry',class:'light',soldier:'aby_grd_2g, 4, 0, 1',attributes:'sea_faring, hide_forest, general_unit, command',formation:'2, 2, 4, 4, 2, square',stat_pri:'5, 3, no, 0, 0, melee, melee_blade, slashing, sword, 25, 1',stat_pri_attr:'no',stat_pri_armour:'4, 4, 0, leather',stat_ground:'0, 0, 0, 0',stat_mental:'6, disciplined, highly_trained',stat_cost:'1, 1200, 400, 100, 100, 1200, 1, 400'},[0,1,2]);
e=set(e,'fra_blacks_ab',{dictionary:'fra_blacks_ab ; Näftäñña (Fusil Modèle 1874 Gras)',soldier:'aby_inf_3g, 40, 0, 1',attributes:'free_upkeep_unit, sea_faring, hide_forest, gunmen, start_not_skirmishing, cannot_skirmish',formation:'1.2, 1.2, 2.0, 2.4, 3, square',stat_pri:'37, 0, rifle_bullet_c, 240, 35, missile, missile_gunpowder, piercing, none, musket_shot_set, 0, -999',stat_sec:'6, 3, no, 0, 0, melee, melee_blade, piercing, axe, 25, 1',stat_pri_armour:'3, 3, 1, leather',stat_ground:'0, 0, 0, 0',stat_mental:'5, normal, trained',stat_fire_delay:'0',stat_cost:'2, 1500, 500, 100, 100, 1500, 3, 500'},[1,2]);
e=set(e,'aby_inf_2g',{dictionary:'aby_inf_2g ; Tigrayan Riflemen (Fusil Modèle 1874 Gras)',soldier:'aby_inf_2g_skirm, 30, 0, 1',attributes:'free_upkeep_unit, sea_faring, hide_forest, gunmen',formation:'1.4, 1.8, 2.8, 3.6, 3, square',stat_pri:'37, 0, rifle_bullet_b, 280, 35, missile, missile_gunpowder, piercing, none, musket_shot_set, 0, -999',stat_sec:'6, 3, no, 0, 0, melee, melee_blade, slashing, axe, 25, 1',stat_sec_attr:'ap',stat_pri_armour:'3, 3, 0, leather',stat_ground:'0, 0, 0, 0',stat_mental:'5, normal, trained',stat_cost:'2, 1500, 500, 100, 100, 1500, 1, 500'},[1,2]);
e=set(e,'aby_nob_2g',{dictionary:'aby_nob_2g ; Mehal Sefari (Fusil Modèle 1874 Gras)',soldier:'aby_nob_2g, 40, 0, 1',attributes:'free_upkeep_unit, sea_faring, hide_forest, gunmen, start_not_skirmishing, cannot_skirmish, stakes',formation:'1.2, 1.4, 2.4, 2.8, 3, square',stat_pri:'37, 0, rifle_bullet_b, 240, 35, missile, missile_gunpowder, piercing, none, musket_shot_set, 0, -999',stat_sec:'7, 4, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1',stat_pri_armour:'3, 4, 0, leather',stat_ground:'0, 0, 0, 0',stat_mental:'7, disciplined, highly_trained',stat_cost:'2, 1700, 567, 100, 100, 1700, 1, 567'},[2]);
e=set(e,'aby_cav_1g',{dictionary:'aby_cav_1g ; Oromo Horsemen',class:'missile',soldier:'aby_cav_1g, 24, 0, 1',attributes:'free_upkeep_unit, sea_faring, hide_forest, can_withdraw',stat_pri:'6, 2, javelin, 65, 6, thrown, missile_mechanical, piercing, spear, 25, 1',stat_sec:'5, 3, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1',stat_pri_armour:'4, 4, 1, leather',stat_ground:'0, 0, 0, 0',stat_mental:'5, impetuous, trained',stat_cost:'2, 1000, 333, 100, 100, 1000, 3, 333'},[0,1,2]);
e=set(e,'aby_roy_1g',{dictionary:'aby_roy_1g ; Shewan Horsemen',class:'missile',soldier:'aby_roy_1g, 24, 0, 1',attributes:'free_upkeep_unit, sea_faring, hide_forest, can_withdraw',stat_pri:'6, 2, javelin, 65, 6, thrown, missile_mechanical, piercing, spear, 25, 1',stat_sec:'6, 4, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1',stat_pri_armour:'4, 4, 1, leather',stat_ground:'0, 0, 0, 0',stat_mental:'6, impetuous, trained',stat_cost:'2, 1200, 400, 100, 100, 1200, 1, 400'},[0,1]);
e=set(e,'aby_crb_3g',{dictionary:'aby_crb_3g ; Mounted Näftäñña (Mauser M1871 Carbine)',class:'missile',soldier:'aby_crb_3g, 24, 0, 1',attributes:'free_upkeep_unit, sea_faring, hide_forest, guncavalry, gunmen, start_not_skirmishing, stakes',formation:'2, 2, 4, 4, 3, square',stat_pri:'37, 2, rifle_carbine_bullet_c, 220, 35, missile, missile_gunpowder, piercing, none, musket_shot_set, 0, -999',stat_sec:'5, 3, no, 0, 0, melee, melee_blade, slashing, sword, 25, 1',stat_pri_armour:'4, 4, 0, leather',stat_ground:'0, 0, 0, 0',stat_mental:'5, normal, trained',stat_cost:'3, 1700, 567, 100, 100, 1700, 1, 567'},[2]);
for(const n of ['aby_cav_2g','africa_cav','african_warband','mahdist_inf','fra_blacks_az','mahdist_camel_cav','mahdist_cav','Ethiopia Sudanese Musketeers','Ethiopia Sudanese Warriors'])e=strip(e,n);fs.writeFileSync(p,e)}
let m=fs.readFileSync(P.join(R,mp),'utf8');function mb(n){const start=m.search(new RegExp(`^${n.length} ${n}\\s*$`,'m')),tail=m.indexOf('16 -0.090000004 0 0 -0.34999999 0.80000001 0.60000002',start),end=m.indexOf('\n',tail)+1;if(start<0||tail<0)throw Error('model '+n);return [start,end,m.slice(start,end)]}
{let [s,e,b]=mb('aby_inf_3g');b=b.replace('20 MTW2_Fast_Arquebus_3','14 MTW2_Musket_SS');m=m.slice(0,s)+b+m.slice(e)}
if(!/^17 aby_inf_2g_skirm\s*$/m.test(m)){let [s,e,b]=mb('aby_inf_2g');b=b.replace(/^10 aby_inf_2g\s*$/m,'17 aby_inf_2g_skirm ').replace('18 MTW2_Fast_Musket_3','15 MTW2_Musket_SSK');m=m.slice(0,e)+b+m.slice(e);m=m.replace(/^(22 serialization::archive 3 0 0 0 0 )(\d+)( 0 0 )/m,(_,a,n,z)=>a+(+n+1)+z)}
fs.writeFileSync(P.join(R,mp),m);
let buf=fs.readFileSync(P.join(R,lp)),bom=buf[0]===255&&buf[1]===254,l=buf.subarray(bom?2:0).toString('utf16le');for(const [k,v] of Object.entries({merc_viet_early_inf:'Č̣äwa',ethiopian_warband:'Fanno',aby_grd_2g:'Ras and Retinue',fra_blacks_ab:'Näftäñña',aby_inf_2g:'Tigrayan Riflemen',aby_nob_2g:'Mehal Sefari',aby_cav_1g:'Oromo Horsemen',aby_roy_1g:'Shewan Horsemen',aby_crb_3g:'Mounted Näftäñña'})){const re=new RegExp(`\\{${k}\\}[^\\r\\n]*`);l=re.test(l)?l.replace(re,`{${k}}${v}`):l+`\r\n{${k}}${v}`}fs.writeFileSync(P.join(R,lp),Buffer.concat([Buffer.from([255,254]),Buffer.from(l,'utf16le')]));console.log('Balanced Ethiopian core roster and removed non-national custom-battle ownership.');
