const fs=require('fs');
const source='tools/mesh_work/siam_sword_cav/siam_sword_cav_source.glb';
const output='tools/mesh_work/siam_sword_cav/siam_sword_cav.glb';
const data=fs.readFileSync(source),jsonLength=data.readUInt32LE(12);
const doc=JSON.parse(data.subarray(20,20+jsonLength));
const meshes=doc.meshes||[],nodes=doc.nodes||[];
const one=(a,p,k)=>{const v=a.map((x,i)=>[(x.name||'').startsWith(p),i]).filter(x=>x[0]).map(x=>x[1]);if(v.length!==1)throw Error(k+' count '+v.length);return v[0]};
const gunMesh=one(meshes,'primaryactive0','gun mesh'),swordMesh=one(meshes,'secondaryactive0','sword mesh');
const gunNode=one(nodes,'primaryactive0','gun node'),swordNode=one(nodes,'secondaryactive0','sword node');
for(const node of nodes)if(node.children)node.children=node.children.filter(i=>i!==gunNode).map(i=>i-(i>gunNode));
for(const scene of doc.scenes||[])scene.nodes=(scene.nodes||[]).filter(i=>i!==gunNode).map(i=>i-(i>gunNode));
nodes.splice(gunNode,1);
for(const node of nodes)if(node.mesh>gunMesh)node.mesh--;
meshes.splice(gunMesh,1);
meshes[swordMesh-(swordMesh>gunMesh)].name=meshes[swordMesh-(swordMesh>gunMesh)].name.replace('secondaryactive0','primaryactive0');
nodes[swordNode-(swordNode>gunNode)].name=nodes[swordNode-(swordNode>gunNode)].name.replace('secondaryactive0','primaryactive0');
let json=Buffer.from(JSON.stringify(doc));json=Buffer.concat([json,Buffer.alloc((4-json.length%4)%4,32)]);
const rest=data.subarray(20+jsonLength),head=Buffer.alloc(20);head.write('glTF');head.writeUInt32LE(2,4);head.writeUInt32LE(20+json.length+rest.length,8);head.writeUInt32LE(json.length,12);head.writeUInt32LE(0x4e4f534a,16);
fs.writeFileSync(output,Buffer.concat([head,json,rest]));
console.log('Prepared unarmoured Siam rider: sabre primary, carbine geometry physically removed.');
