const fs=require('fs'),P=require('path'),R=P.resolve(__dirname,'..'),B=P.join(R,'tools/backup_before_ethiopian_firearm_diversity_20260918');fs.mkdirSync(B,{recursive:true});
const files=['data/tow_steamsteel/export_descr_unit.txt','data/export_descr_unit.txt','data/unit_models/battle_models.modeldb','data/text/export_units.txt','AGENTS.md'];for(const f of files)fs.copyFileSync(P.join(R,f),P.join(B,f.replace(/[\\/]/g,'__')));
const unit=(s,n)=>{const m=s.match(new RegExp(`^type\\s+${n}\\s*$[\\s\\S]*?(?=^type\\s+|(?![\\s\\S]))`,'m'));if(!m)throw Error(n);return m[0]};const line=(b,k,v)=>b.replace(new RegExp(`^${k}.*$`,'m'),k.padEnd(17)+v);const eras=(b,a)=>{b=b.replace(/^era [012].*\r?\n/gm,'');for(const e of a)b+=`era ${e}`.padEnd(17)+'papal_states, slave\n';return b};
for(const f of files.slice(0,2)){const p=P.join(R,f);let s=fs.readFileSync(p,'utf8');let gras=unit(s,'fra_blacks_ab');gras=line(gras,'dictionary','fra_blacks_ab ; Näftäñña (Fusil Gras and Mixed Breechloaders)');gras=line(gras,'soldier','aby_inf_3g_gras, 40, 0, 1');gras=line(gras,'attributes','free_upkeep_unit, sea_faring, hide_forest, gunmen, start_not_skirmishing, cannot_skirmish');gras=line(gras,'formation','1.2, 1.2, 2.0, 2.4, 3, square');gras=line(gras,'stat_pri','37, 0, rifle_bullet_c, 240, 35, missile, missile_gunpowder, piercing, none, musket_shot_set, 0, -999');gras=line(gras,'stat_mental','4, impetuous, untrained');gras=line(gras,'stat_cost','2, 1300, 433, 100, 100, 1300, 2, 433');gras=eras(gras,[1,2]);s=s.replace(unit(s,'fra_blacks_ab'),gras);
if(!/^type\s+eth_rifled_musketeers$/m.test(s)){let r=gras.replace(/^type.*$/m,'type             eth_rifled_musketeers').replace(/^dictionary.*$/m,'dictionary       eth_rifled_musketeers ; Näftäñña (Mixed Rifle-Muskets)').replace(/^soldier.*$/m,'soldier          aby_inf_3g, 40, 0, 1').replace(/^attributes.*$/m,'attributes       free_upkeep_unit, sea_faring, hide_forest, gunpowder_unit, gunmen, start_not_skirmishing, cannot_skirmish').replace(/^formation.*$/m,'formation        1.2, 1.2, 1.2, 1.2, 3, square').replace(/^stat_pri.*$/m,'stat_pri         37, 0, rifled_musket_bullet_c, 220, 35, missile, missile_gunpowder, piercing, none, musket_shot_set, 0, -999').replace(/^stat_cost.*$/m,'stat_cost        2, 1000, 333, 100, 100, 1000, 2, 333');r=eras(r,[0,1,2]);s=s.replace(gras,gras+'\n\n'+r)}
let t=unit(s,'aby_inf_2g');t=line(t,'dictionary','aby_inf_2g ; Tigrayan Musketeers (Old Trade Muskets)');t=line(t,'attributes','free_upkeep_unit, sea_faring, hide_forest, gunpowder_unit, gunmen');t=line(t,'stat_pri','37, 0, musket_bullet_b, 240, 35, missile, missile_gunpowder, piercing, none, musket_shot_set, 0, -999');t=line(t,'stat_cost','2, 800, 267, 100, 100, 800, 1, 267');t=eras(t,[0,1,2]);s=s.replace(unit(s,'aby_inf_2g'),t);fs.writeFileSync(p,s)}
let p=P.join(R,files[2]),m=fs.readFileSync(p,'utf8');function mb(n){const a=m.search(new RegExp(`^${n.length} ${n}\\s*$`,'m')),t=m.indexOf('16 -0.090000004 0 0 -0.34999999 0.80000001 0.60000002',a),e=m.indexOf('\n',t)+1;if(a<0||t<0)throw Error(n);return[a,e,m.slice(a,e)]}if(!/^15 aby_inf_3g_gras\s*$/m.test(m)){let[a,e,b]=mb('aby_inf_3g');b=b.replace(/^10 aby_inf_3g\s*$/m,'15 aby_inf_3g_gras ').replace('20 MTW2_Fast_Arquebus_3','14 MTW2_Musket_SS');m=m.slice(0,e)+b+m.slice(e);m=m.replace(/^(22 serialization::archive 3 0 0 0 0 )(\d+)( 0 0 )/m,(_,a,n,z)=>a+(+n+1)+z)}fs.writeFileSync(p,m);
const src=P.join(R,'data/ui/units/papal_states/#fra_blacks_ab.tga'),dst=P.join(R,'data/ui/units/papal_states/#eth_rifled_musketeers.tga');if(fs.existsSync(src))fs.copyFileSync(src,dst);
p=P.join(R,files[3]);let buf=fs.readFileSync(p),bom=buf[0]===255&&buf[1]===254,l=buf.subarray(bom?2:0).toString('utf16le');for(const [k,v] of Object.entries({fra_blacks_ab:'Näftäñña with Breechloaders',eth_rifled_musketeers:'Näftäñña with Rifle-Muskets',aby_inf_2g:'Tigrayan Musketeers'})){for(const [suf,val] of [['',v],['_descr',v+'.'],['_descr_short',v+'.']]){const key=k+suf,re=new RegExp(`\\{${key}\\}[^\\r\\n]*`);l=re.test(l)?l.replace(re,`{${key}}${val}`):l+`\r\n{${key}}${val}`}}fs.writeFileSync(p,Buffer.concat([Buffer.from([255,254]),Buffer.from(l,'utf16le')]));console.log('Diversified Ethiopian firearms: trade muskets, rifle-muskets, breechloaders, and late central-host rifles.');
