const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const tool=path.join(root,'tools/standardize_union.js');
let source=fs.readFileSync(tool,'utf8');
source=source.replace("sharpsCarbine:{name:'Sharps Model 1859 carbine',damage:31,family:'rifled_musket_carbine',range:200,ammo:35,smoke:'musket_shot_set',base:1200,muzzle:true}","sharpsCarbine:{name:'Sharps Model 1859 carbine',damage:20,family:'rifle_carbine',range:220,ammo:35,smoke:'musket_shot_set',base:1500}");
fs.writeFileSync(tool,source);
for(const rel of ['data/tow_steamsteel/export_descr_unit.txt','data/export_descr_unit.txt']){const file=path.join(root,rel);let text=fs.readFileSync(file,'utf8');for(const [type,total] of [['uni_volunteer_cavalry_early',1500],['uni_dragoons_early',1700]]){const m=text.match(new RegExp(`^type\\s+${type}\\r?\\n[\\s\\S]*?(?=^type\\s+)`,'m'));if(!m)throw Error('Missing '+type);let b=m[0].replace(/^attributes\s+(.*)$/m,(line,attrs)=>'attributes       '+attrs.split(',').map(x=>x.trim()).filter(x=>x!=='gunpowder_unit').join(', ')).replace(/^stat_pri\s+.*$/m,'stat_pri         20, 2, rifle_carbine_bullet_c, 220, 35, missile, missile_gunpowder, piercing, none, musket_shot_set, 25, 1').replace(/^stat_cost\s+.*$/m,`stat_cost        3, ${total}, ${Math.round(total/3)}, 100, 100, ${total}, ${type==='uni_volunteer_cavalry_early'?3:1}, ${Math.round(total/3)}`);text=text.replace(m[0],b);}fs.writeFileSync(file,text);}
const validator=path.join(root,'tools/validate_union.js');let check=fs.readFileSync(validator,'utf8');if(!check.includes('Sharps carbine rows'))check=check.replace("const header=+(","for(const t of ['uni_volunteer_cavalry_early','uni_dragoons_early']){const b=block(t);ok(/^stat_pri\\s+20, 2, rifle_carbine_bullet_c, 220,/m.test(b)&&!/^attributes\\s+.*\\bgunpowder_unit\\b/m.test(b),t+' Sharps carbine rows');}\n+const header=+(");fs.writeFileSync(validator,check);
console.log('Corrected the Sharps Model 1859 cavalry weapons as breech-loading rifle carbines.');
