const fs=require('fs'),path=require('path'),R=path.resolve(__dirname,'..');
const files=['data/tow_steamsteel/export_descr_unit.txt','data/export_descr_unit.txt'];
const pistol=/Bodyguard|Revolver Kihei|Enomoto|Hijikata|Itagaki|Jules Brunet|Kondo Isami|Matsudaira|Saigo Takamori|Sakamoto Ryoma|Takeda Ayasaburo|Tokugawa Yoshinobu/;
const skirm=/Kiheitai|Saga Hoheitai|Jinshotai|Karasugumi|Raijintai|Kijutai|Hokuchin Butai|Hoppo Keibitai|Tondenhei/;
const magazine=/(?:Rikuguntai|Rikusentai|Ezo Rikuguntai|Goshimpei|Ryukihei|Hokuchin Butai).*(?:1890|1900|1905)/;
const rifle=/(?:Denshutai(?! Kihei)|Kaiso Shinsengumi|Shinsenryodan)|(?:Rikuguntai|Rikusentai|Ezo Rikuguntai|Goshimpei|Hoppo Keibitai|Tondenhei).*(?:1870|1880)/;
const rifled=/(?:Shotai|Satsuma Hoheitai|Yamagunitai|Kiheitai|Saga Hoheitai|Jinshotai|Suzakutai|Nagaoka Hoheitai|Shohotai|Gakuheitai|Karasugumi|Raijintai|Shinsengumi|Kaga Hoheitai|Matsushiro Hoheitai|Hokokutai|Keishitai|Shizoku|Yukantai|Ainu Minieru|Heimin Partisans Minieru|Korean Byeolgigun|korean_rifles_mercs)/;
const musket=/(?:Teppotai|Sampeitai|Byakkotai|Ainu Geberu|Heimin Partisans Geberu|Korean Musketeers)/;
const arquebus=/(?:Ainu Teppo|Heimin Partisans$)/;
function family(t){if(magazine.test(t))return ['magazine_rifle_bullet',260,false];if(rifle.test(t))return ['rifle_bullet',240,false];if(rifled.test(t))return ['rifled_musket_bullet',220,true];if(musket.test(t))return ['musket_bullet',200,true];if(arquebus.test(t))return ['arquebus_bullet',160,true];return null}
for(const rel of files){const p=path.join(R,rel);let s=fs.readFileSync(p,'utf8').replace(/\r/g,'');s=s.split(/(?=^type\s+)/m).map(b=>{const tm=b.match(/^type\s+(.+)$/m);if(!tm||!/(?:^ownership|^era [012]).*\bsaxons\b/m.test(b))return b;const t=tm[1].trim();if(t==='korean_cav_mercs')b=b.replace(/^soldier\s+([^,]+),\s*\d+/m,'soldier          $1, 24');if(pistol.test(t)){b=b.replace(/^stat_pri\s+[^\n]+$/m,'stat_pri         20, 2, magazine_rifle_bullet_c, 60, 15, missile, missile_gunpowder, piercing, none, musket_shot_set, 25, 1');b=b.replace(/,?\s*gunpowder_unit/g,'');return b}const f=family(t);if(!f)return b;const old=b.match(/^stat_pri\s+(.+)$/m);if(!old||!/bullet/.test(old[1]))return b;const suffix=(old[1].match(/_(c|b|a|s)\b/)||[])[1]||'c',range=f[1]+(skirm.test(t)?40:0);b=b.replace(/^stat_pri\s+([^,]+),\s*([^,]+),\s*[^,]+,\s*\d+/m,`stat_pri         $1, $2, ${f[0]}_${suffix}, ${range}`);b=b.replace(/^formation\s+.*$/m,skirm.test(t)?'formation        1.4, 1.8, 2.8, 3.6, 3, square':f[0]==='magazine_rifle_bullet'?'formation        1.2, 1.4, 2.4, 2.8, 3, square':f[2]?'formation        1.2, 1.2, 1.2, 1.2, 3, square':'formation        1.2, 1.2, 2.0, 2.4, 3, square');if(f[2]&&!/gunpowder_unit/.test(b))b=b.replace(/^attributes\s+(.+)$/m,'attributes       $1, gunpowder_unit');if(!f[2])b=b.replace(/,?\s*gunpowder_unit/g,'');return b}).join('');fs.writeFileSync(p,s.replace(/\n/g,'\r\n'))}
console.log('Corrected Japanese firearm families, pistol rows, formations, and Korean cavalry strength.');
