const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'..');const canonical=path.join(root,'data/tow_steamsteel/export_descr_unit.txt'),runtime=path.join(root,'data/export_descr_unit.txt');
const infantry={};
function add(types,stats){for(const t of types)infantry[t]={...stats};}
add(['spa_inf_early','spa_inf_mid','spa_inf_high'],{melee:6,charge:4,def:3,morale:4,disc:'normal',train:'trained',limit:2,quality:'regular'});
add(['spa_caz_early','spa_caz_mid','spa_caz_high'],{melee:6,charge:4,def:3,morale:4,disc:'normal',train:'trained',limit:2,quality:'regular',skirm:true});
add(['spa_milicia_nacional_early','spa_milicia_nacional_mid','spa_milicia_nacional_high'],{melee:4,charge:3,def:2,morale:3,disc:'low',train:'trained',limit:1,quality:'militia'});
add(['austro_sailor_spain_early','austro_sailor_spain_mid','austro_sailor_spain_high'],{melee:6,charge:4,def:3,morale:4,disc:'normal',train:'trained',limit:1,quality:'regular'});
add(['spa_col_inf_early','spa_col_inf_mid','spa_col_inf_high'],{melee:4,charge:3,def:3,morale:4,disc:'normal',train:'trained',limit:1,quality:'colonial'});
add(['cuban_inf_high'],{melee:4,charge:3,def:3,morale:4,disc:'normal',train:'trained',limit:1,quality:'sharpshooter',skirm:true});
const baseCost={early:1200,mid:1500,high:1800};
function period(t){return t.endsWith('_early')?'early':t.endsWith('_mid')?'mid':'high';}
function cost(n,limit){const u=Math.round(n/3);return`3, ${n}, ${u}, 100, 100, ${n}, ${limit}, ${u}`;}
function normalizeInf(t,b,s){const p=period(t),x=infantry[t];let attrs=['free_upkeep_unit','sea_faring','hide_forest'];if(p==='early')attrs.push('gunpowder_unit');attrs.push('gunmen','start_not_skirmishing','cannot_skirmish');if(p==='high')attrs.push('stakes');
  b=b.replace(/^officer\s+.*\r?\n/gm,'').replace(/^(soldier\s+.*)$/m,`$1\nofficer          shk_off_1g${p!=='high'?'\nofficer          russia_qi':''}`);
  b=b.replace(/^attributes\s+.*$/m,`attributes       ${attrs.join(', ')}`);
  b=b.replace(/^formation\s+.*$/m,`formation        ${x.skirm?'1.4, 1.8, 2.8, 3.6, 3, square':p==='early'?'1.2, 1.2, 1.2, 1.2, 3, square':p==='mid'?'1.2, 1.2, 2.0, 2.4, 3, square':'1.2, 1.4, 2.4, 2.8, 3, square'}`);
  b=b.replace(/^(stat_pri\s+\d+,\s*\d+,\s*)[^,]+/m,(m,a)=>{let q=x.quality==='militia'?'c':x.quality==='sharpshooter'?'s':x.skirm?'a':'b';return a+m.match(/(?:rifled_musket|magazine_rifle|rifle)_bullet_/)[0]+q;});
  b=b.replace(/^stat_sec\s+.*$/m,`stat_sec         ${x.melee}, ${x.charge}, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1.2`).replace(/^stat_pri_armour\s+.*$/m,`stat_pri_armour  3, ${x.def}, 0, leather`).replace(/^stat_mental\s+.*$/m,`stat_mental      ${x.morale}, ${x.disc}, ${x.train}`);
  b=b.replace(/^stat_fire_delay\s+.*$/m,`stat_fire_delay  ${p==='early'?-100000:0}`);
  let n=baseCost[p]+(x.quality==='militia'?-200:x.quality==='colonial'?-100:x.quality==='sharpshooter'?100:0);b=b.replace(/^stat_cost\s+.*$/m,`stat_cost        ${cost(n,x.limit)}`);return b;}
function cav(t,label,soldier,kind,eras){const pistol=kind==='pistol',carbine=kind==='carbine',cuir=kind==='cuirass',general=kind==='general',lance=kind==='lance';const heavy=cuir||general?'heavy':'light';const attrs=['free_upkeep_unit','sea_faring','hide_forest','can_withdraw'];if(pistol||carbine||cuir){attrs.push('guncavalry','gunmen','start_not_skirmishing','cannot_skirmish');if(carbine)attrs.push('stakes');}if(general)attrs.push('general_unit','command');let pri,sec,priAttr='ap',secAttr='ap',melee=5,charge=3,def=4,morale=4,disc='normal',train='trained',price=1000,arm='4, 4, 0, leather',mount='hussar';
  if(carbine){const p=period(t),fam=p==='early'?'rifled_musket':p==='mid'?'rifle':'magazine_rifle',d=p==='high'?13:p==='early'?37:24,r=p==='early'?200:p==='mid'?220:240,a=p==='high'?40:35,sm=p==='high'?'smokeless_shot_set':'musket_shot_set';pri=`${d}, 2, ${fam}_carbine_bullet_c, ${r}, ${a}, missile, missile_gunpowder, piercing, none, ${sm}, 25, 1`;sec=`5, 3, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1`;price=(p==='early'?1200:p==='mid'?1500:1800)+200;mount='dragoon';}
  else if(pistol||cuir||general){pri='20, 4, magazine_rifle_bullet_c, 60, 15, missile, missile_gunpowder, piercing, none, musket_shot_set, 25, 1';if(cuir){melee=7;charge=4;def=5;morale=6;disc='disciplined';train='highly_trained';price=1700;arm='7, 5, 0, metal';}else if(general){melee=7;charge=4;morale=6;disc='disciplined';train='highly_trained';price=200;}else{melee=4;price=1100;}sec=`${melee}, ${charge}, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1`;}
  else{pri=`5, 3, no, 0, 0, melee, melee_blade, piercing, ${lance?'spear':'sword'}, 25, 1`;sec='5, 3, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1';price=lance?1200:1000;priAttr=lance?'spear, ap':'ap';}
  return[`type             ${t}`,`dictionary       ${t} ; ${label}`,'category         cavalry',`class            ${heavy}`,'voice_type       Heavy','accent           spanish','banner faction   main_cavalry','banner holy      crusade_cavalry',`soldier          ${soldier}, ${general?4:24}, 0, 1`,'officer          shk_off_1g',`mount            ${mount}`,'mount_effect     elephant -4, camel -4',`attributes       ${attrs.join(', ')}`,`formation        2, 2, 4, 4, ${general?2:3}, square`,'stat_health      1, 0',`stat_pri         ${pri}`,`stat_pri_attr    ${priAttr}`,`stat_sec         ${sec}`,`stat_sec_attr    ${secAttr}`,`stat_pri_armour  ${arm}`,'stat_sec_armour  0, 0, flesh','stat_heat        0','stat_ground      0, 0, 0, 0',`stat_mental      ${morale}, ${disc}, ${train}`,'stat_charge_dist 45','stat_fire_delay  -20000','stat_food        60, 300',`stat_cost        ${cost(price,1)}`,'ownership        spain, slave',...eras.map(e=>`era ${e}            spain`)].join('\n')+'\n\n';}
const cavBlocks={spa_cav_early:cav('spa_cav_early','Carabineros (Early)','us_front_cav_sp','carbine',[0]),spa_cav_mid:cav('spa_cav_mid','Carabineros (Mid)','spa_scout_cav','carbine',[1]),spa_cav_high:cav('spa_cav_high','Carabineros (Late)','spa_scout_cav','carbine',[2]),spa_col_cav_mid:cav('spa_col_cav_mid','Caballería Indígenas','spa_scout_cav','pistol',[0,1,2]),spa_cuirassiers_early:cav('spa_cuirassiers_early','Coracero','bol_hussar','cuirass',[0,1,2]),civil_guard:cav('civil_guard','General y Estado Mayor','spa_general_staff','general',[0,1,2]),euro_hussars:cav('euro_hussars','Lanceros','spa_lancer','lance',[0,1,2])};
let edu=fs.readFileSync(canonical,'utf8').replace(/\r\n/g,'\n');const starts=[...edu.matchAll(/^type\s+(\S+)/gm)],parts=[edu.slice(0,starts[0].index)];for(let i=0;i<starts.length;i++){const t=starts[i][1],end=i+1<starts.length?starts[i+1].index:edu.length;let b=edu.slice(starts[i].index,end);if(infantry[t])b=normalizeInf(t,b);if(cavBlocks[t])b=cavBlocks[t];parts.push(b);}edu=parts.join('');const out=edu.replace(/\n/g,'\r\n');fs.writeFileSync(canonical,out);fs.writeFileSync(runtime,out);console.log('Normalized restored Spanish records.');
