const fs=require('fs'),P=require('path'),R=P.resolve(__dirname,'..'),B=P.join(R,'tools/backup_before_ethiopian_mixed_firearms_20260918');fs.mkdirSync(B,{recursive:true});
const files=['data/tow_steamsteel/export_descr_unit.txt','data/export_descr_unit.txt','data/unit_models/battle_models.modeldb','data/text/export_units.txt','tools/validate_ethiopia.js','AGENTS.md'];for(const f of files)fs.copyFileSync(P.join(R,f),P.join(B,f.replace(/[\\/]/g,'__')));
const unit=(s,n)=>{const m=s.match(new RegExp(`^type\\s+${n}\\s*$[\\s\\S]*?(?=^type\\s+|(?![\\s\\S]))`,'m'));if(!m)throw Error(n);return m[0]};
const line=(b,k,v)=>b.replace(new RegExp(`^${k}.*$`,'m'),k.padEnd(17)+v);const eras=(b,a)=>{b=b.replace(/^era [012].*\r?\n/gm,'');for(const e of a)b+=`era ${e}`.padEnd(17)+'papal_states, slave\n';return b};
for(const f of files.slice(0,2)){const p=P.join(R,f);let s=fs.readFileSync(p,'utf8');let b=unit(s,'fra_blacks_ab');for(const [k,v] of Object.entries({dictionary:'fra_blacks_ab ; Näftäñña (Mixed Rifled Muskets)',soldier:'aby_inf_3g, 40, 0, 1',attributes:'free_upkeep_unit, sea_faring, hide_forest, gunpowder_unit, gunmen, start_not_skirmishing, cannot_skirmish',formation:'1.2, 1.2, 1.2, 1.2, 3, square',stat_pri:'37, 0, rifled_musket_bullet_c, 220, 35, missile, missile_gunpowder, piercing, none, musket_shot_set, 0, -999',stat_sec:'4, 2, no, 0, 0, melee, melee_blade, piercing, axe, 25, 1',stat_pri_armour:'3, 2, 1, leather',stat_mental:'4, impetuous, untrained',stat_cost:'2, 1000, 333, 100, 100, 1000, 3, 333'}))b=line(b,k,v);b=eras(b,[0,1,2]);s=s.replace(unit(s,'fra_blacks_ab'),b);
b=unit(s,'aby_inf_2g');for(const [k,v] of Object.entries({dictionary:'aby_inf_2g ; Tigrayan Riflemen (Mixed Rifled Muskets)',soldier:'aby_inf_2g_skirm, 30, 0, 1',attributes:'free_upkeep_unit, sea_faring, hide_forest, gunpowder_unit, gunmen',formation:'1.4, 1.8, 2.8, 3.6, 3, square',stat_pri:'37, 0, rifled_musket_bullet_b, 260, 35, missile, missile_gunpowder, piercing, none, musket_shot_set, 0, -999',stat_sec:'4, 2, no, 0, 0, melee, melee_blade, slashing, axe, 25, 1',stat_pri_armour:'3, 2, 0, leather',stat_mental:'4, impetuous, untrained',stat_cost:'2, 1000, 333, 100, 100, 1000, 1, 333'}))b=line(b,k,v);b=eras(b,[0,1,2]);s=s.replace(unit(s,'aby_inf_2g'),b);
b=unit(s,'aby_nob_2g');for(const [k,v] of Object.entries({dictionary:'aby_nob_2g ; Mehal Sefari (Mixed Breech-Loading Rifles)',attributes:'free_upkeep_unit, sea_faring, hide_forest, gunmen, start_not_skirmishing, cannot_skirmish, stakes',stat_pri:'37, 0, rifle_bullet_c, 240, 35, missile, missile_gunpowder, piercing, none, musket_shot_set, 0, -999',stat_mental:'6, impetuous, trained',stat_cost:'2, 1500, 500, 100, 100, 1500, 1, 500'}))b=line(b,k,v);s=s.replace(unit(s,'aby_nob_2g'),b);fs.writeFileSync(p,s)}
let p=P.join(R,files[2]),m=fs.readFileSync(p,'utf8');function mb(n){const a=m.search(new RegExp(`^${n.length} ${n}\\s*$`,'m')),t=m.indexOf('16 -0.090000004 0 0 -0.34999999 0.80000001 0.60000002',a),e=m.indexOf('\n',t)+1;return[a,e,m.slice(a,e)]}for(const [n,from,to] of [['aby_inf_3g','14 MTW2_Musket_SS','20 MTW2_Fast_Arquebus_3'],['aby_inf_2g_skirm','15 MTW2_Musket_SSK','18 MTW2_Fast_Musket_3']]){let[a,e,b]=mb(n);if(b.includes(from))b=b.replace(from,to);if(!b.includes(to))throw Error(n+' animation');m=m.slice(0,a)+b+m.slice(e)}fs.writeFileSync(p,m);
p=P.join(R,files[3]);let buf=fs.readFileSync(p),bom=buf[0]===255&&buf[1]===254,l=buf.subarray(bom?2:0).toString('utf16le');for(const [k,v] of Object.entries({fra_blacks_ab:'Näftäñña',aby_inf_2g:'Tigrayan Riflemen',aby_nob_2g:'Mehal Sefari'}))l=l.replace(new RegExp(`\\{${k}\\}[^\\r\\n]*`),`{${k}}${v}`);fs.writeFileSync(p,Buffer.concat([Buffer.from([255,254]),Buffer.from(l,'utf16le')]));console.log('Revised Ethiopia around mixed irregular firearms throughout all periods.');
