const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const eduC=path.join(root,'data/tow_steamsteel/export_descr_unit.txt'),eduR=path.join(root,'data/export_descr_unit.txt');
const edbC=path.join(root,'data/tow_steamsteel/export_descr_buildings.txt'),edbR=path.join(root,'data/export_descr_buildings.txt');
const modelP=path.join(root,'data/unit_models/battle_models.modeldb'),locP=path.join(root,'data/text/export_units.txt');
const cards=path.join(root,'data/ui/units/denmark'),archive=path.join(root,'tools/card_source_archive/peru_before_standardization');
const stratC=path.join(root,'data/world/maps/campaign/camp_steamsteel/descr_strat.txt'),stratR=path.join(root,'data/world/maps/campaign/imperial_campaign/descr_strat.txt');
const backup=path.join(root,'tools/backup_before_peru_20260914');

const E={early:{n:0,label:'Early',form:'1.2, 1.2, 1.2, 1.2, 3, square'},mid:{n:1,label:'Mid',form:'1.2, 1.2, 2.0, 2.4, 3, square'},high:{n:2,label:'Late',form:'1.2, 1.4, 2.4, 2.8, 3, square'}};
const W={
 lorenz:{name:'Lorenz Model 1854 rifle-musket',damage:29,family:'rifled_musket',range:220,smoke:'musket_shot_set',base:1200,muzzle:true},
 minie:{name:'Prussian Model 1839/55 Minie rifle-musket',damage:29,family:'rifled_musket',range:220,smoke:'musket_shot_set',base:1200,muzzle:true},
 comblain:{name:'Comblain II conversion rifle',damage:29,family:'rifled_musket',range:220,smoke:'musket_shot_set',base:1200},
 remington:{name:'Remington Rolling Block Modelo 1871 rifle',damage:24,family:'rifle',range:240,smoke:'musket_shot_set',base:1500},
 mauser:{name:'Mauser Modelo 1891 magazine rifle',damage:13,family:'magazine_rifle',range:260,smoke:'smokeless_shot_set',base:1800}
};
const Q={militia:{melee:2,charge:2,def:2,morale:3,disc:'low',train:'trained',proj:'c',premium:-200},regular:{melee:4,charge:3,def:3,morale:4,disc:'low',train:'trained',proj:'c',premium:0},elite:{melee:6,charge:4,def:4,morale:6,disc:'normal',train:'highly_trained',proj:'b',premium:200}};
const inf=[];
function add(type,label,p,w,donor,card,quality,role='line',limit=1){inf.push({type,label,p,w,donor,card,quality,role,limit});}
add('per_line_early','Infanteria de Linea','early',W.lorenz,'peru_early_inf','peru_early_inf','regular','line',3);
add('per_line_mid','Infanteria de Linea','mid',W.comblain,'peru_conscript','rus_conscript_de','regular','line',3);
add('per_line_high','Infanteria de Linea','high',W.mauser,'peru_conscript','rus_conscript_de','regular','line',3);
add('per_guard_early','Guardia Nacional','early',W.minie,'per_lgt_1g','tzar_inf','militia','line',3);
add('per_guard_mid','Guardia Nacional','mid',W.remington,'per_lgt_1g','tzar_inf','militia','line',3);
add('per_guard_high','Guardia Nacional','high',W.remington,'per_lgt_1g','tzar_inf','militia','line',3);
add('per_cazadores_early','Cazadores','early',W.lorenz,'per_lgt_1g','peru_roy_inf','regular','skirmisher',1);
add('per_cazadores_mid','Cazadores','mid',W.comblain,'per_lgt_1g','peru_roy_inf','regular','skirmisher',1);
add('per_cazadores_high','Cazadores','high',W.mauser,'per_lgt_1g','peru_roy_inf','regular','skirmisher',1);
add('per_montoneros_early','Montoneros','early',W.lorenz,'peru_foot','peru_foot','militia','skirmisher',2);
add('per_montoneros_mid','Montoneros','mid',W.remington,'peru_foot','peru_foot','militia','skirmisher',2);
add('per_marines_mid','Infanteria de Marina','mid',W.remington,'fra_sailors','fra_sailors_denmark','regular','line',1);
add('per_marines_high','Infanteria de Marina','high',W.mauser,'fra_sailors','fra_sailors_denmark','regular','line',1);
const cav=[
 {type:'per_husares_junin',label:'Husares de Junin',kind:'pistol',donor:'bol_hussar',card:'bol_hussar',quality:'elite',eras:[0,1,2]},
 {type:'per_lanceros_torata',label:'Lanceros de Torata',kind:'lance',donor:'spa_lancer',cardFrom:['venice','ita_lancieri'],quality:'regular',eras:[0,1]},
 {type:'per_carabineros_torata',label:'Carabineros de Torata',kind:'carbine',donor:'per_cav_1g',card:'peru_carb',quality:'regular',eras:[2]},
 {type:'per_general_staff',label:'General y Estado Mayor',kind:'command',donor:'per_grd_1g',card:'peru_hussars',quality:'elite',eras:[0,1,2]}
];
const up=n=>Math.round(n/3),cost=(n,limit=1,time=3)=>`${time}, ${n}, ${up(n)}, 100, 100, ${n}, ${limit}, ${up(n)}`;
const projUp={c:'b',b:'a',a:'s',s:'s'};
function infRecord(u){const q=Q[u.quality],sk=u.role==='skirmisher';let proj=q.proj;if(sk)proj=projUp[proj];const attrs=['free_upkeep_unit','sea_faring','hide_forest'];if(u.w.muzzle)attrs.push('gunpowder_unit');attrs.push('gunmen','start_not_skirmishing');if(sk)attrs.push('can_withdraw');else attrs.push('cannot_skirmish');if(u.p==='high')attrs.push('stakes');const total=u.w.base+q.premium;const range=u.w.range+(sk?40:0);const bearer=!sk&&u.p!=='high';return [
`type             ${u.type}`,`dictionary       ${u.type} ; ${u.label} (${E[u.p].label}; ${u.w.name})`,'category         infantry','class            missile','voice_type       Light','accent           spanish','banner faction   main_infantry','banner holy      crusade',`soldier          ${u.type}, ${sk?30:40}, 0, ${sk?'1.0':'1.2'}`,'officer          fra_off_1g',...(bearer?['officer          per_standard_bearer']:[]),`attributes       ${attrs.join(', ')}`,`formation        ${sk?'1.4, 1.8, 2.8, 3.6, 3, square':E[u.p].form}`,'stat_health      1, 0',`stat_pri         ${u.w.damage}, 0, ${u.w.family}_bullet_${proj}, ${range}, 35, missile, missile_gunpowder, piercing, none, ${u.w.smoke}, 0, -999`,'stat_pri_attr    ap',`stat_sec         ${q.melee}, ${q.charge}, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1.2`,'stat_sec_attr    ap, short_pike',`stat_pri_armour  3, ${q.def}, 0, leather`,'stat_sec_armour  0, 0, flesh','stat_heat        0','stat_ground      0, 0, 0, 0',`stat_mental      ${q.morale}, ${u.type.startsWith('per_montoneros')?'impetuous':q.disc}, ${q.train}`,'stat_charge_dist 40','stat_fire_delay  0','stat_food        60, 300',`stat_cost        ${cost(total,u.limit)}`,'ownership        denmark, slave',`era ${E[u.p].n}            denmark`].join('\n');}
function cavRecord(u){const q=Q[u.quality],command=u.kind==='command';let total,rows,attrs=['free_upkeep_unit','sea_faring','hide_forest','can_withdraw'];if(u.kind==='pistol'){total=1400;attrs.push('guncavalry','gunmen','start_not_skirmishing','cannot_skirmish');rows=['stat_pri         20, 2, magazine_rifle_bullet_c, 60, 15, missile, missile_gunpowder, piercing, none, musket_shot_set, 25, 1','stat_pri_attr    ap',`stat_sec         ${q.melee}, ${q.charge}, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1`,'stat_sec_attr    no'];}
else if(u.kind==='lance'){total=1200;attrs.push('can_formed_charge');rows=[`stat_pri         ${q.melee}, ${q.charge+3}, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1`,'stat_pri_attr    no',`stat_sec         ${q.melee}, ${q.charge}, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1`,'stat_sec_attr    no'];}
else if(u.kind==='carbine'){total=1700;attrs.push('guncavalry','gunmen','start_not_skirmishing','cannot_skirmish','stakes');rows=['stat_pri         24, 2, rifle_carbine_bullet_c, 220, 35, missile, missile_gunpowder, piercing, none, musket_shot_set, 25, 1','stat_pri_attr    ap',`stat_sec         ${q.melee}, ${q.charge}, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1`,'stat_sec_attr    no'];}
else {total=200;attrs.push('general_unit','command');rows=[`stat_pri         ${q.melee}, ${q.charge}, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1`,'stat_pri_attr    no','stat_sec         0, 0, no, 0, 0, no, melee_simple, blunt, none, 0, 1','stat_sec_attr    no'];}
return [`type             ${u.type}`,`dictionary       ${u.type} ; ${u.label} (${command?'mounted command':u.kind==='pistol'?'Revolver Lefaucheux Modelo 1858 and sabre':u.kind==='lance'?'lance and sabre':'Remington Rolling Block cavalry carbine and sabre'})`,'category         cavalry',`class            ${u.kind==='carbine'?'missile':'light'}`,'voice_type       Heavy','accent           spanish','banner faction   main_cavalry','banner holy      crusade_cavalry',`soldier          ${u.type}, ${command?4:32}, 0, 1`,'officer          fra_off_1g',`mount            ${u.kind==='lance'?'lancer':'hussar'}`,'mount_effect     elephant -4, camel -4',`attributes       ${attrs.join(', ')}`,`formation        2, 2, 4, 4, ${command?2:3}, square`,'stat_health      1, 0',...rows,`stat_pri_armour  4, ${q.def}, 0, leather`,'stat_sec_armour  0, 0, flesh','stat_heat        0','stat_ground      0, 0, 0, 0',`stat_mental      ${q.morale}, ${q.disc}, ${q.train}`,'stat_charge_dist 45','stat_fire_delay  0','stat_food        60, 300',`stat_cost        ${cost(total,1,command?1:3)}`,'ownership        denmark, slave',...u.eras.map(e=>`era ${e}            denmark`)].join('\n');}
const all=[...inf,...cav],records=all.map(u=>u.kind?cavRecord(u):infRecord(u));
const legacy=['mex_foot_denmark','rus_conscript_de','tzar_inf','peru_foot','peru_carb','peru_early_inf','bol_hussar','peru_hussars','fra_sailors_denmark','gaucho_cav','merc_us_farmers'];
function stripDenmark(b){b=b.replace(/^ownership\s+(.+)$/m,(m,x)=>{const a=x.split(',').map(s=>s.trim()).filter(s=>s&&s!=='denmark');return `ownership        ${a.length?a.join(', '):'slave'}`;});b=b.replace(/^era ([012])\s+(.+)$/gm,(m,e,x)=>{const a=x.split(',').map(s=>s.trim()).filter(s=>s&&s!=='denmark');return a.length?`era ${e}            ${a.join(', ')}`:'';});return b.replace(/\n{3,}/g,'\n\n');}
for(const f of [eduC,eduR,edbC,edbR,modelP,locP,stratC,stratR])if(fs.existsSync(f)){fs.mkdirSync(backup,{recursive:true});const d=path.join(backup,path.basename(f));if(!fs.existsSync(d))fs.copyFileSync(f,d);}
let edu=fs.readFileSync(eduC,'utf8').replace(/\r\n/g,'\n');const begin='; BEGIN STANDARDIZED PERU',end='; END STANDARDIZED PERU';if(edu.includes(begin)){const a=edu.indexOf(begin),z=edu.indexOf(end,a);edu=edu.slice(0,a)+edu.slice(z+end.length).replace(/^\s*/,'');}
let ms=[...edu.matchAll(/^type\s+(\S+)/gm)],parts=[edu.slice(0,ms[0].index)];for(let i=0;i<ms.length;i++){let b=edu.slice(ms[i].index,i+1<ms.length?ms[i+1].index:edu.length);if(legacy.includes(ms[i][1]))b=stripDenmark(b);parts.push(b);}edu=parts.join('');const at=edu.indexOf('type             mex_foot_denmark');if(at<0)throw Error('Peru insertion point missing');edu=edu.slice(0,at)+`${begin}\n\n${records.join('\n\n')}\n\n${end}\n\n`+edu.slice(at);fs.writeFileSync(eduC,edu.replace(/\n/g,'\r\n'));fs.writeFileSync(eduR,edu.replace(/\n/g,'\r\n'));

function ungate(line){return line.replace(/\s+and (?:not )?event_counter military_reforms_(?:1870|1890|1) 1/g,'');}
function gate(line,type,when){let s=ungate(line).replace(/recruit_pool "[^"]+"/,`recruit_pool "${type}"`);return s+(when==='early'?' and not event_counter military_reforms_1870 1':when==='mid'?' and event_counter military_reforms_1870 1 and not event_counter military_reforms_1890 1':when==='high'?' and event_counter military_reforms_1890 1':'');}
let edb=fs.readFileSync(edbC,'utf8').split(/\r?\n/).flatMap(line=>{if(!line.includes('recruit_pool'))return [line];if(line.includes('"peru_early_inf"'))return [gate(line,'per_line_early','early'),gate(line,'per_guard_early','early'),gate(line,'per_cazadores_early','early'),gate(line,'per_montoneros_early','early')];if(line.includes('"rus_conscript_de"'))return [gate(line,'per_line_mid','mid'),gate(line,'per_line_high','high'),gate(line,'per_cazadores_mid','mid'),gate(line,'per_cazadores_high','high')];if(line.includes('"tzar_inf"'))return [gate(line,'per_guard_mid','mid'),gate(line,'per_guard_high','high')];if(line.includes('"peru_foot"'))return [gate(line,'per_montoneros_mid','mid')];if(line.includes('"peru_carb"'))return [gate(line,'per_lanceros_torata','early'),gate(line,'per_lanceros_torata','mid'),gate(line,'per_carabineros_torata','high')];if(line.includes('"bol_hussar"')&&line.includes('denmark'))return [gate(line,'per_husares_junin','all')];if(line.includes('"peru_hussars"'))return [gate(line,'per_general_staff','all')];if(line.includes('"fra_sailors_denmark"'))return [gate(line,'per_marines_mid','mid'),gate(line,'per_marines_high','high')];return [line];}).join('\r\n');fs.writeFileSync(edbC,edb);fs.writeFileSync(edbR,edb);
for(const p of [stratC,stratR])if(fs.existsSync(p)){let s=fs.readFileSync(p,'utf8');const aliases={peru_early_inf:'per_line_early',rus_conscript_de:'per_line_mid',tzar_inf:'per_guard_mid',peru_foot:'per_montoneros_mid',peru_carb:'per_lanceros_torata',bol_hussar:'per_husares_junin',peru_hussars:'per_general_staff',fra_sailors_denmark:'per_marines_mid'};for(const [a,b] of Object.entries(aliases))s=s.replace(new RegExp(`(?<=type\\s+)${a}(?=\\s+exp)`,'g'),b);fs.writeFileSync(p,s);}

function entries(text){const a=text.replace(/\r\n/g,'\n').split('\n'),r=[];let start=1;for(let i=1;i<a.length;i++)if(/^16 -0\.090000004 /.test(a[i])){r.push({lines:a.slice(start,i+1),name:(a[start].match(/^\d+ (\S+)/)||[])[1]});start=i+1;}return r;}
function entry(text,n){const e=entries(text).find(x=>x.name===n);if(!e)throw Error('Missing model donor '+n);return e.lines.join('\n');}
function counted(s,a,b){return s.split(`${a.length} ${a}`).join(`${b.length} ${b}`);}
function clone(text,donor,name,anim){let e=entry(text,donor);e=e.replace(new RegExp(`^${donor.length} ${donor}\\s*$`,'m'),`${name.length} ${name} `);if(anim){const a=anim==='muzzle'?'20 MTW2_Fast_Arquebus_3':anim==='skirm'?'15 MTW2_Musket_SSK':anim==='mag'?'20 MTW2_Fast_Arquebus_3':'14 MTW2_Musket_SS';e=e.replace(/(?:20 MTW2_Fast_Arquebus_3|18 MTW2_Fast_Arquebus|18 MTW2_Fast_Musket_3|14 MTW2_Musket_SS|15 MTW2_Musket_SSK)(?=\s)/,a);}return e;}
let model=fs.readFileSync(modelP,'utf8').replace(/\r\n/g,'\n'),added=0;
function put(name,fresh){if(entries(model).some(x=>x.name===name))model=model.replace(entry(model,name),fresh);else{model=model.trimEnd()+'\n'+fresh+'\n';added++;}}
for(const u of inf){const anim=u.w.muzzle?'muzzle':u.role==='skirmisher'?'skirm':u.w===W.mauser?'mag':'line';put(u.type,clone(model,u.donor,u.type,anim));}
for(const u of cav){let fresh=clone(model,u.donor,u.type);if(u.kind==='lance')fresh=fresh.replace(/^5 spain\s*$/gm,'7 denmark ');if(u.kind==='command')fresh=fresh.replace(/16 MTW2_CR_Arquebus 9 MTW2_Pike\s*\n1\s*\n24 MTW2_HR_Arquebus_Primary\s*\n1\s*\n18 MTW2_Sword_Primary/,'13 MTW2_HR_Sword 0 \n1 \n18 MTW2_Sword_Primary \n0');put(u.type,fresh);}
{let fresh=clone(model,'mex_standard_bearer','per_standard_bearer');fresh=fresh.replace(/^8 scotland\s*$/gm,'7 denmark ');fresh=counted(fresh,'unit_models/_Units/bnw/textures/mex_standard_bearer.texture','unit_models/_Units/bnw/textures/per_standard_bearer.texture');fresh=counted(fresh,'unit_models/_Units/bnw/textures/mex_standard_flag.texture','unit_models/_Units/bnw/textures/per_standard_flag.texture');fresh=counted(fresh,'unit_models/_Units/bnw/textures/mex_standard_flag_n.texture','unit_models/_Units/bnw/textures/per_standard_flag_n.texture');put('per_standard_bearer',fresh);}
if(added){const h=model.match(/^(22 serialization::archive 3 0 0 0 0 )(\d+)( 0 0 )/);if(!h)throw Error('Bad modeldb header');model=model.replace(h[0],`${h[1]}${+h[2]+added}${h[3]}`);}fs.writeFileSync(modelP,model.replace(/\n/g,'\r\n'));

let raw=fs.readFileSync(locP),loc=raw.slice(raw[0]===255&&raw[1]===254?2:0).toString('utf16le').replace(/\r\n/g,'\n');for(const u of all)for(const k of [u.type,u.type+'_descr',u.type+'_descr_short'])loc=loc.replace(new RegExp(`^\\{${k}\\}.*(?:\\n|$)`,'gm'),'');const desc={
 'Infanteria de Linea':'Regular infantry of the Peruvian Republic, equipped according to the reforms and available imports of their period.',
 'Guardia Nacional':'Citizen infantry mobilised in large numbers to reinforce Peru’s small standing army.',
 'Cazadores':'Light infantry trained to fight in open order and engage targets beyond the main line.',
 'Montoneros':'Locally raised irregular riflemen accustomed to broken country and decentralised fighting.',
 'Infanteria de Marina':'Naval infantry serving ashore and aboard Peruvian warships.',
 'Husares de Junin':'Prestigious Peruvian cavalry descended from the regiment celebrated at Junin.',
 'Lanceros de Torata':'Peruvian regular cavalry armed with Western-pattern lances and sabres.',
 'Carabineros de Torata':'Late-period mounted riflemen carrying Remington Rolling Block cavalry carbines.',
 'General y Estado Mayor':'A mounted commander and the small staff required to direct the army in battle.'};
const rows=all.map(u=>{let equip=u.kind?(u.kind==='pistol'?'Revolver Lefaucheux Modelo 1858 and sabre':u.kind==='lance'?'lance and sabre':u.kind==='carbine'?'Remington Rolling Block cavalry carbine and sabre':'mounted command'):u.w.name;return `{${u.type}}${u.label}\n{${u.type}_descr}${desc[u.label]}\n{${u.type}_descr_short}${u.label} (${equip})`;});loc=loc.trimEnd()+'\n\n'+rows.join('\n\n')+'\n';fs.writeFileSync(locP,Buffer.concat([Buffer.from([255,254]),Buffer.from(loc.replace(/\n/g,'\r\n'),'utf16le')]));

fs.mkdirSync(archive,{recursive:true});for(const n of ['peru_early_inf','rus_conscript_de','tzar_inf','peru_roy_inf','peru_foot','fra_sailors_denmark','bol_hussar','peru_carb','peru_hussars']){const s=path.join(cards,'#'+n+'.tga'),d=path.join(archive,'#'+n+'.tga');if(fs.existsSync(s)&&!fs.existsSync(d))fs.copyFileSync(s,d);}for(const u of all){let src;if(u.cardFrom)src=path.join(root,'data/ui/units',u.cardFrom[0],'#'+u.cardFrom[1]+'.tga');else src=path.join(cards,'#'+u.card+'.tga');const dst=path.join(cards,'#'+u.type+'.tga');if(!fs.existsSync(src))throw Error('Missing card donor '+src);fs.copyFileSync(src,dst);}
if(!fs.readFileSync(eduC).equals(fs.readFileSync(eduR)))throw Error('EDU mirrors differ');if(!fs.readFileSync(edbC).equals(fs.readFileSync(edbR)))throw Error('EDB mirrors differ');console.log(`Standardized Peru: ${records.length} records; added ${added} model entries.`);
