const fs=require('fs'),path=require('path'),R=path.resolve(__dirname,'..');
const EDU=path.join(R,'data/tow_steamsteel/export_descr_unit.txt'),MIR=path.join(R,'data/export_descr_unit.txt'),LOC=path.join(R,'data/text/export_units.txt');
const BACK=path.join(R,'tools/backup_before_zulu_20260918');fs.mkdirSync(BACK,{recursive:true});for(const p of [EDU,MIR,LOC]){const d=path.join(BACK,path.basename(p));if(!fs.existsSync(d))fs.copyFileSync(p,d)}
let e=fs.readFileSync(EDU,'utf8').replace(/\r/g,'');
function block(t){const m=e.match(new RegExp(`^type\\s+${t}\\n[\\s\\S]*?(?=^type\\s+|(?![\\s\\S]))`,'m'));if(!m)throw Error('missing '+t);return m[0].trimEnd()}
function rep(t,b){e=e.replace(block(t),b.trimEnd())} function unit(t,x){rep(t,`type             ${t}\n${x.join('\n')}`)} const keep=n=>Math.round(n/3),cost=(n,l=1,time=1)=>`${time}, ${n}, ${keep(n)}, 100, 100, ${n}, ${l}, ${keep(n)}`;
const base=(t,label,soldier,count,q,shield,eras,limit=1)=>{const Q={militia:[4,3,1,3,500],regular:[6,4,2,4,700],elite:[8,5,3,6,900]}[q];return [`dictionary       ${t} ; ${label}`,'category         infantry','class            light','voice_type       Heavy','banner faction   main_infantry','banner holy      crusade',`soldier          ${soldier}, ${count}, 0, 1.0`,'attributes       free_upkeep_unit, sea_faring, hide_forest','formation        1.2, 1.2, 2.4, 2.8, 6, square','stat_health      1, 0',`stat_pri         ${Q[0]}, ${Q[1]}, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1`,'stat_pri_attr    no',`stat_sec         0, 0, no, 0, 0, no, melee_simple, blunt, none, 25, 1`,'stat_sec_attr    no',`stat_pri_armour  3, ${Q[2]}, ${shield}, flesh`,'stat_sec_armour  0, 0, flesh','stat_heat        2','stat_ground      0, 0, 0, 0',`stat_mental      ${Q[3]}, impetuous, ${q==='elite'?'highly_trained':'trained'}`,'stat_charge_dist 30','stat_fire_delay  0','stat_food        60, 300',`stat_cost        ${cost(Q[4],limit)}`,'ownership        lith, slave',...eras.map(n=>`era ${n}            lith, slave`)];};
unit('zulu_spearmen',base('zulu_spearmen','Amabutho amaXhosa','zulu_spearmen',96,'militia',4,[0,1,2],2));
unit('zulu_royals',base('zulu_royals','Amabutho Amadala','zulu_royals',80,'elite',4,[0,1,2],1));
let guard=base('zulu_guard','Amabutho amaZulu','zulu_guard',96,'regular',4,[0,1,2],3);guard=guard.map(x=>x.startsWith('stat_pri         ')?'stat_pri         5, 4, javelin, 60, 1, thrown, missile_mechanical, piercing, spear, 25, 1':x.startsWith('stat_pri_attr')?'stat_pri_attr    prec, thrown':x.startsWith('stat_sec         ')?'stat_sec         6, 4, no, 0, 0, melee, melee_blade, blunt, mace, 25, 1':x.startsWith('stat_sec_attr')?'stat_sec_attr    no':x);unit('zulu_guard',guard);
unit('zulu_rifles',[`dictionary       zulu_rifles ; Ibutho Lezibhamu (Pattern 1853 Enfield Rifle-Musket)`,`category         infantry`,`class            missile`,`voice_type       Light`,`banner faction   main_missile`,`banner holy      crusade`,`soldier          zulu_rifles, 30, 0, 1.0`,`attributes       free_upkeep_unit, sea_faring, hide_forest, can_withdraw, gunpowder_unit, gunmen, start_not_skirmishing, stakes`,`formation        1.4, 1.8, 2.8, 3.6, 3, square`,`stat_health      1, 0`,`stat_pri         37, 0, rifled_musket_bullet_b, 260, 35, missile, missile_gunpowder, piercing, none, musket_shot_set, 0, -999`,`stat_pri_attr    ap`,`stat_sec         5, 3, no, 0, 0, melee, melee_blade, slashing, sword, 25, 1`,`stat_sec_attr    no`,`stat_pri_armour  3, 1, 0, flesh`,`stat_sec_armour  0, 0, flesh`,`stat_heat        2`,`stat_ground      0, 0, 0, 0`,`stat_mental      3, impetuous, untrained`,`stat_charge_dist 30`,`stat_fire_delay  0`,`stat_food        60, 300`,`stat_cost        ${cost(1000,1,2)}`,`ownership        lith, slave`,`era 2            lith, slave`]);
unit('zulu_elite',[`dictionary       zulu_elite ; iNduna Nezikhulu (Trade Musket)`,`category         infantry`,`class            light`,`voice_type       Heavy`,`banner faction   main_infantry`,`banner holy      crusade`,`soldier          zulu_elite, 4, 0, 1.3`,`attributes       free_upkeep_unit, sea_faring, command, general_unit, gunpowder_unit, gunmen, start_not_skirmishing`,`formation        1.2, 1.2, 2.4, 2.8, 2, square`,`stat_health      1, 0`,`stat_pri         37, 0, musket_bullet_c, 200, 15, missile, missile_gunpowder, piercing, none, musket_shot_set, 0, -999`,`stat_pri_attr    ap`,`stat_sec         9, 5, no, 0, 0, melee, melee_blade, slashing, sword, 25, 1`,`stat_sec_attr    no`,`stat_pri_armour  3, 3, 0, flesh`,`stat_sec_armour  0, 0, flesh`,`stat_heat        2`,`stat_ground      0, 0, 0, 0`,`stat_mental      6, impetuous, highly_trained`,`stat_charge_dist 30`,`stat_fire_delay  0`,`stat_food        60, 300`,`stat_cost        ${cost(200,1,1)}`,`ownership        lith, slave`,`era 0            lith, slave`,`era 1            lith, slave`,`era 2            lith, slave`]);
for(const t of ['zulu_cav','merc_zulu_rifles','africa_cav','african_warband','zul_maxim','zul_12lb','zul_5lb','zul_gatling','zul_armstrong']){let x=block(t).replace(/,?\s*lith,?/g,',').replace(/,\s*,/g,',').replace(/\s+,/g,',').replace(/,\s*$/gm,'').replace(/^era [012]\s*$/gm,'');rep(t,x)}
e=e.replace(/^ownership,\s*/gm,'ownership        ').replace(/^era ([012]),\s*/gm,'era $1            ').replace(/^era [012]\s*$/gm,'').replace(/\n/g,'\r\n');fs.writeFileSync(EDU,e);fs.writeFileSync(MIR,e);
let buf=fs.readFileSync(LOC),bom=buf[0]===255&&buf[1]===254,s=buf.subarray(bom?2:0).toString('utf16le');const names={zulu_spearmen:'Amabutho amaXhosa',zulu_guard:'Amabutho amaZulu',zulu_royals:'Amabutho Amadala',zulu_rifles:'Ibutho Lezibhamu',zulu_elite:'iNduna Nezikhulu'};for(const[k,v]of Object.entries(names)){for(const suf of ['', '_descr_short']){const key=`${k}${suf}`,re=new RegExp(`\\{${key}\\}[^\\r\\n]*`);if(re.test(s))s=s.replace(re,`{${key}}${v}`)}}fs.writeFileSync(LOC,Buffer.concat([Buffer.from([255,254]),Buffer.from(s,'utf16le')]));
console.log('Standardized Zulu as D tier with +2 melee, +1 charge, and +1 morale; excluded unsuitable cavalry, duplicate auxiliaries, and artillery.');
