const fs=require('fs'),path=require('path');
const R=path.resolve(__dirname,'..'), EDU=path.join(R,'data/tow_steamsteel/export_descr_unit.txt');
const MIR=path.join(R,'data/export_descr_unit.txt'), LOC=path.join(R,'data/text/export_units.txt');
const BACK=path.join(R,'tools/backup_before_turkestan_20260916'); fs.mkdirSync(BACK,{recursive:true});
for(const p of [EDU,MIR,LOC]){const d=path.join(BACK,path.basename(p));if(!fs.existsSync(d))fs.copyFileSync(p,d)}
let e=fs.readFileSync(EDU,'utf8').replace(/\r/g,'');
function block(t){const m=e.match(new RegExp(`^type\\s+${t}\\n[\\s\\S]*?(?=^type\\s+|(?![\\s\\S]))`,'m'));if(!m)throw Error('missing '+t);return m[0].trimEnd()}
function rep(t,b){e=e.replace(block(t),b.trimEnd())}
function unit(t,lines){const old=block(t), keep=[];for(const key of ['officer','mount','mount_effect','move_speed_mod']){for(const m of old.matchAll(new RegExp(`^${key}\\s+.*$`,'gm')))keep.push(m[0])}rep(t,[`type             ${t}`,...lines].join('\n'))}
const cost=(n,lim,time=2)=>`${time}, ${n}, ${Math.round(n/3)}, 100, 100, ${n}, ${lim}, ${Math.round(n/3)}`;
unit('kok_spears',[`dictionary       kok_spears ; Cherik Nayzadorlar`,`category         infantry`,`class            spearmen`,`voice_type       Heavy`,`accent           eastern_european`,`banner faction   main_spear`,`banner holy      crusade`,`soldier          kok_spears, 80, 0, 1`,`attributes       free_upkeep_unit, sea_faring, hide_forest`,`formation        1.2, 1.2, 1.2, 1.2, 3, square`,`stat_health      1, 0`,`stat_pri         2, 2, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1`,`stat_pri_attr    no`,`stat_sec         0, 0, no, 0, 0, no, melee_simple, blunt, none, 0, 1`,`stat_sec_attr    no`,`stat_pri_armour  3, 1, 3, flesh`,`stat_sec_armour  0, 0, flesh`,`stat_heat        2`,`stat_ground      0, 0, 0, 0`,`stat_mental      2, low, untrained`,`stat_charge_dist 40`,`stat_fire_delay  0`,`stat_food        60, 300`,`stat_cost        ${cost(500,2,1)}`,`ownership        cuman`,`era 0            cuman`]);
function gun(t,name,soldier,quality,weapon,damage,proj,range,ammo,periods,limit,melee,charge,def,morale,disc,train,total,formation='1.2, 1.2, 1.2, 1.2, 3, square',attrs='free_upkeep_unit, sea_faring, hide_forest, gunpowder_unit, gunmen, start_not_skirmishing, cannot_skirmish',sec='spear',secattr='ap, short_pike'){
 unit(t,[`dictionary       ${t} ; ${name}`,`category         infantry`,`class            missile`,`voice_type       Light`,`accent           eastern_european`,`banner faction   main_missile`,`banner holy      crusade`,`soldier          ${soldier}, ${formation.startsWith('1.4')?30:40}, 0, 1`,`attributes       ${attrs}`,`formation        ${formation}`,`stat_health      1, 0`,`stat_pri         ${damage}, 0, ${proj}, ${range}, ${ammo}, missile, missile_gunpowder, piercing, none, musket_shot_set, 0, -999`,`stat_pri_attr    ap`,`stat_sec         ${melee}, ${charge}, no, 0, 0, melee, melee_blade, ${sec==='axe'?'slashing':'piercing'}, ${sec}, 25, 1`,`stat_sec_attr    ${secattr}`,`stat_pri_armour  3, ${def}, ${t==='buk_guard'?2:0}, leather`,`stat_sec_armour  0, 0, flesh`,`stat_heat        2`,`stat_ground      0, 0, 0, 0`,`stat_mental      ${morale}, ${disc}, ${train}`,`stat_charge_dist 40`,`stat_fire_delay  0`,`stat_food        60, 300`,`stat_cost        ${cost(total,limit,2)}`,`ownership        cuman, slave`,...periods.map(p=>`era ${p}            cuman, slave`)]);
}
gun('turkmen_inf','Tufangchilar (Matchlock Musket)','turkmen_inf','militia','matchlock',32,'arquebus_bullet_c',160,35,[0,1],2,3,2,1,2,'low','untrained',700,'1.2, 1.2, 1.2, 1.2, 3, square',undefined,'sword','no');
gun('ghulja_inf','Ghulja Tufangchilari (Arquebus)','ghulja_inf','militia','arquebus',32,'arquebus_bullet_c',200,35,[0,1],1,2,2,1,2,'low','untrained',700,'1.4, 1.8, 2.8, 3.6, 3, square',undefined,'axe','ap');
gun('buk_guard','Darkhan Ovchilari (Hand-Crafted Long Gun)','buk_guard','militia','long gun',29,'rifled_musket_bullet_c',260,35,[0],1,2,2,1,2,'impetuous','trained',1000,'1.4, 1.8, 2.8, 3.6, 3, square',undefined,'axe','ap');
gun('kok_ww1','Bahodirlar (Model 1828 Musket)','kok_ww1','regular','musket',37,'musket_bullet_c',200,35,[0,1],1,4,3,2,3,'low','trained',1000);
gun('kashgar_inf','Sarbazlar (M1844 Percussion Musket)','kashgar_inf','regular','musket',37,'musket_bullet_c',200,35,[1],2,4,3,2,3,'low','trained',1000);
gun('kok_inf','Sarbazlar (Late; Berdan II Rifle)','kok_inf','regular','rifle',19,'rifle_bullet_c',240,35,[2],3,4,3,2,3,'low','trained',1500,'1.2, 1.4, 2.4, 2.8, 3, square','free_upkeep_unit, sea_faring, hide_forest, gunmen, start_not_skirmishing, cannot_skirmish, stakes');
function cav(t,name,soldier,kind,proj,range,ammo,melee,charge,def,morale,disc,train,total,limit,eras,mount='lancer'){
 const gun=!!proj; unit(t,[`dictionary       ${t} ; ${name}`,`category         cavalry`,`class            ${gun?'missile':'light'}`,`voice_type       Heavy`,`accent           eastern_european`,`banner faction   main_cavalry`,`banner holy      crusade_cavalry`,`soldier          ${soldier}, 24, 0, 1`,`mount            ${mount}`,`mount_effect     elephant -4, camel -4`,`attributes       free_upkeep_unit, sea_faring, can_withdraw, hide_forest${gun?', gunpowder_unit, gunmen, guncavalry, start_not_skirmishing':''}`,`formation        2, 2, 4, 4, 3, square`,`stat_health      1, 0`,gun?`stat_pri         32, 0, ${proj}, ${range}, ${ammo}, missile, missile_gunpowder, piercing, none, musket_shot_set, 50, 1`:`stat_pri         ${melee}, ${charge+3}, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1`,`stat_pri_attr    ${gun?'ap':'no'}`,`stat_sec         ${melee}, ${charge}, no, 0, 0, melee, melee_blade, ${gun?'slashing':'piercing'}, sword, 25, 1`,`stat_sec_attr    no`,`stat_pri_armour  4, ${def}, 0, leather`,`stat_sec_armour  0, 0, flesh`,`stat_heat        2`,`stat_ground      0, 0, 0, 0`,`stat_mental      ${morale}, ${disc}, ${train}`,`stat_charge_dist 50`,`stat_fire_delay  0`,`stat_food        60, 300`,`stat_cost        ${cost(total,limit,3)}`,`ownership        cuman, slave`,...eras.map(p=>`era ${p}            cuman, slave`)]);
}
cav('kok_cav','Jigitlar','kok_cav','lance',null,0,0,4,3,2,3,'low','trained',1200,3,[0,1,2]);
cav('kok_royal_cav','Turkman Otliqlari (Matchlock Carbine)','kok_royal_cav','gun','arquebus_bullet_c',140,35,4,3,2,3,'impetuous','trained',1100,2,[0,1,2]);
cav('kaz_cav','Qozoq Otliqlari (Arquebus)','kaz_cav','gun','arquebus_bullet_c',140,35,2,2,1,2,'impetuous','untrained',900,1,[0,1,2]);
cav('uyghur_camel_cav','Uygur Tuyachilari (Arquebus)','uyghur_camel_cav','gun','arquebus_bullet_c',140,35,2,2,1,2,'low','untrained',900,1,[0,1,2],'camel');
unit('kok_rcav',[`dictionary       kok_rcav ; Qorboshi va Mulozimlar`,`category         cavalry`,`class            light`,`voice_type       Heavy`,`accent           eastern_european`,`banner faction   main_cavalry`,`banner holy      crusade_cavalry`,`soldier          kok_rcav, 4, 0, 1`,`officer          kok_rcav`,`mount            lancer`,`mount_effect     elephant -8, camel -4`,`attributes       free_upkeep_unit, sea_faring, general_unit, command`,`formation        2, 2, 4, 4, 2, square`,`stat_health      1, 0`,`stat_pri         6, 4, no, 0, 0, melee, melee_blade, slashing, sword, 25, 1`,`stat_pri_attr    no`,`stat_sec         0, 0, no, 0, 0, no, melee_simple, blunt, none, 0, 1`,`stat_sec_attr    no`,`stat_pri_armour  4, 3, 0, leather`,`stat_sec_armour  0, 0, flesh`,`stat_heat        2`,`stat_ground      0, 0, 0, 0`,`stat_mental      5, normal, highly_trained`,`stat_charge_dist 50`,`stat_fire_delay  0`,`stat_food        60, 300`,`stat_cost        ${cost(200,1,1)}`,`ownership        cuman, slave`,`era 0            cuman, slave`,`era 1            cuman, slave`,`era 2            cuman, slave`]);
// Keep the unique barrier but rationalise custom-battle availability.
let w=block('camel_wagon').replace(/^dictionary.*$/m,'dictionary       camel_wagon ; Arava Tosiqlari (Wall Gun)').replace(/^class\s+.*$/m,'class            missile').replace(/^stat_fire_delay.*$/m,'stat_fire_delay  0').replace(/^stat_cost.*$/m,'stat_cost        2, 1700, 567, 100, 100, 1700, 1, 567');rep('camel_wagon',w);
// Remove Tibetan and duplicate mercenary records from Turkestan custom battles only.
for(const t of ['merc_kaz_inf','merc_kaz_cav','merc_kashgar_inf','merc_tib_noble_cav','tib_militia','merc_tib_inf','tib_horse_archer','tib_roy_inf','tib_tribal_archer','tib_heavy_spear']){
 let b=block(t).replace(/^(ownership\s+)(.*)$/m,(x,p,v)=>p+v.split(',').map(s=>s.trim()).filter(s=>s&&s!=='cuman').join(', '));
 b=b.replace(/^era(\s+[012]\s+)(.*)$/gm,(x,p,v)=>{const q=v.split(',').map(s=>s.trim()).filter(s=>s&&s!=='cuman');return q.length?'era'+p+q.join(', '):''}).replace(/\n{3,}/g,'\n\n');rep(t,b);
}
function artillery(t,eras,visible=true){let b=block(t).replace(/^stat_cost\s+([^\n]*,\s*)\d+,\s*([^,\n]+)$/m,(x,p,last)=>'stat_cost        '+p+'1, '+last);b=b.replace(/^ownership\s+.*$/m,visible?'ownership        cuman, slave':'ownership        slave').replace(/^era\s+[012].*$/gm,'').trimEnd();if(visible)for(const p of eras)b+=`\nera ${p}            cuman, slave`;rep(t,b)}
artillery('kok_armstrong',[0,1]); artillery('kok_5lb',[2]); artillery('kok_12lb',[2]); artillery('kok_maxim',[2]); artillery('kok_gatling',[],false); artillery('kok_150mm',[],false);
// These legacy meshes are visibly broken in battle. Remove the records
// completely: slave-only stubs still leak into this mod's custom battles.
for(const t of ['kaz_inf','kok_ww1','kaz_cav','merc_kaz_inf','merc_kaz_cav']){
 e=e.replace(block(t),'');
}
e=e.replace(/\n/g,'\r\n');fs.writeFileSync(EDU,e);fs.writeFileSync(MIR,e);
let mp=path.join(R,'data/unit_models/battle_models.modeldb'),m=fs.readFileSync(mp,'utf8');
function modelBlock(n){const re=new RegExp(`^${n.length} ${n}\\s*$[\\s\\S]*?(?=^\\d+ [^\\s;]+\\s*$\\r?\\n\\d+ \\d+\\s*$|(?![\\s\\S]))`,'m'),x=m.match(re);if(!x)throw Error('model '+n);return x[0]}
function modelRep(n,fn){const old=modelBlock(n),neo=fn(old);m=m.replace(old,neo)}
modelRep('turkmen_inf',b=>b.replace('19 MTW2_2H_Axe_primary','18 MTW2_Sword_Primary'));
modelRep('kok_inf',b=>b.replace('20 MTW2_Fast_Arquebus_3','14 MTW2_Musket_SS').replace('21 MTW2_Arquebus_Primary','19 MTW2_Musket_Primary'));
fs.writeFileSync(mp,m);
// Localisation is UTF-16LE with BOM in this project.
let raw=fs.readFileSync(LOC), bom=raw[0]===0xff&&raw[1]===0xfe, l=raw.subarray(bom?2:0).toString('utf16le').replace(/\r/g,'');
const names={kok_spears:['Cherik Nayzadorlar','Early spear levies of the khanate.'],turkmen_inf:['Tufangchilar','Irregular matchlock infantry.'],ghulja_inf:['Ghulja Tufangchilari','Frontier arquebus skirmishers.'],buk_guard:['Darkhan Ovchilari','Long-gun frontier skirmishers.'],kok_ww1:['Bahodirlar','Selected infantry armed with Model 1828 muskets.'],kashgar_inf:['Sarbazlar (Mid)','Russian-trained regular infantry with M1844 percussion muskets.'],kok_inf:['Sarbazlar (Late)','Russian-trained regular infantry with Berdan II rifles.'],kok_cav:['Jigitlar','Steppe lance-and-sabre cavalry.'],kok_royal_cav:['Turkman Otliqlari','Turkmen mounted matchlock gunmen.'],kaz_cav:['Qozoq Otliqlari','Regional Kazakh mounted arquebusiers.'],uyghur_camel_cav:['Uygur Tuyachilari','Uyghur camel-mounted arquebusiers.'],kok_rcav:['Qorboshi va Mulozimlar','The commander and his mounted staff.'],camel_wagon:['Arava Tosiqlari','A camel-drawn wagon barrier defended by wall guns.']};
for(const [k,[n,d]] of Object.entries(names)){for(const [s,v] of [[k,n],[k+'_descr',d],[k+'_descr_short',d]]){const re=new RegExp(`^\\{${s.replace(/[.*+?^${}()|[\\]\\\\]/g,'\\$&')}\\}.*$`,'m');l=re.test(l)?l.replace(re,`{${s}}${v}`):l+`\n{${s}}${v}`}}
fs.writeFileSync(LOC,Buffer.concat([Buffer.from([0xff,0xfe]),Buffer.from(l.replace(/\n/g,'\r\n'),'utf16le')]));
console.log('Standardized Turkestan D-tier roster and removed non-national Tibetan custom-battle ownership.');
