const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),eduC=path.join(root,'data/tow_steamsteel/export_descr_unit.txt'),eduR=path.join(root,'data/export_descr_unit.txt'),modelP=path.join(root,'data/unit_models/battle_models.modeldb'),locP=path.join(root,'data/text/export_units.txt'),soundP=path.join(root,'data/export_descr_sounds_units_voice.txt');
const E={early:{n:0,name:'Early',form:'1.2, 1.2, 1.2, 1.2, 3, square'},mid:{n:1,name:'Mid',form:'1.2, 1.2, 2.0, 2.4, 3, square'},high:{n:2,name:'Late',form:'1.2, 1.4, 2.4, 2.8, 3, square'}};
const cost=(n,limit=1,time=3)=>`${time}, ${n}, ${Math.round(n/3)}, 100, 100, ${n}, ${limit}, ${Math.round(n/3)}`;
const arms={
 minie:{name:'Greek Minié Rifle-Musket',damage:37,family:'rifled_musket',range:220,ammo:35,smoke:'musket_shot_set',muzzle:true,mode:'fast',base:1200},
 nafplion:{name:'Nafplion M1833 Percussion Musket',damage:37,family:'musket',range:200,ammo:35,smoke:'musket_shot_set',muzzle:true,mode:'fast',base:1000},
 chassepot:{name:'Chassepot M1866',damage:20,family:'rifle',range:240,ammo:35,smoke:'musket_shot_set',mode:'musket',base:1500},
 mylonas:{name:'Mylonas M1872',damage:20,family:'rifle',range:240,ammo:35,smoke:'musket_shot_set',mode:'musket',base:1500},
 gras:{name:'Greek Gras M1874/M80',damage:20,family:'rifle',range:240,ammo:35,smoke:'musket_shot_set',mode:'musket',base:1500}
};
const Q={militia:{melee:3,charge:2,def:2,morale:3,disc:'low',train:'trained',premium:-200},regular:{melee:5,charge:3,def:3,morale:4,disc:'low',train:'trained',premium:0},elite:{melee:7,charge:4,def:4,morale:6,disc:'normal',train:'highly_trained',premium:200}};
const letter=(quality,role)=>{let n=quality==='militia'?0:quality==='elite'?2:1;if(role==='skirmisher')n++;n--;return 'cbas'[Math.max(0,Math.min(3,n))];};
const inf=[];
function addInf(type,label,period,quality,role,arm,donor,limit=1){inf.push({type,label,period,quality,role,arm,donor,limit,...Q[quality]});}
for(const p of ['early','mid','high'])addInf(`gre_line_${p}`,'Pezikó',p,'regular','line',p==='early'?arms.minie:p==='mid'?arms.mylonas:arms.gras,p==='early'?'greek_early_inf':`gre_line_${p==='mid'?'early':'mid'}`,3);
addInf('gre_ethnofylaki_early','Ethnofylakí','early','militia','line',arms.nafplion,'greek_early_inf',2);
addInf('gre_efedroi_mid','Éfedroi','mid','militia','line',arms.chassepot,'gre_ethnofylaki_early',2);
addInf('gre_efedroi_high','Éfedroi','high','militia','line',arms.mylonas,'gre_efedroi_mid',2);
for(const p of ['early','mid','high'])addInf(`gre_evzones_${p}`,'Evzones',p,'elite','skirmisher',p==='early'?arms.minie:p==='mid'?arms.mylonas:arms.gras,p==='early'?'evzones_inf':`gre_evzones_${p==='mid'?'early':'mid'}`);
for(const p of ['early','mid','high'])addInf(`gre_marines_${p}`,'Naftikó Ágima',p,'regular','line',p==='early'?arms.minie:p==='mid'?arms.chassepot:arms.gras,p==='early'?'austro_sailor_spain_early':`gre_marines_${p==='mid'?'early':'mid'}`);
function infantry(u){const a=u.arm,attrs=['free_upkeep_unit','sea_faring','hide_forest'];if(a.muzzle)attrs.push('gunpowder_unit');attrs.push('gunmen','start_not_skirmishing','cannot_skirmish');if(u.period==='high')attrs.push('stakes');return [`type             ${u.type}`,`dictionary       ${u.type} ; ${u.label} (${E[u.period].name}; ${a.name})`,'category         infantry','class            missile','voice_type       Light','accent           greek','banner faction   main_infantry','banner holy      crusade',`soldier          ${u.type}, ${u.role==='skirmisher'?30:40}, 0, 1.2`,'officer          fra_off_1g',...(u.period!=='high'?['officer          francejunqshou']:[]),`attributes       ${attrs.join(', ')}`,`formation        ${u.role==='skirmisher'?'1.4, 1.8, 2.8, 3.6, 3, square':E[u.period].form}`,'stat_health      1, 0',`stat_pri         ${a.damage}, 0, ${a.family}_bullet_${letter(u.quality,u.role)}, ${a.range+(u.role==='skirmisher'?40:0)}, ${a.ammo}, missile, missile_gunpowder, piercing, none, ${a.smoke}, 0, -999`,'stat_pri_attr    ap',`stat_sec         ${u.melee}, ${u.charge}, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1.2`,'stat_sec_attr    short_pike, ap',`stat_pri_armour  3, ${u.def}, 0, leather`,'stat_sec_armour  0, 0, flesh','stat_heat        0','stat_ground      0, 0, 0, 0',`stat_mental      ${u.morale}, ${u.disc}, ${u.train}`,'stat_charge_dist 40','stat_fire_delay  0','stat_food        60, 300',`stat_cost        ${cost(a.base+u.premium,u.limit)}`,'ownership        mongols, slave',`era ${E[u.period].n}            mongols`].join('\n');}
const cav=[
 {type:'gre_lancers',label:'Ipparchía Lonchistón',weapon:'lance and sabre',kind:'lance',donor:'aus_lancers',className:'light',quality:'regular',total:1200},
 {type:'gre_royal_escort',label:'Ágima',weapon:'Lefaucheux M1854 revolver and sabre',kind:'pistol',donor:'fra_hussar',className:'heavy',quality:'elite',total:1400},
 {type:'gre_carbineers_mid',label:'Ipparchía Akrovolistón',period:'mid',weapon:'Mylonas M1872 carbine and sabre',kind:'carbine',donor:'fra_cav',className:'missile',damage:20,projectile:'rifle_carbine_bullet_c',range:220,ammo:35,smoke:'musket_shot_set',quality:'regular',total:1700},
 {type:'gre_carbineers_high',label:'Ipparchía Akrovolistón',period:'high',weapon:'Steyr–Gras M1874 carbine and sabre',kind:'carbine',donor:'gre_carbineers_mid',className:'missile',damage:20,projectile:'rifle_carbine_bullet_c',range:220,ammo:35,smoke:'musket_shot_set',quality:'regular',total:1700},
 {type:'gre_general_staff',label:'Stratigós kai Epiteleío',weapon:'Lefaucheux M1854 revolver and sabre',kind:'pistol',donor:'fra_hussar',className:'heavy',quality:'elite',total:200,general:true}
];
function cavalry(u){const q=Q[u.quality],pistol=u.kind==='pistol',attrs=['free_upkeep_unit','sea_faring','hide_forest','can_withdraw'];if(u.kind!=='lance')attrs.push('guncavalry','gunmen','start_not_skirmishing','cannot_skirmish');if(u.kind==='carbine')attrs.push('stakes');if(u.general)attrs.push('general_unit','command');let pri,sec;if(u.kind==='lance'){pri=`5, 3, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1`;sec=`5, 3, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1`;}else{pri=pistol?'20, 4, magazine_rifle_bullet_c, 60, 15, missile, missile_gunpowder, piercing, none, musket_shot_set, 25, 1':`${u.damage}, 2, ${u.projectile}, ${u.range}, ${u.ammo}, missile, missile_gunpowder, piercing, none, ${u.smoke}, 25, 1`;sec=`${q.melee}, ${q.charge}, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1`;}return [`type             ${u.type}`,`dictionary       ${u.type} ; ${u.label}${u.period?` (${E[u.period].name}; ${u.weapon})`:` (${u.weapon})`}`,'category         cavalry',`class            ${u.className}`,'voice_type       Heavy','accent           greek','banner faction   main_cavalry','banner holy      crusade_cavalry',`soldier          ${u.type}, ${u.general?4:24}, 0, 1`,'officer          fra_off_1g','mount            hussar','mount_effect     elephant -4, camel -4',`attributes       ${attrs.join(', ')}`,`formation        2, 2, 4, 4, ${u.general?2:3}, square`,'stat_health      1, 0',`stat_pri         ${pri}`,`stat_pri_attr    ${u.kind==='lance'?'spear, ap':'ap'}`,`stat_sec         ${sec}`,'stat_sec_attr    ap',`stat_pri_armour  4, ${q.def}, 0, leather`,'stat_sec_armour  0, 0, flesh','stat_heat        0','stat_ground      0, 0, 0, 0',`stat_mental      ${q.morale}, ${q.disc}, ${q.train}`,'stat_charge_dist 45','stat_fire_delay  -20000','stat_food        60, 300',`stat_cost        ${cost(u.total)}`,'ownership        mongols, slave',...(u.period?[`era ${E[u.period].n}            mongols`]:['era 0            mongols','era 1            mongols','era 2            mongols'])].join('\n');}
const sapper=[`type             gre_sappers_high`,`dictionary       gre_sappers_high ; Michanikó (Late)`,`category         infantry`,`class            missile`,`voice_type       Heavy`,`accent           greek`,`banner faction   main_missile`,`banner holy      crusade`,`soldier          gr_inf1, 16, 0, 0.9`,`officer          fra_off_1g`,`attributes       free_upkeep_unit, sea_faring, hide_forest, incendiary, start_not_skirmishing, cannot_skirmish, stakes`,`formation        ${E.high.form}`,`stat_health      1, 0`,`stat_pri         7, 3, greek_fire, 60, 2, missile, missile_gunpowder, slashing, none, 25, 1`,`stat_pri_attr    ap, bp`,`stat_sec         7, 4, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1`,`stat_sec_attr    ap`,`stat_pri_armour  3, 4, 0, leather`,`stat_sec_armour  0, 0, flesh`,`stat_heat        0`,`stat_ground      0, 0, 0, 0`,`stat_mental      6, normal, highly_trained`,`stat_charge_dist 40`,`stat_fire_delay  0`,`stat_food        60, 300`,`stat_cost        ${cost(1600)}`,`ownership        mongols, slave`,`era 2            mongols`].join('\n');
const records=Object.fromEntries([...inf.map(u=>[u.type,infantry(u)]),...cav.map(u=>[u.type,cavalry(u)]),['gre_sappers_high',sapper]]);
const legacy={fra_hussar_mongols:['gre_general_staff','fra_hussar'],evzones_inf:['gre_evzones_mid','evzones_inf'],greek_roy:['gre_sappers_high','gr_inf1'],greek_guard_cav:['gre_carbineers_mid','fra_cav'],swed_inf:['gre_line_high','dutch_inf'],rom_cav:['gre_carbineers_high','rom_cav'],greek_early_inf:['gre_line_early','greek_early_inf']};
function alias(old,modern,soldier){return records[modern].replace(/^type\s+.*$/m,`type             ${old}`).replace(/^dictionary\s+\S+/m,`dictionary       ${old}`).replace(/^soldier\s+\S+,/m,`soldier          ${soldier},`).replace(/^ownership\s+.*$/m,'ownership        slave').replace(/^era [012]\s+mongols\n?/gm,'').trimEnd();}
const all=[...inf,...cav,{type:'gre_sappers_high',label:'Michanikó',period:'high',weapon:'Incendiary equipment',donor:'greek_roy'}];
const block=['; ============================================================================','; Greece (mongols) — standardized infantry and cavalry','; ============================================================================',...inf.map(infantry),...cav.map(cavalry),sapper,'; Legacy internal-name compatibility (not assigned to custom-battle eras)',...Object.entries(legacy).map(([o,[m,s]])=>alias(o,m,s))].join('\n\n')+'\n\n';
let edu=fs.readFileSync(eduC,'utf8').replace(/\r\n/g,'\n');const title=edu.indexOf('; Greece (mongols)'),start=edu.lastIndexOf('; ============================================================================',title),italy=edu.indexOf(';################ Kingdom of Italy',title),end=edu.lastIndexOf('\n;;;;;;;;;;;;;;;;',italy)+1;if(start<0||end<1)throw Error('Greece block not found');edu=edu.slice(0,start)+block+edu.slice(end);
for(const t of ['armenian_inf','rom_guard','it_royals_mongols','austro_sailor_mongols','balk_cav_mongols','bulgarian_inf_mongols']){const re=new RegExp(`(^type\\s+${t}\\s*$[\\s\\S]*?)(?=^type\\s+|^; =+|\\z)`,'m');const m=edu.match(re);if(!m)continue;const clean=m[1].replace(/^ownership\s+.*$/m,'ownership        slave').replace(/^era [012]\s+.*mongols.*\n?/gm,'');edu=edu.replace(m[1],clean);}
edu=edu.replace(/^accent\s+greek$/gm,'accent           Mediterranean');
const out=edu.replace(/\n/g,'\r\n');fs.writeFileSync(eduC,out);fs.writeFileSync(eduR,out);
function entry(text,name){const a=text.replace(/\r\n/g,'\n').split('\n'),i=a.findIndex(x=>new RegExp(`^${name.length} ${name}\\s*$`).test(x));if(i<0)throw Error(`Missing donor ${name}`);let j=i;while(j<a.length&&!/^16 -0\.090000004 /.test(a[j]))j++;return a.slice(i,j+1).join('\n');}
function clone(text,donor,name,mode,kind){let e=entry(text,donor).replace(new RegExp(`^${donor.length} ${donor}\\s*$`,'m'),`${name.length} ${name} `);if(mode==='musket')e=e.replace(/(?:20 MTW2_Fast_Arquebus_3|15 MTW2_Musket_SSK) 9 MTW2_Pike /,'14 MTW2_Musket_SS 9 MTW2_Pike ');if(mode==='skirmisher')e=e.replace(/(?:20 MTW2_Fast_Arquebus_3|14 MTW2_Musket_SS) 9 MTW2_Pike /,'15 MTW2_Musket_SSK 9 MTW2_Pike ');if(mode==='fast')e=e.replace(/(?:14 MTW2_Musket_SS|15 MTW2_Musket_SSK) 9 MTW2_Pike /,'20 MTW2_Fast_Arquebus_3 9 MTW2_Pike ');if(kind==='lance')e=e.replace(/^7 hungary\s*$/gm,'7 mongols ').replace(/^50 unit_models\/_Units\/aus\/textures\/aus_lan_1g\.texture\s*$/gm,'50 unit_models/_Units/gre/textures/gre_cav_2g.texture ');if(donor==='austro_sailor_spain_early')e=e.replace(/^5 spain\s*$/gm,'7 mongols ');if(kind==='sword')e=e.replace('14 MTW2_HR_Pistol 13 MTW2_HR_Spear','14 MTW2_HR_Pistol 13 MTW2_HR_Sword').replace('21 MTW2_HR_spear_Primary','18 MTW2_Sword_Primary');return e;}
const models=[];for(const u of inf)models.push([u.donor,u.type,u.role==='skirmisher'&&!u.arm.muzzle?'skirmisher':u.arm.mode,null]);for(const u of cav)models.push([u.donor,u.type,null,u.kind==='lance'?'lance':u.kind==='pistol'?'sword':null]);let model=fs.readFileSync(modelP,'utf8').replace(/\r\n/g,'\n'),added=0;for(const [d,n,m,k] of models){const fresh=clone(model,d,n,m,k);if(new RegExp(`^${n.length} ${n} $`,'m').test(model))model=model.replace(entry(model,n),fresh);else{model=model.trimEnd()+'\n'+fresh+'\n';added++;}}if(added){const h=model.match(/^(22 serialization::archive 3 0 0 0 0 )(\d+)( 0 0 )/);if(!h)throw Error('Bad modeldb header');model=model.replace(h[0],`${h[1]}${+h[2]+added}${h[3]}`);}fs.writeFileSync(modelP,model.replace(/\n/g,'\r\n'));
let buf=fs.readFileSync(locP),loc=buf.slice(buf[0]===255&&buf[1]===254?2:0).toString('utf16le').replace(/\r\n/g,'\n');for(const u of all)loc=loc.replace(new RegExp(`^\\{${u.type}(?:_descr|_descr_short)?\\}.*(?:\\n|$)`,'gm'),'');loc=loc.trimEnd()+'\n\n'+all.map(u=>`{${u.type}}${u.label}${u.period?` (${E[u.period].name})`:''}\n{${u.type}_descr}${u.label} serve in the Hellenic Army with the equipment and battlefield role appropriate to this period.\n{${u.type}_descr_short}${u.label} (${u.arm?u.arm.name:u.weapon})`).join('\n\n')+'\n';fs.writeFileSync(locP,Buffer.concat([Buffer.from([255,254]),Buffer.from(loc.replace(/\n/g,'\r\n'),'utf16le')]));
const aliasLoc={fra_hussar_mongols:['Stratigós kai Epiteleío','Lefaucheux M1854 revolver and sabre'],evzones_inf:['Evzones (Mid)','Mylonas M1872'],greek_roy:['Michanikó (Late)','Incendiary equipment'],greek_guard_cav:['Ipparchía Akrovolistón (Mid)','Mylonas M1872 carbine and sabre'],swed_inf:['Pezikó (Late)','Greek Gras M1874/M80'],rom_cav:['Ipparchía Akrovolistón (Late)','Steyr–Gras M1874 carbine and sabre'],greek_early_inf:['Pezikó (Early)','Greek Minié Rifle-Musket']};
buf=fs.readFileSync(locP);loc=buf.slice(2).toString('utf16le').replace(/\r\n/g,'\n');for(const t of Object.keys(aliasLoc))loc=loc.replace(new RegExp(`^\\{${t}(?:_descr|_descr_short)?\\}.*(?:\\n|$)`,'gm'),'');loc=loc.trimEnd()+'\n\n'+Object.entries(aliasLoc).map(([t,[label,weapon]])=>`{${t}}${label}\n{${t}_descr}${label} is retained as a campaign compatibility record for the standardized Hellenic roster.\n{${t}_descr_short}${label} (${weapon})`).join('\n\n')+'\n';fs.writeFileSync(locP,Buffer.concat([Buffer.from([255,254]),Buffer.from(loc.replace(/\n/g,'\r\n'),'utf16le')]));
const unitDir=path.join(root,'data/ui/units/mongols'),infoDir=path.join(root,'data/ui/unit_info/mongols');for(const u of all){const src=u.type.startsWith('gre_line_')||u.type.startsWith('gre_ethno')||u.type.startsWith('gre_efed')?'greek_early_inf':u.type.startsWith('gre_evzones_')?'evzones_inf':u.type.startsWith('gre_marines_')?'austro_sailor_mongols':u.type==='gre_sappers_high'?'greek_roy':u.type==='gre_lancers'?'balk_cav_mongols':u.type==='gre_royal_escort'||u.type==='gre_general_staff'?'fra_hussar_mongols':u.type.startsWith('gre_carbineers_')?'greek_guard_cav':'greek_early_inf';fs.copyFileSync(path.join(unitDir,`#${src}.tga`),path.join(unitDir,`#${u.type}.tga`));const isCav=cav.some(x=>x.type===u.type),candidates=[`${src}_info.tga`,isCav?'balk_cav_mongols_info.tga':'bulgarian_inf_mongols_info.tga'];const info=candidates.map(x=>path.join(infoDir,x)).find(fs.existsSync);if(info)fs.copyFileSync(info,path.join(infoDir,`${u.type}_info.tga`));}
fs.copyFileSync(path.join(root,'data/ui/units/hungary/#aus_lancers.tga'),path.join(unitDir,'#gre_lancers.tga'));
if(fs.existsSync(path.join(root,'data/ui/unit_info/hungary/aus_lancers_info.tga')))fs.copyFileSync(path.join(root,'data/ui/unit_info/hungary/aus_lancers_info.tga'),path.join(infoDir,'gre_lancers_info.tga'));
for(const p of ['early','mid','high']){fs.copyFileSync(path.join(root,`data/ui/units/spain/#austro_sailor_spain_${p}.tga`),path.join(unitDir,`#gre_marines_${p}.tga`));fs.copyFileSync(path.join(root,`data/ui/unit_info/spain/austro_sailor_spain_${p}_info.tga`),path.join(infoDir,`gre_marines_${p}_info.tga`));}
let sounds=fs.readFileSync(soundP,'utf8').replace(/\r\n/g,'\n');const tmpl=sounds.match(/(^\s*unit greek_early_inf\n\s*event\n\s*folder[^\n]+\n(?:\s+[^\n]+\.wav\n)+\s*end)/m);if(tmpl){const indent=tmpl[1].match(/^(\s*)unit/m)[1],adds=all.filter(u=>!new RegExp(`^\\s*unit ${u.type}$`,'m').test(sounds)).map(u=>tmpl[1].replace(`${indent}unit greek_early_inf`,`${indent}unit ${u.type}`));if(adds.length)sounds=sounds.replace(tmpl[1],tmpl[1]+'\n'+adds.join('\n'));fs.writeFileSync(soundP,sounds.replace(/\n/g,'\r\n'));}
const types=[...out.matchAll(/^type\s+(.+)$/gm)].map(m=>m[1].trim());if(new Set(types).size!==types.length)throw Error('Duplicate EDU types');if(!fs.readFileSync(eduC).equals(fs.readFileSync(eduR)))throw Error('EDU mirrors differ');console.log(`Standardized ${all.length} Greek records; added ${added} model entries.`);
