const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const eduC=path.join(root,'data/tow_steamsteel/export_descr_unit.txt'),eduR=path.join(root,'data/export_descr_unit.txt');
const edbC=path.join(root,'data/tow_steamsteel/export_descr_buildings.txt'),edbR=path.join(root,'data/export_descr_buildings.txt');
const modelP=path.join(root,'data/unit_models/battle_models.modeldb'),locP=path.join(root,'data/text/export_units.txt');
const cardDir=path.join(root,'data/ui/units/golden'),archiveDir=path.join(root,'tools/card_source_archive/oman_before_standardization');

const E={early:{n:0,name:'Early',form:'1.2, 1.2, 1.2, 1.2, 3, square'},mid:{n:1,name:'Mid',form:'1.2, 1.2, 2.0, 2.4, 3, square'},high:{n:2,name:'Late',form:'1.2, 1.2, 2.0, 2.4, 3, square'}};
const W={
  tupak:{name:'Omani tupak matchlock musket',damage:32,family:'arquebus',range:160,ammo:35,smoke:'musket_shot_set',base:900,muzzle:true},
  enfield:{name:'Pattern 1853 Enfield rifle-musket',damage:37,family:'rifled_musket',range:220,ammo:35,smoke:'musket_shot_set',base:1200,muzzle:true},
  snider:{name:'Snider-Enfield conversion rifle',damage:29,family:'rifle',range:240,ammo:35,smoke:'musket_shot_set',base:1500},
  martini:{name:'Martini-Henry Mk III rifle',damage:21,family:'rifle',range:240,ammo:35,smoke:'musket_shot_set',base:1500},
  peabody:{name:'Peabody-Martini Model 1874 rifle',damage:21,family:'rifle',range:240,ammo:35,smoke:'musket_shot_set',base:1500},
  francotte:{name:'Belgian Francotte Martini-Henry rifle',damage:21,family:'rifle',range:240,ammo:35,smoke:'musket_shot_set',base:1500}
};
const Q={
  militia:{melee:2,charge:2,def:1,morale:2,disc:'low',training:'trained',proj:'c',cost:-200},
  regular:{melee:4,charge:3,def:2,morale:3,disc:'low',training:'trained',proj:'c',cost:0},
  elite:{melee:6,charge:4,def:3,morale:5,disc:'normal',training:'highly_trained',proj:'b',cost:200}
};
const infantry=[];
function add(type,label,p,w,donor,card,quality,limit=1){infantry.push({type,label,p,w,donor,card,quality,limit});}
add('oma_baluchi_musketeers','Asakir al-Balush','early',W.tupak,'moroccan_gunner','__generated_baluchi','militia',2);
infantry[0].eras=[0,1,2];
add('oma_regular_early','al-Mushat al-Nizamiyya','early',W.enfield,'arab_sailors1','us_zouave_go','regular',3);
add('oma_regular_mid','al-Mushat al-Nizamiyya','mid',W.snider,'oma_regular_early','us_zouave_go','regular',3);
add('oma_regular_high','al-Mushat al-Nizamiyya','high',W.martini,'oma_regular_mid','us_zouave_go','regular',3);
add('oma_palace_guard_early','Haras al-Qasr','early',W.enfield,'oman_inf','omani_roy','elite');
add('oma_palace_guard_mid','Haras al-Qasr','mid',W.peabody,'oma_palace_guard_early','omani_roy','elite');
add('oma_palace_guard_high','Haras al-Qasr','high',W.francotte,'oma_palace_guard_mid','omani_roy','elite');
add('oma_zanzibar_mid','Asakir Zanjibar','mid',W.snider,'pru_ww1_gren','otto_inf','regular',2);
add('oma_zanzibar_high','Asakir Zanjibar','high',W.snider,'oma_zanzibar_mid','otto_inf','regular',2);
const cavalry=[
  {type:'oma_bedouin_camelry',label:'al-Hajjana al-Badawiyya',kind:'camel',donor:'moroccan_camel_gunner',card:'moroccan_camel_gunner_golden',quality:'militia',eras:[0,1,2]},
  ...['early','mid','high'].map(p=>({type:`oma_horse_guard_${p}`,label:'al-Khayyala al-Sultaniyya',kind:'pistol',p,donor:'omani_cav',card:'__generated_horse_guard',quality:'elite',eras:[E[p].n]})),
  {type:'oma_command_retinue',label:'Hashiyat al-Sultan',kind:'command',donor:'omani_cav',card:'__generated_command_retinue',quality:'elite',eras:[0,1,2]}
];
const upkeep=n=>Math.round(n/3),cost=(n,limit=1)=>`3, ${n}, ${upkeep(n)}, 100, 100, ${n}, ${limit}, ${upkeep(n)}`;
const swordInfantry=u=>u.type==='oma_baluchi_musketeers'||u.type.startsWith('oma_regular_')||u.type.startsWith('oma_palace_guard_');
function infRecord(u){const q=Q[u.quality],sword=swordInfantry(u),attrs=['free_upkeep_unit','sea_faring','hide_forest'];if(u.w.muzzle)attrs.push('gunpowder_unit');attrs.push('gunmen','start_not_skirmishing','cannot_skirmish');if(u.p==='high')attrs.push('stakes');const total=u.w.base+q.cost,eras=u.eras||[E[u.p].n],period=eras.length===1?`${E[u.p].name}; `:'',bearer=u.p!=='high'&&u.type!=='oma_baluchi_musketeers',equip=`${u.w.name}${sword?' and sword':''}`;return [
  `type             ${u.type}`,`dictionary       ${u.type} ; ${u.label} (${period}${equip})`,'category         infantry','class            missile','voice_type       Light','accent           arabic','banner faction   main_infantry','banner holy      crusade',`soldier          ${u.type}, 40, 0, 1.2`,'officer          fez_off_1g',...(bearer?['officer          oma_standard_bearer']:[]),`attributes       ${attrs.join(', ')}`,`formation        ${E[u.p].form}`,'stat_health      1, 0',`stat_pri         ${u.w.damage}, 0, ${u.w.family}_bullet_${q.proj}, ${u.w.range}, ${u.w.ammo}, missile, missile_gunpowder, piercing, none, ${u.w.smoke}, 0, -999`,'stat_pri_attr    ap',`stat_sec         ${q.melee+(sword?1:0)}, ${q.charge}, no, 0, 0, melee, melee_blade, piercing, ${sword?'sword, 25, 1':'spear, 25, 1.2'}`,`stat_sec_attr    ${sword?'no':'ap, short_pike'}`,`stat_pri_armour  3, ${q.def}, 0, leather`,'stat_sec_armour  0, 0, flesh','stat_heat        0','stat_ground      0, 0, 0, 0',`stat_mental      ${q.morale}, ${q.disc}, ${q.training}`,'stat_charge_dist 40','stat_fire_delay  0','stat_food        60, 300',`stat_cost        ${cost(total,u.limit)}`,'ownership        golden, slave',...eras.map(e=>`era ${e}            golden`)].join('\n');}
function cavRecord(u){const q=Q[u.quality],camel=u.kind==='camel',command=u.kind==='command',pistol=u.kind==='pistol'||command,attrs=['free_upkeep_unit','sea_faring','hide_forest','can_withdraw','guncavalry','gunmen','start_not_skirmishing','cannot_skirmish'];if(camel||u.w?.muzzle)attrs.push('gunpowder_unit');if(command)attrs.push('general_unit','command');const pistolRow='20, 4, magazine_rifle_bullet_c, 60, 15, missile, missile_gunpowder, piercing, none, musket_shot_set, 25, 1';const pri=pistol?pistolRow:camel?'32, 2, arquebus_bullet_c, 140, 35, missile, missile_gunpowder, piercing, none, musket_shot_set, 25, 1':`${u.w.damage}, 2, ${u.w.family}_bullet_c, ${u.w.range}, ${u.w.ammo}, missile, missile_gunpowder, piercing, none, ${u.w.smoke}, 25, 1`;const total=command?200:u.kind==='pistol'?1400:camel?900:u.w.base+200+q.cost;const def=camel?3:4;const equip=pistol?'Beaumont-Adams revolver and sabre':camel?'Omani tupak matchlock carbine and sabre':`${u.w.name} and sabre`;return [
  `type             ${u.type}`,`dictionary       ${u.type} ; ${u.label}${u.p?` (${E[u.p].name}; ${equip})`:` (${equip})`}`,'category         cavalry',`class            ${pistol?'light':'missile'}`,'voice_type       Heavy','accent           arabic','banner faction   main_cavalry','banner holy      crusade_cavalry',`soldier          ${u.type}, ${command?4:24}, 0, 1`,...(camel?[]:['officer          fez_off_1g']),`mount            ${camel?'camel':pistol?'hussar':'dragoon'}`,`mount_effect     ${camel?'elephant -4, horse +4':'elephant -4, camel -4'}`,`attributes       ${attrs.join(', ')}`,`formation        2, 2, 4, 4, ${command?2:3}, square`,'stat_health      1, 0',`stat_pri         ${pri}`,'stat_pri_attr    ap',`stat_sec         ${q.melee}, ${q.charge}, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1`,'stat_sec_attr    ap',`stat_pri_armour  4, ${def}, 0, leather`,'stat_sec_armour  0, 0, flesh','stat_heat        0','stat_ground      0, 0, 0, 0',`stat_mental      ${q.morale}, ${camel?'impetuous':q.disc}, ${q.training}`,'stat_charge_dist 45','stat_fire_delay  0','stat_food        60, 300',`stat_cost        ${cost(total)}`,'ownership        golden, slave',...u.eras.map(e=>`era ${e}            golden`)].join('\n');}

const records=[...infantry.map(infRecord),...cavalry.map(cavRecord)],byType=Object.fromEntries([...infantry.map(u=>[u.type,infRecord(u)]),...cavalry.map(u=>[u.type,cavRecord(u)])]);
const legacy=['otto_cav_golden','moroccan_camel_gunner_golden','moroccan_gunner_golden','us_zouave_go','omani_roy','omani_cav','otto_inf'];
const auxiliaries=['africa_cav','african_warband','merc_zulu_rifles','mahdist_inf','fra_blacks_az','mahdist_camel_cav','mahdist_cav'];
function stripGolden(b){b=b.replace(/^ownership\s+(.+)$/m,(m,x)=>{const a=x.split(',').map(y=>y.trim()).filter(y=>y&&y!=='golden');return a.length?`ownership        ${a.join(', ')}`:'';});b=b.replace(/^era ([012])\s+(.+)$/gm,(m,e,x)=>{const a=x.split(',').map(y=>y.trim()).filter(y=>y&&y!=='golden');return a.length?`era ${e}            ${a.join(', ')}`:'';});return b.replace(/\n{3,}/g,'\n\n');}
function replaceType(text,type,replacement){const s=[...text.matchAll(/^type\s+(\S+)/gm)],i=s.findIndex(x=>x[1]===type);if(i<0)throw Error(`Missing Oman legacy type ${type}`);return text.slice(0,s[i].index)+replacement+'\n\n'+text.slice(i+1<s.length?s[i+1].index:text.length);}
let edu=fs.readFileSync(eduC,'utf8').replace(/\r\n/g,'\n');const begin='; BEGIN STANDARDIZED OMAN',end='; END STANDARDIZED OMAN';
if(edu.includes(begin)){const a=edu.indexOf(begin),z=edu.indexOf(end,a);if(z<0)throw Error('Unclosed Oman block');edu=edu.slice(0,a)+edu.slice(z+end.length).replace(/^\s*/,'');}
let starts=[...edu.matchAll(/^type\s+(\S+)/gm)],parts=[edu.slice(0,starts[0].index)];for(let i=0;i<starts.length;i++){const t=starts[i][1],z=i+1<starts.length?starts[i+1].index:edu.length;let b=edu.slice(starts[i].index,z);if([...legacy,...auxiliaries].includes(t))b=stripGolden(b);if(['african_warband','mahdist_inf'].includes(t))b=b.replace(/^(soldier\s+\S+,\s*)100,/m,'$196,');parts.push(b);}edu=parts.join('');
const at=edu.indexOf('type             otto_cav_golden');if(at<0)throw Error('Oman insertion point missing');edu=edu.slice(0,at)+`${begin}\n\n${records.join('\n\n')}\n\n${end}\n\n`+edu.slice(at);
const aliases={otto_cav_golden:'oma_horse_guard_early',moroccan_camel_gunner_golden:'oma_bedouin_camelry',moroccan_gunner_golden:'oma_baluchi_musketeers',us_zouave_go:'oma_regular_early',omani_roy:'oma_palace_guard_early',omani_cav:'oma_horse_guard_high',otto_inf:'oma_zanzibar_high'};
for(const [old,modern] of Object.entries(aliases)){const a=byType[modern].replace(/^type\s+.*$/m,`type             ${old}`).replace(/^dictionary\s+\S+.*$/m,`dictionary       ${old}`).replace(/^soldier\s+\S+,/m,`soldier          ${modern},`).replace(/^ownership\s+.*$/m,'ownership        slave').replace(/^era [012]\s+.*\n?/gm,'').trimEnd();edu=replaceType(edu,old,a);}
fs.writeFileSync(eduC,edu.replace(/\n/g,'\r\n'));fs.writeFileSync(eduR,edu.replace(/\n/g,'\r\n'));

let edb=fs.readFileSync(edbC,'utf8');for(const [old,modern] of Object.entries(aliases))edb=edb.split(`"${old}"`).join(`"${modern}"`);fs.writeFileSync(edbC,edb);fs.writeFileSync(edbR,edb);

function modelEntries(text){const a=text.replace(/\r\n/g,'\n').split('\n'),r=[];let start=1;for(let i=1;i<a.length;i++)if(/^16 -0\.090000004 /.test(a[i])){r.push({lines:a.slice(start,i+1),name:(a[start].match(/^\d+ (\S+)/)||[])[1]});start=i+1;}return r;}
function modelEntry(text,name){const e=modelEntries(text).find(x=>x.name===name);if(!e)throw Error(`Missing Oman model donor ${name}`);return e.lines.join('\n');}
function cloneModel(text,donor,name,mode,mounted=false){let e=modelEntry(text,donor).replace(new RegExp(`^${donor.length} ${donor}\\s*$`,'m'),`${name.length} ${name} `);if(mode){const anim=mode==='fast'?'20 MTW2_Fast_Arquebus_3':'14 MTW2_Musket_SS';e=e.replace(/(?:20 MTW2_Fast_Arquebus_3|18 MTW2_Fast_Arquebus|18 MTW2_Fast_Musket_3|14 MTW2_Musket_SS|15 MTW2_Musket_SSK)(?=\s)/,anim);}if(mounted)e=e.replace(/^\d+ unit_sprites\/[^\s]+_sprite\.spr\s*$/gm,'35 unit_sprites/tmp_cavalry_sprite.spr ');return e;}
function setInfantrySwordAnimations(entry){entry=entry.replace(/(?:9 MTW2_Pike|11 MTW2_2H_Axe|14 MTW2_Swordsman|16 MTW2_2HSwordsman)(?!_primary)/,'16 MTW2_2HSwordsman');entry=entry.replace(/(?:17 MTW2_Pike_primary|18 MTW2_Sword_Primary|19 MTW2_2H_Axe_primary|24 MTW2_2HSwordsman_Primary)/,'24 MTW2_2HSwordsman_Primary');return entry;}
function counted(e,oldPath,newPath){return e.replace(`${oldPath.length} ${oldPath}`,`${newPath.length} ${newPath}`);}
function omanBearerModel(text){const donor='ott_standard_bearer',name='oma_standard_bearer',oldMesh='unit_models/_Units/off/ott_standard_bearer_lod0.mesh',mesh='unit_models/_Units/off/oma_standard_bearer_lod0.mesh',oldBody='unit_models/_Units/ott/textures/ott_inf_1g.texture',body='unit_models/_Units/oma/textures/oma_inf_2g.texture',oldFlag='unit_models/_Units/bnw/textures/ott_standard_flag.texture',flag='unit_models/_Units/bnw/textures/oma_standard_flag.texture',oldFlagN='unit_models/_Units/bnw/textures/ott_standard_flag_n.texture',flagN='unit_models/_Units/bnw/textures/oma_standard_flag_n.texture',oldSprite='unit_sprites/turks_Janissary_Musketeers_sprite.spr',sprite='unit_sprites/milan_Dummy_EN_Spearmen_ug1_sprite.spr';let e=modelEntry(text,donor).replace(new RegExp(`^${donor.length} ${donor}\\s*$`,'m'),`${name.length} ${name} `).replace(/^5 turks\s*$/gm,'6 golden ');for(const [a,b] of [[oldMesh,mesh],[oldBody,body],[oldFlag,flag],[oldFlagN,flagN],[oldSprite,sprite]])e=counted(e,a,b);return e;}
let model=fs.readFileSync(modelP,'utf8').replace(/\r\n/g,'\n'),added=0;
for(const u of infantry){const mode=u.w.muzzle?'fast':'line';let fresh=cloneModel(model,u.donor,u.type,mode);if(u.type.startsWith('oma_regular_'))fresh=fresh.replace(/^6 venice\s*$/gm,'6 golden ');if(swordInfantry(u))fresh=setInfantrySwordAnimations(fresh);if(modelEntries(model).some(x=>x.name===u.type))model=model.replace(modelEntry(model,u.type),fresh);else{model=model.trimEnd()+'\n'+fresh+'\n';added++;}}
for(const u of cavalry){let fresh=cloneModel(model,u.donor,u.type,null,true);if(u.kind==='pistol'||u.kind==='command')fresh=counted(fresh,'unit_models/_Units/oma/oma_cav_1g_lod0.mesh','unit_models/_Units/oma/oma_cav_pistol_sabre_lod0.mesh');if(modelEntries(model).some(x=>x.name===u.type))model=model.replace(modelEntry(model,u.type),fresh);else{model=model.trimEnd()+'\n'+fresh+'\n';added++;}}
{const name='oma_standard_bearer',fresh=omanBearerModel(model);if(modelEntries(model).some(x=>x.name===name))model=model.replace(modelEntry(model,name),fresh);else{model=model.trimEnd()+'\n'+fresh+'\n';added++;}}
if(added){const h=model.match(/^(22 serialization::archive 3 0 0 0 0 )(\d+)( 0 0 )/);if(!h)throw Error('Bad modeldb header');model=model.replace(h[0],`${h[1]}${+h[2]+added}${h[3]}`);}fs.writeFileSync(modelP,model.replace(/\n/g,'\r\n'));

let lb=fs.readFileSync(locP),loc=lb.slice(lb[0]===255&&lb[1]===254?2:0).toString('utf16le').replace(/\r\n/g,'\n');for(const u of [...infantry,...cavalry])for(const k of [u.type,`${u.type}_descr`,`${u.type}_descr_short`])loc=loc.replace(new RegExp(`^\\{${k}\\}.*(?:\\n|$)`,'gm'),'');
const locRows=[...infantry.map(u=>{const equip=`${u.w.name}${swordInfantry(u)?' and sword':''}`;return `{${u.type}}${u.label}${u.eras?.length>1?'':` (${E[u.p].name})`}\n{${u.type}_descr}${u.label} serve the Sultanate of Oman and its western Indian Ocean possessions.\n{${u.type}_descr_short}${u.label} (${equip})`;}),...cavalry.map(u=>{const equip=u.kind==='command'||u.kind==='pistol'?'Beaumont-Adams revolver and sabre':u.kind==='camel'?'Omani tupak matchlock carbine and sabre':u.w.name+' and sabre';return `{${u.type}}${u.label}${u.p?` (${E[u.p].name})`:''}\n{${u.type}_descr}${u.label} serve in the mounted forces of the Sultanate of Oman.\n{${u.type}_descr_short}${u.label} (${equip})`;})];loc=loc.trimEnd()+'\n\n'+locRows.join('\n\n')+'\n';fs.writeFileSync(locP,Buffer.concat([Buffer.from([255,254]),Buffer.from(loc.replace(/\n/g,'\r\n'),'utf16le')]));

fs.mkdirSync(archiveDir,{recursive:true});for(const source of new Set([...infantry.map(u=>u.card),...cavalry.map(u=>u.card)].filter(x=>!x.startsWith('__generated_')))){const src=path.join(cardDir,`#${source}.tga`),arc=path.join(archiveDir,`#${source}.tga`);if(!fs.existsSync(src))throw Error(`Missing Oman card donor ${source}`);if(!fs.existsSync(arc))fs.copyFileSync(src,arc);}for(const u of [...infantry,...cavalry])if(!u.card.startsWith('__generated_'))fs.copyFileSync(path.join(cardDir,`#${u.card}.tga`),path.join(cardDir,`#${u.type}.tga`));
if(!fs.readFileSync(eduC).equals(fs.readFileSync(eduR)))throw Error('Oman EDU mirrors differ');if(!fs.readFileSync(edbC).equals(fs.readFileSync(edbR)))throw Error('Oman EDB mirrors differ');console.log(`Standardized ${records.length} Oman records; added ${added} model entries.`);
