const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),eduC=path.join(root,'data/tow_steamsteel/export_descr_unit.txt'),eduR=path.join(root,'data/export_descr_unit.txt'),modelP=path.join(root,'data/unit_models/battle_models.modeldb'),locP=path.join(root,'data/text/export_units.txt'),soundP=path.join(root,'data/export_descr_sounds_units_voice.txt');
const era={early:{n:0,name:'Early',form:'1.2, 1.2, 1.2, 1.2, 3, square'},mid:{n:1,name:'Mid',form:'1.2, 1.2, 2.0, 2.4, 3, square'},high:{n:2,name:'Late',form:'1.2, 1.4, 2.4, 2.8, 3, square'}};
const cost=(n,limit=1)=>`3, ${n}, ${Math.round(n/3)}, 100, 100, ${n}, ${limit}, ${Math.round(n/3)}`;
const arms={
 sweEarly:{weapon:'Gevär m/1860',damage:37,family:'rifled_musket',range:220,ammo:35,smoke:'musket_shot_set',muzzle:true,mode:'fast',baseCost:1200},
 norEarly:{weapon:'Kammerlader m/1849/55',damage:31,family:'rifled_musket',range:220,ammo:35,smoke:'musket_shot_set',mode:'musket',baseCost:1200,earlyBreech:true},
 remington:{weapon:'Gevär m/1867 Remington',damage:37,family:'rifle',range:240,ammo:35,smoke:'musket_shot_set',mode:'musket',baseCost:1500},
 norRemington:{weapon:'Remingtongevær m/1867',damage:37,family:'rifle',range:240,ammo:35,smoke:'musket_shot_set',mode:'musket',baseCost:1500},
 mauser:{weapon:'Gevär m/1896 Mauser',damage:13,family:'magazine_rifle',range:260,ammo:40,smoke:'smokeless_shot_set',mode:'fast',baseCost:1800},
 krag:{weapon:'Krag–Jørgensen m/1894',damage:20,family:'magazine_rifle',range:260,ammo:40,smoke:'smokeless_shot_set',mode:'fast',baseCost:1800},
 minie:{weapon:'Gevär m/1856 Minié',damage:37,family:'rifled_musket',range:220,ammo:35,smoke:'musket_shot_set',muzzle:true,mode:'fast',baseCost:1200},
 wrede:{weapon:'Wredes gevär m/1860',damage:37,family:'rifled_musket',range:220,ammo:35,smoke:'musket_shot_set',muzzle:true,mode:'fast',baseCost:1200}
};
const tierLetter=(quality,role,w)=>{let n=quality==='elite'?2:quality==='militia'?0:1;n+=(role==='skirmisher'?1:0)+1;if(w.earlyBreech)n--;return 'cbas'[Math.max(0,Math.min(3,n))];};
const makeInf=(type,label,period,quality,role,arm,donor,limit=1)=>{const q=quality==='elite'?{melee:8,charge:5,defence:5,morale:6,discipline:'disciplined',training:'highly_trained',premium:200}:quality==='militia'?{melee:4,charge:3,defence:3,morale:3,discipline:'low',training:'trained',premium:-200}:{melee:6,charge:4,defence:4,morale:4,discipline:'normal',training:'trained',premium:0};return{type,label,period,quality,role,arm,donor,limit,...q,projectile:`${arm.family}_bullet_${tierLetter(quality,role,arm)}`,total:arm.baseCost+q.premium+300,strength:role==='skirmisher'?30:40};};
const inf=[];
for(const p of ['early','mid','high'])inf.push(makeInf(`swe_line_${p}`,'Svenskt linjeinfanteri',p,'regular','line',p==='early'?arms.sweEarly:p==='mid'?arms.remington:arms.mauser,p==='early'?'swed_inf2':`swe_line_${p==='mid'?'early':'mid'}`,3));
for(const p of ['early','mid','high'])inf.push(makeInf(`nor_line_${p}`,'Norsk linjeinfanteri',p,'regular','line',p==='early'?arms.norEarly:p==='mid'?arms.norRemington:arms.krag,p==='early'?'swed_roy':p==='mid'?'nor_line_early':'norwegian_inf',3));
for(const p of ['early','mid','high'])inf.push(makeInf(`swe_bevaring_${p}`,'Beväring',p,'militia','line',p==='early'?arms.minie:p==='mid'?arms.sweEarly:arms.remington,p==='early'?'swed_inf2':`swe_bevaring_${p==='mid'?'early':'mid'}`,2));
for(const p of ['early','mid','high'])inf.push(makeInf(`swe_jagare_${p}`,'Jägare',p,'regular','skirmisher',p==='early'?arms.wrede:p==='mid'?arms.remington:arms.mauser,p==='early'?'swe_guard':`swe_jagare_${p==='mid'?'early':'mid'}`));
for(const p of ['early','mid','high'])inf.push(makeInf(`swe_guard_${p}`,'Svea livgarde',p,'elite','line',p==='early'?arms.sweEarly:p==='mid'?arms.remington:arms.mauser,p==='early'?'swed_roy':`swe_guard_${p==='mid'?'early':'mid'}`));
for(const p of ['early','mid','high'])inf.push(makeInf(`nor_guard_${p}`,'Hans Majestet Kongens Garde',p,'elite','line',p==='early'?arms.norEarly:p==='mid'?arms.norRemington:arms.krag,p==='early'?'swed_roy':p==='mid'?'nor_guard_early':'norwegian_inf'));
function infantry(u){const a=u.arm,attrs=['free_upkeep_unit','sea_faring','hide_forest'];if(a.muzzle)attrs.push('gunpowder_unit');attrs.push('gunmen','start_not_skirmishing','cannot_skirmish');if(u.period==='high')attrs.push('stakes');const officers=[`officer          swe_off_1g`,...(u.period!=='high'?['officer          russia_qi']:[])];return [`type             ${u.type}`,`dictionary       ${u.type} ; ${u.label} (${era[u.period].name}; ${a.weapon})`,'category         infantry','class            missile','voice_type       Light','accent           swed','banner faction   main_infantry','banner holy      crusade',`soldier          ${u.type}, ${u.strength}, 0, 1.2`,...officers,`attributes       ${attrs.join(', ')}`,`formation        ${u.role==='skirmisher'?'1.4, 1.8, 2.8, 3.6, 3, square':era[u.period].form}`,'stat_health      1, 0',`stat_pri         ${a.damage}, 0, ${u.projectile}, ${a.range+(u.role==='skirmisher'?40:0)}, ${a.ammo}, missile, missile_gunpowder, piercing, none, ${a.smoke}, 0, -999`,'stat_pri_attr    ap',`stat_sec         ${u.melee}, ${u.charge}, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1.2`,'stat_sec_attr    short_pike, ap',`stat_pri_armour  3, ${u.defence}, 0, leather`,'stat_sec_armour  0, 0, flesh','stat_heat        0','stat_ground      0, 0, 0, 0',`stat_mental      ${u.morale}, ${u.discipline}, ${u.training}`,'stat_charge_dist 40','stat_fire_delay  0','stat_food        60, 300',`stat_cost        ${cost(u.total,u.limit)}`,'ownership        normans, slave',`era ${era[u.period].n}            normans`].join('\n');}
const cav=[
 {type:'swe_hussars',label:'Livregementets husarer',weapon:'Pistol m/1850 och sabel',arm:'pistol',className:'light',donor:'euro_hussars',melee:6,charge:4,defence:5,morale:4,training:'trained',total:1500},
 {type:'swe_dragoons_early',label:'Livregementets dragoner',period:'early',weapon:'Karbin m/1854 och sabel',arm:'carbine',className:'missile',donor:'dan_cav',damage:31,projectile:'rifled_musket_carbine_bullet_b',range:200,ammo:35,smoke:'musket_shot_set',muzzle:true,melee:6,charge:4,defence:5,morale:4,training:'trained',total:1700},
 {type:'swe_dragoons_mid',label:'Livregementets dragoner',period:'mid',weapon:'Karbin m/1870 och sabel',arm:'carbine',className:'missile',donor:'swe_dragoons_early',damage:20,projectile:'rifle_carbine_bullet_b',range:220,ammo:35,smoke:'musket_shot_set',melee:6,charge:4,defence:5,morale:4,training:'trained',total:2000},
 {type:'swe_dragoons_high',label:'Livregementets dragoner',period:'high',weapon:'Karbin m/1894 och sabel',arm:'carbine',className:'missile',donor:'swe_dragoons_mid',damage:13,projectile:'magazine_rifle_carbine_bullet_b',range:240,ammo:40,smoke:'smokeless_shot_set',melee:6,charge:4,defence:5,morale:4,training:'trained',total:2300},
 {type:'swe_lifeguard_horse',label:'Livgardet till häst',weapon:'Revolver m/1871 och sabel',arm:'pistol',className:'heavy',donor:'balk_cav',melee:8,charge:5,defence:5,morale:6,training:'highly_trained',total:1700},
 {type:'swe_general_staff',label:'General och stab',weapon:'Revolver m/1871 och sabel',arm:'pistol',className:'heavy',donor:'balk_cav',melee:8,charge:5,defence:5,morale:6,training:'highly_trained',total:200,general:true}
];
function cavalry(u){const pistol=u.arm==='pistol',attrs=['free_upkeep_unit','sea_faring','hide_forest','can_withdraw','guncavalry','gunmen','start_not_skirmishing','cannot_skirmish'];if(u.muzzle)attrs.push('gunpowder_unit');if(u.arm==='carbine')attrs.push('stakes');if(u.general)attrs.push('general_unit','command');const pri=pistol?'20, 4, magazine_rifle_bullet_c, 60, 15, missile, missile_gunpowder, piercing, none, musket_shot_set, 25, 1':`${u.damage}, 2, ${u.projectile}, ${u.range}, ${u.ammo}, missile, missile_gunpowder, piercing, none, ${u.smoke}, 25, 1`;return [`type             ${u.type}`,`dictionary       ${u.type} ; ${u.label}${u.period?` (${era[u.period].name}; ${u.weapon})`:` (${u.weapon})`}`,'category         cavalry',`class            ${u.className}`,'voice_type       Heavy','accent           swed','banner faction   main_cavalry','banner holy      crusade_cavalry',`soldier          ${u.type}, ${u.general?4:24}, 0, 1`,'officer          swe_off_1g','mount            dragoon','mount_effect     elephant -4, camel -4',`attributes       ${attrs.join(', ')}`,`formation        2, 2, 4, 4, ${u.general?2:3}, square`,'stat_health      1, 0',`stat_pri         ${pri}`,'stat_pri_attr    ap',`stat_sec         ${u.melee}, ${u.charge}, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1`,'stat_sec_attr    ap',`stat_pri_armour  4, ${u.defence}, 0, leather`,'stat_sec_armour  0, 0, flesh','stat_heat        0','stat_ground      0, 0, 0, 0',`stat_mental      ${u.morale}, ${u.training==='highly_trained'?'disciplined':'normal'}, ${u.training}`,'stat_charge_dist 45','stat_fire_delay  -20000','stat_food        60, 300',`stat_cost        ${cost(u.total)}`,'ownership        normans, slave',...(u.period?[`era ${era[u.period].n}            normans`]:['era 0            normans','era 1            normans','era 2            normans'])].join('\n');}
const records=Object.fromEntries([...inf.map(u=>[u.type,infantry(u)]),...cav.map(u=>[u.type,cavalry(u)])]);
const legacy={euro_hussars_normans:['swe_hussars','euro_hussars'],rus_cos_guard_no:['swe_line_mid','dan_inf'],swed_roy:['nor_line_early','swed_roy'],fra_carbs_no:['swe_dragoons_mid','dan_cav'],rus_imp_cav_no:['swe_general_staff','balk_cav'],rus_sib_cossacks_no:['swe_lifeguard_horse','rus_sib_cossacks'],swe_guard:['swe_jagare_early','swe_guard'],norwegian_inf:['nor_line_high','norwegian_inf'],swed_inf2:['swe_line_early','swed_inf2']};
function alias(old,modern,soldier){return records[modern].replace(/^type\s+.*$/m,`type             ${old}`).replace(/^dictionary\s+\S+/m,`dictionary       ${old}`).replace(/^soldier\s+\S+,/m,`soldier          ${soldier},`).replace(/^ownership\s+.*$/m,'ownership        slave').replace(/^era [012]\s+normans\n?/gm,'').trimEnd();}
const block=['; ============================================================================','; Swe-Nor (normans) — standardized infantry and cavalry','; ============================================================================',...inf.map(infantry),...cav.map(cavalry),'; Legacy internal-name compatibility (not assigned to custom-battle eras)',...Object.entries(legacy).map(([o,[m,s]])=>alias(o,m,s))].join('\n\n')+'\n\n';
let edu=fs.readFileSync(eduC,'utf8').replace(/\r\n/g,'\n');const titleAt=Math.max(edu.indexOf('; Swe-Nor (normans) — standardized infantry and cavalry'),edu.indexOf('; Swe-Nor (normans) — infantry and cavalry')),start=edu.lastIndexOf('; ============================================================================',titleAt),greekAt=edu.indexOf(';################ Kingdom of Greece',titleAt),end=edu.lastIndexOf('\n;;;;;;;;;;;;;;;;',greekAt)+1;if(start<0||end<1)throw Error('Sweden-Norway block not found');edu=edu.slice(0,start)+block+edu.slice(end);edu=edu.replace(/(^type\s+austro_sailor_normans\s*$[\s\S]*?^ownership\s+).+?(?=\r?$)/m,'$1slave').replace(/(^type\s+austro_sailor_normans\s*$[\s\S]*?)(^era [012]\s+normans\s*$\r?\n?)/gm,'$1');const out=edu.replace(/\n/g,'\r\n');fs.writeFileSync(eduC,out);fs.writeFileSync(eduR,out);
function entry(text,name){const a=text.replace(/\r\n/g,'\n').split('\n'),i=a.findIndex(x=>new RegExp(`^${name.length} ${name}\\s*$`).test(x));if(i<0)throw Error(`Missing donor ${name}`);let j=i;while(j<a.length&&!/^16 -0\.090000004 /.test(a[j]))j++;return a.slice(i,j+1).join('\n');}
function clone(text,donor,name,mode,kind){let e=entry(text,donor).replace(new RegExp(`^${donor.length} ${donor}\\s*$`,'m'),`${name.length} ${name} `);if(mode==='musket')e=e.replace(/(?:20 MTW2_Fast_Arquebus_3|15 MTW2_Musket_SSK) 9 MTW2_Pike /,'14 MTW2_Musket_SS 9 MTW2_Pike ');if(mode==='skirmisher')e=e.replace(/(?:20 MTW2_Fast_Arquebus_3|14 MTW2_Musket_SS) 9 MTW2_Pike /,'15 MTW2_Musket_SSK 9 MTW2_Pike ');if(mode==='fast')e=e.replace(/(?:14 MTW2_Musket_SS|15 MTW2_Musket_SSK) 9 MTW2_Pike /,'20 MTW2_Fast_Arquebus_3 9 MTW2_Pike ');if(kind==='hussar')e=e.replace('14 MTW2_HR_Pistol 13 MTW2_HR_Spear','14 MTW2_HR_Pistol 13 MTW2_HR_Sword').replace('21 MTW2_HR_spear_Primary','18 MTW2_Sword_Primary');return e;}
const models=[];for(const u of inf)models.push([u.donor,u.type,u.role==='skirmisher'&&!u.arm.muzzle?'skirmisher':u.arm.mode,null]);for(const u of cav)models.push([u.donor,u.type,null,u.type==='swe_hussars'?'hussar':null]);
let model=fs.readFileSync(modelP,'utf8').replace(/\r\n/g,'\n'),added=0;for(const [d,n,m,k] of models){const fresh=clone(model,d,n,m,k);if(new RegExp(`^${n.length} ${n} $`,'m').test(model))model=model.replace(entry(model,n),fresh);else{model=model.trimEnd()+'\n'+fresh+'\n';added++;}}if(added){const h=model.match(/^(22 serialization::archive 3 0 0 0 0 )(\d+)( 0 0 )/);if(!h)throw Error('Bad modeldb header');model=model.replace(h[0],`${h[1]}${+h[2]+added}${h[3]}`);}fs.writeFileSync(modelP,model.replace(/\n/g,'\r\n'));
const all=[...inf,...cav],oldLoc=Object.entries(legacy).map(([type,[m]])=>({...all.find(x=>x.type===m),type}));let buf=fs.readFileSync(locP),loc=buf.slice(buf[0]===255&&buf[1]===254?2:0).toString('utf16le').replace(/\r\n/g,'\n');for(const u of [...all,...oldLoc])loc=loc.replace(new RegExp(`^\\{${u.type}(?:_descr|_descr_short)?\\}.*(?:\\n|$)`,'gm'),'');loc=loc.trimEnd()+'\n\n'+[...all,...oldLoc].map(u=>{const weapon=u.arm?u.arm.weapon:u.weapon;return `{${u.type}}${u.label}${u.period?` (${era[u.period].name})`:''}\n{${u.type}_descr}${u.label} serve in the united Swedish–Norwegian forces. Armed with ${weapon}, they have the training and battlefield role appropriate to this period.\n{${u.type}_descr_short}${u.label} (${weapon})`;}).join('\n\n')+'\n';fs.writeFileSync(locP,Buffer.concat([Buffer.from([255,254]),Buffer.from(loc.replace(/\n/g,'\r\n'),'utf16le')]));
for(const u of all){let s=u.type.startsWith('swe_line_')||u.type.startsWith('swe_bevaring_')?'swed_inf2':u.type.startsWith('nor_line_')||u.type.startsWith('nor_guard_')?(u.period==='high'?'norwegian_inf':'swed_roy'):u.type.startsWith('swe_jagare_')?'swe_guard':u.type.startsWith('swe_guard_')?'swed_roy':u.type==='swe_hussars'?'euro_hussars_normans':u.type.startsWith('swe_dragoons_')?'fra_carbs_no':u.type==='swe_lifeguard_horse'?'rus_sib_cossacks_no':'rus_imp_cav_no';const unitDir=path.join(root,'data/ui/units/normans'),infoDir=path.join(root,'data/ui/unit_info/normans');fs.copyFileSync(path.join(unitDir,`#${s}.tga`),path.join(unitDir,`#${u.type}.tga`));let info=path.join(infoDir,`${s}_info.tga`);if(!fs.existsSync(info))info=path.join(infoDir,u.type.includes('dragoon')||u.type.includes('hussar')||u.type.includes('horse')||u.general?'rus_sib_cossacks_no_info.tga':'swed_roy_info.tga');fs.copyFileSync(info,path.join(infoDir,`${u.type}_info.tga`));}
let sounds=fs.readFileSync(soundP,'utf8').replace(/\r\n/g,'\n');const tmpl=sounds.match(/(^\s*unit swed_inf2\n\s*event\n\s*folder[^\n]+\n(?:\s+[^\n]+\.wav\n)+\s*end)/m);if(tmpl){const indent=tmpl[1].match(/^(\s*)unit/m)[1],adds=all.filter(u=>!new RegExp(`^\\s*unit ${u.type}$`,'m').test(sounds)).map(u=>tmpl[1].replace(`${indent}unit swed_inf2`,`${indent}unit ${u.type}`));if(adds.length)sounds=sounds.replace(tmpl[1],tmpl[1]+'\n'+adds.join('\n'));fs.writeFileSync(soundP,sounds.replace(/\n/g,'\r\n'));}
const types=[...out.matchAll(/^type\s+(.+)$/gm)].map(m=>m[1].trim());if(new Set(types).size!==types.length)throw Error('Duplicate EDU types');if(!fs.readFileSync(eduC).equals(fs.readFileSync(eduR)))throw Error('EDU mirrors differ');console.log(`Standardized ${all.length} Sweden-Norway records; added ${added} model entries.`);
