const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const eduC=path.join(root,'data/tow_steamsteel/export_descr_unit.txt'),eduR=path.join(root,'data/export_descr_unit.txt');
const edbC=path.join(root,'data/tow_steamsteel/export_descr_buildings.txt'),edbR=path.join(root,'data/export_descr_buildings.txt');
const modelP=path.join(root,'data/unit_models/battle_models.modeldb'),locP=path.join(root,'data/text/export_units.txt');
const cards=path.join(root,'data/ui/units/timurids'),archive=path.join(root,'tools/card_source_archive/afghanistan_before_standardization');
const stratC=path.join(root,'data/world/maps/campaign/camp_steamsteel/descr_strat.txt'),stratR=path.join(root,'data/world/maps/campaign/imperial_campaign/descr_strat.txt');

const E={early:{n:0,name:'Early',form:'1.2, 1.2, 1.2, 1.2, 3, square'},mid:{n:1,name:'Mid',form:'1.2, 1.2, 2.0, 2.4, 3, square'},high:{n:2,name:'Late',form:'1.2, 1.4, 2.4, 2.8, 3, square'}};
const W={
  jezail:{name:'hand-crafted Afghan jezail',damage:29,family:'rifled_musket',range:220,ammo:35,smoke:'musket_shot_set',base:1200,muzzle:true},
  wall:{name:'Afghan wall gun',damage:32,projectile:'wall_gun_bullet',range:240,ammo:20,smoke:'musket_shot_set',base:900,muzzle:true},
  brown:{name:'India Pattern Brown Bess musket',damage:40,family:'musket',range:200,ammo:35,smoke:'musket_shot_set',base:1000,muzzle:true},
  snider:{name:'Snider-Enfield conversion rifle',damage:29,family:'rifled_musket',range:220,ammo:35,smoke:'musket_shot_set',base:1200,conversion:true},
  martini:{name:'Martini-Henry Mk I rifle',damage:21,family:'rifle',range:240,ammo:35,smoke:'musket_shot_set',base:1500},
  mauser:{name:'Mauser M1890 Turkish magazine rifle',damage:13,family:'magazine_rifle',range:260,ammo:40,smoke:'smokeless_shot_set',base:1800}
};
const Q={militia:{melee:3,charge:2,def:2,morale:3,proj:'c',training:'trained',premium:-200},regular:{melee:5,charge:3,def:3,morale:4,proj:'b',training:'trained',premium:0},elite:{melee:7,charge:4,def:4,morale:6,proj:'a',training:'highly_trained',premium:200}};
const up={c:'b',b:'a',a:'s',s:'s'},down={c:'c',b:'c',a:'b',s:'a'};
const infantry=[
 {type:'afg_tajik_hillmen',label:'Jezailchiyan-e Tajik',p:'early',w:W.jezail,donor:'afghan_militia',card:'afghan_militia',quality:'militia',role:'skirmisher',eras:[0,1,2],limit:2,sword:'one'},
 {type:'afg_pashtun_wall_gunners',label:'Tufangchiyan-e Pashtun',p:'early',w:W.wall,donor:'pashtun_inf',card:'pashtun_inf',quality:'militia',role:'sharpshooter',eras:[0,1,2],limit:2,sword:'two'},
 {type:'afg_regular_early',label:'Sarbazan-e Nizami',p:'early',w:W.brown,donor:'afghan_rifles',card:'afghan_rifles',quality:'regular',role:'line',eras:[0],limit:3,sword:'one'},
 {type:'afg_regular_mid',label:'Sarbazan-e Nizami',p:'mid',w:W.snider,donor:'afg_regular_early',card:'afghan_rifles',quality:'regular',role:'line',eras:[1],limit:3,sword:'one'},
 {type:'afg_regular_high',label:'Sarbazan-e Nizami',p:'high',w:W.martini,donor:'kabul_guard',card:'kabul_guard',quality:'regular',role:'line',eras:[2],limit:3},
 {type:'afg_ghilzai_nobles',label:'Khanan-e Ghilzai',p:'mid',w:W.snider,donor:'afghan_sword',card:'__generated_nobles',quality:'elite',role:'line',eras:[1,2],limit:1,sword:'two'},
 {type:'afg_sharpshooters_high',label:'Neshanzanan-e Afghani',p:'high',w:W.mauser,donor:'moroccan_gunner1',card:'__generated_sharpshooters',quality:'regular',role:'sharpshooter',eras:[2],limit:1,sword:'two'},
 {type:'afg_kabul_guard_high',label:'Negahbanan-e Kabul',p:'high',w:W.martini,donor:'kabul_guard',card:'kabul_guard',quality:'elite',role:'line',eras:[2],limit:1}
];
const cavalry=[
 {type:'afg_tribal_cavalry',label:'Savaran-e Qawmi',kind:'lance',donor:'afghan_cav',card:'__generated_tribal_cavalry',quality:'militia',eras:[0,1,2],limit:2},
 {type:'afg_regular_cavalry',label:'Savaran-e Nizami',kind:'lance',donor:'afghan_cav',card:'afghan_cav',quality:'regular',eras:[1,2],limit:1},
 {type:'afg_pashtun_camelry',label:'Shutur-savaran-e Pashtun',kind:'camel',donor:'pashtun_camel_gunner',card:'pashtun_camel_gunner',quality:'militia',eras:[0,1,2],limit:1},
 {type:'afg_general_staff',label:'Sipahsalar va Setad',kind:'command',donor:'afghan_gen',card:'__generated_general',quality:'elite',eras:[0,1,2],limit:1}
];
const upkeep=n=>Math.round(n/3),cost=(n,limit=1,time=3)=>`${time}, ${n}, ${upkeep(n)}, 100, 100, ${n}, ${limit}, ${upkeep(n)}`;
function projectile(u){if(u.w.projectile)return u.w.projectile;let p=Q[u.quality].proj;if(u.role==='skirmisher')p=up[p];if(u.role==='sharpshooter')p=up[up[p]];if(u.w.conversion)p=down[p];return `${u.w.family}_bullet_${down[p]}`;}
function infRecord(u){const q=Q[u.quality],sword=!!u.sword,range=u.w.range+(u.role==='line'?0:40),attrs=['free_upkeep_unit','sea_faring','hide_forest'];if(u.w.muzzle)attrs.push('gunpowder_unit');attrs.push('gunmen','start_not_skirmishing','cannot_skirmish');if(u.p==='high')attrs.push('stakes');const total=u.w.base+q.premium+(u.role==='sharpshooter'?200:0);return [
`type             ${u.type}`,`dictionary       ${u.type} ; ${u.label}${u.eras.length===1?` (${E[u.p].name}; ${u.w.name}${sword?' and pulwar':''})`:` (${u.w.name}${sword?' and pulwar':''})`}`,'category         infantry','class            missile','voice_type       Light','accent           farsi','banner faction   main_infantry','banner holy      crusade',`soldier          ${u.type}, ${u.role==='line'?40:30}, 0, ${u.role==='line'?'1.2':'1'}`,'officer          fez_off_1g',`attributes       ${attrs.join(', ')}`,`formation        ${u.role==='line'?E[u.p].form:'1.4, 1.8, 2.8, 3.6, 3, square'}`,'stat_health      1, 0',`stat_pri         ${u.w.damage}, 0, ${projectile(u)}, ${range}, ${u.w.ammo}, missile, missile_gunpowder, piercing, none, ${u.w.smoke}, 0, -999`,'stat_pri_attr    ap',`stat_sec         ${q.melee+(sword?1:0)}, ${q.charge+1}, no, 0, 0, melee, melee_blade, piercing, ${sword?'sword, 25, 1':'spear, 25, 1.2'}`,`stat_sec_attr    ${sword?'no':'short_pike, ap'}`,`stat_pri_armour  3, ${q.def-1}, 0, leather`,'stat_sec_armour  0, 0, flesh','stat_heat        0','stat_ground      0, 0, 0, 0',`stat_mental      ${q.morale}, impetuous, ${q.training}`,'stat_charge_dist 40','stat_fire_delay  0','stat_food        60, 300',`stat_cost        ${cost(total,u.limit)}`,'ownership        timurids, slave',...u.eras.map(e=>`era ${e}            timurids`)].join('\n');}
function lashkarRecord(){return ['type             afg_lashkar_qawmi','dictionary       afg_lashkar_qawmi ; Lashkar-e Qawmi (Afghan jezail and pulwar)','category         infantry','class            missile','voice_type       Heavy','accent           farsi','banner faction   main_infantry','banner holy      crusade','soldier          afg_lashkar_qawmi, 40, 0, 1','officer          fez_off_1g','attributes       free_upkeep_unit, sea_faring, hide_forest, gunpowder_unit, gunmen, start_not_skirmishing, cannot_skirmish','formation        1.2, 1.2, 1.2, 1.2, 3, square','stat_health      1, 0','stat_pri         29, 0, rifled_musket_bullet_c, 220, 35, missile, missile_gunpowder, piercing, none, musket_shot_set, 0, -999','stat_pri_attr    ap','stat_sec         4, 3, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1','stat_sec_attr    no','stat_pri_armour  3, 1, 0, leather','stat_sec_armour  0, 0, flesh','stat_heat        0','stat_ground      0, 0, 0, 0','stat_mental      3, impetuous, trained','stat_charge_dist 40','stat_fire_delay  0','stat_food        60, 300',`stat_cost        ${cost(1000,3,2)}`,'ownership        timurids, slave','era 0            timurids','era 1            timurids','era 2            timurids'].join('\n');}
function cavRecord(u){const q=Q[u.quality],command=u.kind==='command',camel=u.kind==='camel',melee=q.melee,charge=q.charge+1,def=q.def-1,total=command?200:camel?900:u.quality==='militia'?1000:1200;const attrs=['free_upkeep_unit','sea_faring','hide_forest','can_withdraw'];if(u.kind==='lance')attrs.push('can_formed_charge');if(camel)attrs.push('gunpowder_unit','guncavalry','gunmen','start_not_skirmishing','cannot_skirmish','frighten_mounted');if(command)attrs.push('general_unit','command');const rows=command?[`stat_pri         ${melee}, ${charge}, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1`,'stat_pri_attr    no','stat_sec         0, 0, no, 0, 0, no, melee_simple, blunt, none, 0, 1','stat_sec_attr    no']:camel?['stat_pri         32, 2, harquebus_bullet_c, 140, 35, missile, missile_gunpowder, piercing, none, musket_shot_set, 25, 1','stat_pri_attr    ap',`stat_sec         ${melee+1}, ${charge}, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1`,'stat_sec_attr    no']:[`stat_pri         ${melee}, ${charge+3}, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1`,'stat_pri_attr    no',`stat_sec         ${melee}, ${charge}, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1`,'stat_sec_attr    no'];return [
`type             ${u.type}`,`dictionary       ${u.type} ; ${u.label} (${command?'mounted command':camel?'matchlock carbine and pulwar':'lance and pulwar'})`,'category         cavalry',`class            ${camel?'missile':'light'}`,'voice_type       Heavy','accent           farsi','banner faction   main_cavalry','banner holy      crusade_cavalry',`soldier          ${u.type}, ${command?4:24}, 0, 1`,...(command?[]:['officer          fez_off_1g']),`mount            ${camel?'camel':u.kind==='lance'?'lancer':'hussar'}`,`mount_effect     ${camel?'elephant -4, horse +4':'elephant -4, camel -4'}`,`attributes       ${attrs.join(', ')}`,`formation        2, 2, 4, 4, ${command?2:3}, square`,'stat_health      1, 0',...rows,`stat_pri_armour  ${command?6:4}, ${def}, ${command?1:0}, leather`,'stat_sec_armour  0, 0, flesh','stat_heat        0','stat_ground      0, 0, 0, 0',`stat_mental      ${q.morale}, impetuous, ${q.training}`,'stat_charge_dist 45','stat_fire_delay  0','stat_food        60, 300',`stat_cost        ${cost(total,u.limit,command?1:3)}`,'ownership        timurids, slave',...u.eras.map(e=>`era ${e}            timurids`)].join('\n');}
const all=[{type:'afg_lashkar_qawmi',label:'Lashkar-e Qawmi',donor:'moroccan_gunner',card:'__generated_lashkar'},...infantry,...cavalry];
const records=[lashkarRecord(),...infantry.map(infRecord),...cavalry.map(cavRecord)];
function stripFaction(b,f){b=b.replace(/^ownership\s+(.+)$/m,(m,x)=>{const a=x.split(',').map(y=>y.trim()).filter(y=>y&&y!==f);return `ownership        ${a.length?a.join(', '):'slave'}`;});b=b.replace(/^era ([012])\s+(.+)$/gm,(m,e,x)=>{const a=x.split(',').map(y=>y.trim()).filter(y=>y&&y!==f);return a.length?`era ${e}            ${a.join(', ')}`:'';});return b.replace(/\n{3,}/g,'\n\n');}
let edu=fs.readFileSync(eduC,'utf8').replace(/\r\n/g,'\n'),begin='; BEGIN STANDARDIZED AFGHANISTAN',end='; END STANDARDIZED AFGHANISTAN';if(edu.includes(begin)){const a=edu.indexOf(begin),z=edu.indexOf(end,a);edu=edu.slice(0,a)+edu.slice(z+end.length).replace(/^\s*/,'');}
const legacy=['afghan_sword','pashtun_inf','afghan_gen','herat_inf','afghan_cav','pashtun_camel_gunner','afghan_gunner','afghan_rifles','afghan_militia','kabul_guard','indian_bow_cav'];let starts=[...edu.matchAll(/^type\s+(\S+)/gm)],parts=[edu.slice(0,starts[0].index)];for(let i=0;i<starts.length;i++){const t=starts[i][1],z=i+1<starts.length?starts[i+1].index:edu.length;let b=edu.slice(starts[i].index,z);if(legacy.includes(t))b=stripFaction(b,'timurids');parts.push(b);}edu=parts.join('');const at=edu.indexOf('type             afghan_sword');if(at<0)throw Error('Afghanistan insertion point missing');edu=edu.slice(0,at)+`${begin}\n\n${records.join('\n\n')}\n\n${end}\n\n`+edu.slice(at);fs.writeFileSync(eduC,edu.replace(/\n/g,'\r\n'));fs.writeFileSync(eduR,edu.replace(/\n/g,'\r\n'));

let edb=fs.readFileSync(edbC,'utf8').replace(/\r\n/g,'\n');const simple={pashtun_inf:'afg_pashtun_wall_gunners',afghan_gen:'afg_general_staff',pashtun_camel_gunner:'afg_pashtun_camelry',afghan_gunner:'afg_sharpshooters_high',afghan_sword:'afg_ghilzai_nobles',kabul_guard:'afg_kabul_guard_high'};for(const [a,b] of Object.entries(simple))edb=edb.split(`"${a}"`).join(`"${b}"`);
function cleanGates(s){return s.replace(/\s+and (?:not )?event_counter military_reforms_(?:1870|1890|1|2) 1/g,'');}
edb=edb.split('\n').flatMap(line=>{if(line.includes('recruit_pool "herat_inf"'))return [cleanGates(line.replace('"herat_inf"','"afg_lashkar_qawmi"'))];if(line.includes('recruit_pool "afghan_cav"')){const base=cleanGates(line);return [base.replace('"afghan_cav"','"afg_tribal_cavalry"'),base.replace('"afghan_cav"','"afg_regular_cavalry"')+' and event_counter military_reforms_1870 1'];}if(line.includes('recruit_pool "afghan_rifles"')){const base=cleanGates(line);return [base.replace('"afghan_rifles"','"afg_regular_early"')+' and not event_counter military_reforms_1870 1',base.replace('"afghan_rifles"','"afg_regular_mid"')+' and event_counter military_reforms_1870 1 and not event_counter military_reforms_1890 1',base.replace('"afghan_rifles"','"afg_regular_high"')+' and event_counter military_reforms_1890 1'];}if(line.includes('recruit_pool "afghan_militia"')&&line.includes('timurids')){const clone=line.replace('"afghan_militia"','"afg_tajik_hillmen"').replace(/requires factions \{[^}]*\}/,'requires factions { timurids, }');const keep=line.replace(/timurids,?\s*/g,'');return keep.includes('requires factions {  }')?[clone]:[keep,clone];}return [line];}).join('\n');fs.writeFileSync(edbC,edb.replace(/\n/g,'\r\n'));fs.writeFileSync(edbR,edb.replace(/\n/g,'\r\n'));
let strat=fs.readFileSync(stratC,'utf8');
const startMap={afghan_gen:'afg_general_staff',afghan_rifles:'afg_regular_early',afghan_militia:'afg_tajik_hillmen',pashtun_camel_gunner:'afg_pashtun_camelry',herat_inf:'afg_lashkar_qawmi',pashtun_inf:'afg_pashtun_wall_gunners',indian_bow_cav:'afg_tribal_cavalry'};
const factionMatch=strat.match(/(^faction\s+timurids\b[\s\S]*?)(?=^faction\s+bulga\b)/m);
if(!factionMatch)throw Error('Afghanistan campaign block missing');
let factionBlock=factionMatch[1];
for(const [from,to] of Object.entries(startMap))factionBlock=factionBlock.replace(new RegExp(`^(\\s*unit\\s+)${from}(\\s+)`,'gm'),`$1${to}$2`);
strat=strat.replace(factionMatch[1],factionBlock);fs.writeFileSync(stratC,strat);fs.writeFileSync(stratR,strat);

function entries(text){const a=text.replace(/\r\n/g,'\n').split('\n'),r=[];let start=1;for(let i=1;i<a.length;i++)if(/^16 -0\.090000004 /.test(a[i])){r.push({lines:a.slice(start,i+1),name:(a[start].match(/^\d+ (\S+)/)||[])[1]});start=i+1;}return r;}function entry(text,n){const e=entries(text).find(x=>x.name===n);if(!e)throw Error(`Missing model donor ${n}`);return e.lines.join('\n');}function clone(text,donor,name){return entry(text,donor).replace(new RegExp(`^${donor.length} ${donor}\\s*$`,'m'),`${name.length} ${name} `);}function mounted(e){return e.replace(/^\d+ unit_sprites\/[^\s]+_sprite\.spr\s*$/gm,'35 unit_sprites/tmp_cavalry_sprite.spr ');}function anim(e,u){const pri=u.w?.muzzle?'20 MTW2_Fast_Arquebus_3':u.role==='sharpshooter'?'15 MTW2_Musket_SSK':'14 MTW2_Musket_SS';e=e.replace(/(?:20 MTW2_Fast_Arquebus_3|18 MTW2_Fast_Musket_3|18 MTW2_Fast_Arquebus|14 MTW2_Musket_SS|15 MTW2_Musket_SSK)(?=\s)/,pri);if(u.sword==='one')e=e.replace(/(?:11 MTW2_2H_Axe|16 MTW2_2HSwordsman|9 MTW2_Pike)(?!_primary)/,'14 MTW2_Swordsman').replace(/(?:19 MTW2_2H_Axe_primary|24 MTW2_2HSwordsman_Primary|17 MTW2_Pike_primary)/,'18 MTW2_Sword_Primary');if(u.sword==='two')e=e.replace(/(?:11 MTW2_2H_Axe|14 MTW2_Swordsman|9 MTW2_Pike)(?!_primary)/,'16 MTW2_2HSwordsman').replace(/(?:19 MTW2_2H_Axe_primary|18 MTW2_Sword_Primary|17 MTW2_Pike_primary)/,'24 MTW2_2HSwordsman_Primary');return e;}
let model=fs.readFileSync(modelP,'utf8').replace(/\r\n/g,'\n'),added=0;for(const u of all){let fresh=clone(model,u.donor,u.type);if(u.type==='afg_lashkar_qawmi')fresh=anim(fresh,{w:W.jezail,role:'line',sword:'two'});if(infantry.includes(u))fresh=anim(fresh,u);if(cavalry.includes(u))fresh=mounted(fresh);const old=entries(model).find(x=>x.name===u.type);if(old)model=model.replace(old.lines.join('\n'),fresh);else{model=model.trimEnd()+'\n'+fresh+'\n';added++;}}if(added){const h=model.match(/^(22 serialization::archive 3 0 0 0 0 )(\d+)( 0 0 )/);if(!h)throw Error('Bad modeldb header');model=model.replace(h[0],`${h[1]}${+h[2]+added}${h[3]}`);}fs.writeFileSync(modelP,model.replace(/\n/g,'\r\n'));

let raw=fs.readFileSync(locP),loc=raw.slice(raw[0]===255&&raw[1]===254?2:0).toString('utf16le').replace(/\r\n/g,'\n');for(const u of all)for(const k of [u.type,`${u.type}_descr`,`${u.type}_descr_short`])loc=loc.replace(new RegExp(`^\\{${k}\\}.*(?:\\n|$)`,'gm'),'');const rows=all.map(u=>{const b=u.type==='afg_lashkar_qawmi'?'A massed tribal host armed with hand-crafted Afghan jezails and pulwars.':u.type==='afg_tajik_hillmen'?'Tajik mountain skirmishers armed with long hand-crafted jezails and pulwars.':u.type==='afg_general_staff'?'The Afghan commander-in-chief and his compact mounted staff.':`${u.label} serve in the army of the Afghan Amir.`;return `{${u.type}}${u.label}\n{${u.type}_descr}${b}\n{${u.type}_descr_short}${u.label}`;});loc=loc.trimEnd()+'\n\n'+rows.join('\n\n')+'\n';fs.writeFileSync(locP,Buffer.concat([Buffer.from([255,254]),Buffer.from(loc.replace(/\n/g,'\r\n'),'utf16le')]));
fs.mkdirSync(archive,{recursive:true});for(const n of ['afghan_sword','pashtun_inf','afghan_gen','herat_inf','afghan_cav','pashtun_camel_gunner','afghan_gunner','afghan_rifles','afghan_militia','kabul_guard']){const s=path.join(cards,`#${n}.tga`),d=path.join(archive,`#${n}.tga`);if(!fs.existsSync(d))fs.copyFileSync(s,d);}const cardMap={afg_tajik_hillmen:'afghan_militia',afg_pashtun_wall_gunners:'pashtun_inf',afg_regular_early:'afghan_rifles',afg_regular_mid:'afghan_rifles',afg_regular_high:'kabul_guard',afg_kabul_guard_high:'kabul_guard',afg_regular_cavalry:'afghan_cav',afg_pashtun_camelry:'pashtun_camel_gunner'};for(const [to,from] of Object.entries(cardMap))fs.copyFileSync(path.join(cards,`#${from}.tga`),path.join(cards,`#${to}.tga`));
if(!fs.readFileSync(eduC).equals(fs.readFileSync(eduR)))throw Error('EDU mirrors differ');if(!fs.readFileSync(edbC).equals(fs.readFileSync(edbR)))throw Error('EDB mirrors differ');console.log(`Standardized Afghanistan: ${records.length} records; added ${added} model entries.`);
