const fs=require('fs'),path=require('path'),R=path.resolve(__dirname,'..');
const EDU=path.join(R,'data/tow_steamsteel/export_descr_unit.txt'),MIR=path.join(R,'data/export_descr_unit.txt'),LOC=path.join(R,'data/text/export_units.txt');
const BACK=path.join(R,'tools/backup_before_indian_princely_20260917');fs.mkdirSync(BACK,{recursive:true});for(const p of [EDU,MIR,LOC]){const d=path.join(BACK,path.basename(p));if(!fs.existsSync(d))fs.copyFileSync(p,d)}
let e=fs.readFileSync(EDU,'utf8').replace(/\r/g,'');
function block(t){const m=e.match(new RegExp(`^type\\s+${t}\\n[\\s\\S]*?(?=^type\\s+|(?![\\s\\S]))`,'m'));if(!m)throw Error('missing '+t);return m[0].trimEnd()}
function rep(t,b){e=e.replace(block(t),b.trimEnd())} function unit(t,x){rep(t,`type             ${t}\n${x.join('\n')}`)}
const cost=(n,lim,time=2)=>`${time}, ${n}, ${Math.round(n/3)}, 100, 100, ${n}, ${lim}, ${Math.round(n/3)}`;
unit('indian_bow_cav',[`dictionary       indian_bow_cav ; Sowar Banduqchi (Matchlock Carbine)`,`category         cavalry`,`class            missile`,`voice_type       Heavy`,`accent           hindi`,`banner faction   main_cavalry`,`banner holy      crusade_cavalry`,`soldier          indian_bow_cav, 24, 0, 1`,`officer          yindujunguan`,`mount            dragoon`,`mount_effect     elephant -4, camel -4`,`attributes       free_upkeep_unit, sea_faring, can_withdraw, hide_forest, gunpowder_unit, gunmen, guncavalry, start_not_skirmishing`,`formation        2, 2, 4, 4, 3, square`,`stat_health      1, 0`,`stat_pri         32, 0, arquebus_bullet_c, 140, 35, missile, missile_gunpowder, piercing, none, musket_shot_set, 50, 1`,`stat_pri_attr    ap`,`stat_sec         4, 3, no, 0, 0, melee, melee_blade, slashing, sword, 25, 1`,`stat_sec_attr    no`,`stat_pri_armour  4, 2, 0, leather`,`stat_sec_armour  0, 0, flesh`,`stat_heat        2`,`stat_ground      0, 0, 0, 0`,`stat_mental      3, low, trained`,`stat_charge_dist 50`,`stat_fire_delay  0`,`stat_food        60, 300`,`stat_cost        ${cost(1100,2,3)}`,`ownership        bulga, slave`,`era 0            bulga, slave`,`era 1            bulga, slave`]);
unit('indian_spear_cav',[`dictionary       indian_spear_cav ; Risala Lancers`,`category         cavalry`,`class            light`,`voice_type       Light`,`accent           hindi`,`banner faction   main_cavalry`,`banner holy      crusade_cavalry`,`soldier          indian_spear_cav, 24, 0, 1`,`officer          yindujunguan`,`mount            lancer`,`mount_effect     elephant -4, camel -4`,`attributes       free_upkeep_unit, sea_faring, can_withdraw`,`formation        2, 2, 4, 4, 3, square`,`stat_health      1, 0`,`stat_pri         4, 6, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1`,`stat_pri_attr    no`,`stat_sec         4, 3, no, 0, 0, melee, melee_blade, slashing, sword, 25, 1`,`stat_sec_attr    no`,`stat_pri_armour  4, 2, 0, leather`,`stat_sec_armour  0, 0, flesh`,`stat_heat        2`,`stat_ground      0, 0, 0, 0`,`stat_mental      3, low, trained`,`stat_charge_dist 50`,`stat_fire_delay  0`,`stat_food        60, 300`,`stat_cost        ${cost(1200,1,3)}`,`ownership        bulga, slave`,`era 1            bulga, slave`,`era 2            bulga, slave`]);
unit('Sikh_heavy_cavalry',[`dictionary       Sikh_heavy_cavalry ; Khalsa Gorchara`,`category         cavalry`,`class            heavy`,`voice_type       Heavy`,`accent           hindi`,`banner faction   main_cavalry`,`banner holy      crusade_cavalry`,`soldier          Sikh_heavy_cavalry, 24, 0, 1`,`officer          yindujunguan`,`mount            heavy horse`,`mount_effect     elephant -4, camel -4`,`attributes       free_upkeep_unit, sea_faring, can_withdraw`,`formation        2, 2, 4, 4, 3, square`,`stat_health      1, 0`,`stat_pri         6, 4, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1`,`stat_pri_attr    no`,`stat_sec         6, 4, no, 0, 0, melee, melee_blade, slashing, sword, 25, 1`,`stat_sec_attr    no`,`stat_pri_armour  4, 3, 1, metal`,`stat_sec_armour  0, 0, flesh`,`stat_heat        3`,`stat_ground      0, 0, 0, 0`,`stat_mental      5, impetuous, highly_trained`,`stat_charge_dist 50`,`stat_fire_delay  0`,`stat_food        60, 300`,`stat_cost        ${cost(1200,1,3)}`,`ownership        bulga, slave`,`era 0            bulga, slave`]);
unit('indian_spears',[`dictionary       indian_spears ; Lashkar Nayzabaz`,`category         infantry`,`class            spearmen`,`voice_type       Light`,`accent           hindi`,`banner faction   main_spear`,`banner holy      crusade`,`soldier          indian_spears, 80, 0, 1`,`officer          yindujunguan`,`attributes       free_upkeep_unit, sea_faring, hide_forest`,`formation        1.2, 1.2, 1.2, 1.2, 3, square`,`stat_health      1, 0`,`stat_pri         2, 2, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1`,`stat_pri_attr    spear`,`stat_sec         0, 0, no, 0, 0, no, melee_simple, blunt, none, 0, 1`,`stat_sec_attr    no`,`stat_pri_armour  3, 1, 4, flesh`,`stat_sec_armour  0, 0, flesh`,`stat_heat        2`,`stat_ground      0, 0, 0, 0`,`stat_mental      2, low, untrained`,`stat_charge_dist 40`,`stat_fire_delay  0`,`stat_food        60, 300`,`stat_cost        ${cost(500,2,1)}`,`ownership        bulga, slave`,`era 0            bulga, slave`]);
function gun(t,name,soldier,n,proj,range,quality,melee,charge,shield,total,limit,eras,sec='spear',secattr='ap, short_pike',formation='1.2, 1.2, 1.2, 1.2, 3, square',attrs='free_upkeep_unit, sea_faring, hide_forest, gunpowder_unit, gunmen, start_not_skirmishing, cannot_skirmish'){
 const q=quality==='elite'?{def:3,mor:5,disc:'normal',train:'highly_trained'}:quality==='regular'?{def:2,mor:3,disc:'low',train:'trained'}:{def:1,mor:2,disc:'low',train:'untrained'};
 unit(t,[`dictionary       ${t} ; ${name}`,`category         infantry`,`class            missile`,`voice_type       Light`,`accent           hindi`,`banner faction   main_missile`,`banner holy      crusade`,`soldier          ${soldier}, ${n}, 0, 1`,`officer          yindujunguan`,`attributes       ${attrs}`,`formation        ${formation}`,`stat_health      1, 0`,`stat_pri         ${proj==='rifle_bullet_b'?19:proj==='wall_gun_bullet'?45:proj==='long_gun_bullet'?29:37}, 0, ${proj}, ${range}, 35, missile, missile_gunpowder, piercing, none, musket_shot_set, 0, -999`,`stat_pri_attr    ap`,`stat_sec         ${melee}, ${charge}, no, 0, 0, melee, melee_blade, ${sec==='axe'?'slashing':sec==='sword'?'slashing':'piercing'}, ${sec}, 25, 1`,`stat_sec_attr    ${secattr}`,`stat_pri_armour  3, ${q.def}, ${shield}, leather`,`stat_sec_armour  0, 0, flesh`,`stat_heat        2`,`stat_ground      0, 0, 0, 0`,`stat_mental      ${q.mor}, ${q.disc}, ${q.train}`,`stat_charge_dist 40`,`stat_fire_delay  0`,`stat_food        60, 300`,`stat_cost        ${cost(total,limit,2)}`,`ownership        bulga, slave`,...eras.map(x=>`era ${x}            bulga, slave`)]);
}
gun('indian_heavy_banduqchis','Rajput Banduqchi (Hand-Crafted Long Gun)','rajput_snipers',30,'long_gun_bullet',280,'regular',5,3,0,900,1,[0,1,2],'axe','ap','1.4, 1.8, 2.8, 3.6, 3, square');
gun('indian_new_musk','Maratha Paltan (Brown Bess Musket)','indian_new_musk',40,'musket_bullet_c',200,'regular',5,3,0,1000,2,[0,1],'sword','no');
gun('india_sepoy','Purbiya Sepoys (Brown Bess Musket)','uk_sikh_reg',40,'musket_bullet_c',200,'regular',4,3,0,1000,2,[0]);
gun('sikh_warriors','Khalsa Guard (Martini-Henry Rifle)','sikh_warriors',40,'rifle_bullet_b',240,'elite',7,4,2,1700,1,[1,2],'sword','no','1.2, 1.2, 2.0, 2.4, 3, square','free_upkeep_unit, sea_faring, hide_forest, gunmen, start_not_skirmishing, cannot_skirmish');
gun('india_militia','Jazailchi Gingal Wall Gunners','india_militia',30,'wall_gun_bullet',240,'militia',3,2,0,700,1,[0,1],'axe','ap','1.4, 1.8, 2.8, 3.6, 3, square');
unit('sikh_gen',[`dictionary       sikh_gen ; Maharaja aur Lashkar`,`category         cavalry`,`class            light`,`voice_type       Heavy`,`accent           hindi`,`banner faction   main_cavalry`,`banner holy      crusade_cavalry`,`soldier          sikh_gen, 4, 0, 1`,`officer          yindujunguan`,`mount            hussar`,`mount_effect     elephant -4, camel -4`,`attributes       free_upkeep_unit, sea_faring, general_unit, command`,`formation        2, 2, 4, 4, 2, square`,`stat_health      1, 0`,`stat_pri         6, 4, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1`,`stat_pri_attr    no`,`stat_sec         6, 4, no, 0, 0, melee, melee_blade, slashing, sword, 25, 1`,`stat_sec_attr    no`,`stat_pri_armour  4, 3, 2, leather`,`stat_sec_armour  0, 0, flesh`,`stat_heat        2`,`stat_ground      0, 0, 0, 0`,`stat_mental      5, normal, highly_trained`,`stat_charge_dist 50`,`stat_fire_delay  0`,`stat_food        60, 300`,`stat_cost        ${cost(200,1,1)}`,`ownership        bulga, slave`,`era 0            bulga, slave`,`era 1            bulga, slave`,`era 2            bulga, slave`]);
unit('indian_fanatic',[`dictionary       indian_fanatic ; Akali Jatha`,`category         infantry`,`class            light`,`voice_type       Light`,`accent           hindi`,`banner faction   main_spear`,`banner holy      crusade`,`soldier          indian_fanatic, 80, 0, 1`,`officer          yindujunguan`,`attributes       free_upkeep_unit, sea_faring, hide_forest`,`formation        1.2, 1.2, 1.2, 1.2, 3, square`,`stat_health      1, 0`,`stat_pri         5, 2, javelin, 60, 2, thrown, missile_mechanical, piercing, spear, 25, 1`,`stat_pri_attr    prec, thrown`,`stat_sec         7, 4, no, 0, 0, melee, melee_blade, slashing, sword, 25, 1`,`stat_sec_attr    no`,`stat_pri_armour  3, 3, 2, flesh`,`stat_sec_armour  0, 0, flesh`,`stat_heat        2`,`stat_ground      0, 0, 0, 0`,`stat_mental      5, impetuous, highly_trained`,`stat_charge_dist 40`,`stat_fire_delay  0`,`stat_food        60, 300`,`stat_cost        ${cost(900,1,1)}`,`ownership        bulga, slave`,`era 0            bulga, slave`,`era 1            bulga, slave`]);
const bhutan=`type             ind_bhutan_warrior\ndictionary       ind_bhutan_warrior ; Druk Pahlam\ncategory         infantry\nclass            light\nvoice_type       Heavy\nbanner faction   main_infantry\nbanner holy      crusade\nsoldier          bhutan_warrior, 80, 0, 1\nattributes       free_upkeep_unit, sea_faring, hide_forest\nformation        1.2, 1.2, 1.2, 1.2, 3, square\nstat_health      1, 0\nstat_pri         3, 2, no, 0, 0, melee, melee_blade, slashing, sword, 25, 1\nstat_pri_attr    no\nstat_sec         0, 0, no, 0, 0, no, melee_simple, blunt, none, 0, 1\nstat_sec_attr    no\nstat_pri_armour  3, 1, 2, flesh\nstat_sec_armour  0, 0, flesh\nstat_heat        2\nstat_ground      0, 0, 0, 0\nstat_mental      2, low, untrained\nstat_charge_dist 15\nstat_fire_delay  0\nstat_food        60, 300\nstat_cost        ${cost(500,1,1)}\nownership        bulga, slave\nera 0            bulga, slave\nera 1            bulga, slave\nera 2            bulga, slave`;
if(/(^|\n)type\s+ind_bhutan_warrior\n/.test(e))rep('ind_bhutan_warrior',bhutan);else e=e.replace(block('merc_bhutan_warrior').trimEnd(),block('merc_bhutan_warrior').trimEnd()+'\n\n'+bhutan);
let sharedBhutan=block('merc_bhutan_warrior').replace(/^ownership.*$/m,'ownership        slave, england').replace(/^era\s+([012]).*$/gm,'era $1            england');rep('merc_bhutan_warrior',sharedBhutan);
let el=block('indian_ele').replace(/^dictionary.*$/m,'dictionary       indian_ele ; Hathi Banduqchi').replace(/^attributes.*$/m,'attributes       sea_faring, can_withdraw, can_run_amok, frighten_foot, frighten_mounted, gunpowder_unit').replace(/^stat_ground.*$/m,'stat_ground      0, 0, 0, 0').replace(/^stat_mental.*$/m,'stat_mental      3, low, trained').replace(/^stat_fire_delay.*$/m,'stat_fire_delay  0').replace(/^stat_cost.*$/m,'stat_cost        4, 2600, 867, 100, 100, 2600, 1, 867');rep('indian_ele',el);
function artillery(t,eras,visible=true){let b=block(t).replace(/^stat_fire_delay.*$/m,'stat_fire_delay  0').replace(/^stat_mental.*$/m,'stat_mental      3, low, trained').replace(/^ownership.*$/m,visible?'ownership        bulga, slave':'ownership        slave').replace(/^era\s+[012].*$/gm,'').trimEnd();const row=(b.match(/^stat_cost\s+(.+)$/m)||[,''])[1].split(',').map(x=>Number(x.trim()));if(row.length===8){const upkeep=Math.round(row[1]/3);b=b.replace(/^stat_cost.*$/m,`stat_cost        ${row[0]}, ${row[1]}, ${upkeep}, 100, 100, ${row[5]}, ${row[6]}, ${upkeep}`)}if(visible)for(const x of eras)b+=`\nera ${x}            bulga, slave`;rep(t,b)}
artillery('ind_armstrong',[0,1]);artillery('ind_12lb',[2]);artillery('ind_5lb',[2]);artillery('ind_maxim',[2]);artillery('ind_gatling',[],false);artillery('ind_150mm',[],false);
e=e.replace(/\n/g,'\r\n');fs.writeFileSync(EDU,e);fs.writeFileSync(MIR,e);
let mp=path.join(R,'data/unit_models/battle_models.modeldb'),m=fs.readFileSync(mp,'utf8');function mb(n){const x=m.match(new RegExp(`^${n.length} ${n}\\s*$[\\s\\S]*?(?=^\\d+ [^\\s;]+\\s*$\\r?\\n\\d+ \\d+\\s*$|(?![\\s\\S]))`,'m'));if(!x)throw Error('model '+n);return x[0]}function mr(n,f){const o=mb(n);m=m.replace(o,f(o))}
const donor=mb('sikh_gen').replace(/^8 sikh_gen\s*$/m,'16 indian_spear_cav');m=m.replace(mb('indian_spear_cav'),donor);
mr('indian_new_musk',b=>b.replace('11 MTW2_Musket','20 MTW2_Fast_Arquebus_3'));mr('rajput_snipers',b=>b.replace('18 MTW2_Fast_Musket_3','20 MTW2_Fast_Arquebus_3'));const wallDonor=mb('india_light_musk').replace(/^16 india_light_musk\s*$/m,'13 india_militia').replace('18 MTW2_Fast_Musket_3','20 MTW2_Fast_Arquebus_3');m=m.replace(mb('india_militia'),wallDonor);fs.writeFileSync(mp,m);
let buf=fs.readFileSync(LOC),bom=buf[0]===255&&buf[1]===254,s=buf.subarray(bom?2:0).toString('utf16le');const names={indian_bow_cav:'Sowar Banduqchi (Matchlock Carbine)',indian_spear_cav:'Risala Lancers',Sikh_heavy_cavalry:'Khalsa Gorchara',indian_spears:'Lashkar Nayzabaz',indian_heavy_banduqchis:'Rajput Banduqchi (Hand-Crafted Long Gun)',indian_new_musk:'Maratha Paltan (Brown Bess Musket)',india_sepoy:'Purbiya Sepoys (Brown Bess Musket)',sikh_gen:'Maharaja aur Lashkar',sikh_warriors:'Khalsa Guard (Martini-Henry Rifle)',indian_fanatic:'Akali Jatha',indian_ele:'Hathi Banduqchi',india_militia:'Jazailchi Gingal Wall Gunners',ind_bhutan_warrior:'Druk Pahlam'};for(const [k,v] of Object.entries(names)){const line=`{${k}}${v}`;if(new RegExp(`\\{${k}\\}`).test(s))s=s.replace(new RegExp(`\\{${k}\\}[^\\r\\n]*`),line);else s+=`\r\n${line}\r\n{${k}_descr}Bhutanese sword-and-shield auxiliaries recruited from the Himalayan valleys.\r\n{${k}_descr_short}Bhutanese sword-and-shield auxiliaries.\r\n`}fs.writeFileSync(LOC,Buffer.concat([Buffer.from([255,254]),Buffer.from(s,'utf16le')]));
console.log('Standardized Indian Princely States as D tier with mesh-supported bonuses only.');
