const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),eduC=path.join(root,'data/tow_steamsteel/export_descr_unit.txt'),eduR=path.join(root,'data/export_descr_unit.txt'),modelP=path.join(root,'data/unit_models/battle_models.modeldb'),locP=path.join(root,'data/text/export_units.txt'),soundP=path.join(root,'data/export_descr_sounds_units_voice.txt');
const E={early:{n:0,name:'Early',form:'1.2, 1.2, 1.2, 1.2, 3, square'},mid:{n:1,name:'Mid',form:'1.2, 1.2, 2.0, 2.4, 3, square'},high:{n:2,name:'Late',form:'1.2, 1.4, 2.4, 2.8, 3, square'}};
const W={m1860:{weapon:'Fucile di fanteria Mod. 1860',damage:37,family:'rifled_musket',range:220,ammo:35,smoke:'musket_shot_set',cost:1200,muzzle:true,mode:'fast'},vetterli:{weapon:'Fucile Vetterli Mod. 1870',damage:19,family:'rifle',range:240,ammo:35,smoke:'musket_shot_set',cost:1500,mode:'musket'},vitali:{weapon:'Fucile Vetterli-Vitali Mod. 1870/87',damage:19,family:'magazine_rifle',range:260,ammo:40,smoke:'smokeless_shot_set',cost:1800,mode:'fast'},carcano:{weapon:'Fucile Carcano Mod. 1891',damage:10,family:'magazine_rifle',range:260,ammo:40,smoke:'smokeless_shot_set',cost:1800,mode:'fast'}};
const Q={militia:{melee:3,charge:2,defence:2,morale:3,discipline:'low',training:'trained',premium:-200},regular:{melee:5,charge:3,defence:3,morale:4,discipline:'normal',training:'trained',premium:0},elite:{melee:7,charge:4,defence:4,morale:6,discipline:'disciplined',training:'highly_trained',premium:200}};
const cost=(n,limit=1)=>`3, ${n}, ${Math.round(n/3)}, 100, 100, ${n}, ${limit}, ${Math.round(n/3)}`;
const tier=(q,role)=>'cbas'[Math.min(3,(q==='militia'?0:q==='elite'?2:1)+(role==='skirmisher'?1:0))];
function U(type,label,period,q,role,weapon,donor,card,opts={}){const b={...Q[q]};return{type,label,period,q,role,weapon,donor,card,...b,discipline:opts.discipline||b.discipline,strength:opts.strength||(role==='skirmisher'?30:40),limit:opts.limit||1,total:weapon.cost+b.premium+(opts.costDelta||0),...opts};}
const inf=[];
for(const p of ['early','mid','high'])inf.push(U(`ita_line_${p}`,'Fanteria di linea',p,'regular','line',p==='early'?W.m1860:p==='mid'?W.vetterli:W.carcano,p==='early'?'rus_cos_guard_ve':p==='mid'?'ita_line_early':'it_bers','rus_cos_guard_ve',{limit:3}));
for(const p of ['early','mid','high'])inf.push(U(`ita_milizia_${p}`,p==='early'?'Guardia Nazionale Mobile':'Milizia Mobile',p,'militia','line',p==='early'?W.m1860:p==='mid'?W.m1860:W.vetterli,p==='early'?'rus_cos_guard_ve':`ita_milizia_${p==='mid'?'early':'mid'}`,'it_royals',{limit:2}));
for(const p of ['early','mid','high'])inf.push(U(`ita_granatieri_${p}`,'Granatieri di Sardegna',p,'elite','line',p==='early'?W.m1860:p==='mid'?W.vetterli:W.carcano,p==='early'?'peru_roy_inf':p==='mid'?'ita_granatieri_early':'ita_granatieri_mid','fra_guard_ve',{special:true}));
for(const p of ['early','mid','high'])inf.push(U(`ita_bersaglieri_${p}`,'Bersaglieri',p,'regular','skirmisher',p==='early'?W.m1860:p==='mid'?W.vetterli:W.carcano,p==='early'?'it_bers':p==='mid'?'ita_bersaglieri_early':'ita_bersaglieri_mid','it_bers',{special:true}));
for(const p of ['mid','high'])inf.push(U(`ita_alpini_${p}`,'Alpini',p,'regular','skirmisher',p==='mid'?W.vetterli:W.carcano,p==='mid'?'it_sailor':'ita_alpini_mid','it_arditi',{special:true}));
for(const p of ['early','mid','high'])inf.push(U(`ita_marina_${p}`,p==='early'?'Fanteria Real Marina':p==='mid'?'Fucilieri di Marina':'Brigata Marina',p,'regular','line',p==='early'?W.m1860:p==='mid'?W.vetterli:W.vitali,p==='early'?'fra_sailors':p==='mid'?'ita_marina_early':'ita_marina_mid','fra_sailors_venice'));
for(const p of ['early','mid','high'])inf.push(U(`ita_zappatori_${p}`,'Zappatori del Genio',p,'regular','line',p==='early'?W.m1860:p==='mid'?W.vetterli:W.vitali,p==='early'?'dan_inf_ve':p==='mid'?'ita_zappatori_early':'ita_zappatori_mid','dan_inf_ve',{special:true}));
inf.push(U('ita_garibaldini_early','Volontari Garibaldini','early','regular','line',W.m1860,'peru_roy_inf','us_front_inf_it',{volunteer:true,discipline:'impetuous'}));
inf.push(U('ita_arditi_high','Arditi','high','elite','line',W.carcano,'it_sailor','merc_it_arditi',{special:true,cardSource:'mercs'}));
inf.push(U('ita_ascari_high','Ascari eritrei','high','regular','line',W.vitali,'arab_sailors1','libya_inf',{colonial:true,costDelta:-100}));
inf.push(U('ita_libici_high','Fanteria libica','high','regular','line',W.vitali,'arab_sailors1','libya_inf',{colonial:true,costDelta:-100,cardSource:'slave'}));
function infantry(u){const w=u.weapon,attrs=['free_upkeep_unit','sea_faring','hide_forest'];if(w.muzzle)attrs.push('gunpowder_unit');attrs.push('gunmen','start_not_skirmishing','cannot_skirmish');if(u.period==='high'||u.type.startsWith('ita_zappatori_'))attrs.push('stakes');return [`type             ${u.type}`,`dictionary       ${u.type} ; ${u.label} (${E[u.period].name}; ${w.weapon})`,'category         infantry','class            missile','voice_type       Light','accent           italian','banner faction   main_infantry','banner holy      crusade',`soldier          ${u.type}, ${u.strength}, 0, 1.2`,'officer          shk_off_1g',`attributes       ${attrs.join(', ')}`,`formation        ${u.role==='skirmisher'?'1.4, 1.8, 2.8, 3.6, 3, square':E[u.period].form}`,'stat_health      1, 0',`stat_pri         ${w.damage}, 0, ${w.family}_bullet_${tier(u.q,u.role)}, ${w.range+(u.role==='skirmisher'?40:0)}, ${w.ammo}, missile, missile_gunpowder, piercing, none, ${w.smoke}, 0, -999`,'stat_pri_attr    ap',`stat_sec         ${u.melee}, ${u.charge}, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1.2`,'stat_sec_attr    short_pike, ap',`stat_pri_armour  3, ${u.defence}, 0, leather`,'stat_sec_armour  0, 0, flesh','stat_heat        0','stat_ground      0, 0, 0, 0',`stat_mental      ${u.morale}, ${u.discipline}, ${u.training}`,'stat_charge_dist 40','stat_fire_delay  0','stat_food        60, 300',`stat_cost        ${cost(u.total,u.limit)}`,'ownership        venice, slave',`era ${E[u.period].n}            venice`].join('\n');}
const CW={early:{weapon:'Carabina rigata Mod. 1860',damage:37,family:'rifled_musket_carbine',range:200,ammo:35,smoke:'musket_shot_set',cost:1400,muzzle:true},mid:{weapon:'Carabina Vetterli Mod. 1870',damage:19,family:'rifle_carbine',range:220,ammo:35,smoke:'musket_shot_set',cost:1700},high:{weapon:'Moschetto Carcano Mod. 1891 da cavalleria',damage:10,family:'magazine_rifle_carbine',range:240,ammo:40,smoke:'smokeless_shot_set',cost:2000}};
const cav=[{type:'ita_cavalleggeri',label:'Cavalleggeri',kind:'pistol',donor:'euro_hussars',card:'euro_hussars_venice',morale:4,total:1200},{type:'ita_lancieri',label:'Lancieri',kind:'lance',donor:'gre_lancers',card:'aus_lancers',morale:4,total:1200},{type:'ita_general_staff',label:'Generale e Stato Maggiore',kind:'pistol',donor:'it_pistoleer',card:'it_pistoleer',morale:6,total:200,general:true}];
for(const p of ['early','mid','high'])cav.push({type:`ita_carabinieri_${p}`,label:'Carabinieri Reali',period:p,kind:'carbine',weapon:CW[p],donor:p==='early'?'it_carbs':`ita_carabinieri_${p==='mid'?'early':'mid'}`,card:'it_carbs',morale:4,total:CW[p].cost});
function cavalry(u){const carbine=u.kind==='carbine',lance=u.kind==='lance',elite=u.general,q=elite?Q.elite:Q.regular,attrs=['free_upkeep_unit','sea_faring','hide_forest','can_withdraw'];if(!lance)attrs.push('guncavalry','gunmen','start_not_skirmishing','cannot_skirmish');if(carbine){if(u.weapon.muzzle)attrs.push('gunpowder_unit');if(u.period==='high')attrs.push('stakes');}if(u.general)attrs.push('general_unit','command');let pri=lance?'5, 4, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1':carbine?`${u.weapon.damage}, 2, ${u.weapon.family}_bullet_c, ${u.weapon.range}, ${u.weapon.ammo}, missile, missile_gunpowder, piercing, none, ${u.weapon.smoke}, 25, 1`:'20, 4, magazine_rifle_bullet_c, 60, 15, missile, missile_gunpowder, piercing, none, musket_shot_set, 25, 1';const equip=lance?'lancia e sciabola':carbine?`${u.weapon.weapon} e sciabola`:'Revolver Mod. 1889 Bodeo e sciabola';return [`type             ${u.type}`,`dictionary       ${u.type} ; ${u.label}${u.period?` (${E[u.period].name}; ${equip})`:` (${equip})`}`,'category         cavalry',`class            ${carbine?'missile':elite?'heavy':'light'}`,'voice_type       Heavy','accent           italian','banner faction   main_cavalry','banner holy      crusade_cavalry',`soldier          ${u.type}, ${elite?4:24}, 0, 1`,'officer          shk_off_1g','mount            hussar','mount_effect     elephant -4, camel -4',`attributes       ${attrs.join(', ')}`,'formation        2, 2, 4, 4, 3, square','stat_health      1, 0',`stat_pri         ${pri}`,'stat_pri_attr    ap',`stat_sec         ${q.melee}, ${q.charge}, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1`,'stat_sec_attr    ap',`stat_pri_armour  4, ${elite?4:3}, 0, leather`,'stat_sec_armour  0, 0, flesh','stat_heat        0','stat_ground      0, 0, 0, 0',`stat_mental      ${u.morale}, ${q.discipline}, ${q.training}`,'stat_charge_dist 45','stat_fire_delay  -20000','stat_food        60, 300',`stat_cost        ${cost(u.total)}`,'ownership        venice, slave',...(u.period?[`era ${E[u.period].n}            venice`]:['era 0            venice','era 1            venice','era 2            venice'])].join('\n');}
const all=[...inf,...cav],records=Object.fromEntries([...inf.map(u=>[u.type,infantry(u)]),...cav.map(u=>[u.type,cavalry(u)])]);
records.ita_general_staff=records.ita_general_staff
  .replace('class            heavy','class            light')
  .replace('formation        2, 2, 4, 4, 3, square','formation        2, 2, 4, 4, 2, square');
for(const type of [
  'ita_line_early','ita_line_mid','ita_milizia_early','ita_milizia_mid',
  'ita_granatieri_early','ita_granatieri_mid','ita_bersaglieri_early','ita_bersaglieri_mid',
  'ita_alpini_mid','ita_marina_early','ita_marina_mid','ita_zappatori_early',
  'ita_zappatori_mid','ita_garibaldini_early'
]) records[type]=records[type].replace('officer          shk_off_1g','officer          shk_off_1g\nofficer          russia_qi');
const legacy={fra_sailors_venice:['ita_marina_mid','fra_sailors'],euro_hussars_venice:['ita_cavalleggeri','euro_hussars'],it_carbs:['ita_carabinieri_mid','it_carbs'],it_pistoleer:['ita_general_staff','it_pistoleer'],rus_cos_guard_ve:['ita_line_early','rus_cos_guard_ve'],dan_inf_ve:['ita_zappatori_early','dan_inf_ve'],it_bers:['ita_line_high','it_bers'],us_front_inf_it:['ita_garibaldini_early','peru_roy_inf'],it_arditi:['ita_alpini_high','it_sailor'],libya_inf:['ita_libici_high','arab_sailors1']};
function alias(old,modern,soldier){return records[modern].replace(/^type\s+.*$/m,`type             ${old}`).replace(/^dictionary\s+\S+/m,`dictionary       ${old}`).replace(/^soldier\s+\S+,/m,`soldier          ${soldier},`).replace(/^ownership\s+.*$/m,'ownership        slave').replace(/^era [012]\s+venice\n?/gm,'').trimEnd();}
const block=['; ============================================================================','; Italy (venice) — standardized infantry and cavalry','; ============================================================================',...inf.map(infantry),...cav.map(cavalry),'; Legacy internal-name compatibility (not assigned to custom-battle eras)',...Object.entries(legacy).map(([o,[m,s]])=>alias(o,m,s))].join('\n\n')+'\n\n';
let edu=fs.readFileSync(eduC,'utf8').replace(/\r\n/g,'\n');const title=edu.indexOf('; Italy (venice)'),start=edu.lastIndexOf('; ============================================================================',title),russia=edu.indexOf(';################ The Russian Empire',title),end=edu.lastIndexOf('\n;;;;;;;;;;;;;;;;',russia)+1;if(start<0||end<1)throw Error('Italy block not found');edu=edu.slice(0,start)+block+edu.slice(end);edu=edu.replace(/(^type\s+it_royals\s*$[\s\S]*?)(?=^type\s+|^; =+)/m,m=>m.replace(/^era [012]\s+.*venice.*\n?/gm,''));const out=edu.replace(/\n/g,'\r\n');fs.writeFileSync(eduC,out);fs.writeFileSync(eduR,out);
function entry(text,name){const a=text.replace(/\r\n/g,'\n').split('\n'),i=a.findIndex(x=>new RegExp(`^${name.length} ${name}\\s*$`).test(x));if(i<0)throw Error(`Missing donor ${name}`);let j=i;while(j<a.length&&!/^16 -0\.090000004 /.test(a[j]))j++;return a.slice(i,j+1).join('\n');}
function clone(text,donor,name,mode,italianLance=false,pistolSabre=false){let e=entry(text,donor).replace(new RegExp(`^${donor.length} ${donor}\\s*$`,'m'),`${name.length} ${name} `);if(mode==='musket')e=e.replace(/(?:20 MTW2_Fast_Arquebus_3|15 MTW2_Musket_SSK|17 MTW2_Flamethrower) 9 MTW2_Pike /,'14 MTW2_Musket_SS 9 MTW2_Pike ');if(mode==='skirmisher')e=e.replace(/(?:20 MTW2_Fast_Arquebus_3|14 MTW2_Musket_SS|17 MTW2_Flamethrower) 9 MTW2_Pike /,'15 MTW2_Musket_SSK 9 MTW2_Pike ');if(mode==='fast')e=e.replace(/(?:14 MTW2_Musket_SS|15 MTW2_Musket_SSK|17 MTW2_Flamethrower) 9 MTW2_Pike /,'20 MTW2_Fast_Arquebus_3 9 MTW2_Pike ');if(italianLance)e=e.replace(/7 mongols/g,'6 venice').replace(/unit_models\/_Units\/gre\/textures\/gre_cav_2g\.texture/g,'unit_models/_Units/aus/textures/aus_lan_1g.texture');if(pistolSabre)e=e.replace('14 MTW2_HR_Pistol 13 MTW2_HR_Spear','14 MTW2_HR_Pistol 13 MTW2_HR_Sword').replace('21 MTW2_HR_spear_Primary','18 MTW2_Sword_Primary');return e;}
let model=fs.readFileSync(modelP,'utf8').replace(/\r\n/g,'\n'),added=0;for(const u of inf){const mode=u.role==='skirmisher'&&!u.weapon.muzzle?'skirmisher':u.weapon.mode;const fresh=clone(model,u.donor,u.type,mode);if(new RegExp(`^${u.type.length} ${u.type} $`,'m').test(model))model=model.replace(entry(model,u.type),fresh);else{model=model.trimEnd()+'\n'+fresh+'\n';added++;}}for(const u of cav){const fresh=clone(model,u.donor,u.type,null,u.kind==='lance',u.kind==='pistol');if(new RegExp(`^${u.type.length} ${u.type} $`,'m').test(model))model=model.replace(entry(model,u.type),fresh);else{model=model.trimEnd()+'\n'+fresh+'\n';added++;}}function setCavalryVisual(name,to){const old=entry(model,name);let fresh=old.replaceAll(/koi_(?:crb|pis)_1g_lod0\.mesh/g,`koi_${to}_1g_lod0.mesh`).replaceAll(/koi_(?:crb|pis)_1g\.texture/g,`koi_${to}_1g.texture`).replace(/^\d+ unit_sprites\/(?:milan_Dummy_EN_Spearmen_ug1|england_Feudal_Knights|tmp_cavalry)_sprite\.spr\s*$/gm,'35 unit_sprites/tmp_cavalry_sprite.spr ');model=model.replace(old,fresh);}setCavalryVisual('ita_cavalleggeri','pis');for(const name of ['ita_carabinieri_early','ita_carabinieri_mid','ita_carabinieri_high'])setCavalryVisual(name,'crb');if(added){const h=model.match(/^(22 serialization::archive 3 0 0 0 0 )(\d+)( 0 0 )/);if(!h)throw Error('Bad modeldb header');model=model.replace(h[0],`${h[1]}${+h[2]+added}${h[3]}`);}fs.writeFileSync(modelP,model.replace(/\n/g,'\r\n'));
let buf=fs.readFileSync(locP),loc=buf.slice(buf[0]===255&&buf[1]===254?2:0).toString('utf16le').replace(/\r\n/g,'\n');for(const u of all)loc=loc.replace(new RegExp(`^\\{${u.type}(?:_descr|_descr_short)?\\}.*(?:\\n|$)`,'gm'),'');loc=loc.trimEnd()+'\n\n'+all.map(u=>{const equip=u.weapon?u.weapon.weapon:u.kind==='lance'?'lancia e sciabola':'Revolver Mod. 1889 Bodeo e sciabola';return `{${u.type}}${u.label}${u.period?` (${E[u.period].name})`:''}\n{${u.type}_descr}${u.label} serve in the Italian forces with the equipment and battlefield role appropriate to this period.\n{${u.type}_descr_short}${u.label} (${equip})`;}).join('\n\n')+'\n';fs.writeFileSync(locP,Buffer.concat([Buffer.from([255,254]),Buffer.from(loc.replace(/\n/g,'\r\n'),'utf16le')]));
const generatedCards=new Set(['ita_milizia_early','ita_milizia_mid','ita_milizia_high','ita_cavalleggeri','ita_lancieri','ita_carabinieri_early','ita_carabinieri_mid','ita_carabinieri_high']);const unitDir=path.join(root,'data/ui/units/venice'),infoDir=path.join(root,'data/ui/unit_info/venice');for(const u of all){const dirs=u.cardSource?[u.cardSource,'venice','slave','mercs','hungary']:['venice','slave','mercs','hungary'],a=dirs.map(d=>path.join(root,'data/ui/units',d,`#${u.card}.tga`)).find(fs.existsSync),b=path.join(unitDir,`#${u.type}.tga`);if(!a)throw Error(`Missing card donor ${u.card}`);if(!generatedCards.has(u.type)||!fs.existsSync(b))fs.copyFileSync(a,b);const ai=[path.join(infoDir,`${u.card}_info.tga`),path.join(root,'data/ui/unit_info/hungary',`${u.card}_info.tga`),path.join(infoDir,'it_arditi_info.tga'),path.join(infoDir,'fra_sailors_venice_info.tga')].find(fs.existsSync);if(ai)fs.copyFileSync(ai,path.join(infoDir,`${u.type}_info.tga`));}
let sounds=fs.readFileSync(soundP,'utf8').replace(/\r\n/g,'\n');const tmpl=sounds.match(/(^\s*unit rus_cos_guard_ve\n\s*event\n\s*folder[^\n]+\n(?:\s+[^\n]+\.wav\n)+\s*end)/m);if(tmpl){const indent=tmpl[1].match(/^(\s*)unit/m)[1],adds=all.filter(u=>!new RegExp(`^\\s*unit ${u.type}$`,'m').test(sounds)).map(u=>tmpl[1].replace(`${indent}unit rus_cos_guard_ve`,`${indent}unit ${u.type}`));if(adds.length)sounds=sounds.replace(tmpl[1],tmpl[1]+'\n'+adds.join('\n'));fs.writeFileSync(soundP,sounds.replace(/\n/g,'\r\n'));}
const types=[...out.matchAll(/^type\s+(.+)$/gm)].map(m=>m[1].trim());if(new Set(types).size!==types.length)throw Error('Duplicate EDU types');if(!fs.readFileSync(eduC).equals(fs.readFileSync(eduR)))throw Error('EDU mirrors differ');console.log(`Standardized ${all.length} Italian records; added ${added} model entries.`);
