const fs=require('fs'),path=require('path'),R=path.resolve(__dirname,'..');
const files=['data/tow_steamsteel/export_descr_unit.txt','data/export_descr_unit.txt'];
const militia=/Heimin|Ainu|Byakkotai|Korean|Teppotai Merc/;
const elite=/Yumitai|Seishi|Satsuma|Yamagunitai|Shinsengumi|Kaiso|Denshutai|Goshimpei|Kijutai|Battotai|Kenyotai|Shogitai|Bodyguard|Enomoto|Hijikata|Itagaki|Jules Brunet|Kondo Isami|Matsudaira|Saigo Takamori|Sakamoto Ryoma|Takeda Ayasaburo|Tokugawa Yoshinobu|sho_mod_cav/;
const skirm=/Kiheitai|Saga Hoheitai|Jinshotai|Karasugumi|Raijintai|Kijutai|Hokuchin Butai|Hoppo Keibitai|Tondenhei/;
const sharp=/Kijutai/;
const lateB=/(?:1880|1890|1900|1905)|Bodyguard IJA/;
const artillery=/^(?:jap_|sho_|Japan Armstrong)/;
const qbase={militia:{atk:3,ch:2,def:2,mor:3,disc:'low',train:'trained',acc:0,cost:-200},regular:{atk:5,ch:3,def:3,mor:4,disc:'normal',train:'trained',acc:1,cost:0},elite:{atk:7,ch:4,def:4,mor:6,disc:'disciplined',train:'highly_trained',acc:2,cost:200}};
const fam={arquebus_bullet:[900,160],musket_bullet:[1000,200],rifled_musket_bullet:[1200,220],rifle_bullet:[1500,240],magazine_rifle_bullet:[1800,260],musket_carbine_bullet:[1200,220],rifled_musket_carbine_bullet:[1200,220],rifle_carbine_bullet:[1500,240],magazine_rifle_carbine_bullet:[1800,260]};
const tiers=['c','b','a','s'],disc=['low','normal','disciplined'];
for(const rel of files){const p=path.join(R,rel);let s=fs.readFileSync(p,'utf8').replace(/\r/g,'');s=s.split(/(?=^type\s+)/m).map(b=>{const tm=b.match(/^type\s+(.+)$/m);if(!tm||!/(?:^ownership|^era [012]).*\bsaxons\b/m.test(b))return b;const t=tm[1].trim();if(artillery.test(t))return b;const q=militia.test(t)?'militia':elite.test(t)?'elite':'regular',Q=qbase[q],tier=lateB.test(t)?'B':'C',pen=tier==='C'?-1:0,isCav=/^category\s+cavalry/m.test(b),isSk=skirm.test(t),isSharp=sharp.test(t);let atk=Q.atk+pen,ch=Q.ch,def=Q.def+pen,mor=Q.mor,di=Q.disc;if(tier==='C')di=disc[Math.max(0,disc.indexOf(di)-1)];const pri=b.match(/^stat_pri\s+(.+)$/m),sec=b.match(/^stat_sec\s+(.+)$/m);const ranged=pri&&/missile|thrown/.test(pri[1]);const meleeKey=ranged?'stat_sec':'stat_pri';const sword=new RegExp(`^${meleeKey}\\s+.*\\bsword\\b`,'m').test(b);if(ranged&&sword&&!isCav)atk++;b=b.replace(new RegExp(`^${meleeKey}\\s+(-?\\d+),\\s*(-?\\d+),`,'m'),`${meleeKey.padEnd(17)}${atk}, ${ch},`);b=b.replace(/^stat_pri_armour\s+(\d+),\s*\d+,\s*(\d+),\s*(\w+)/m,`stat_pri_armour  $1, ${Math.max(0,def)}, $2, $3`);b=b.replace(/^stat_mental\s+.*$/m,`stat_mental      ${mor}, ${di}, ${Q.train}`);b=b.replace(/^stat_ground\s+.*$/m,'stat_ground      0, 0, 0, 0');if(ranged&&!/javelin|arrow|grenade/.test(pri[1])){for(const [f,[base,range]] of Object.entries(fam)){const re=new RegExp(`${f}_(?:c|b|a|s)`);if(re.test(b)){let ai=Q.acc+pen+(isSharp?2:isSk?1:0)-(isCav?1:0);ai=Math.max(0,Math.min(3,ai));b=b.replace(re,`${f}_${tiers[ai]}`);b=b.replace(/^stat_pri\s+([^,]+,\s*[^,]+,\s*[^,]+),\s*\d+/m,`stat_pri         $1, ${range+(isSharp||isSk?40:0)-(isCav?20:0)}`);let total=base+Q.cost+(isSharp?200:0)+(isCav?200:0);b=b.replace(/^stat_cost\s+(.+)$/m,(z,row)=>{const a=row.split(',').map(x=>x.trim());a[1]=a[5]=String(total);a[2]=a[7]=String(Math.round(total/3));return 'stat_cost        '+a.join(', ')});break}}}return b}).join('');fs.writeFileSync(p,s.replace(/\n/g,'\r\n'))}
console.log('Applied Japanese C-tier early/mid and B-tier late performance baselines.');
