const fs=require('fs'),path=require('path'),R=path.resolve(__dirname,'..');
const EDU=path.join(R,'data/tow_steamsteel/export_descr_unit.txt'),MIR=path.join(R,'data/export_descr_unit.txt'),LOC=path.join(R,'data/text/export_units.txt');
const BACK=path.join(R,'tools/backup_before_siam_20260917');fs.mkdirSync(BACK,{recursive:true});for(const p of [EDU,MIR,LOC]){const d=path.join(BACK,path.basename(p));if(!fs.existsSync(d))fs.copyFileSync(p,d)}
let e=fs.readFileSync(EDU,'utf8').replace(/\r/g,'');
function block(t){const m=e.match(new RegExp(`^type\\s+${t}\\n[\\s\\S]*?(?=^type\\s+|(?![\\s\\S]))`,'m'));if(!m)throw Error('missing '+t);return m[0].trimEnd()}
function rep(t,b){e=e.replace(block(t),b.trimEnd())}function unit(t,x){rep(t,`type             ${t}\n${x.join('\n')}`)}const keep=n=>Math.round(n/3),cost=(n,l=1,time=2)=>`${time}, ${n}, ${keep(n)}, 100, 100, ${n}, ${l}, ${keep(n)}`;
const common=(t,n,soldier,q,weapon,eras,limit=1,secondary='spear',sword=false)=>{const Q={militia:[2,2,1,2,'low','trained',-200],regular:[4,3,2,3,'low','trained',0],elite:[6,4,3,5,'normal','highly_trained',200]}[q],W={arquebus:['arquebus_bullet_c',160,900,true],musket:['musket_bullet_c',200,1000,true],rifled:['rifled_musket_bullet_c',220,1200,true],rifle:['rifle_bullet_c',240,1500,false]}[weapon],attrs=['free_upkeep_unit','sea_faring','hide_forest'];if(W[3])attrs.push('gunpowder_unit');attrs.push('gunmen','start_not_skirmishing','cannot_skirmish');return [`dictionary       ${t} ; ${n}`,'category         infantry','class            missile','voice_type       Light','accent           middle_east','banner faction   main_infantry','banner holy      crusade',`soldier          ${soldier}, 40, 0, 1.2`,`attributes       ${attrs.join(', ')}`,`formation        ${weapon==='rifle'?'1.2, 1.2, 2.0, 2.4, 3, square':'1.2, 1.2, 1.2, 1.2, 3, square'}`,'stat_health      1, 0',`stat_pri         37, 0, ${W[0]}, ${W[1]}, 35, missile, missile_gunpowder, piercing, none, musket_shot_set, 0, -999`,'stat_pri_attr    ap',`stat_sec         ${Q[0]+(sword?1:0)}, ${Q[1]}, no, 0, 0, melee, melee_blade, ${sword?'slashing':'piercing'}, ${secondary}, 25, 1`,`stat_sec_attr    ${sword?'no':'ap, short_pike'}`,`stat_pri_armour  3, ${Q[2]}, 0, leather`,'stat_sec_armour  0, 0, flesh','stat_heat        2','stat_ground      0, 0, 0, 0',`stat_mental      ${Q[3]}, ${Q[4]}, ${Q[5]}`,'stat_charge_dist 40','stat_fire_delay  0','stat_food        60, 300',`stat_cost        ${cost(W[2]+Q[6],limit)}`,'ownership        cru, slave',...eras.map(x=>`era ${x}            cru, slave`)];};
unit('siam_agent',common('siam_agent','Kong Asa (Matchlock Arquebus)','siam_agent','militia','arquebus',[0],2));
unit('Siam_Archers',common('Siam_Archers','Thahan Ban (Brown Bess Musket)','Siam_Archers','militia','musket',[0,1],2));
unit('siam_inf',common('siam_inf','Thahan Bok (Pattern 1853 Enfield Rifle-Musket)','siam_inf','regular','rifled',[0,1],2));
unit('siam_late_inf',common('siam_late_inf','Thahan Bok Samai Mai (Martini-Henry Mk I Rifle)','siam_late_inf','regular','rifle',[2],2));
unit('siam_sea',common('siam_sea','Thahan Ruea (Remington Rolling Block M1867 Rifle)','siam_sea','regular','rifle',[1,2],1));
unit('fra_vietna',common('fra_vietna','Quan Viet Phu Tro (Chassepot Mle 1866 Rifle)','fra_vietna','regular','rifle',[2],1,'axe',true));
unit('burmese_inf',common('burmese_inf','Tattha Myanma (Pattern 1853 Enfield Rifle-Musket)','burmese_inf','regular','rifled',[0,1],1));
unit('siam_late_cav',[`dictionary       siam_late_cav ; Thahan Ma (Snider-Enfield Carbine)`,`category         cavalry`,`class            missile`,`voice_type       Heavy`,`accent           middle_east`,`banner faction   main_cavalry`,`banner holy      crusade_cavalry`,`soldier          siam_late_cav, 24, 0, 1`,`mount            dragoon`,`mount_effect     elephant -4, camel -4`,`attributes       free_upkeep_unit, sea_faring, hide_forest, can_withdraw, gunmen, guncavalry, start_not_skirmishing, stakes`,`formation        2, 2, 4, 4, 3, square`,`stat_health      1, 0`,`stat_pri         29, 0, rifled_musket_carbine_bullet_c, 200, 35, missile, missile_gunpowder, piercing, none, musket_shot_set, 25, 1`,`stat_pri_attr    ap`,`stat_sec         4, 3, no, 0, 0, melee, melee_blade, slashing, sword, 25, 1`,`stat_sec_attr    no`,`stat_pri_armour  4, 2, 0, leather`,`stat_sec_armour  0, 0, flesh`,`stat_heat        2`,`stat_ground      0, 0, 0, 0`,`stat_mental      3, low, trained`,`stat_charge_dist 50`,`stat_fire_delay  0`,`stat_food        60, 300`,`stat_cost        ${cost(1400,1,3)}`,`ownership        cru, slave`,`era 2            cru, slave`]);
unit('Siam_bodyguard',[`dictionary       Siam_bodyguard ; Mae Thap lae Khana (Webley No. 1 Revolver)`,`category         cavalry`,`class            light`,`voice_type       Heavy`,`accent           middle_east`,`banner faction   main_cavalry`,`banner holy      crusade_cavalry`,`soldier          Siam_bodyguard, 4, 0, 1`,`mount            hussar`,`mount_effect     elephant -4, camel -4`,`attributes       free_upkeep_unit, sea_faring, general_unit, command`,`formation        2, 2, 4, 4, 2, square`,`stat_health      1, 0`,`stat_pri         20, 0, magazine_rifle_bullet_c, 60, 15, missile, missile_gunpowder, piercing, none, musket_shot_set, 25, 1`,`stat_pri_attr    ap`,`stat_sec         6, 4, no, 0, 0, melee, melee_blade, slashing, sword, 25, 1`,`stat_sec_attr    no`,`stat_pri_armour  4, 3, 0, leather`,`stat_sec_armour  0, 0, flesh`,`stat_heat        2`,`stat_ground      0, 0, 0, 0`,`stat_mental      5, normal, highly_trained`,`stat_charge_dist 50`,`stat_fire_delay  0`,`stat_food        60, 300`,`stat_cost        ${cost(200,1,1)}`,`ownership        cru, slave`,`era 0            cru, slave`,`era 1            cru, slave`,`era 2            cru, slave`]);
let el=block('siam_ele_gunner').replace(/^dictionary.*$/m,'dictionary       siam_ele_gunner ; Chang Suek Phon Puen (Brown Bess Musket)').replace(/^stat_pri\s+.*$/m,'stat_pri         37, 1, musket_bullet_c, 200, 35, missile, missile_gunpowder, piercing, none, musket_shot_set, 25, 1').replace(/^stat_pri_armour.*$/m,'stat_pri_armour  3, 2, 0, flesh').replace(/^stat_mental.*$/m,'stat_mental      3, low, trained').replace(/^stat_ground.*$/m,'stat_ground      0, 0, 0, 0').replace(/^stat_fire_delay.*$/m,'stat_fire_delay  0').replace(/^stat_cost.*$/m,'stat_cost        4, 2600, 867, 100, 100, 2600, 1, 867').replace(/^era\s+[012].*$/gm,'').trimEnd()+`\nera 0            cru, slave\nera 1            cru, slave\nera 2            cru, slave`;rep('siam_ele_gunner',el);
for(const t of ['viet_inf','merc_aceh_marines','merc_aceh_noble','merc_aceh_reg','merc_aceh_gold','merc_aceh_warband','merc_aceh_inf']){let x=block(t).replace(/,?\s*cru,?/g,',').replace(/,\s*,/g,',').replace(/\s+,/g,',').replace(/,\s*$/gm,'');rep(t,x)}
function cloneArt(src,dst,label,eras){let x=block(src).replace(new RegExp(`^type\\s+${src}$`,'m'),`type             ${dst}`).replace(/^dictionary.*$/m,`dictionary       ${dst} ; ${label}`).replace(/^ownership.*$/m,'ownership        cru, slave').replace(/^era\s+[012].*$/gm,'').replace(/^stat_mental.*$/m,'stat_mental      3, low, trained').replace(/^stat_ground.*$/m,'stat_ground      0, 0, 0, 0').replace(/^stat_fire_delay.*$/m,'stat_fire_delay  0').replace(/^stat_cost\s+(.+)$/m,(z,row)=>{let a=row.split(',').map(v=>+v.trim());let k=keep(a[1]);return `stat_cost        ${a[0]}, ${a[1]}, ${k}, 100, 100, ${a[5]}, 1, ${k}`}).trimEnd()+eras.map(n=>`\nera ${n}            cru, slave`).join('');if(new RegExp(`^type\\s+${dst}$`,'m').test(e))rep(dst,x);else e=e.replace(block(src),block(src)+'\n\n'+x)}
cloneArt('byz_armstrong','siam_armstrong','Bronze Field Cannon',[0,1]);cloneArt('byz_12lb','siam_12lb','Muzzle-Loading Smoothbore Cannon',[1,2]);cloneArt('byz_5lb','siam_5lb','Mortar',[2]);cloneArt('byz_maxim','siam_maxim','Maxim Gun',[2]);
for(const t of ['byz_armstrong','byz_12lb','byz_5lb','byz_maxim','byz_gatling','byz_150mm']){let x=block(t).replace(/,?\s*cru,?/g,',').replace(/,\s*,/g,',').replace(/\s+,/g,',').replace(/,\s*$/gm,'');rep(t,x)}
e=e.replace(/^ownership,\\s*/gm,'ownership        ').replace(/^era ([012]),\\s*/gm,'era $1            ').replace(/^era [012]\\s*$/gm,'');e=e.replace(/\n/g,'\r\n');fs.writeFileSync(EDU,e);fs.writeFileSync(MIR,e);
let mp=path.join(R,'data/unit_models/battle_models.modeldb'),m=fs.readFileSync(mp,'utf8');function mb(n){const x=m.match(new RegExp(`^${n.length} ${n}\\s*$[\\s\\S]*?(?=^\\d+ [^\\s;]+\\s*$\\r?\\n\\d+ \\d+\\s*$|(?![\\s\\S]))`,'m'));if(!x)throw Error('model '+n);return x[0]}function mr(n,f){m=m.replace(mb(n),f(mb(n)))}for(const n of ['siam_late_inf','siam_sea'])mr(n,x=>x.replace('20 MTW2_Fast_Arquebus_3','14 MTW2_Musket_SS'));mr('fra_vietna',x=>x.replace(/\d+ MTW2_[^\s]+(?=\s+\d+ MTW2_2H_Axe)/,'14 MTW2_Musket_SS'));fs.writeFileSync(mp,m);
let buf=fs.readFileSync(LOC),bom=buf[0]===255&&buf[1]===254,s=buf.subarray(bom?2:0).toString('utf16le');const names={siam_agent:'Kong Asa',Siam_Archers:'Thahan Ban',siam_inf:'Thahan Bok',siam_late_inf:'Thahan Bok Samai Mai',siam_sea:'Thahan Ruea',fra_vietna:'Quan Viet Phu Tro',burmese_inf:'Tattha Myanma',siam_late_cav:'Thahan Ma',Siam_bodyguard:'Mae Thap lae Khana',siam_ele_gunner:'Chang Suek Phon Puen',siam_armstrong:'Bronze Field Cannon',siam_12lb:'Muzzle-Loading Smoothbore Cannon',siam_5lb:'Mortar',siam_maxim:'Maxim Gun'};for(const[k,v]of Object.entries(names)){const line=`{${k}}${v}`;if(new RegExp(`\\{${k}\\}`).test(s))s=s.replace(new RegExp(`\\{${k}\\}[^\\r\\n]*`),line);else s+=`\r\n${line}\r\n{${k}_descr}${v} in Royal Siamese service.\r\n{${k}_descr_short}${v}.\r\n`}fs.writeFileSync(LOC,Buffer.concat([Buffer.from([255,254]),Buffer.from(s,'utf16le')]));
console.log('Standardized Siam as D tier and separated shared auxiliary/artillery records.');
