const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),eduC=path.join(root,'data/tow_steamsteel/export_descr_unit.txt'),eduR=path.join(root,'data/export_descr_unit.txt'),modelP=path.join(root,'data/unit_models/battle_models.modeldb'),locP=path.join(root,'data/text/export_units.txt'),soundP=path.join(root,'data/export_descr_sounds_units_voice.txt');
const era={early:{n:0,name:'Early',form:'1.2, 1.2, 1.2, 1.2, 3, square'},mid:{n:1,name:'Mid',form:'1.2, 1.2, 2.0, 2.4, 3, square'},high:{n:2,name:'Late',form:'1.2, 1.4, 2.4, 2.8, 3, square'}};
const cost=(n,limit=1)=>`3, ${n}, ${Math.round(n/3)}, 100, 100, ${n}, ${limit}, ${Math.round(n/3)}`;
const W={
 early:{weapon:'Getrokken Geweer No. 1',damage:31,projectile:'rifled_musket_bullet_b',range:220,ammo:35,smoke:'musket_shot_set',muzzle:true,mode:'fast'},
 mid:{weapon:'Beaumontgeweer M1871',damage:20,projectile:'rifle_bullet_b',range:240,ammo:35,smoke:'musket_shot_set',mode:'musket'},
 high:{weapon:'Beaumont-Vitaligeweer M1871/88',damage:13,projectile:'magazine_rifle_bullet_b',range:260,ammo:40,smoke:'smokeless_shot_set',mode:'fast'}
};
const base=(type,label,period,quality='regular',role='line',weapon=W[period],opts={})=>{
 const q=quality==='elite'?{melee:8,charge:4,defence:5,morale:6,discipline:'disciplined',training:'highly_trained',cost:200}:quality==='militia'?{melee:3,charge:2,defence:2,morale:3,discipline:'low',training:'trained',cost:-200}:{melee:opts.bonus===false?5:6,charge:3,defence:opts.bonus===false?3:4,morale:4,discipline:opts.bonus===false?'normal':'disciplined',training:'trained',cost:0};
 const roleShift=role==='skirmisher'?1:0, qualityTier=quality==='elite'?2:quality==='militia'?0:1, p=weapon.projectile.replace(/_bullet_[cbas]$/,m=>`_bullet_${'cbas'[Math.min(3,qualityTier+roleShift)]}`);
 const premium=opts.bonus===false?0:200;
 return {type,label,period,quality,role,...weapon,projectile:p,...q,cost:weapon.cost+q.cost+premium,limit:opts.limit||1,form:opts.form||era[period].form,strength:opts.strength||40,colonial:opts.colonial};
};
W.early.cost=1200;W.mid.cost=1500;W.high.cost=1800;
const inf=[];
for(const p of ['early','mid','high'])inf.push(base(`net_line_${p}`,'Infanterie van Linie',p,'regular','line',W[p],{limit:3}));
for(const p of ['early','mid','high'])inf.push(base(`net_grenadiers_${p}`,'Grenadiers',p,'elite','line',p==='high'?{...W.high,weapon:'Geweer M.95 (Mannlicher)'}:W[p]));
for(const p of ['early','mid','high'])inf.push(base(`net_jagers_${p}`,'Jagers',p,'regular','skirmisher',p==='high'?{...W.high,weapon:'Geweer M.95 (Mannlicher)'}:W[p],{strength:30}));
const marineWeapons={early:{...W.early,weapon:'Getrokken Marinegeweer No. 1'},mid:{...W.mid,weapon:'Snider Marinegeweer M1867',damage:29},high:{...W.mid,weapon:'Beaumont Marinegeweer M1873',damage:21}};
for(const p of ['early','mid','high'])inf.push(base(`net_mariniers_${p}`,'Korps Mariniers',p,'regular','line',marineWeapons[p],{form:p==='high'?era.mid.form:undefined}));
const militiaWeapons={early:W.early,mid:{...W.mid,weapon:'Snidergeweer M1867',damage:29},high:{...W.mid,weapon:'Beaumontgeweer M1871'}};
for(const p of ['early','mid','high'])inf.push(base(`net_schutterij_${p}`,'Schutterij',p,'militia','line',militiaWeapons[p],{bonus:false,limit:2,form:p==='high'?era.mid.form:undefined}));
const knilWeapons={early:{...W.early,weapon:'Pattern 1853 Enfield'},mid:{...W.mid,weapon:'Beaumontgeweer M1873 Koloniaal'},high:{...W.high,weapon:'Geweer M.95 KNIL'}};
for(const p of ['early','mid','high'])inf.push(base(`net_knil_${p}`,'Koninklijk Nederlands-Indisch Leger',p,'regular','line',knilWeapons[p],{bonus:false,colonial:true}));

function infantry(u){const attrs=['free_upkeep_unit','sea_faring','hide_forest'];if(u.muzzle)attrs.push('gunpowder_unit');attrs.push('gunmen','start_not_skirmishing','cannot_skirmish');if(u.period==='high')attrs.push('stakes');return [`type             ${u.type}`,`dictionary       ${u.type} ; ${u.label} (${era[u.period].name}; ${u.weapon})`,'category         infantry','class            missile','voice_type       Light','accent           dutch','banner faction   main_infantry','banner holy      crusade',`soldier          ${u.type}, ${u.strength}, 0, 1.2`,'officer          shk_off_1g',`attributes       ${attrs.join(', ')}`,`formation        ${u.role==='skirmisher'?'1.4, 1.8, 2.8, 3.6, 3, square':u.form}`,'stat_health      1, 0',`stat_pri         ${u.damage}, 0, ${u.projectile}, ${u.role==='skirmisher'?u.range+40:u.range}, ${u.ammo}, missile, missile_gunpowder, piercing, none, ${u.smoke}, 0, -999`,'stat_pri_attr    ap',`stat_sec         ${u.melee}, ${u.charge}, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1.2`,'stat_sec_attr    short_pike, ap',`stat_pri_armour  3, ${u.defence}, 0, leather`,'stat_sec_armour  0, 0, flesh','stat_heat        0','stat_ground      0, 0, 0, 0',`stat_mental      ${u.morale}, ${u.discipline}, ${u.training}`,'stat_charge_dist 40','stat_fire_delay  0','stat_food        60, 300',`stat_cost        ${cost(u.cost,u.limit)}`,'ownership        portugal, slave',`era ${era[u.period].n}            portugal`].join('\n');}
const cav=[
 {type:'net_dragonders',label:'Dragonders',weapon:'Revolver M1873 en sabel',arm:'pistol',className:'heavy',melee:6,charge:3,defence:5,cost:1400},
 {type:'net_huzaren',label:'Huzaren',weapon:'Revolver M1873 en sabel',arm:'pistol',className:'light',melee:6,charge:3,defence:5,cost:1400},
 {type:'net_karabiniers_early',label:'Karabiniers',period:'early',weapon:'Getrokken Karabijn No. 1 en sabel',arm:'carbine',className:'missile',damage:31,projectile:'rifled_musket_carbine_bullet_c',range:200,ammo:35,smoke:'musket_shot_set',melee:6,charge:3,defence:5,cost:1600,muzzle:true},
 {type:'net_karabiniers_mid',label:'Karabiniers',period:'mid',weapon:'Beaumontkarabijn M1871 en sabel',arm:'carbine',className:'missile',damage:20,projectile:'rifle_carbine_bullet_c',range:220,ammo:35,smoke:'musket_shot_set',melee:6,charge:3,defence:5,cost:1900},
 {type:'net_karabiniers_high',label:'Karabiniers',period:'high',weapon:'Karabijn M.95 en sabel',arm:'carbine',className:'missile',damage:13,projectile:'magazine_rifle_carbine_bullet_c',range:240,ammo:40,smoke:'smokeless_shot_set',melee:6,charge:3,defence:5,cost:2200},
 {type:'net_general_staff',label:'Generaal en Staf',weapon:'Revolver M1873 en sabel',arm:'pistol',className:'heavy',melee:8,charge:4,defence:5,cost:200,general:true}
];
function cavalry(u){const pistol=u.arm==='pistol',attrs=['free_upkeep_unit','sea_faring','hide_forest','can_withdraw','guncavalry','gunmen','start_not_skirmishing','cannot_skirmish'];if(u.muzzle)attrs.push('gunpowder_unit');if(u.arm==='carbine')attrs.push('stakes');if(u.general)attrs.push('general_unit','command');const pri=pistol?`20, 4, magazine_rifle_bullet_c, 60, 15, missile, missile_gunpowder, piercing, none, musket_shot_set, 25, 1`:`${u.damage}, 2, ${u.projectile}, ${u.range}, ${u.ammo}, missile, missile_gunpowder, piercing, none, ${u.smoke}, 25, 1`;return [`type             ${u.type}`,`dictionary       ${u.type} ; ${u.label}${u.period?` (${era[u.period].name}; ${u.weapon})`:` (${u.weapon})`}`,'category         cavalry',`class            ${u.className}`,'voice_type       Heavy','accent           dutch','banner faction   main_cavalry','banner holy      crusade_cavalry',`soldier          ${u.type}, ${u.general?4:24}, 0, 1`,'officer          shk_off_1g','mount            dragoon','mount_effect     elephant -4, camel -4',`attributes       ${attrs.join(', ')}`,`formation        2, 2, 4, 4, ${u.general?2:3}, square`,'stat_health      1, 0',`stat_pri         ${pri}`,'stat_pri_attr    ap',`stat_sec         ${u.melee}, ${u.charge}, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1`,'stat_sec_attr    ap',`stat_pri_armour  4, ${u.defence}, 0, leather`,'stat_sec_armour  0, 0, flesh','stat_heat        0','stat_ground      0, 0, 0, 0',`stat_mental      ${u.general?6:4}, disciplined, ${u.general?'highly_trained':'trained'}`,'stat_charge_dist 45','stat_fire_delay  -20000','stat_food        60, 300',`stat_cost        ${cost(u.cost)}`,'ownership        portugal, slave',...(u.period?[`era ${era[u.period].n}            portugal`]:['era 0            portugal','era 1            portugal','era 2            portugal'])].join('\n');}
const byType=Object.fromEntries([...inf.map(u=>[u.type,infantry(u)]),...cav.map(u=>[u.type,cavalry(u)])]);
const legacy={l_pith_cav_portugal:['net_dragonders','l_pith_cav'],dutch_pith:['net_line_high','dutch_pith'],nl_roy:['net_grenadiers_early','fra_ww1_inf'],dutch_ww1:['net_line_high','unused_023'],dutch_askari:['net_knil_high','mex_natl_guard1'],dutch_askari2:['net_knil_early','aceh_noble'],dutch_inf:['net_line_early','fra_inf_sc1'],nl_colonial:['net_mariniers_mid','nl_colonial'],nl_carbs:['net_huzaren','fra_carbs'],balk_cav_nl:['net_general_staff','it_pistoleer']};
function alias(old,modern,soldier){return byType[modern].replace(/^type\s+.*$/m,`type             ${old}`).replace(/^dictionary\s+\S+/m,`dictionary       ${old}`).replace(/^soldier\s+\S+,/m,`soldier          ${soldier},`).replace(/^ownership\s+.*$/m,'ownership        slave').replace(/^era [012]\s+portugal\n?/gm,'').trimEnd();}
const block=['; ============================================================================','; Netherlands (portugal) — standardized infantry and cavalry','; ============================================================================',...inf.map(infantry),...cav.map(cavalry),'; Legacy internal-name compatibility (not assigned to custom-battle eras)',...Object.entries(legacy).map(([o,[m,s]])=>alias(o,m,s))].join('\n\n')+'\n\n';
let edu=fs.readFileSync(eduC,'utf8').replace(/\r\n/g,'\n');const titleAt=Math.max(edu.indexOf('; Netherlands (portugal) — standardized infantry and cavalry'),edu.indexOf('; Netherlands (portugal) — infantry and cavalry'));const start=edu.lastIndexOf('; ============================================================================',titleAt),denAt=edu.indexOf(';################ Kingdom of Denmark',titleAt),end=edu.lastIndexOf('\n;;;;;;;;;;;;;;;;',denAt)+1;if(start<0||end<1)throw Error('Dutch block not found');edu=edu.slice(0,start)+block+edu.slice(end);edu=edu.replace(/(^type\s+rus_sailors_portugal\s*$[\s\S]*?^ownership\s+).+?(?=\r?$)/m,'$1slave').replace(/(^type\s+rus_sailors_portugal\s*$[\s\S]*?)(^era [012]\s+portugal\s*$\r?\n?)/gm,'$1');const out=edu.replace(/\n/g,'\r\n');fs.writeFileSync(eduC,out);fs.writeFileSync(eduR,out);
function entry(text,name){const a=text.replace(/\r\n/g,'\n').split('\n'),i=a.findIndex(x=>new RegExp(`^${name.length} ${name}\\s*$`).test(x));if(i<0)throw Error(`Missing donor ${name}`);let j=i;while(j<a.length&&!/^16 -0\.090000004 /.test(a[j]))j++;return a.slice(i,j+1).join('\n');}
function clone(text,donor,name,mode){let e=entry(text,donor).replace(new RegExp(`^${donor.length} ${donor}\\s*$`,'m'),`${name.length} ${name} `);if(mode==='musket')e=e.replace(/20 MTW2_Fast_Arquebus_3 9 MTW2_Pike /,'14 MTW2_Musket_SS 9 MTW2_Pike ');if(mode==='skirmisherMusket')e=e.replace(/(?:20 MTW2_Fast_Arquebus_3|14 MTW2_Musket_SS) 9 MTW2_Pike /,'15 MTW2_Musket_SSK 9 MTW2_Pike ');if(mode==='fast')e=e.replace(/(?:14 MTW2_Musket_SS|15 MTW2_Musket_SSK) 9 MTW2_Pike /,'20 MTW2_Fast_Arquebus_3 9 MTW2_Pike ');if(mode==='portugalCarbine')e=e.replace(/^3 hre\s*$/gm,'8 portugal ');return e;}
const donors=[];for(const u of inf){let d;if(u.type.startsWith('net_line_'))d=u.period==='early'?'fra_inf_sc1':u.period==='mid'?'net_line_early':'dutch_pith';else if(u.type.startsWith('net_grenadiers_'))d=u.period==='early'?'dan_inf':u.period==='mid'?'net_grenadiers_early':'net_grenadiers_mid';else if(u.type.startsWith('net_jagers_'))d=u.period==='early'?'fra_inf_sc1':u.period==='mid'?'net_jagers_early':'net_jagers_mid';else if(u.type.startsWith('net_mariniers_'))d=u.period==='early'?'nl_colonial':u.period==='mid'?'net_mariniers_early':'net_mariniers_mid';else if(u.type.startsWith('net_schutterij_'))d=u.period==='early'?'fra_inf_sc1':u.period==='mid'?'net_schutterij_early':'net_schutterij_mid';else d=u.period==='early'?'aceh_noble':u.period==='mid'?'net_knil_early':'net_knil_mid';const mode=u.role==='skirmisher'&&!u.muzzle?'skirmisherMusket':u.mode;donors.push([d,u.type,mode]);}
donors.push(['l_pith_cav','net_dragonders',null],['fra_hussards','net_huzaren',null],['pru_dragoner_early','net_karabiniers_early','portugalCarbine'],['net_karabiniers_early','net_karabiniers_mid',null],['net_karabiniers_mid','net_karabiniers_high',null],['it_pistoleer','net_general_staff',null]);
let model=fs.readFileSync(modelP,'utf8').replace(/\r\n/g,'\n'),added=0;for(const [d,n,m] of donors){const fresh=clone(model,d,n,m);if(new RegExp(`^${n.length} ${n} $`,'m').test(model))model=model.replace(entry(model,n),fresh);else{model=model.trimEnd()+'\n'+fresh+'\n';added++;}}if(added){const h=model.match(/^(22 serialization::archive 3 0 0 0 0 )(\d+)( 0 0 )/);if(!h)throw Error('Bad modeldb header');model=model.replace(h[0],`${h[1]}${+h[2]+added}${h[3]}`);}fs.writeFileSync(modelP,model.replace(/\n/g,'\r\n'));
const all=[...inf,...cav],oldLoc=Object.entries(legacy).map(([type,[m]])=>({...all.find(x=>x.type===m),type}));let buf=fs.readFileSync(locP),loc=buf.slice(buf[0]===255&&buf[1]===254?2:0).toString('utf16le').replace(/\r\n/g,'\n');for(const u of [...all,...oldLoc])loc=loc.replace(new RegExp(`^\\{${u.type}(?:_descr|_descr_short)?\\}.*(?:\\n|$)`,'gm'),'');loc=loc.trimEnd()+'\n\n'+[...all,...oldLoc].map(u=>`{${u.type}}${u.label}${u.period?` (${era[u.period].name})`:''}\n{${u.type}_descr}${u.label} serve in the Dutch forces and are equipped and trained for their stated battlefield role.\n{${u.type}_descr_short}${u.label} (${u.weapon})`).join('\n\n')+'\n';fs.writeFileSync(locP,Buffer.concat([Buffer.from([255,254]),Buffer.from(loc.replace(/\n/g,'\r\n'),'utf16le')]));
const cards={};for(const u of all){let s=u.type.startsWith('net_line_')?(u.period==='high'?'dutch_pith':'dutch_inf'):u.type.startsWith('net_grenadiers_')?'nl_roy':u.type.startsWith('net_jagers_')?'dutch_inf':u.type.startsWith('net_mariniers_')?'nl_colonial':u.type.startsWith('net_schutterij_')?'dutch_militia':u.type.startsWith('net_knil_')?(u.period==='early'?'dutch_askari2':'dutch_askari'):u.type==='net_dragonders'?'l_pith_cav_portugal':u.type==='net_huzaren'?'nl_carbs':u.type.startsWith('net_karabiniers_')?'nl_carbs':'balk_cav_nl';const a=path.join(root,'data/ui/units/portugal',`#${s}.tga`),b=path.join(root,'data/ui/units/portugal',`#${u.type}.tga`);if(fs.existsSync(a))fs.copyFileSync(a,b);const ai=path.join(root,'data/ui/unit_info/portugal',`${s}_info.tga`),bi=path.join(root,'data/ui/unit_info/portugal',`${u.type}_info.tga`);if(fs.existsSync(ai))fs.copyFileSync(ai,bi);}
let sounds=fs.readFileSync(soundP,'utf8').replace(/\r\n/g,'\n');const tmpl=sounds.match(/(^\s*unit dutch_inf\n\s*event\n\s*folder[^\n]+\n(?:\s+[^\n]+\.wav\n)+\s*end)/m);if(tmpl){const indent=tmpl[1].match(/^(\s*)unit/m)[1],adds=all.filter(u=>!new RegExp(`^\\s*unit ${u.type}$`,'m').test(sounds)).map(u=>tmpl[1].replace(`${indent}unit dutch_inf`,`${indent}unit ${u.type}`));if(adds.length)sounds=sounds.replace(tmpl[1],tmpl[1]+'\n'+adds.join('\n'));fs.writeFileSync(soundP,sounds.replace(/\n/g,'\r\n'));}
const types=[...out.matchAll(/^type\s+(.+)$/gm)].map(m=>m[1].trim());if(new Set(types).size!==types.length)throw Error('Duplicate EDU types');if(!fs.readFileSync(eduC).equals(fs.readFileSync(eduR)))throw Error('EDU mirrors differ');console.log(`Standardized ${all.length} Dutch records; added ${added} model entries.`);
