const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),eduC=path.join(root,'data/tow_steamsteel/export_descr_unit.txt'),eduR=path.join(root,'data/export_descr_unit.txt'),modelP=path.join(root,'data/unit_models/battle_models.modeldb'),locP=path.join(root,'data/text/export_units.txt');
const periods=['early','mid','high'],lines=['pekhota','opolchenie','leib_guard','grenadery','strelki','marines','sapery','siberian'],expected=[...lines.flatMap(x=>periods.map(p=>`rus_${x}_${p}`)),...['draguny','kazaki'].flatMap(x=>periods.map(p=>`rus_${x}_${p}`)),'rus_gusary','rus_ulany','rus_guard_cuirassiers','rus_general_staff'];
const aliases=['rus_conscript','rus_gen_cav','rus_sailors','rus_imp_cav','rus_conscript_ru','rus_roy_cav_ru','rus_roy_inf_ru','rus_guard','russ_inf','rus_cos_guard_ru','rus_lat_inf_ru'],auxiliaries=['armenian_inf_russia','rus_cos_hussar','rus_georgian_cav'];
const edu=fs.readFileSync(eduC,'utf8').replace(/\r\n/g,'\n'),model=fs.readFileSync(modelP,'utf8').replace(/\r\n/g,'\n'),fail=[],ok=(x,m)=>{if(!x)fail.push(m);};
function block(type){const s=[...edu.matchAll(/^type\s+(\S+)/gm)],i=s.findIndex(x=>x[1]===type);return i<0?'':edu.slice(s[i].index,i+1<s.length?s[i+1].index:edu.length);}
const types=[...edu.matchAll(/^type\s+(.+)$/gm)].map(x=>x[1].trim()),dicts=[...edu.matchAll(/^dictionary\s+(\S+)/gm)].map(x=>x[1]);ok(new Set(types).size===types.length,'duplicate EDU type');ok(new Set(dicts).size===dicts.length,'duplicate EDU dictionary');ok(fs.readFileSync(eduC).equals(fs.readFileSync(eduR)),'EDU mirrors differ');
const head=model.match(/^22 serialization::archive 3 0 0 0 0 (\d+) 0 0 /),headers=[...model.matchAll(/^(\d+) ([^\s;]+)\s*\n\d+ \d+\s*$/gm)].filter(m=>+m[1]===m[2].length);ok(head&&+head[1]-headers.length===1,`modeldb count mismatch: ${head&&head[1]} declared, ${headers.length} detected`);
const modelNames=new Set(headers.map(x=>x[2])),buf=fs.readFileSync(locP),loc=buf.slice(2).toString('utf16le');ok(buf[0]===255&&buf[1]===254,'localization is not UTF-16LE BOM');
const costs={pekhota:[1000,1300,1600],opolchenie:[600,800,1100],leib_guard:[1200,1500,1800],grenadery:[1200,1500,1800],strelki:[1000,1300,1600],marines:[1000,1300,1600],sapery:[1000,1300,1600],siberian:[900,1200,1500],draguny:[1200,1500,1800],kazaki:[1000,1300,1600]};
for(const t of expected){const b=block(t);ok(b,`${t}: missing EDU record`);if(!b)continue;const sm=(b.match(/^soldier\s+(\S+),/m)||[])[1];ok(modelNames.has(sm),`${t}: missing soldier model ${sm}`);for(const o of [...b.matchAll(/^officer\s+(\S+)/gm)].map(x=>x[1]))ok(modelNames.has(o),`${t}: missing officer ${o}`);ok(/^stat_ground\s+0, 0, 0, 0$/m.test(b),`${t}: nonzero ground modifier`);ok(!/(hardy|very_hardy|hide_improved_forest)/.test((b.match(/^attributes\s+(.+)$/m)||[])[1]||''),`${t}: inherited special attribute`);ok(fs.existsSync(path.join(root,'data/ui/units/russia',`#${t}.tga`)),`${t}: missing tactical card`);for(const k of [t,`${t}_descr`,`${t}_descr_short`])ok(loc.includes(`{${k}}`),`${t}: missing ${k}`);const row=((b.match(/^stat_cost\s+(.+)$/m)||[])[1]||'').split(',').map(x=>+x.trim());ok(row.length===8&&row[2]===Math.round(row[1]/3)&&row[3]===100&&row[4]===100&&row[5]===row[1]&&row[7]===Math.round(row[1]/3),`${t}: bad cost row`);const m=t.match(/^rus_(pekhota|opolchenie|leib_guard|grenadery|strelki|marines|sapery|siberian|draguny|kazaki)_(early|mid|high)$/);if(m){const pi=periods.indexOf(m[2]);ok(row[1]===costs[m[1]][pi],`${t}: expected cost ${costs[m[1]][pi]}, got ${row[1]}`);ok(new RegExp(`^era ${pi}\\s+russia$`,'m').test(b),`${t}: wrong era`);}}
for(const x of lines){for(const [i,p] of periods.entries()){const b=block(`rus_${x}_${p}`),off=[...b.matchAll(/^officer\s+/gm)].length;ok(off===(i<2?2:1),`rus_${x}_${p}: wrong officer count ${off}`);ok((i===2||x==='sapery')===/attributes\s+.*\bstakes\b/.test(b),`rus_${x}_${p}: stakes rule mismatch`);}}
for(const p of periods){const sb=block(`rus_siberian_${p}`),kb=block(`rus_kazaki_${p}`),db=block(`rus_draguny_${p}`);ok(/^stat_sec\s+3, 3,/m.test(sb),`rus_siberian_${p}: additional melee penalty missing`);ok(/^stat_mental\s+3, low, trained$/m.test(kb),`rus_kazaki_${p}: not militia quality`);ok(/^stat_sec\s+2, 2,/m.test(kb),`rus_kazaki_${p}: wrong militia melee row`);ok(/^class\s+missile$/m.test(kb)&&/^class\s+missile$/m.test(db),`${p}: carbine cavalry not missile class`);ok((p==='high')===/attributes\s+.*\bstakes\b/.test(kb),`rus_kazaki_${p}: stakes mismatch`);}
for(const t of ['rus_gusary','rus_ulany','rus_guard_cuirassiers'])ok(/^formation\s+2, 2, 4, 4, 3, square$/m.test(block(t)),`${t}: cavalry formation not 3 ranks`);const g=block('rus_general_staff');ok(/^soldier\s+rus_general_staff, 4,/m.test(g),'general strength not 4');ok(/^class\s+light$/m.test(g),'general not light cavalry');ok(/^formation\s+2, 2, 4, 4, 2, square$/m.test(g),'general not two ranks');ok(/^stat_cost\s+3, 200, 67, 100, 100, 200, 1, 67$/m.test(g),'general cost not fixed at 200');for(const t of ['rus_gusary','rus_guard_cuirassiers','rus_general_staff'])ok(/^class\s+(light|heavy)$/m.test(block(t))&&!/^class\s+missile$/m.test(block(t)),`${t}: pistol cavalry identified as missile class`);
for(const t of aliases)ok(!/^ownership\s+.*russia/m.test(block(t))&&!/^era [012]\s+.*russia/m.test(block(t)),`${t}: legacy alias still in Russian roster`);for(const t of auxiliaries)ok(!/^ownership\s+.*russia/m.test(block(t))&&!/^era [012]\s+.*russia/m.test(block(t)),`${t}: regional auxiliary still in national roster`);
function me(n){const a=model.split('\n'),i=a.findIndex(x=>new RegExp(`^${n.length} ${n}\\s*$`).test(x));if(i<0)return'';let j=i;while(j<a.length&&!/^16 -0\.090000004 /.test(a[j]))j++;return a.slice(i,j+1).join('\n');}
for(const t of ['rus_strelki_mid','rus_strelki_high'])ok(/15 MTW2_Musket_SSK 9 MTW2_Pike/.test(me(t)),`${t}: lacks skirmisher animation`);for(const x of ['pekhota','opolchenie','leib_guard','grenadery','marines','sapery','siberian'])for(const p of ['mid','high']){const fast=(p==='mid'&&x==='opolchenie')||(p==='high'&&x!=='opolchenie'),anim=fast?'20 MTW2_Fast_Arquebus_3':'14 MTW2_Musket_SS';ok(new RegExp(`${anim} 9 MTW2_Pike`).test(me(`rus_${x}_${p}`)),`rus_${x}_${p}: wrong firearm animation`);}ok(/aus_lan_1g_lod0\.mesh/.test(me('rus_ulany'))&&/13 MTW2_HR_Lance 13 MTW2_HR_Sword/.test(me('rus_ulany')),'rus_ulany: not using European lance/sabre donor');for(const t of expected.filter(x=>/^rus_(draguny|kazaki)_/.test(x)||['rus_gusary','rus_ulany','rus_guard_cuirassiers','rus_general_staff'].includes(x)))ok(/unit_sprites\/tmp_cavalry_sprite\.spr/.test(me(t)),`${t}: non-mounted distant sprite`);
if(fail.length){console.error(fail.join('\n'));process.exit(1);}console.log(`Russia validation passed: ${expected.length} core records; modeldb ${head[1]} declared entries.`);
