const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),eduC=path.join(root,'data/tow_steamsteel/export_descr_unit.txt'),eduR=path.join(root,'data/export_descr_unit.txt'),modelP=path.join(root,'data/unit_models/battle_models.modeldb'),locP=path.join(root,'data/text/export_units.txt');
const expected=['gre_line_early','gre_line_mid','gre_line_high','gre_ethnofylaki_early','gre_efedroi_mid','gre_efedroi_high','gre_evzones_early','gre_evzones_mid','gre_evzones_high','gre_marines_early','gre_marines_mid','gre_marines_high','gre_lancers','gre_royal_escort','gre_carbineers_mid','gre_carbineers_high','gre_general_staff','gre_sappers_high'];
const aliases=['fra_hussar_mongols','evzones_inf','greek_roy','greek_guard_cav','swed_inf','rom_cav','greek_early_inf'];
const auxiliaries=['armenian_inf','rom_guard','it_royals_mongols','austro_sailor_mongols','balk_cav_mongols','bulgarian_inf_mongols'];
const edu=fs.readFileSync(eduC,'utf8').replace(/\r\n/g,'\n'),model=fs.readFileSync(modelP,'utf8').replace(/\r\n/g,'\n');
const fail=[],ok=(x,m)=>{if(!x)fail.push(m);};
function block(type){const starts=[...edu.matchAll(/^type\s+(\S+)/gm)];const i=starts.findIndex(x=>x[1]===type);return i<0?'':edu.slice(starts[i].index,i+1<starts.length?starts[i+1].index:edu.length);}
const types=[...edu.matchAll(/^type\s+(.+)$/gm)].map(x=>x[1].trim()),dicts=[...edu.matchAll(/^dictionary\s+(\S+)/gm)].map(x=>x[1]);const dupTypes=[...new Set(types.filter((x,i)=>types.indexOf(x)!==i))],dupDicts=[...new Set(dicts.filter((x,i)=>dicts.indexOf(x)!==i))];ok(!dupTypes.length,`duplicate EDU type: ${dupTypes.join(', ')}`);ok(!dupDicts.length,`duplicate EDU dictionary: ${dupDicts.join(', ')}`);ok(fs.readFileSync(eduC).equals(fs.readFileSync(eduR)),'EDU mirrors differ');
const mb=model.match(/^22 serialization::archive 3 0 0 0 0 (\d+) 0 0 /),entryHeaders=[...model.matchAll(/^(\d+) ([^\s;]+)\s*\n\d+ \d+\s*$/gm)].filter(m=>+m[1]===m[2].length),modelEntryCount=entryHeaders.length+1;ok(mb&&+mb[1]===modelEntryCount,`modeldb header ${mb&&mb[1]} != entries ${modelEntryCount}`);
const modelNames=new Set([...model.matchAll(/^\d+ ([^\s;]+)\s*$/gm)].filter(m=>+m[0].trim().split(/\s+/)[0]===m[1].length).map(m=>m[1]));
const locBuf=fs.readFileSync(locP),loc=locBuf.slice(2).toString('utf16le');ok(locBuf[0]===255&&locBuf[1]===254,'localization lacks UTF-16LE BOM');
for(const t of expected){const b=block(t);ok(b,`missing ${t}`);if(!b)continue;const soldier=(b.match(/^soldier\s+(\S+),/m)||[])[1];ok(modelNames.has(soldier),`${t}: missing model ${soldier}`);for(const o of [...b.matchAll(/^officer\s+(\S+)/gm)].map(x=>x[1]))ok(modelNames.has(o),`${t}: missing officer ${o}`);ok(fs.existsSync(path.join(root,'data/ui/units/mongols',`#${t}.tga`)),`${t}: missing card`);ok(fs.existsSync(path.join(root,'data/ui/unit_info/mongols',`${t}_info.tga`)),`${t}: missing info card`);for(const k of [t,`${t}_descr`,`${t}_descr_short`])ok(loc.includes(`{${k}}`),`${t}: missing localization ${k}`);const c=(b.match(/^stat_cost\s+(.+)$/m)||[])[1];if(c){const n=c.split(',').map(x=>+x.trim());ok(n[2]===Math.round(n[1]/3)&&n[5]===n[1]&&n[7]===Math.round(n[1]/3),`${t}: bad cost arithmetic`);ok(n[3]===100&&n[4]===100,`${t}: upgrade costs not 100`);}ok(/^stat_ground\s+0, 0, 0, 0$/m.test(b),`${t}: nonstandard ground modifiers`);}
for(const t of aliases){const b=block(t);ok(b&&!/^ownership\s+.*mongols/m.test(b)&&!/^era [012]\s+.*mongols/m.test(b),`${t}: legacy alias still Greek-owned`);}for(const t of auxiliaries){const b=block(t);ok(b&&!/^ownership\s+.*mongols/m.test(b)&&!/^era [012]\s+.*mongols/m.test(b),`${t}: auxiliary still in Greek roster`);}
for(const t of ['gre_line_early','gre_ethnofylaki_early','gre_evzones_early','gre_marines_early'])ok(/gunpowder_unit/.test(block(t)),`${t}: muzzle-loader lacks gunpowder_unit`);for(const t of expected.filter(x=>!['gre_line_early','gre_ethnofylaki_early','gre_evzones_early','gre_marines_early'].includes(x)))if(/_mid|_high/.test(t)&&!t.includes('sappers'))ok(!/gunpowder_unit/.test(block(t)),`${t}: breechloader has gunpowder_unit`);
for(const t of ['gre_line_high','gre_efedroi_high','gre_evzones_high','gre_marines_high','gre_carbineers_high','gre_sappers_high'])ok(/attributes\s+.*stakes/.test(block(t)),`${t}: late infantry/carbine unit lacks stakes`);
function modelEntry(n){const a=model.split('\n'),i=a.findIndex(x=>new RegExp(`^${n.length} ${n}\\s*$`).test(x));if(i<0)return'';let j=i;while(j<a.length&&!/^16 -0\.090000004 /.test(a[j]))j++;return a.slice(i,j+1).join('\n');}
for(const t of ['gre_evzones_mid','gre_evzones_high'])ok(/15 MTW2_Musket_SSK 9 MTW2_Pike/.test(modelEntry(t)),`${t}: not using skirmisher animation`);for(const t of ['gre_line_mid','gre_line_high','gre_efedroi_mid','gre_efedroi_high','gre_marines_mid','gre_marines_high'])ok(/14 MTW2_Musket_SS 9 MTW2_Pike/.test(modelEntry(t)),`${t}: not using line breechloader animation`);for(const t of ['gre_marines_early','gre_marines_mid','gre_marines_high']){const marine=modelEntry(t);ok(/unit_models\/_Units\/fra\/fra_nav_1g_lod0\.mesh/.test(marine),`${t}: lacks corrected French naval mesh`);ok(/7 mongols\s*\n50 unit_models\/_Units\/fra\/textures\/fra_nav_1g\.texture/.test(marine),`${t}: lacks matching naval texture`);}const lance=modelEntry('gre_lancers');ok(/unit_models\/_Units\/aus\/aus_lan_1g_lod0\.mesh/.test(lance),'Greek lancers lack Austrian European lancer mesh');ok(/13 MTW2_HR_Lance 13 MTW2_HR_Sword/.test(lance),'Greek lancers lack lance/sabre model weapons');ok(/7 mongols\s*\n50 unit_models\/_Units\/gre\/textures\/gre_cav_2g\.texture/.test(lance),'Greek lancers lack Greek cavalry texture mapping');
if(fail.length){console.error(fail.join('\n'));process.exit(1);}console.log(`Greece validation passed: ${expected.length} roster records, ${modelEntryCount} modeldb entries.`);
