const fs=require('fs'),path=require('path'),R=path.resolve(__dirname,'..');
const e=fs.readFileSync(path.join(R,'data/tow_steamsteel/export_descr_unit.txt'),'utf8').replace(/\r/g,''),mirror=fs.readFileSync(path.join(R,'data/export_descr_unit.txt'),'utf8').replace(/\r/g,''),m=fs.readFileSync(path.join(R,'data/unit_models/battle_models.modeldb'),'utf8');
const fail=[];const ok=(v,s)=>{if(!v)fail.push(s)};
function b(t){const x=e.match(new RegExp(`^type\\s+${t}\\n[\\s\\S]*?(?=^type\\s+|(?![\\s\\S]))`,'m'));if(!x){fail.push('missing '+t);return ''}return x[0]}
function mb(n){const x=m.match(new RegExp(`^${n.length} ${n}\\s*$[\\s\\S]*?(?=^\\d+ [^\\s;]+\\s*$\\r?\\n\\d+ \\d+\\s*$|(?![\\s\\S]))`,'m'));if(!x){fail.push('model '+n);return ''}return x[0]}
const roster=['indian_bow_cav','indian_spear_cav','Sikh_heavy_cavalry','indian_spears','indian_heavy_banduqchis','indian_new_musk','india_sepoy','sikh_gen','sikh_warriors','indian_fanatic','indian_ele','india_militia','ind_bhutan_warrior'];
ok(e===mirror,'EDU mirror differs');
for(const t of roster){const x=b(t);ok(/^stat_ground\s+0, 0, 0, 0$/m.test(x),t+' terrain');ok(/^stat_fire_delay\s+0$/m.test(x),t+' fire delay');const c=(x.match(/^stat_cost\s+(.+)$/m)||[,''])[1].split(',').map(v=>+v.trim());ok(c.length===8&&c[3]===100&&c[4]===100,t+' cost');const f=path.join(R,'data/ui/units/bulga','#'+t+'.tga');ok(fs.existsSync(f),t+' card');if(fs.existsSync(f)){const q=fs.readFileSync(f);ok(q.readUInt16LE(12)===48&&q.readUInt16LE(14)===64&&q[16]===32,t+' card format')}}
ok(/soldier\s+indian_bow_cav, 24/.test(b('indian_bow_cav'))&&/class\s+missile/.test(b('indian_bow_cav'))&&/arquebus_bullet_c, 140/.test(b('indian_bow_cav')),'Sowar role');
ok(/soldier\s+indian_spear_cav, 24/.test(b('indian_spear_cav'))&&/stat_pri\s+4, 6, no/.test(b('indian_spear_cav')),'lancer stats');
ok(/stat_pri_armour\s+4, 3, 1, metal/.test(b('Sikh_heavy_cavalry')),'Gorchara shield');ok(/soldier\s+indian_spears, 80/.test(b('indian_spears'))&&/stat_pri_armour\s+3, 1, 4, flesh/.test(b('indian_spears')),'spear levy');
ok(/soldier\s+rajput_snipers, 30/.test(b('indian_heavy_banduqchis'))&&/long_gun_bullet, 280/.test(b('indian_heavy_banduqchis'))&&/stat_sec\s+5, 3,[^\n]+axe/.test(b('indian_heavy_banduqchis')),'Rajput long gun axe');
ok(/soldier\s+indian_new_musk, 40/.test(b('indian_new_musk'))&&/stat_sec\s+5, 3,[^\n]+sword/.test(b('indian_new_musk')),'Maratha sword');ok(/soldier\s+uk_sikh_reg, 40/.test(b('india_sepoy'))&&/stat_sec\s+4, 3,[^\n]+spear/.test(b('india_sepoy')),'Sepoy bayonet');
ok(/rifle_bullet_b, 240/.test(b('sikh_warriors'))&&!/gunpowder_unit/.test(b('sikh_warriors'))&&/stat_pri_armour\s+3, 3, 2, leather/.test(b('sikh_warriors')),'Khalsa Guard');ok(/soldier\s+sikh_gen, 4/.test(b('sikh_gen'))&&/class\s+light/.test(b('sikh_gen'))&&/formation\s+2, 2, 4, 4, 2, square/.test(b('sikh_gen')),'general');ok(/soldier\s+indian_fanatic, 80/.test(b('indian_fanatic'))&&/stat_pri_armour\s+3, 3, 2, flesh/.test(b('indian_fanatic')),'Akali');ok(/soldier\s+india_militia, 30/.test(b('india_militia'))&&/wall_gun_bullet, 240/.test(b('india_militia'))&&/formation\s+1.4, 1.8, 2.8, 3.6, 3, square/.test(b('india_militia')),'wall gunner skirmisher conventions');
ok(/^stat_cost\s+1, 500, 167, 100, 100, 500, 2, 167$/m.test(b('indian_spears')),'militia melee infantry price');ok(/^stat_cost\s+1, 500, 167, 100, 100, 500, 1, 167$/m.test(b('ind_bhutan_warrior')),'auxiliary militia melee infantry price');ok(/^stat_cost\s+1, 900, 300, 100, 100, 900, 1, 300$/m.test(b('indian_fanatic')),'elite melee infantry price');
ok(/^stat_cost\s+2, 900, 300, 100, 100, 900, 1, 300$/m.test(b('indian_heavy_banduqchis')),'regular arquebus skirmisher price');ok(/^stat_cost\s+2, 700, 233, 100, 100, 700, 1, 233$/m.test(b('india_militia')),'militia wall-gunner price');ok(/^stat_cost\s+2, 1000, 333, 100, 100, 1000, 2, 333$/m.test(b('indian_new_musk'))&&/^stat_cost\s+2, 1000, 333, 100, 100, 1000, 2, 333$/m.test(b('india_sepoy')),'regular musket infantry prices');ok(/^stat_cost\s+2, 1700, 567, 100, 100, 1700, 1, 567$/m.test(b('sikh_warriors')),'elite rifle infantry price');
ok(/soldier\s+bhutan_warrior, 80/.test(b('ind_bhutan_warrior'))&&/stat_pri\s+3, 2,[^\n]+sword/.test(b('ind_bhutan_warrior'))&&/stat_pri_armour\s+3, 1, 2, flesh/.test(b('ind_bhutan_warrior'))&&/stat_ground\s+0, 0, 0, 0/.test(b('ind_bhutan_warrior')),'Bhutanese D-tier sword/shield auxiliary');ok(!/^ownership\s+.*\bbulga\b/m.test(b('merc_bhutan_warrior'))&&!/^era\s+[012].*\bbulga\b/m.test(b('merc_bhutan_warrior')),'shared Bhutan record still exposes bulga');
for(const n of ['indian_new_musk','rajput_snipers','india_militia'])ok(/20 MTW2_Fast_Arquebus_3/.test(mb(n)),n+' animation');ok(/malata_buzu_huoqiang_lod0\.mesh/.test(mb('india_militia'))&&/MTW2_2H_Axe/.test(mb('india_militia')),'wall gunner face-safe gun/axe donor');ok(/MTW2_HR_Lance/.test(mb('indian_spear_cav'))&&/MTW2_HR_Sword/.test(mb('indian_spear_cav'))&&/indu_royal_cav_lod0\.mesh/.test(mb('indian_spear_cav')),'regional lancer mesh');
for(const t of ['ind_gatling','ind_150mm'])ok(!/^ownership\s+.*\bbulga\b/m.test(b(t)),t+' visible');ok(/era 0\s+bulga, slave/.test(b('ind_armstrong'))&&/era 1\s+bulga, slave/.test(b('ind_armstrong'))&&!/era 2\s+bulga/.test(b('ind_armstrong')),'Armstrong eras');for(const t of ['ind_12lb','ind_5lb','ind_maxim'])ok(/era 2\s+bulga, slave/.test(b(t))&&!/era [01]\s+bulga/.test(b(t)),t+' eras');
for(const t of ['ind_armstrong','ind_12lb','ind_5lb','ind_maxim']){const x=b(t),c=(x.match(/^stat_cost\s+(.+)$/m)||[,''])[1].split(',').map(v=>+v.trim());ok(c.length===8&&c[2]===Math.round(c[1]/3)&&c[3]===100&&c[4]===100&&c[7]===Math.round(c[1]/3),t+' artillery cost');ok(/^stat_mental\s+3, low, trained$/m.test(x),t+' D-tier crew morale')}
for(const t of ['ind_armstrong','ind_12lb','ind_5lb','ind_maxim']){const f=path.join(R,'data/ui/units/bulga','#'+t+'.tga'),q=fs.readFileSync(f);ok(q.readUInt16LE(12)===48&&q.readUInt16LE(14)===64&&q[16]===32,t+' artillery card')}
if(fail.length){console.error(fail.join('\n'));process.exit(1)}console.log('Indian Princely States validation passed.');
