const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'..');
const edu=fs.readFileSync(path.join(root,'data/tow_steamsteel/export_descr_unit.txt'),'utf8').replace(/\r/g,''),mirror=fs.readFileSync(path.join(root,'data/export_descr_unit.txt'),'utf8').replace(/\r/g,''),model=fs.readFileSync(path.join(root,'data/unit_models/battle_models.modeldb'),'utf8').replace(/\r/g,'');
const types=[...edu.matchAll(/^type\s+(ott_(?:nizamiye|redif|avci|hassa|bahriye|mustahfiz|suvari|mizrakli|ertugrul|general)[^\s]*)/gm)].map(x=>x[1]),expected=24;
function fail(s){throw Error(s)} if(types.length!==expected)fail(`Expected ${expected} Ottoman records, found ${types.length}`);if(edu!==mirror)fail('Canonical/runtime EDU mismatch');
if(new Set(types).size!==types.length)fail('Duplicate standardized Ottoman types');
for(const t of types){const a=edu.indexOf(`type             ${t}`),z=edu.indexOf('\ntype             ',a+1),b=edu.slice(a,z<0?edu.length:z);if(!/^ownership\s+.*\bturks\b/m.test(b))fail(`${t}: no turks ownership`);if(!/^era [012]\s+.*\bturks\b/m.test(b))fail(`${t}: no turks era`);if(!/^stat_fire_delay\s+0$/m.test(b))fail(`${t}: nonzero fire delay`);if(!/^stat_ground\s+0, 0, 0, 0$/m.test(b))fail(`${t}: nonstandard ground`);if(/hardy|very_hardy|hide_improved_forest/.test(b))fail(`${t}: inherited special attribute`);const s=(b.match(/^soldier\s+(\S+),/m)||[])[1];if(!s||!new RegExp(`^${s.length} ${s}\\s*$`,'m').test(model))fail(`${t}: missing model ${s}`);const card=path.join(root,'data/ui/units/turks',`#${t}.tga`);if(!fs.existsSync(card))fail(`${t}: missing tactical card`);const c=(b.match(/^stat_cost\s+(.+)$/m)||[])[1].split(',').map(x=>+x.trim());if(c[3]!==100||c[4]!==100||c[1]!==c[5]||c[2]!==c[7])fail(`${t}: bad cost arithmetic`);}
function unitBlock(t){const a=edu.indexOf(`type             ${t}`),z=edu.indexOf('\ntype             ',a+1);if(a<0)fail(`${t}: missing EDU record`);return edu.slice(a,z<0?edu.length:z);}
function modelBlock(t){const marker=`${t.length} ${t} \n`,a=model.indexOf(marker),z=model.indexOf('\n16 -0.090000004 ',a);if(a<0)fail(`${t}: missing modeldb record`);return model.slice(a,z<0?model.length:z);}
const infantryLineages='nizamiye|redif|avci|hassa|bahriye|mustahfiz';
for(const t of types.filter(x=>new RegExp(`^ott_(?:${infantryLineages})_(?:early|mid|high)$`).test(x))){const b=unitBlock(t),officers=[...b.matchAll(/^officer\s+(\S+)\s*$/gm)].map(x=>x[1]),late=t.endsWith('_high');if(late){if(officers.join(',')!=='fez_off_1g')fail(`${t}: late infantry must have only the Ottoman officer`);}else if(officers.join(',')!=='fez_off_1g,ott_standard_bearer')fail(`${t}: early/mid infantry must have officer plus Ottoman standard bearer`);}
{const t='ott_standard_bearer',mb=modelBlock(t),mesh='unit_models/_Units/off/ott_standard_bearer_lod0.mesh',body='unit_models/_Units/ott/textures/ott_inf_1g.texture',bodyN='unit_models/_Units/attachments/textures/blank_norm.texture',flag='unit_models/_Units/bnw/textures/ott_standard_flag.texture',flagN='unit_models/_Units/bnw/textures/ott_standard_flag_n.texture',sprite='unit_sprites/turks_Janissary_Musketeers_sprite.spr';for(const p of [mesh,body,bodyN,flag,flagN])if(!fs.existsSync(path.join(root,'data',p)))fail(`${t}: missing asset ${p}`);for(const p of [body,bodyN,flag,flagN]){const x=fs.readFileSync(path.join(root,'data',p));if(x.subarray(48,52).toString('ascii')!=='DDS ')fail(`${t}: invalid texture container ${p}`);}const meshBuffer=fs.readFileSync(path.join(root,'data',mesh)),meshBytes=meshBuffer.toString('latin1');if(meshBuffer.readUInt32LE(0)!==22||!meshBytes.includes('big_flag')||!meshBytes.includes('yifu')||!meshBytes.includes('head8')||!meshBytes.includes('hat')||meshBytes.includes('berdan_01'))fail(`${t}: mesh is not the Nizamiye body and face set with verified flag geometry`);for(const p of [mesh,body,bodyN,flag,flagN,sprite])if(!mb.includes(`${p.length} ${p} `))fail(`${t}: bad or missing modeldb mapping ${p}`);if(!mb.includes('5 turks ')||!mb.includes('9 MTW2_Pike ')||!mb.includes('17 MTW2_Pike_primary '))fail(`${t}: incomplete Turkish faction or bearer animation mapping`);}
{const mesh='unit_models/_Units/ott/ott_inf_1g_lod0.mesh',body='unit_models/_Units/ott/textures/ott_inf_1g.texture',face='unit_models/_Units/attachments/textures/per_rugbxx.texture',repaint='unit_models/_Units/ott/textures/ott_mustahfiz_faces.texture';for(const t of ['ott_mustahfiz_early','ott_mustahfiz_mid']){const mb=modelBlock(t);if(!mb.includes(`${mesh.length} ${mesh} `)||!mb.includes(`${body.length} ${body} `))fail(`${t}: does not use the complete native Ottoman infantry model mapping`);for(const faction of ['turks','slave']){const mappings=[...mb.matchAll(new RegExp(`^${faction.length} ${faction}\\s*$\\n(\\d+ unit_models/_Units/\\S+/textures/\\S+\\.texture\\s*)$`,'gm'))].map(x=>x[1].trim());if(mappings.length<2||mappings[1]!==`${face.length} ${face}`)fail(`${t}: ${faction} does not retain the native Ottoman face attachment`);}if(mb.includes(repaint)||mb.includes('unit_models/_Units/nej/nej_inf_2g_lod0.mesh'))fail(`${t}: still uses the faulty Nejd face setup`);}}
const pistolModels={
  ott_hassa_suvarisi:{mesh:'unit_models/_Units/otto/ott_hassa_suvarisi_lod0.mesh',body:'unit_models/_Units/otto/textures/otto_reg.texture',gear:'unit_models/_Units/otto/textures/ott_hassa_pistol_gear.texture',oldWeapon:'buqiang',bodyGroup:'yifu'},
  ott_general_staff:{mesh:'unit_models/_Units/ott/ott_general_staff_lod0.mesh',body:'unit_models/_Units/ott/textures/ott_cav_1g.texture',gear:'unit_models/_Units/ott/textures/ott_general_pistol_gear.texture',oldWeapon:'sm_01',bodyGroup:'coat_01'}
};
for(const [t,total,upkeep] of [['ott_hassa_suvarisi',1400,467],['ott_general_staff',200,67]]){const b=unitBlock(t),eras=[...b.matchAll(/^era ([012])\s+.*\bturks\b/gm)].map(x=>+x[1]).sort();if(eras.join(',')!=='0,1,2')fail(`${t}: pistol unit must span all three eras without period variants`);if(!b.includes('Smith & Wesson No. 3 revolver and sabre'))fail(`${t}: pistol is not identified by its exact weapon name`);if(!/^class\s+light$/m.test(b)||/^class\s+missile$/m.test(b))fail(`${t}: pistol unit must be light cavalry`);if(!/^stat_pri\s+20, 4, magazine_rifle_bullet_c, 60, 15, missile, missile_gunpowder, piercing, none, musket_shot_set, 25, 1$/m.test(b))fail(`${t}: incorrect fixed pistol row`);if(/\bgunpowder_unit\b|\bstakes\b/.test((b.match(/^attributes\s+(.+)$/m)||[])[1]||''))fail(`${t}: pistol unit has invalid muzzle-loader or stakes attribute`);const c=(b.match(/^stat_cost\s+(.+)$/m)||[])[1].split(',').map(x=>+x.trim());if(c[1]!==total||c[2]!==upkeep)fail(`${t}: expected cost/upkeep ${total}/${upkeep}`);const mb=modelBlock(t),spec=pistolModels[t];if(!/14 MTW2_HR_Pistol\s+13 MTW2_HR_Sword\s+/.test(mb)||!mb.includes('22 MTW2_HR_Pistol_Primary '))fail(`${t}: missing pistol animation mapping`);if(!mb.includes(`${spec.mesh.length} ${spec.mesh} `)||/unit_models\/_units\/japan\/revolver_cavalry_lod0\.mesh/i.test(mb))fail(`${t}: not using the Ottoman-body pistol mesh`);if(!mb.includes(`${spec.body.length} ${spec.body} `)||!mb.includes(`${spec.gear.length} ${spec.gear} `))fail(`${t}: missing original Ottoman body or combined pistol gear texture`);const meshBuffer=fs.readFileSync(path.join(root,'data',spec.mesh));if(meshBuffer.readUInt32LE(0)!==22||meshBuffer.subarray(4,26).toString('ascii')!=='serialization::archive')fail(`${t}: corrupt mesh serialization header`);const meshBytes=meshBuffer.toString('latin1');if(!meshBytes.includes('swrevolver_01')||!meshBytes.includes(spec.bodyGroup)||meshBytes.includes(spec.oldWeapon))fail(`${t}: mesh does not contain the Ottoman body with carbine replaced by revolver`);const sprites=[...mb.matchAll(/^\d+ (unit_sprites\/[^\s]+\.spr)\s*$/gm)].map(x=>x[1]);if(!sprites.length||sprites.some(x=>x!=='unit_sprites/tmp_cavalry_sprite.spr'))fail(`${t}: pistol model has a non-mounted distant sprite`);}
const lance=(()=>{const t='ott_mizrakli_suvari',a=edu.indexOf(`type             ${t}`),z=edu.indexOf('\ntype             ',a+1),b=edu.slice(a,z);return b})();const pc=+(lance.match(/^stat_pri\s+\d+,\s*(\d+)/m)||[])[1],sc=+(lance.match(/^stat_sec\s+\d+,\s*(\d+)/m)||[])[1];if(pc!==sc+3)fail('Ottoman lancer primary charge is not sabre +3');
for(const t of ['rus_georgian_cav_turks','fra_blacks_turks','georgian_inf','moroccan_camel_gunner','moroccan_gunner','mahdist_inf','fra_blacks_az','merc_bulgarian_inf','mahdist_camel_cav','mahdist_cav','bashi_inf']){const i=edu.indexOf(`type             ${t}`);if(i<0)continue;const z=edu.indexOf('\ntype             ',i+1),b=edu.slice(i,z<0?edu.length:z);if(/^ownership\s+.*\bturks\b/m.test(b)||/^era [012]\s+.*\bturks\b/m.test(b))fail(`${t}: auxiliary remains in Ottoman main roster`);}
const header=+(model.match(/^22 serialization::archive 3 0 0 0 0 (\d+) 0 0 /)||[])[1],headers=[...model.matchAll(/^(\d+) ([^\s;]+)\s*\n1 \d+\s*$/gm)].filter(x=>+x[1]===x[2].length);if(header-headers.length!==1)fail(`modeldb count mismatch ${header}/${headers.length}`);console.log(`Ottoman validation passed: ${types.length} records; modeldb ${header}.`);
