const fs=require('fs'),path=require('path'),crypto=require('crypto');const root=path.resolve(__dirname,'..');
const edu=fs.readFileSync(path.join(root,'data/tow_steamsteel/export_descr_unit.txt'),'utf8').replace(/\r/g,''),mirror=fs.readFileSync(path.join(root,'data/export_descr_unit.txt'),'utf8').replace(/\r/g,'');
const edb=fs.readFileSync(path.join(root,'data/tow_steamsteel/export_descr_buildings.txt'),'utf8'),edbMirror=fs.readFileSync(path.join(root,'data/export_descr_buildings.txt'),'utf8');const model=fs.readFileSync(path.join(root,'data/unit_models/battle_models.modeldb'),'utf8').replace(/\r/g,'');
const fail=m=>{throw Error(m)},ok=(c,m)=>{if(!c)fail(m)};ok(edu===mirror,'EDU mirrors differ');ok(edb===edbMirror,'EDB mirrors differ');
const types=['oma_baluchi_musketeers','oma_regular_early','oma_regular_mid','oma_regular_high','oma_palace_guard_early','oma_palace_guard_mid','oma_palace_guard_high','oma_zanzibar_mid','oma_zanzibar_high','oma_bedouin_camelry','oma_horse_guard_early','oma_horse_guard_mid','oma_horse_guard_high','oma_command_retinue'];
function block(t){const m=edu.match(new RegExp(`^type\\s+${t}\\n([\\s\\S]*?)(?=^type\\s+|(?![\\s\\S]))`,'m'));if(!m)fail(`missing ${t}`);return `type             ${t}\n${m[1]}`;}
for(const t of types){const b=block(t);ok((edu.match(new RegExp(`^type\\s+${t}$`,'gm'))||[]).length===1,`${t}: duplicate`);ok(/^ownership\s+golden, slave$/m.test(b),`${t}: ownership`);ok(/^stat_ground\s+0, 0, 0, 0$/m.test(b),`${t}: ground`);ok(/^stat_fire_delay\s+0$/m.test(b),`${t}: fire delay`);ok(!/hide_improved_forest|hardy|very_hardy|affected_by_rain/.test(b),`${t}: inherited special attribute`);ok(/^stat_cost\s+\d+, \d+, \d+, 100, 100, \d+, \d+, \d+$/m.test(b),`${t}: cost format`);}
const infantryTypes=['oma_baluchi_musketeers','oma_regular_early','oma_regular_mid','oma_regular_high','oma_palace_guard_early','oma_palace_guard_mid','oma_palace_guard_high','oma_zanzibar_mid','oma_zanzibar_high'],bearerUnits=new Set(['oma_regular_early','oma_regular_mid','oma_palace_guard_early','oma_palace_guard_mid','oma_zanzibar_mid']);
for(const t of infantryTypes){const officers=[...block(t).matchAll(/^officer\s+(\S+)\s*$/gm)].map(x=>x[1]),expected=bearerUnits.has(t)?'fez_off_1g,oma_standard_bearer':'fez_off_1g';ok(officers.join(',')===expected,`${t}: officer/bearer complement`);}
const swordAttack={oma_baluchi_musketeers:3,oma_regular_early:5,oma_regular_mid:5,oma_regular_high:5,oma_palace_guard_early:7,oma_palace_guard_mid:7,oma_palace_guard_high:7};
for(const [t,attack] of Object.entries(swordAttack)){const b=block(t);ok(new RegExp(`^stat_sec\\s+${attack}, \\d+, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1$`,'m').test(b),`${t}: +1 sword attack row mismatch`);ok(/^stat_sec_attr\s+no$/m.test(b),`${t}: sword must not retain AP or bayonet attributes`);ok(/and sword/.test(b),`${t}: sword omitted from equipment name`);}
for(const t of ['oma_zanzibar_mid','oma_zanzibar_high']){const b=block(t);ok(/^stat_sec\s+4, 3, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1\.2$/m.test(b)&&/^stat_sec_attr\s+ap, short_pike$/m.test(b),`${t}: Zanzibar bayonet row changed`);}
for(const t of ['oma_regular_early','oma_palace_guard_early'])ok(/rifled_musket_bullet_/.test(block(t))&&/gunpowder_unit/.test(block(t)),`${t}: early weapon`);
for(const t of ['oma_regular_mid','oma_regular_high','oma_palace_guard_mid','oma_palace_guard_high','oma_zanzibar_mid','oma_zanzibar_high'])ok(/rifle_bullet_/.test(block(t))&&!/gunpowder_unit/.test(block(t)),`${t}: breechloader attributes`);
ok(/Peabody-Martini Model 1874 rifle/.test(block('oma_palace_guard_mid'))&&/^stat_pri\s+21, 0, rifle_bullet_b,/m.test(block('oma_palace_guard_mid')),'Palace Guard mid weapon mismatch');
ok(/Belgian Francotte Martini-Henry rifle/.test(block('oma_palace_guard_high'))&&/^stat_pri\s+21, 0, rifle_bullet_b,/m.test(block('oma_palace_guard_high')),'Palace Guard late weapon mismatch');
ok(/Snider-Enfield conversion rifle/.test(block('oma_zanzibar_high'))&&/^stat_pri\s+29, 0, rifle_bullet_c,/m.test(block('oma_zanzibar_high')),'Zanzibar late weapon mismatch');
ok(/soldier\s+oma_command_retinue, 4,/.test(block('oma_command_retinue'))&&/class\s+light/.test(block('oma_command_retinue'))&&/formation\s+2, 2, 4, 4, 2, square/.test(block('oma_command_retinue'))&&/magazine_rifle_bullet_c, 60, 15/.test(block('oma_command_retinue')),'command retinue mismatch');
for(const t of ['oma_horse_guard_early','oma_horse_guard_mid','oma_horse_guard_high']){const b=block(t);ok(/^class\s+light$/m.test(b),`${t}: pistol cavalry must be light class`);ok(/^mount\s+hussar$/m.test(b),`${t}: wrong pistol-rider mount`);ok(/^stat_pri\s+20, 4, magazine_rifle_bullet_c, 60, 15, missile, missile_gunpowder, piercing, none, musket_shot_set, 25, 1$/m.test(b),`${t}: pistol row mismatch`);ok(/Beaumont-Adams revolver and sabre/.test(b),`${t}: named equipment mismatch`);ok(!/gunpowder_unit|stakes/.test(b),`${t}: invalid pistol attributes`);ok(/^stat_cost\s+3, 1400, 467, 100, 100, 1400, 1, 467$/m.test(b),`${t}: pistol cost mismatch`);}
for(const e of [0,1,2])ok(new RegExp(`^era ${e}\\s+golden$`,'m').test(block('oma_baluchi_musketeers')),`Baluchi musketeers missing era ${e}`);
ok(/mount\s+camel/.test(block('oma_bedouin_camelry'))&&/stat_pri\s+32, 2, arquebus_bullet_c, 140/.test(block('oma_bedouin_camelry')),'camelry mismatch');
ok(/soldier\s+african_spearmen, 96,/.test(block('african_warband')),'African Warband not 96');ok(/soldier\s+mahdist_inf, 96,/.test(block('mahdist_inf')),'Mahdist Warriors not 96');
for(const t of ['africa_cav','african_warband','merc_zulu_rifles','mahdist_inf','fra_blacks_az','mahdist_camel_cav','mahdist_cav']){const b=block(t);ok(!/^ownership\s+.*\bgolden\b/m.test(b)&&!/^era [012]\s+.*\bgolden\b/m.test(b),`${t}: still in Oman custom roster`);}
function modelBlock(n){const a=model.split('\n'),i=a.findIndex(x=>new RegExp(`^${n.length} ${n}\\s*$`).test(x));if(i<0)fail(`${n}: missing model`);let j=i;while(j<a.length&&!/^16 -0\.090000004 /.test(a[j]))j++;return a.slice(i,j+1).join('\n');}
{const t='oma_standard_bearer',mb=modelBlock(t),mesh='unit_models/_Units/off/oma_standard_bearer_lod0.mesh',proven='unit_models/_Units/off/ott_standard_bearer_lod0.mesh',body='unit_models/_Units/oma/textures/oma_inf_2g.texture',bodyN='unit_models/_Units/attachments/textures/blank_norm.texture',flag='unit_models/_Units/bnw/textures/oma_standard_flag.texture',flagN='unit_models/_Units/bnw/textures/oma_standard_flag_n.texture',sprite='unit_sprites/milan_Dummy_EN_Spearmen_ug1_sprite.spr';for(const p of [mesh,proven,body,bodyN,flag,flagN])ok(fs.existsSync(path.join(root,'data',p)),`${t}: missing asset ${p}`);ok(fs.readFileSync(path.join(root,'data',mesh)).equals(fs.readFileSync(path.join(root,'data',proven))),`${t}: not using the proven visible bearer mesh byte-for-byte`);for(const p of [body,bodyN,flag,flagN]){const x=fs.readFileSync(path.join(root,'data',p));ok(x.subarray(48,52).toString('ascii')==='DDS ',`${t}: invalid texture container ${p}`);}const meshBytes=fs.readFileSync(path.join(root,'data',mesh)).toString('latin1');for(const group of ['big_flag','yifu','kuzi','head','hat'])ok(meshBytes.includes(group),`${t}: missing proven body/flag group ${group}`);for(const p of [mesh,body,bodyN,flag,flagN,sprite])ok(mb.includes(`${p.length} ${p} `),`${t}: bad or missing mapping ${p}`);ok(mb.includes('6 golden ')&&mb.includes('9 MTW2_Pike ')&&mb.includes('17 MTW2_Pike_primary '),`${t}: incomplete faction or bearer animation mapping`);}
for(const t of types){const mb=modelBlock(t);if(t.includes('regular_mid')||t.includes('regular_high')||t.includes('palace_guard_mid')||t.includes('palace_guard_high')||t.includes('zanzibar_'))ok(/14 MTW2_Musket_SS/.test(mb),`${t}: wrong reload animation`);if(t in swordAttack)ok(/16 MTW2_2HSwordsman/.test(mb)&&/24 MTW2_2HSwordsman_Primary/.test(mb)&&!/(?:MTW2_Pike_primary|MTW2_2H_Axe)/.test(mb),`${t}: sword animation mapping mismatch`);ok(!/oma_(?:balush|nizamiye)_faces\.texture|oma_(?:balush_1g|nizamiye_2g)\.texture/.test(mb),`${t}: obsolete Omani face remap remains`);if(t==='oma_baluchi_musketeers'){const mesh='unit_models/_Units/bnw/moroccan_gunner_lod0.mesh',body='unit_models/_Units/bnw/textures/moroccan_golden.texture',gear='unit_models/_Units/bnw/textures/arab_gear_malib.texture';ok(mb.includes(`${mesh.length} ${mesh}`)&&mb.includes(`${body.length} ${body}`)&&mb.includes(`${gear.length} ${gear}`)&&/^6 golden\s*$/m.test(mb)&&/^5 slave\s*$/m.test(mb),`${t}: complete golden Moroccan matchlock-and-sword package missing`);const bytes=fs.readFileSync(path.join(root,'data',mesh)).toString('latin1');ok(bytes.includes('arquebus_01')&&bytes.includes('sword_01')&&bytes.includes('head_07'),`${t}: donor lacks verified arquebus, sword, or native face set`);}if(t.startsWith('oma_regular_')){const mesh='unit_models/_Units/koi/koi_ask_1g_lod0.mesh',body='unit_models/_Units/koi/textures/koi_ask_1g.texture',face='unit_models/_Units/attachments/textures/afr_grfrgb.texture';ok(mb.includes(`${mesh.length} ${mesh}`)&&mb.includes(`${body.length} ${body}`)&&mb.includes(`${face.length} ${face}`)&&/^6 golden\s*$/m.test(mb)&&/^5 slave\s*$/m.test(mb)&&!/^6 venice\s*$/m.test(mb),`${t}: complete Oman-mapped Arab rifle-and-sabre package missing`);const bytes=fs.readFileSync(path.join(root,'data',mesh)).toString('latin1');ok(bytes.includes('chassepot_01')&&bytes.includes('p_sabre')&&bytes.includes('Head')&&bytes.includes('turban'),`${t}: donor lacks verified rifle, sabre, or native head set`);}if(t.startsWith('oma_palace_guard_'))ok(/unit_models\/_Units\/oma\/oma_inf_2g_lod0\.mesh/.test(mb)&&/unit_models\/_Units\/attachments\/textures\/per_rugbxx\.texture/.test(mb),`${t}: original Palace Guard donor mapping missing`);if(t==='oma_command_retinue'||t.includes('horse_guard'))ok(/14 MTW2_HR_Pistol/.test(mb)&&/22 MTW2_HR_Pistol_Primary/.test(mb)&&/unit_models\/_Units\/oma\/oma_cav_pistol_sabre_lod0\.mesh/.test(mb)&&/tmp_cavalry_sprite/.test(mb),`${t}: native pistol mesh, animations, or sprite mismatch`);if(t.includes('horse_guard')||t==='oma_bedouin_camelry')ok(/tmp_cavalry_sprite/.test(mb),`${t}: non-mounted sprite`);}
{const mesh=path.join(root,'data/unit_models/_Units/oma/oma_cav_pistol_sabre_lod0.mesh'),bytes=fs.readFileSync(mesh).toString('latin1');ok(bytes.includes('primaryactive0')&&bytes.includes('secondaryactive0')&&!bytes.includes('priamryactive0'),'corrected Omani rider weapon groups invalid');}
const header=+(model.match(/^22 serialization::archive 3 0 0 0 0 (\d+) 0 0 /)||[])[1],entryHeaders=[...model.matchAll(/^(\d+) ([^\s;]+)\s*\n\d+ \d+\s*$/gm)].filter(m=>+m[1]===m[2].length);ok(header-entryHeaders.length===1,`modeldb count mismatch: ${header} declared, ${entryHeaders.length} detected`);
for(const t of [...types,'oma_standard_bearer']){const mb=modelBlock(t),first=mb.split('\n')[0].match(/^(\d+) (\S+)/);ok(first&&+first[1]===first[2].length,`${t}: name checksum`);for(const line of mb.split('\n')){const m=line.match(/^(\d+) (\S+\.(?:mesh|texture|spr))\s/);if(m){ok(+m[1]===m[2].length,`${t}: path checksum ${m[2]}`);if(!m[2].endsWith('.spr'))ok(fs.existsSync(path.join(root,'data',m[2])),`${t}: missing asset ${m[2]}`);}}}
const cardHash=t=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'data/ui/units/golden',`#${t}.tga`))).digest('hex');
for(const t of types){const p=path.join(root,'data/ui/units/golden',`#${t}.tga`);ok(fs.existsSync(p),`${t}: missing card`);const b=fs.readFileSync(p);ok(b.length>18,`${t}: empty card`);const w=b.readUInt16LE(12),h=b.readUInt16LE(14),depth=b[16];ok(w===48&&h===64&&depth===32,`${t}: card must be 48x64 RGBA`);}
const horseHashes=['oma_horse_guard_early','oma_horse_guard_mid','oma_horse_guard_high'].map(cardHash);ok(new Set(horseHashes).size===1,'Horse Guard lineage cards should share the unchanged pistol-rider composition');ok(cardHash('oma_bedouin_camelry')!==horseHashes[0]&&cardHash('oma_bedouin_camelry')!==cardHash('oma_command_retinue'),'Bedouin camelry card must be distinct from the horse-mounted trees');
const stale=['"otto_cav_golden"','"moroccan_camel_gunner_golden"','"moroccan_gunner_golden"','"us_zouave_go"','"omani_roy"','"omani_cav"','"otto_inf"'];for(const s of stale)ok(!edb.includes(s),`EDB stale recruit ${s}`);
console.log(`Oman validation passed: ${types.length} records; modeldb header ${header}; EDU ${crypto.createHash('sha256').update(edu).digest('hex').slice(0,12)}.`);
