const fs=require('fs'),path=require('path'),crypto=require('crypto');const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p)),text=p=>read(p).toString('utf8').replace(/\r/g,''),fail=m=>{throw Error(m)},ok=(v,m)=>{if(!v)fail(m)};
const edu=text('data/tow_steamsteel/export_descr_unit.txt'),eduMirror=text('data/export_descr_unit.txt');
const edb=read('data/tow_steamsteel/export_descr_buildings.txt'),edbMirror=read('data/export_descr_buildings.txt');
const edbText=edb.toString('utf8').replace(/\r/g,''),model=text('data/unit_models/battle_models.modeldb');
ok(edu===eduMirror,'EDU mirrors differ');ok(edb.equals(edbMirror),'EDB mirrors differ');
const types=['qaj_tofangchi','qaj_sarbaz_early','qaj_sarbaz_mid','qaj_sarbaz_high','qaj_guard_early','qaj_guard_mid','qaj_guard_high','qaj_sharpshooters','qaj_austrian_corps','qaj_tribal_cavalry','qaj_cossack_brigade','qaj_horse_guard','qaj_general_staff'];
function block(t){const m=edu.match(new RegExp(`^type\\s+${t}\\n([\\s\\S]*?)(?=^type\\s+|(?![\\s\\S]))`,'m'));if(!m)fail(`missing EDU record ${t}`);return `type             ${t}\n${m[1]}`;}
for(const t of types){const b=block(t);ok((edu.match(new RegExp(`^type\\s+${t}$`,'gm'))||[]).length===1,`${t}: duplicate`);ok(/^ownership\s+egypt, slave$/m.test(b),`${t}: ownership`);ok(/^stat_ground\s+0, 0, 0, 0$/m.test(b),`${t}: ground`);ok(/^stat_fire_delay\s+0$/m.test(b),`${t}: fire delay`);ok(!/hide_improved_forest|hardy|very_hardy|affected_by_rain/.test(b),`${t}: inherited special attribute`);ok(/^stat_cost\s+\d+, \d+, \d+, 100, 100, \d+, \d+, \d+$/m.test(b),`${t}: cost format`);}
const expectedEras={qaj_tofangchi:[0,1,2],qaj_sarbaz_early:[0],qaj_sarbaz_mid:[1],qaj_sarbaz_high:[2],qaj_guard_early:[0],qaj_guard_mid:[1],qaj_guard_high:[2],qaj_sharpshooters:[1,2],qaj_austrian_corps:[1,2],qaj_tribal_cavalry:[0,1,2],qaj_cossack_brigade:[1,2],qaj_horse_guard:[0,1,2],qaj_general_staff:[0,1,2]};
for(const [t,eras] of Object.entries(expectedEras))for(let e=0;e<3;e++)ok(new RegExp(`^era ${e}\\s+egypt$`,'m').test(block(t))===eras.includes(e),`${t}: era ${e}`);
const projectile={qaj_tofangchi:'arquebus_bullet_c',qaj_sarbaz_early:'rifled_musket_bullet_c',qaj_sarbaz_mid:'rifled_musket_bullet_c',qaj_sarbaz_high:'rifle_bullet_c',qaj_guard_early:'rifled_musket_bullet_b',qaj_guard_mid:'rifled_musket_bullet_b',qaj_guard_high:'rifle_bullet_b',qaj_sharpshooters:'rifle_bullet_a',qaj_austrian_corps:'rifle_bullet_b'};
for(const [t,p] of Object.entries(projectile))ok(new RegExp(`^stat_pri\\s+\\d+, 0, ${p},`,'m').test(block(t)),`${t}: projectile tier`);
for(const t of ['qaj_tofangchi','qaj_sarbaz_early','qaj_guard_early'])ok(/^attributes\s+.*\bgunpowder_unit\b/m.test(block(t)),`${t}: muzzle-loader attribute`);
for(const t of ['qaj_sarbaz_mid','qaj_sarbaz_high','qaj_guard_mid','qaj_guard_high','qaj_sharpshooters','qaj_austrian_corps'])ok(!/\bgunpowder_unit\b/.test(block(t)),`${t}: breechloader retained gunpowder_unit`);
for(const t of ['qaj_sarbaz_high','qaj_guard_high'])ok(/^attributes\s+.*\bstakes\b/m.test(block(t)),`${t}: late stakes missing`);
for(const t of ['qaj_tofangchi','qaj_sarbaz_early','qaj_sarbaz_mid','qaj_guard_early','qaj_guard_mid','qaj_sharpshooters','qaj_austrian_corps'])ok(!/\bstakes\b/.test(block(t)),`${t}: early/mid stakes`);
for(const t of ['qaj_tofangchi','qaj_sharpshooters']){const b=block(t);ok(/^stat_sec\s+\d+, \d+, no, 0, 0, melee, melee_blade, piercing, sword, 25, 1$/m.test(b)&&/^stat_sec_attr\s+no$/m.test(b),`${t}: sword row`);}
for(const t of ['qaj_sarbaz_early','qaj_sarbaz_mid','qaj_sarbaz_high','qaj_guard_early','qaj_guard_mid','qaj_guard_high','qaj_austrian_corps'])ok(/^stat_sec_attr\s+short_pike, ap$/m.test(block(t)),`${t}: bayonet row`);
ok(/^stat_pri\s+29, 0, rifle_bullet_a, 280,/m.test(block('qaj_sharpshooters'))&&/^soldier\s+qaj_sharpshooters, 30,/m.test(block('qaj_sharpshooters')),'sharpshooter role');
for(const t of ['qaj_sarbaz_early','qaj_sarbaz_mid','qaj_sarbaz_high'])ok(/^stat_pri_armour\s+3, 2, 1, leather$/m.test(block(t)),`${t}: Sarbaz shield`);
{const t='afghan_militia',b=block(t);ok(/^soldier\s+afghan_militia, 30, 0, 1$/m.test(b)&&/^formation\s+1.4, 1.8, 2.8, 3.6, 3, square$/m.test(b)&&/^stat_pri\s+29, 0, rifled_musket_bullet_c, 260, 35,/m.test(b)&&/^attributes\s+free_upkeep_unit, sea_faring, hide_forest, gunpowder_unit, gunmen, start_not_skirmishing, cannot_skirmish$/m.test(b)&&/^stat_ground\s+0, 0, 0, 0$/m.test(b)&&/^stat_mental\s+2, low, trained$/m.test(b)&&/^stat_cost\s+3, 1000, 333, 100, 100, 1000, 2, 333$/m.test(b),'Persian Tajik skirmisher profile');}ok(/^stat_sec\s+5, 3,/m.test(block('qaj_austrian_corps'))&&/^stat_pri_armour\s+3, 3,/m.test(block('qaj_austrian_corps'))&&/^stat_mental\s+4, normal, trained$/m.test(block('qaj_austrian_corps')),'Austrian B-tier subgroup');
for(const t of ['qaj_sarbaz_early','qaj_sarbaz_mid','qaj_guard_early','qaj_guard_mid'])ok([...block(t).matchAll(/^officer\s+(\S+)$/gm)].map(x=>x[1]).join(',')==='qajargeneral,qaj_standard_bearer',`${t}: bearer complement`);
for(const t of ['qaj_sarbaz_high','qaj_guard_high'])ok([...block(t).matchAll(/^officer\s+(\S+)$/gm)].map(x=>x[1]).join(',')==='qajargeneral',`${t}: late officer complement`);
ok(/^stat_pri\s+2, 5,/m.test(block('qaj_tribal_cavalry'))&&/^stat_sec\s+2, 2,/m.test(block('qaj_tribal_cavalry'))&&/^stat_mental\s+3, impetuous, trained$/m.test(block('qaj_tribal_cavalry')),'tribal C-tier lancer');
ok(/^stat_pri\s+5, 6,/m.test(block('qaj_cossack_brigade'))&&/^stat_sec\s+5, 3,/m.test(block('qaj_cossack_brigade'))&&/^stat_mental\s+4, disciplined, trained$/m.test(block('qaj_cossack_brigade')),'Cossack B-tier lancer');
ok(/^stat_pri\s+20, 4, magazine_rifle_bullet_c, 60, 15,/m.test(block('qaj_horse_guard'))&&!/\bgunpowder_unit\b|\bstakes\b/.test(block('qaj_horse_guard')),'fixed pistol cavalry');
ok(/^soldier\s+qaj_general_staff, 4,/m.test(block('qaj_general_staff'))&&/^category\s+cavalry$/m.test(block('qaj_general_staff'))&&/^class\s+light$/m.test(block('qaj_general_staff'))&&/^formation\s+2, 2, 4, 4, 2, square$/m.test(block('qaj_general_staff')),'general and staff structure');
for(const t of ['qaj_tribal_cavalry','qaj_cossack_brigade'])ok(/^mount\s+lancer$/m.test(block(t))&&/^formation\s+2, 2, 4, 4, 3, square$/m.test(block(t)),`${t}: lance cavalry structure`);
ok(/^mount\s+hussar$/m.test(block('qaj_horse_guard'))&&/^mount\s+hussar$/m.test(block('qaj_general_staff')),'pistol/command mount');
const removedAliases=['rus_sib_cossacks','gr_inf_eg','qajar_lt','rus_georgian_cav_eg','merc_kaz_inf','merc_kaz_cav'];for(const t of removedAliases)ok(!new RegExp(`^type\\s+${t}$`,'m').test(edu),`${t}: removed alias returned`);
const legacy=['qajar_foot','qajar_inf','rus_guard_eg','us_zouave_eg','merc_kok_royal_cav'];
for(const t of legacy){const b=block(t);ok(!/^ownership\s+.*\begypt\b/m.test(b)&&!/^era [012]\s+.*\begypt\b/m.test(b),`${t}: still in Qajar custom roster`);}
ok(/^ownership\s+slave$/m.test(block('us_zouave_eg')),'us_zouave_eg: missing safe compatibility ownership');
for(const [t,n] of Object.entries({fra_carbs:'fra_chasseurs_cheval',nl_carbs:'net_huzaren',balk_cav_gr:'pru_husaren'})){const b=block(t),mb=modelBlock(n);ok(new RegExp('^soldier\\s+'+n+',','m').test(b),t+': obsolete skeleton model');ok(/^stat_fire_delay\s+0$/m.test(b),t+': unsafe fire delay');ok(/14 MTW2_HR_Pistol 13 MTW2_HR_Sword/.test(mb)&&/22 MTW2_HR_Pistol_Primary/.test(mb)&&/18 MTW2_Sword_Primary/.test(mb),t+': pistol/sword skeleton mapping');}
for(const t of types.filter(x=>x!=='qaj_general_staff'&&x!=='qaj_horse_guard'))ok(edbText.includes(`recruit_pool "${t}"`),`${t}: absent from campaign recruitment`);
for(const t of ['qaj_sarbaz_early','qaj_guard_early'])ok(new RegExp(`recruit_pool "${t}".*not event_counter military_reforms_1870 1`).test(edbText),`${t}: early gate`);
for(const t of ['qaj_sarbaz_mid','qaj_guard_mid'])ok(new RegExp(`recruit_pool "${t}".*event_counter military_reforms_1870 1.*not event_counter military_reforms_1890 1`).test(edbText),`${t}: mid gate`);
for(const t of ['qaj_sarbaz_high','qaj_guard_high'])ok(new RegExp(`recruit_pool "${t}".*event_counter military_reforms_1890 1`).test(edbText),`${t}: late gate`);
for(const old of Object.keys({rus_sib_cossacks:1,qajar_foot:1,gr_inf_eg:1,qajar_lt:1,rus_georgian_cav_eg:1,qajar_inf:1,rus_guard_eg:1}))ok(!edbText.includes(`recruit_pool "${old}"`),`EDB stale Qajar recruit ${old}`);
function modelBlock(n){const a=model.split('\n'),i=a.findIndex(x=>new RegExp(`^${n.length} ${n}\\s*$`).test(x));if(i<0)fail(`${n}: missing model`);let j=i;while(j<a.length&&!/^16 -0\.090000004 /.test(a[j]))j++;return a.slice(i,j+1).join('\n');}
ok(/20 MTW2_Fast_Arquebus_3/.test(modelBlock('afghan_militia')),'Persian Tajik muzzle reload');
for(const t of types){const mb=modelBlock(t);if(['qaj_tofangchi','qaj_sarbaz_early','qaj_guard_early'].includes(t))ok(/20 MTW2_Fast_Arquebus_3/.test(mb),`${t}: muzzle reload`);if(['qaj_sarbaz_mid','qaj_sarbaz_high','qaj_guard_mid','qaj_guard_high','qaj_austrian_corps'].includes(t))ok(/14 MTW2_Musket_SS/.test(mb),`${t}: line reload`);if(t==='qaj_sharpshooters')ok(/15 MTW2_Musket_SSK/.test(mb),`${t}: kneeling reload`);if(['qaj_tofangchi','qaj_sharpshooters'].includes(t))ok(/16 MTW2_2HSwordsman/.test(mb)&&/24 MTW2_2HSwordsman_Primary/.test(mb),`${t}: sword animation`);if(['qaj_tribal_cavalry','qaj_cossack_brigade','qaj_horse_guard','qaj_general_staff'].includes(t))ok(/unit_sprites\/tmp_cavalry_sprite\.spr/.test(mb),`${t}: non-mounted sprite`);}
{const t='qaj_tribal_cavalry',mb=modelBlock(t);ok((mb.match(/^5 egypt\s*$/gm)||[]).length===2,`${t}: missing Egypt body or face mapping`);ok(!/^8 timurids\s*$/m.test(mb),`${t}: retained unusable donor faction mapping`);ok(/unit_models\/_Units\/afg\/textures\/afg_lan_1g\.texture/.test(mb)&&/unit_models\/_Units\/attachments\/textures\/afg_rugbxx\.texture/.test(mb),`${t}: donor appearance or face mapping changed`);}
{const t='qaj_general_staff',mb=modelBlock(t),mesh='unit_models/_Units/qaj/qaj_general_staff_lod0.mesh';ok(mb.includes(`${mesh.length} ${mesh}`),`${t}: not using seated Qajar command rider`);ok(!/qajari_general_lod0\.mesh/.test(mb),`${t}: retained standing foot mesh`);ok(/13 MTW2_HR_Sword 0\s+1\s+18 MTW2_Sword_Primary\s+0/.test(mb)&&!/MTW2_HR_Pistol/.test(mb),`${t}: command weapon skeleton`);const bytes=read('data/'+mesh).toString('latin1'),pri=bytes.indexOf('primaryactive0'),sword=bytes.indexOf('p_sabre',pri),sec=bytes.indexOf('secondaryactive0'),pistol=bytes.indexOf('sm_01',sec);ok(pri>=0&&sword>pri&&sword-pri<64&&sec>=0&&pistol>sec&&pistol-sec<64,`${t}: command mesh weapon groups`);}
{const t='qaj_standard_bearer',mb=modelBlock(t),mesh='unit_models/_Units/off/qaj_standard_bearer_lod0.mesh',body='unit_models/_Units/qaj/textures/qaj_inf_1g.texture',flag='unit_models/_Units/bnw/textures/qaj_standard_flag.texture',flagN='unit_models/_Units/bnw/textures/qaj_standard_flag_n.texture';for(const p of [mesh,body,flag,flagN])ok(fs.existsSync(path.join(root,'data',p)),`${t}: missing ${p}`);const bytes=read('data/'+mesh).toString('latin1');for(const g of ['primaryactive0','big_flag','yifu','kuzi','head','beard','hat'])ok(bytes.includes(g),`${t}: mesh group ${g}`);ok((mb.match(new RegExp(flag.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'g'))||[]).length===2,`${t}: flag must map for egypt and slave`);ok((mb.match(new RegExp(flagN.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'g'))||[]).length===2,`${t}: flag normal must map for egypt and slave`);ok(mb.includes(`${mesh.length} ${mesh}`)&&/5 egypt/.test(mb)&&/5 slave/.test(mb)&&/9 MTW2_Pike/.test(mb),`${t}: model mapping`);}
const header=+(model.match(/^22 serialization::archive 3 0 0 0 0 (\d+) 0 0 /)||[])[1],entryHeaders=[...model.matchAll(/^(\d+) ([^\s;]+)\s*\n\d+ \d+\s*$/gm)].filter(m=>+m[1]===m[2].length);ok(header-entryHeaders.length===1,`modeldb count mismatch: ${header} declared, ${entryHeaders.length} detected`);
for(const t of [...types,'qaj_standard_bearer']){const mb=modelBlock(t);for(const line of mb.split('\n')){const m=line.match(/^(\d+) (\S+\.(?:mesh|texture|spr))\s/);if(m){ok(+m[1]===m[2].length,`${t}: checksum ${m[2]}`);if(!m[2].endsWith('.spr'))ok(fs.existsSync(path.join(root,'data',m[2])),`${t}: missing asset ${m[2]}`);}}}
const cards=path.join(root,'data/ui/units/egypt');for(const t of types){const p=path.join(cards,`#${t}.tga`);ok(fs.existsSync(p),`${t}: missing tactical card`);const b=fs.readFileSync(p);ok(b.readUInt16LE(12)===48&&b.readUInt16LE(14)===64&&b[16]===32,`${t}: card must be 48x64 RGBA`);}
const sources=JSON.parse(text('tools/historical_card_sources.json'));for(const t of ['qaj_tofangchi','qaj_austrian_corps','qaj_tribal_cavalry','qaj_general_staff']){const s=sources.find(x=>x.id===t);ok(s&&s.status==='card-approved'&&s.source_url&&s.source_file&&s.generated_file,`${t}: incomplete card approval`);ok(fs.existsSync(path.join(root,s.source_file))&&fs.existsSync(path.join(root,s.generated_file)),`${t}: missing card source`);}
for(const p of ['data/world/maps/campaign/camp_steamsteel/descr_strat.txt','data/world/maps/campaign/imperial_campaign/descr_strat.txt']){const s=text(p);ok(!/unit\s+(?:rus_sib_cossacks|qajar_inf|qajar_foot|rus_guard_eg)(?:\s|$)/.test(s),p+': stale Qajar starting unit');for(const modern of ['qaj_horse_guard','qaj_guard_early','qaj_tofangchi','qaj_sarbaz_early'])ok(new RegExp('unit\\s+'+modern+'(?:\\s|$)').test(s),p+': missing Qajar starting unit '+modern);}
const locBuf=read('data/text/export_units.txt'),loc=locBuf.subarray(locBuf[0]===255&&locBuf[1]===254?2:0).toString('utf16le');for(const t of types)for(const k of [t,`${t}_descr`,`${t}_descr_short`])ok((loc.match(new RegExp(`\\{${k}\\}`,'g'))||[]).length===1,`${k}: localization count`);
console.log(`Qajar validation passed: ${types.length} records; modeldb header ${header}; EDU ${crypto.createHash('sha256').update(edu).digest('hex').slice(0,12)}.`);
