const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p)),txt=p=>read(p).toString('utf8').replace(/\r/g,''),ok=(v,m)=>{if(!v)throw Error(m)};
const edu=txt('data/tow_steamsteel/export_descr_unit.txt'),mirror=txt('data/export_descr_unit.txt'),edb=txt('data/tow_steamsteel/export_descr_buildings.txt'),edbM=txt('data/export_descr_buildings.txt'),model=txt('data/unit_models/battle_models.modeldb');
ok(edu===mirror,'EDU mirrors differ');ok(edb===edbM,'EDB mirrors differ');ok(read('data/world/maps/campaign/camp_steamsteel/descr_strat.txt').equals(read('data/world/maps/campaign/imperial_campaign/descr_strat.txt')),'campaign mirrors differ');
const types=['uni_state_volunteers_early','uni_regulars_mid','uni_regulars_high','uni_national_guard_mid','uni_national_guard_high','uni_colored_troops_early','uni_irish_brigade_early','uni_zouaves_early','uni_marines_early','uni_marines_mid','uni_marines_high','uni_sharpshooters_early','uni_indian_scouts','uni_volunteer_cavalry_early','uni_dragoons_early','uni_dragoons_mid','uni_dragoons_high','uni_indian_scout_cavalry','uni_general_staff'];
const infantry=types.slice(0,13),cavalry=types.slice(13),skirm=['uni_zouaves_early','uni_sharpshooters_early','uni_indian_scouts'],late=['uni_regulars_high','uni_national_guard_high','uni_marines_high'];
function block(t){const m=edu.match(new RegExp(`^type\\s+${t}\\n[\\s\\S]*?(?=^type\\s+|(?![\\s\\S]))`,'m'));if(!m)throw Error('missing '+t);return m[0];}
function mb(t){const a=model.split('\n'),i=a.findIndex(x=>new RegExp(`^${t.length} ${t}\\s*$`).test(x));ok(i>=0,'missing model '+t);let j=i;while(j<a.length&&!/^16 -0\.090000004 /.test(a[j]))j++;return a.slice(i,j+1).join('\n');}
for(const t of types){const b=block(t);ok((edu.match(new RegExp(`^type\\s+${t}$`,'gm'))||[]).length===1,t+' duplicate');ok(/^ownership\s+portugala, slave$/m.test(b),t+' ownership');ok(/^stat_ground\s+0, 0, 0, 0$/m.test(b),t+' terrain');ok(/^stat_fire_delay\s+0$/m.test(b),t+' fire delay');ok(!/\b(?:hardy|very_hardy|hide_anywhere)\b/.test(b),t+' unjustified attribute');const c=(b.match(/^stat_cost\s+(.*)$/m)||[])[1].split(',').map(x=>+x.trim());ok(c[3]===100&&c[4]===100&&c[1]===c[5]&&c[2]===c[7]&&c[2]===Math.round(c[1]/3),t+' cost arithmetic');}
for(const t of infantry){const b=block(t),off=[...b.matchAll(/^officer\s+(\S+)$/gm)].map(x=>x[1]),expected=t==='uni_indian_scouts'?'':late.includes(t)?'usa_off_1g':'usa_off_1g,usa_standard_bearer';ok(off.join(',')===expected,t+' officer/bearer complement');ok(new RegExp(`^soldier\\s+${t}, ${skirm.includes(t)?30:40},`,'m').test(b),t+' strength');ok(/^formation\s+1\.4, 1\.8, 2\.8, 3\.6, 3, square$/m.test(b)===skirm.includes(t),t+' formation role');}
for(const t of cavalry){const b=block(t),expectedClass=['uni_indian_scout_cavalry','uni_general_staff'].includes(t)?'light':'missile';ok(/^category\s+cavalry$/m.test(b)&&new RegExp('^class\\s+'+expectedClass+'$','m').test(b),t+' cavalry class');ok(new RegExp(`^soldier\\s+${t}, ${t==='uni_general_staff'?4:24},`,'m').test(b),t+' cavalry strength');ok(/unit_sprites\/tmp_cavalry_sprite\.spr/.test(mb(t)),t+' mounted distant sprite');}
const militia=['uni_state_volunteers_early','uni_national_guard_mid','uni_national_guard_high','uni_colored_troops_early','uni_irish_brigade_early','uni_zouaves_early','uni_indian_scouts','uni_volunteer_cavalry_early','uni_indian_scout_cavalry'];for(const t of militia){const b=block(t);ok(/^stat_mental\s+3, (?:low|impetuous), trained$/m.test(b),t+' militia mental');ok(/^stat_pri_armour\s+[34], 2, 0, leather$/m.test(b),t+' militia defence');}
const regular=['uni_regulars_mid','uni_regulars_high','uni_marines_early','uni_marines_mid','uni_marines_high','uni_sharpshooters_early','uni_dragoons_early','uni_dragoons_mid','uni_dragoons_high'];for(const t of regular){const b=block(t);ok(/^stat_mental\s+4, normal, trained$/m.test(b),t+' regular mental');ok(/^stat_pri_armour\s+[34], 3, 0, leather$/m.test(b),t+' regular defence');}
ok(/^stat_pri\s+29, 0, rifled_musket_bullet_a, 260,/m.test(block('uni_sharpshooters_early')),'sharpshooter ballistics');ok(/15 MTW2_Musket_SSK/.test(mb('uni_sharpshooters_early')),'sharpshooter kneeling animation');ok(/^stat_pri\s+29, 0, rifled_musket_bullet_b, 260,/m.test(block('uni_zouaves_early')),'zouave skirmisher tier');
ok(/^stat_sec\s+3, 2, no, 0, 0, melee, melee_blade, piercing, axe, 25, 1$/m.test(block('uni_indian_scouts'))&&/^stat_sec_attr\s+ap$/m.test(block('uni_indian_scouts')),'Indian Scouts tomahawk row');ok(/11 MTW2_2H_Axe/.test(mb('uni_indian_scouts'))&&/19 MTW2_2H_Axe_primary/.test(mb('uni_indian_scouts')),'Indian Scouts tomahawk animation');
for(const t of ['uni_state_volunteers_early','uni_colored_troops_early','uni_irish_brigade_early','uni_zouaves_early','uni_marines_early','uni_indian_scouts'])ok(/20 MTW2_Fast_Arquebus_3/.test(mb(t)),t+' muzzle animation');for(const t of ['uni_regulars_mid','uni_national_guard_mid','uni_marines_mid'])ok(/14 MTW2_Musket_SS/.test(mb(t)),t+' single-shot animation');for(const t of late)ok(/20 MTW2_Fast_Arquebus_3/.test(mb(t)),t+' magazine animation');
for(const t of [...infantry.filter(x=>x!=='uni_indian_scouts'),...cavalry.filter(x=>x!=='uni_indian_scout_cavalry'&&x!=='uni_general_staff')])ok(/^officer\s+usa_off_1g$/m.test(block(t)),t+' national officer');
{const b=mb('usa_standard_bearer');for(const p of ['unit_models/_Units/bnw/fra_qishou_lod0.mesh','unit_models/_Units/bnw/textures/fra_qishou_port.texture','unit_models/_Units/bnw/textures/france_flag_port.texture'])ok(b.includes(`${p.length} ${p}`),`bearer mapping ${p}`);ok(/9 portugala/.test(b)&&/9 MTW2_Pike/.test(b),'bearer faction/animation');}
const legacy=['berdan_inf','ap_front_cav','us_front_cav','us_scout_cav','us_zouave','union_irish_brigade','us_inf','us_blacks','us_colo_inf','us_late_inf','us_front_inf','us_militia','apache_inf','merc_us_farmer_cav','merc_ap_front_cav','merc_apache_inf'];for(const t of legacy){const b=block(t);ok(!/^ownership\s+.*\bportugala\b/m.test(b)&&!/^era [012]\s+.*\bportugala\b/m.test(b),t+' retained Union scope');}
for(const line of edb.split('\n'))if(line.includes('requires factions { portugala')||line.includes('requires factions { portugala,'))ok(!new RegExp(`recruit_pool "(?:${legacy.join('|')})"`).test(line),'stale Union EDB line: '+line.trim());
const camp=(txt('data/world/maps/campaign/camp_steamsteel/descr_strat.txt').match(/(^faction\s+portugala\b[\s\S]*?)(?=^faction\s+)/m)||[])[1];ok(camp,'missing Union campaign block');for(const t of legacy)ok(!new RegExp(`^\\s*unit\\s+${t}\\s`,'m').test(camp),'stale Union start '+t);
for(const t of types){const p=path.join(root,'data/ui/units/portugala',`#${t}.tga`);ok(fs.existsSync(p),t+' missing card');const b=fs.readFileSync(p);ok(b.readUInt16LE(12)===48&&b.readUInt16LE(14)===64&&b[16]===32,t+' card format');}
ok(/^stat_pri\s+20, 4, magazine_rifle_bullet_c, 60, 15,/m.test(block('uni_general_staff'))&&/^stat_sec\s+7, 4,/m.test(block('uni_general_staff')),'General and Staff pistol/sabre rows');ok(/Colt Army Model 1860 revolver and sabre/.test(block('uni_general_staff')),'General and Staff named pistol');ok(/^stat_pri\s+20, 4, magazine_rifle_bullet_c, 60, 15,/m.test(block('uni_indian_scout_cavalry'))&&/^stat_sec\s+3, 2,.*spear/m.test(block('uni_indian_scout_cavalry')),'Indian Scout Cavalry pistol/spear rows');ok(/^stat_cost\s+3, 1000, 333, 100, 100, 1000, 3, 333$/m.test(block('uni_state_volunteers_early')),'State Volunteers mass limit/cost');ok(/^stat_pri\s+29, 0, rifled_musket_bullet_c, 220, 35,/m.test(block('uni_marines_mid'))&&/^stat_cost\s+3, 1200, 400,/m.test(block('uni_marines_mid')),'Marine Remington 1867 early-breechloader baseline');for(const t of ['uni_volunteer_cavalry_early','uni_dragoons_early']){const b=block(t);ok(/^stat_pri\s+29, 2, rifled_musket_carbine_bullet_c, 200,/m.test(b)&&!/^attributes\s+.*\bgunpowder_unit\b/m.test(b),t+' Sharps carbine rows');}
{const registry=JSON.parse(txt('tools/historical_card_sources.json'));for(const cardId of ['uni_indian_scout_cavalry','uni_general_staff']){const r=registry.find(x=>x.id===cardId);ok(r&&r.status==='approved'&&r.source_url&&r.source_file&&r.generated_file&&r.crop_box.length===4,'Indian Scout Cavalry approved source mapping');for(const p of [r.source_file,r.generated_file])ok(fs.existsSync(path.join(root,p)),'missing approved Union card source '+p);}}
ok(!/\{uni_regulars_early(?:_descr|_descr_short)?\}/.test(txt('data/text/export_units.txt')),'stale early Regular localization');
const header=+(model.match(/^22 serialization::archive 3 0 0 0 0 (\d+) 0 0 /)||[])[1],heads=[...model.matchAll(/^(\d+) ([^\s;]+)\s*\n\d+ \d+\s*$/gm)].filter(m=>+m[1]===m[2].length);ok(header-heads.length===1,`model count ${header}/${heads.length}`);
console.log(`Union validation passed: ${types.length} records; modeldb ${header}.`);
