const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),eduC=path.join(root,'data/tow_steamsteel/export_descr_unit.txt'),eduR=path.join(root,'data/export_descr_unit.txt'),modelP=path.join(root,'data/unit_models/battle_models.modeldb'),locP=path.join(root,'data/text/export_units.txt'),cardDir=path.join(root,'data/ui/units/hungary');
const edu=fs.readFileSync(eduC,'utf8').replace(/\r/g,''),model=fs.readFileSync(modelP,'utf8').replace(/\r/g,''),lb=fs.readFileSync(locP),loc=lb.slice(2).toString('utf16le');let errors=[];const ok=(v,m)=>{if(!v)errors.push(m)};
const periods=['early','mid','high'];
const infantry=['aus_line_early','aus_line_mid','aus_line_high','aus_kaiserjaeger_early','aus_kaiserjaeger_mid','aus_kaiserjaeger_high','aus_grenz_early','aus_landwehr_mid','aus_landwehr_high','aus_honved_mid','aus_honved_high','aus_bosniak_mid','aus_bosniak_high','aus_matrosen_early','aus_matrosen_mid','aus_matrosen_high'];
const cavalry=['aus_kuerassiere','aus_dragoner_early','aus_dragoner_mid','aus_dragoner_high','aus_husaren','aus_ulanen','aus_general_staff'],expected=[...infantry,...cavalry];
function block(type){const s=[...edu.matchAll(/^type\s+(\S+)/gm)],i=s.findIndex(x=>x[1]===type);return i<0?'':edu.slice(s[i].index,i+1<s.length?s[i+1].index:edu.length);}
function me(name){const a=model.split('\n'),i=a.findIndex(x=>new RegExp(`^${name.length} ${name}\\s*$`).test(x));if(i<0)return'';let j=i;while(j<a.length&&!/^16 -0\.090000004 /.test(a[j]))j++;return a.slice(i,j+1).join('\n');}
ok(fs.readFileSync(eduC).equals(fs.readFileSync(eduR)),'EDU mirrors differ');ok(lb[0]===255&&lb[1]===254,'localization is not UTF-16LE BOM');
const types=[...edu.matchAll(/^type\s+(.+)$/gm)].map(x=>x[1].trim()),dicts=[...edu.matchAll(/^dictionary\s+(\S+)/gm)].map(x=>x[1]);ok(new Set(types).size===types.length,'duplicate EDU type');ok(new Set(dicts).size===dicts.length,'duplicate EDU dictionary');
const head=model.match(/^22 serialization::archive 3 0 0 0 0 (\d+) 0 0 /),headers=[...model.matchAll(/^(\d+) ([^\s;]+)\s*\n1 \d+\s*$/gm)].filter(x=>+x[1]===x[2].length);ok(head&&+head[1]-headers.length===1,`modeldb count mismatch: ${head&&head[1]} declared, ${headers.length} detected`);const names=new Set(headers.map(x=>x[2]));
for(const t of expected){const b=block(t);ok(b,`${t}: missing EDU record`);if(!b)continue;const soldier=(b.match(/^soldier\s+(\S+),/m)||[])[1];ok(names.has(soldier),`${t}: missing model ${soldier}`);ok(/^ownership\s+hungary, slave$/m.test(b),`${t}: wrong ownership`);ok(/^stat_ground\s+0, 0, 0, 0$/m.test(b),`${t}: ground modifier`);ok(/^stat_fire_delay\s+0$/m.test(b),`${t}: unsafe firing delay`);ok(!/(hardy|very_hardy|hide_improved_forest)/.test((b.match(/^attributes\s+(.+)$/m)||[])[1]||''),`${t}: inherited attribute`);for(const k of [t,`${t}_descr`,`${t}_descr_short`])ok(loc.includes(`{${k}}`),`${t}: missing localization ${k}`);const p=path.join(cardDir,`#${t}.tga`);ok(fs.existsSync(p),`${t}: missing tactical card`);if(fs.existsSync(p)){const x=fs.readFileSync(p);ok(x.readUInt16LE(12)===48&&x.readUInt16LE(14)===64&&x[16]===32,`${t}: card is not 48x64 RGBA`);}const row=((b.match(/^stat_cost\s+(.+)$/m)||[])[1]||'').split(',').map(x=>+x.trim());ok(row.length===8&&row[2]===Math.round(row[1]/3)&&row[3]===100&&row[4]===100&&row[5]===row[1]&&row[7]===Math.round(row[1]/3),`${t}: cost arithmetic`);}
for(const t of infantry){const b=block(t),p=t.endsWith('_early')?'early':t.endsWith('_mid')?'mid':'high',skirm=/kaiserjaeger|grenz/.test(t),off=[...b.matchAll(/^officer\s+/gm)].length;ok(off===(p==='high'?1:2),`${t}: officer/bearer count`);ok(/^stat_sec\s+6, 3,/m.test(b)&&/^stat_pri_armour\s+3, 4, 0, leather$/m.test(b)&&/^stat_mental\s+4, normal, trained$/m.test(b),`${t}: B tier plus Austrian melee/defence`);ok((p==='high')===/attributes\s+.*\bstakes\b/.test(b),`${t}: stakes mismatch`);ok(skirm===/^formation\s+1.4, 1.8, 2.8, 3.6, 3, square$/m.test(b),`${t}: role formation mismatch`);if(skirm)ok(!/attributes\s+.*\bcannot_skirmish\b/.test(b),`${t}: skirmishing disabled`);}
for(const p of periods){const b=block(`aus_dragoner_${p}`);ok(/^class\s+missile$/m.test(b),`aus_dragoner_${p}: not carbine cavalry`);ok(/^stat_sec\s+6, 3,/m.test(b)&&/^stat_pri_armour\s+4, 5, 0, leather$/m.test(b),`aus_dragoner_${p}: wrong melee/defence`);ok((p==='high')===/attributes\s+.*\bstakes\b/.test(b),`aus_dragoner_${p}: stakes mismatch`);ok(/unit_sprites\/tmp_cavalry_sprite\.spr/.test(me(`aus_dragoner_${p}`)),`aus_dragoner_${p}: standing distant sprite`);}
for(const t of ['aus_husaren','aus_ulanen'])ok(/^stat_sec\s+6, 3,/m.test(block(t))&&/^stat_pri_armour\s+4, 5, 0, leather$/m.test(block(t)),`${t}: wrong Austrian cavalry bonus`);ok(/^stat_pri\s+20, 4, magazine_rifle_bullet_c, 60, 15,/m.test(block('aus_husaren')),'Husaren pistol row');ok(/^stat_pri\s+6, 6, no,/m.test(block('aus_ulanen')),'Ulanen lance primary charge');ok(/aus_lan_1g_lod0\.mesh/.test(me('aus_ulanen'))&&/13 MTW2_HR_Lance 13 MTW2_HR_Sword/.test(me('aus_ulanen')),'Ulanen model lacks European lance/sabre');
const g=block('aus_general_staff');ok(/^soldier\s+aus_general_staff, 4,/m.test(g)&&/^class\s+light$/m.test(g)&&/^formation\s+2, 2, 4, 4, 2, square$/m.test(g),'general structure');ok(/^stat_cost\s+3, 200, 67, 100, 100, 200, 1, 67$/m.test(g),'general cost');ok(/^stat_pri\s+20, 4, magazine_rifle_bullet_c,/m.test(g),'general pistol');
for(const t of ['merc_pol_hussars','merc_polish_inf','it_royals_hungary','bulgarian_inf','merc_bulgarian_inf'])ok(!/^(?:ownership|era [012]).*\bhungary\b/m.test(block(t)),`${t}: detached auxiliary still in main roster`);
if(errors.length){console.error(errors.join('\n'));process.exit(1);}console.log(`Austria validation passed: ${expected.length} roster records; modeldb ${head[1]} declared entries.`);
