const fs=require('fs'),path=require('path'),crypto=require('crypto');const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p)),txt=p=>read(p).toString('utf8').replace(/\r/g,''),ok=(v,m)=>{if(!v)throw Error(m)};
const edu=txt('data/tow_steamsteel/export_descr_unit.txt'),mirror=txt('data/export_descr_unit.txt'),edb=txt('data/tow_steamsteel/export_descr_buildings.txt'),edbM=txt('data/export_descr_buildings.txt'),model=txt('data/unit_models/battle_models.modeldb');ok(edu===mirror,'EDU mirrors differ');ok(edb===edbM,'EDB mirrors differ');
const types=['arg_line_early','arg_line_mid','arg_line_high','arg_national_guard_early','arg_national_guard_mid','arg_national_guard_high','arg_cazadores_early','arg_cazadores_mid','arg_tiradores_high','arg_cavalry_early','arg_cavalry_mid','arg_cavalry_high','arg_lancers_early','arg_lancers_mid','arg_frontier_gauchos','arg_general_staff'];function block(t){const m=edu.match(new RegExp(`^type\\s+${t}\\n[\\s\\S]*?(?=^type\\s+|(?![\\s\\S]))`,'m'));ok(m,'missing '+t);return m[0]};function mb(t){const a=model.split('\n'),i=a.findIndex(x=>new RegExp(`^${t.length} ${t}\\s*$`).test(x));ok(i>=0,'missing model '+t);let j=i;while(j<a.length&&!/^16 -0\\.090000004 /.test(a[j]))j++;return a.slice(i,j+1).join('\n')}
for(const t of types){ok((edu.match(new RegExp(`^type\\s+${t}$`,'gm'))||[]).length===1,t+' duplicate');const b=block(t);ok(/^stat_fire_delay\s+0$/m.test(b),t+' unsafe fire delay');ok(/^stat_ground\s+0, 0, 0, 0$/m.test(b),t+' ground');const c=path.join(root,'data/ui/units/aztecs',`#${t}.tga`);ok(fs.existsSync(c),t+' card missing');const x=fs.readFileSync(c);ok(x.readUInt16LE(12)===48&&x.readUInt16LE(14)===64&&x[16]===32,t+' bad card')}
for(const t of ['arg_cazadores_early','arg_cazadores_mid','arg_tiradores_high']){const b=block(t);ok(/^soldier\s+\S+, 30,/m.test(b)&&/^formation\s+1.4, 1.8, 2.8, 3.6, 3, square$/m.test(b),t+' skirmisher');if(t!=='arg_cazadores_early')ok(/15 MTW2_Musket_SSK/.test(mb(t))&&!/^attributes.*gunpowder_unit/m.test(b),t+' SSK mismatch')}
for(const t of ['arg_cavalry_early','arg_cavalry_mid','arg_cavalry_high']){const b=block(t);ok(/^category\s+cavalry$/m.test(b)&&/^class\s+missile$/m.test(b)&&/^soldier\s+\S+, 24,/m.test(b),t+' cavalry class/size');ok(/unit_sprites\/tmp_cavalry_sprite\.spr/.test(mb(t)),t+' sprite')}
const g=block('arg_general_staff');ok(/^soldier\s+arg_general_staff, 4,/m.test(g)&&/^formation\s+2, 2, 4, 4, 2, square$/m.test(g)&&/Lefaucheux Model 1858/.test(g),'general');const gau=block('arg_frontier_gauchos');ok(/^stat_mental\s+3, impetuous, trained$/m.test(gau)&&/^stat_cost\s+3, 1000, 333, 100, 100, 1000, 1, 333$/m.test(gau),'gaucho lance cost/mental');
for(const t of types)ok(edb.includes(`recruit_pool "${t}"`),t+' EDB');for(const t of ['arg_line_early','arg_line_mid','arg_national_guard_early','arg_national_guard_mid','arg_cazadores_early','arg_cazadores_mid'])ok(/^officer\s+arg_standard_bearer$/m.test(block(t)),t+' bearer');for(const t of ['arg_line_high','arg_national_guard_high','arg_tiradores_high'])ok(!block(t).includes('arg_standard_bearer'),t+' late bearer');
const bearer=mb('arg_standard_bearer');for(const p of ['arg_standard_bearer.texture','arg_standard_flag.texture','arg_standard_flag_n.texture'])ok(bearer.includes(p),'bearer '+p);const reg=JSON.parse(txt('tools/historical_card_sources.json'));for(const t of ['arg_general_staff','arg_cazadores_early','arg_cazadores_mid','arg_tiradores_high','arg_lancers_early','arg_lancers_mid']){const r=reg.find(x=>x.id===t);ok(r&&r.status==='card-approved'&&r.source_url&&r.source_file&&r.generated_file,t+' card source');ok(fs.existsSync(path.join(root,r.source_file))&&fs.existsSync(path.join(root,r.generated_file)),t+' source files')}
const ca=txt('data/world/maps/campaign/camp_steamsteel/descr_strat.txt'),cb=txt('data/world/maps/campaign/imperial_campaign/descr_strat.txt');ok(ca===cb,'campaign mirrors differ');const ab=ca.match(/^faction\s+aztecs,[\s\S]*?(?=^faction\s+)/m)[0];for(const old of ['gaucho_cav','arg_guard','arg_inf','arg_carb','us_zouave_az'])ok(!new RegExp(`^unit\\s+${old}\\s`,'m').test(ab),'stale campaign '+old);
const header=+(model.match(/^22 serialization::archive 3 0 0 0 0 (\d+) 0 0 /)||[])[1],heads=[...model.matchAll(/^(\d+) ([^\s;]+)\s*\n\d+ \d+\s*$/gm)].filter(m=>+m[1]===m[2].length);ok(header-heads.length===1,`model count ${header}/${heads.length}`);console.log(`Argentina validation passed: ${types.length} units; modeldb ${header}; campaign and runtime mirrors exact.`)