const fs=require('fs'),P=require('path'),R=P.resolve(__dirname,'..');
const EC=P.join(R,'data/tow_steamsteel/export_descr_unit.txt'),ER=P.join(R,'data/export_descr_unit.txt'),MP=P.join(R,'data/unit_models/battle_models.modeldb');
let e=fs.readFileSync(EC,'utf8').replace(/\r/g,''),m=fs.readFileSync(MP,'utf8').replace(/\r/g,'');
const blk=(s,n)=>{const x=s.match(new RegExp(`^type\\s+${n}\\n[\\s\\S]*?(?=^type\\s+|(?![\\s\\S]))`,'m'));if(!x)throw Error(`missing ${n}`);return x[0].trimEnd()},rep=(s,n,b)=>s.replace(blk(s,n),b),up=n=>Math.round(n/3),cost=(n,l)=>`3, ${n}, ${up(n)}, 100, 100, ${n}, ${l}, ${up(n)}`;
function kom(n,label,era,dmg,shot,range,ammo,smoke,total,stakes=''){return `type             ${n}\ndictionary       ${n} ; ${label}\ncategory         infantry\nclass            missile\nvoice_type       Light\naccent           dutch\nbanner faction   main_missile\nbanner holy      crusade\nsoldier          ${n}, 30, 0, 1.3\nofficer          usa_off_1g\nattributes       free_upkeep_unit, sea_faring, hide_forest, gunmen, start_not_skirmishing, cannot_skirmish${stakes}\nformation        1.4, 1.8, 2.8, 3.6, 3, square\nstat_health      1, 0\nstat_pri         ${dmg}, 0, ${shot}, ${range}, ${ammo}, missile, missile_gunpowder, piercing, none, ${smoke}, 0, -999\nstat_pri_attr    ap\nstat_sec         2, 2, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1.2\nstat_sec_attr    ap, short_pike\nstat_pri_armour  3, 2, 0, leather\nstat_sec_armour  0, 0, flesh\nstat_heat        2\nstat_ground      0, 0, 0, 0\nstat_mental      4, impetuous, trained\nstat_charge_dist 40\nstat_fire_delay  0\nstat_food        60, 300\nstat_cost        ${cost(total,3)}\nownership        teu, slave\nera ${era}            teu, slave`;}
const early=kom('boer_kommando_early','Boer Kommando (Early; Westley Richards Monkey Tail)',0,37,'rifled_musket_bullet_a',260,35,'musket_shot_set',1000),mid=kom('boer_kommando_mid','Boer Kommando (Mid; Martini-Henry)',1,29,'rifle_bullet_a',280,35,'musket_shot_set',1300),high=kom('boer_kommando_high','Boer Kommando (Late; Mauser Model 1895)',2,13,'magazine_rifle_bullet_a',300,40,'smokeless_shot_set',1600,', stakes');
e=rep(e,'us_militia_te',early);e=e.replace(blk(e,'csa_volunteers_te'),mid+'\n\n'+high);
let b=blk(e,'boer_guard').replace(/^dictionary.*$/m,'dictionary       boer_guard ; Transvaal Sharpshooters (Mauser Model 1895)').replace(/^attributes.*$/m,'attributes       free_upkeep_unit, sea_faring, hide_forest, gunmen, start_not_skirmishing, cannot_skirmish, stakes').replace(/^stat_pri\s+.*$/m,'stat_pri         13, 0, magazine_rifle_bullet_s, 300, 40, missile, missile_gunpowder, piercing, none, smokeless_shot_set, 0, -999').replace(/^stat_sec\s+.*$/m,'stat_sec         4, 3, no, 0, 0, melee, melee_blade, piercing, spear, 25, 1.2').replace(/^stat_pri_armour.*$/m,'stat_pri_armour  3, 3, 0, leather').replace(/^stat_ground.*$/m,'stat_ground      0, 0, 0, 0').replace(/^stat_mental.*$/m,'stat_mental      5, impetuous, trained').replace(/^stat_cost.*$/m,`stat_cost        ${cost(2000,1)}`);e=rep(e,'boer_guard',b);
b=blk(e,'us_farmer_cav').replace(/^dictionary.*$/m,'dictionary       us_farmer_cav ; Mounted Boer Kommando (Maynard M1858 carbine)').replace(/^attributes.*$/m,'attributes       free_upkeep_unit, sea_faring, can_withdraw, hide_forest, gunmen, guncavalry, start_not_skirmishing').replace(/^stat_pri\s+.*$/m,'stat_pri         25, 2, rifled_musket_carbine_bullet_b, 200, 35, missile, missile_gunpowder, piercing, none, musket_shot_set, 50, 1').replace(/^stat_sec\s+.*$/m,'stat_sec         2, 2, no, 0, 0, melee, melee_blade, blunt, mace, 25, 1').replace(/^stat_pri_armour.*$/m,'stat_pri_armour  4, 4, 0, leather').replace(/^stat_ground.*$/m,'stat_ground      0, 0, 0, 0').replace(/^stat_mental.*$/m,'stat_mental      4, impetuous, trained').replace(/^stat_cost.*$/m,`stat_cost        ${cost(1200,2)}`);e=rep(e,'us_farmer_cav',b);
b=blk(e,'csa_lancer_te').replace(/^class.*$/m,'class            light').replace(/^soldier.*$/m,'soldier          gr_lancer, 4, 0, 1').replace(/^attributes.*$/m,'attributes       free_upkeep_unit, sea_faring, general_unit, command').replace(/^formation.*$/m,'formation        2, 2, 4, 4, 2, square').replace(/^stat_ground.*$/m,'stat_ground      0, 0, 0, 0').replace(/^stat_cost.*$/m,`stat_cost        ${cost(1400,1)}`);e=rep(e,'csa_lancer_te',b);
b=blk(e,'boer_wagon').replace(/^stat_pri\s+.*$/m,'stat_pri         37, 0, rifled_musket_bullet_a, 220, 60, missile, missile_gunpowder, piercing, none, musket_shot_set, 0, -999').replace(/^stat_fire_delay.*$/m,'stat_fire_delay  0');e=rep(e,'boer_wagon',b);
for(const n of ['us_farmers','rus_sailors_teu']){b=blk(e,n).replace(/^ownership.*$/m,'ownership        slave').replace(/^era ([012])\s+.*$/gm,'era $1            slave');e=rep(e,n,b)}
fs.writeFileSync(EC,e.replace(/\n/g,'\r\n'));fs.writeFileSync(ER,e.replace(/\n/g,'\r\n'));
const ents=s=>[...s.matchAll(/^(\d+) ([^\s;]+)\s*\n\d+ \d+\s*$/gm)].filter(x=>+x[1]===x[2].length).map(x=>({n:x[2],i:x.index}));function mb(s,n){const a=ents(s),i=a.findIndex(x=>x.n===n);if(i<0)throw Error(`missing model ${n}`);return s.slice(a[i].i,i+1<a.length?a[i+1].i:s.length).trimEnd()}function clone(d,n){return mb(m,d).replace(new RegExp(`^${d.length} ${d}`),`${n.length} ${n}`).replace(/\n1 \n4 None \n[\s\S]*?(?=\n16 -0\.090000004 )/,'\n1 \n4 None \n15 MTW2_Musket_SSK 9 MTW2_Pike \n1 \n21 MTW2_Arquebus_Primary \n1 \n17 MTW2_Pike_primary ')}
let add=0;for(const [n,d] of [['boer_kommando_early','csa_volunteers'],['boer_kommando_mid','csa_volunteers'],['boer_kommando_high','boer_guard']]){const x=clone(d,n);if(ents(m).some(y=>y.n===n))m=m.replace(mb(m,n),x);else{m=m.trimEnd()+'\n'+x+'\n';add++}}if(add){const h=m.match(/^(22 serialization::archive 3 0 0 0 0 )(\d+)( 0 0 )/);m=m.replace(h[0],`${h[1]}${+h[2]+add}${h[3]}`)}fs.writeFileSync(MP,m.replace(/\n/g,'\r\n'));
const cd=P.join(R,'data/ui/units/teu');for(const n of ['boer_kommando_early','boer_kommando_mid'])fs.copyFileSync(P.join(cd,'#us_militia_te.tga'),P.join(cd,`#${n}.tga`));fs.copyFileSync(P.join(cd,'#csa_volunteers_te.tga'),P.join(cd,'#boer_kommando_high.tga'));
console.log('Boer roster standardized');
